The World Band > [Life expectancy at birth, total](https://data.worldbank.org/indicator/SP.DYN.LE00.IN)<br />
The World Band > [Life expectancy at birth, male](https://data.worldbank.org/indicator/SP.DYN.LE00.MA.IN)<br />
The World Band > [Life expectancy at birth, female](https://data.worldbank.org/indicator/SP.DYN.LE00.FE.IN)<br />
[World Development Indicators > Life expectancy at birth](https://databank.worldbank.org/reports.aspx?source=2&series=SP.DYN.LE00.IN&country=) *(databank.worldbank.org)*<br />
[OECD stat](https://stats.oecd.org/index.aspx?queryid=30114)

"[Список стран по ожидаемой продолжительности жизни](https://ru.wikipedia.org/wiki/Список_стран_по_ожидаемой_продолжительности_жизни)"<br />
"[Продолжительность жизни в субъектах Российской Федерации](https://ru.wikipedia.org/wiki/Продолжительность_жизни_в_субъектах_Российской_Федерации)"<br />
[Таблица подбора цветов](http://mal-bioit.ru/survey-web-colors)<br />
[Список государств и зависимых территорий по населению](https://ru.wikipedia.org/wiki/Список_государств_и_зависимых_территорий_по_населению)

[https://www.mapchart.net](https://www.mapchart.net)

In [1]:
import pandas as pd
from collections import namedtuple

import sys
sys.path.append("..")
import mal_moduls_private.mal_total as mal

In [2]:
SORT_COLUMNS = [2024, 2023]
SELECTED_YEAR = 2024
WRITE_TO_FILE = True
CREATE_LEGEND = False

In [3]:
CountryGroup = namedtuple('CountryGroup', ['group_label', 'color', 'countries'])

In [4]:
df = pd.read_csv('data/World_Bank_Group-total.csv', skiprows=4, index_col=0)
df.head(2).round(2).fillna('')

,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
Country Name,,,,,,,,,,,,,,,,,,,,,
Aruba,ABW,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,64.05,64.22,64.60,64.94,65.30,65.61,66.13,...,75.62,75.88,76.02,75.41,73.66,76.23,76.35,76.50,,
Africa Eastern and Southern,AFE,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,44.17,44.47,44.88,45.16,45.54,45.77,45.77,...,62.59,63.33,63.86,63.77,62.98,64.49,65.15,65.35,,

In [5]:
def extract_data_for_year(df, ls_cols):
    ls_dropping = [
        # 'Hong Kong SAR, China',     # administrative region of China, population 7,291,000
        # 'Macao SAR, China',         # administrative region of China, population 682,000
        'Kosovo',                   # partially recognised state, population 1,806,000
        # 'West Bank and Gaza',        # Palestine, partially recognised state, population 5,227,000
        # 'New Caledonia',             # French Overseas Territory in Oceania, population 271,000
        # 'Channel Islands',           # archipelago in Europe, consisting of two Crown Dependencies, population 172,000
        # 'Curacao',                   #  constituent country of the Netherlands in S.America, population 149,000, little info about LE
        # 'Virgin Islands (U.S.)',     # unincorporated and organized territory of USA, population 87,000
        # 'Isle of Man',               # self-governing Crown Dependency, Europe, population 84,000
        # 'Dominica',                  # micro-state in N.America, population 72,400
        # 'Marshall Islands',          # micro-state in Oceania, population 62,000
        # 'Faroe Islands',             # autonomous territory of Denmark in Europe, population 54,000
        # 'St. Kitts and Nevis',       # micro-state in N.America, population 47,600
        # 'Turks and Caicos Islands',  # British Overseas Territory in N.America, population 44,000
        # 'Sint Maarten (Dutch part)', # constituent country of the Netherlands in N.America, population 41,500
        # 'Gibraltar',                 # British Overseas Territory in Europe, population 34,000
        # 'St. Martin (French part)',  # French Overseas Territory in N.America, population 32,500
        # 'British Virgin Islands',    # British Overseas Territory in N.America, population 30,000
        # 'Palau',           #  mini-state in Oceania, population 22,000, little info about LE
        # 'Tuvalu',                    # island micro-state in Oceania, population 12,000
        # 'Nauru'                      # micro-state in Oceania, population 11,000
        # Monaco             # micro-state in Europe, population 39,000
        # San Marino         # micro-state in Europe, population 33,500
        # Liechtenstein      # micro-state in Europe, population 38,500
        'Euro area',
        'IBRD only',
        'IDA & IBRD total',
        'IDA total',
        'IDA blend',
        'IDA only',
        'OECD members',
        'Small states',
        'Other small states',
        'Europe & Central Asia (excluding high income)',
        'East Asia & Pacific (excluding high income)',
        'Latin America & Caribbean (excluding high income)',
        'Middle East, North Africa, Afghanistan & Pakistan (excluding high income)',
        'Sub-Saharan Africa (excluding high income)',
        'East Asia & Pacific (IDA & IBRD countries)',
        'Europe & Central Asia (IDA & IBRD countries)',
        'Middle East, North Africa, Afghanistan & Pakistan (IDA & IBRD)',
        'Sub-Saharan Africa (IDA & IBRD countries)',           
        'Latin America & the Caribbean (IDA & IBRD countries)',
        'South Asia (IDA & IBRD)',
        'Heavily indebted poor countries (HIPC)',
        # 'Fragile and conflict affected situations',
        'Least developed countries: UN classification',
        'Early-demographic dividend',
        'Late-demographic dividend',
        'Pre-demographic dividend',
        'Post-demographic dividend',
        'Low income',
        'Lower middle income',
        'Low & middle income',
        'Middle income',
        'Upper middle income',
        'High income'
    ]
    
    ser = df.drop(ls_dropping) \
            [ls_cols] \
            .dropna(how='all') \
            .rename(index = {'Russian Federation': 'Russia',
                             'Korea, Rep.': 'South Korea',
                             'Egypt, Arab Rep.': 'Egypt',
                             'Congo, Dem. Rep.': 'DR Congo',   #'Congo, Democratic Republic of',
                             'Congo, Rep.': 'Congo', #'Republic of the Congo', #'Congo Republic',  #'Congo, Republic of',
                             'Yemen, Rep.': 'Yemen',
                             'Micronesia, Fed. Sts.': 'Micronesia',
                             'Gambia, The': 'Gambia',
                             'Iran, Islamic Rep.': 'Iran',
                             "Korea, Dem. People's Rep.": 'North Korea',
                             'Syrian Arab Republic': 'Syria',
                             'Venezuela, RB': 'Venezuela',
                             'Kyrgyz Republic': 'Kyrgyzstan',
                             'Lao PDR': 'Laos',
                             'Czech Republic': 'Czechia',
                             'Slovak Republic': 'Slovakia',
                             'Bahamas, The': 'Bahamas',
                             'Brunei Darussalam': 'Brunei',
                             'Turkiye': 'Türkiye',
                             'West Bank and Gaza': 'Palestinian Territories',
                             'Sint Maarten (Dutch part)': 'Sint Maarten',
                             'St. Martin (French part)': 'Saint Martin',
                             'Hong Kong SAR, China': 'Hong Kong',
                             'Macao SAR, China': 'Macao',
                             'Timor-Leste': 'East Timor',
                             'Virgin Islands (U.S.)': 'US Virgin Islands',
                             'Curacao': 'Curaçao',
                             'St. Vincent and the Grenadines': 'St Vincent and the Grenadines',
                             'St. Lucia': 'St Lucia',
                             'St. Kitts and Nevis': 'St Kitts and Nevis',
                             'Guinea-Bissau': 'Guinea Bissau',
                             "Cote d'Ivoire": "Cote d Ivoire",
                             'Faroe Islands': 'Faeroe Islands',
                             'Viet Nam': 'Vietnam',
                             'Puerto Rico (US)': 'Puerto Rico',
                             'Somalia, Fed. Rep.': 'Somalia',
                             'Naoero' : 'Nauru'
                            })
    
    return ser


selected_years = list(range(2010, 2025))
ls_cols = [str(year) for year in selected_years]
df = extract_data_for_year(df, ls_cols)
df.columns = selected_years

print(df.shape)
df.head(2).round(2)

(231, 15)

,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
Country Name,,,,,,,,,,,,,,,
Aruba,74.30,74.58,74.84,75.07,75.26,75.40,75.54,75.62,75.88,76.02,75.41,73.66,76.23,76.35,76.50
Africa Eastern and Southern,58.83,59.20,60.25,60.90,61.25,61.71,62.17,62.59,63.33,63.86,63.77,62.98,64.49,65.15,65.35

<br>

Determine minimal and maximal life expectancy for yeach year:

In [6]:
# pd.options.display.max_colwidth = 80
# df

In [7]:
mal.min_and_max_values(df, row_center=['Spain', 'France', 'World'], shorten=True, nmb=5, max_lng=13)

Number of records: 231

In [8]:
def filter_df(df, ls, selected_year=SELECTED_YEAR):
    filtered_df = df.loc[ls, [selected_year]]   \
                    .sort_values(by=selected_year, ascending=False) \
                    .dropna()
    
    filtered_df['group_label'] = filtered_df[selected_year].map(lambda x: f"{int(x)}.x")
    
    min_value = filtered_df[selected_year].min()
    max_value = filtered_df[selected_year].max()
    
    print(f"Range: {min_value:.2f} – {max_value:.2f}   " +
          f"({filtered_df[selected_year].idxmin()} – {filtered_df[selected_year].idxmax()})")
    print(f"Number of groups: {int(max_value) - int(min_value) +1}")
    print(f"Number of values: {len(filtered_df)}")

    return filtered_df

In [9]:
dd_legend_main = {
    '85.x' : '002000', 
    '84.x' : '004000', 
    '83.x' : '006000', 
    '82.x' : '008000', 
    '81.x' : '00a000', 
    '80.x' : '00c000', 
    '79.x' : '00e000', 
    '78.x' : '00ff00', 
    '77.x' : '9cff00', 
    '76.x' : 'd8ff00', 
    '75.x' : 'ffff00', 
    '74.x' : 'ffe000', 
    '73.x' : 'ffc000', 
    '72.x' : 'ffa000', 
    '71.x' : 'ff8000', 
    '70.x' : 'ff6000', 
    '69.x' : 'ff4000', 
    '68.x' : 'ff0000', 
    '67.x' : 'e00000', 
    '66.x' : 'c00000', 
    '65.x' : 'a00000', 
    '64.x' : '7c0000', 
    '63.x' : '540000', 
    '62.x' : '200000',
    '61.x' : '00bfff'}


def extract_indexes(subdf, dd_legend = dd_legend_main):
    group_label = subdf['group_label'].iloc[0]
    countries = subdf.index.to_list()
    color = (dd_legend[group_label])
    
    ls_grouping.append(CountryGroup(group_label=group_label, countries=countries, color=color))

    return pd.Series([color, countries], index=['color', 'countries'])

In [10]:
def create_legend_code(dd_legend):
    for k, v in dd_legend.items():
        print(f"{{{{Legend|#{v}|{k}}}}}")  
    print("{{Legend|#d1dbdd|no data}}")

if CREATE_LEGEND:
    create_legend_code(dd_legend_main)

In [11]:
def create_map_code(ls_grouping, region='', *, selected_year=SELECTED_YEAR):
    st = '{"groups":{'
    for group_label, color, countries in ls_grouping[::-1]:
        st_ls_countries = '"' + '","'.join(countries) + '"'
        st_ls_countries = st_ls_countries.replace(' ', '_')
        st += f'"#{color}":{{"label":"{group_label}","paths":[{st_ls_countries}]}},'
        # "#ccaa33":{"label":"89.x","paths":["Spain","Portugal"]},

    st = st[:-1] + '},"title":"' + str(selected_year)
    if region == 'Europe':
        st += '","hidden":["Scotland","Wales","England","Northern_Ireland","Kosovo"],"background":"#fff","borders":"#000","legendFont":"Century Gothic","legendFontColor":"#000","legendBgColor":"#00000000","legendWidth":150,"areBordersShown":true,"defaultColor":"#d1dbdd","labelsColor":"#6a0707","strokeWidth":"medium","areLabelsShown":false,"splitUK":false,"legendPosition":"custom","legendX":"140.00","legendY":"100.00","legendSize":"large","legendStatus":"show","scalingPatterns":true,"legendRowsSameColor":true,"legendColumnCount":1}'
    elif region == 'Middle East':
        st += '","hidden":[],"background":"#fff","borders":"#000","legendFont":"Century Gothic","legendFontColor":"#000","legendBgColor":"#00000000","legendWidth":150,"areBordersShown":true,"defaultColor":"#d1dbdd","labelsColor":"#6a0707","strokeWidth":"medium","areLabelsShown":false,"legendPosition":"custom","legendX":"23.00","legendY":"160.00","legendSize":"large","legendStatus":"show","scalingPatterns":true,"legendRowsSameColor":true,"legendColumnCount":1}'
    elif region == 'Asia':
        st += '","hidden":[],"background":"#fff","borders":"#000","legendFont":"Century Gothic","legendFontColor":"#000","legendBgColor":"#00000000","legendWidth":150,"areBordersShown":true,"defaultColor":"#d1dbdd","labelsColor":"#6a0707","strokeWidth":"medium","areLabelsShown":false,"legendPosition":"bottom_left","legendSize":"large","legendStatus":"show","scalingPatterns":true,"legendRowsSameColor":true,"legendColumnCount":2}'
    elif region == 'Caribbean':
        st += '","hidden":[],"background":"#fff","borders":"#000","legendFont":"Century Gothic","legendFontColor":"#000","legendBgColor":"#00000000","legendWidth":150,"areBordersShown":true,"defaultColor":"#d1dbdd","labelsColor":"#6a0707","strokeWidth":"medium","areLabelsShown":false,"legendPosition":"custom","legendX":"810.00","legendY":"0.00","legendSize":"large","legendStatus":"show","scalingPatterns":true,"legendRowsSameColor":true,"legendColumnCount":2}'
    elif region == 'Americas':
        st += '","hidden":[],"background":"#fff","borders":"#000","legendFont":"Century Gothic","legendFontColor":"#000","legendBgColor":"#00000000","legendWidth":150,"areBordersShown":true,"defaultColor":"#d1dbdd","labelsColor":"#6a0707","strokeWidth":"medium","areLabelsShown":false,"legendPosition":"custom","legendX":"105.00","legendY":"705.00","legendSize":"large","legendStatus":"show","scalingPatterns":true,"legendRowsSameColor":true,"legendColumnCount":1}'
    elif region == 'South America':
        st += '","hidden":["Greenland","Canada","United_States_of_America","Mexico","Guatemala","Honduras","El_Salvador","Belize","Panama","Nicaragua","Costa_Rica","Curaçao","Grenada","Barbados","St_Vincent_and_the_Grenadines","Cuba","Bahamas","Bermuda","Turks_and_Caicos_Islands","Dominican_Republic","Haiti","Jamaica","Cayman_Islands","Puerto_Rico","Virgin_Islands","British_Virgin_Islands","St_Kitts_and_Nevis","St_Pierre_et_Miquelon","Antigua_and_Barbuda","Guadeloupe","Montserrat","Dominica","St_Lucia","Martinique","Aruba","Trinidad_and_Tobago"],"background":"#fff","borders":"#000","legendFont":"Century Gothic","legendFontColor":"#000","legendBgColor":"#00000000","legendWidth":150,"areBordersShown":true,"defaultColor":"#d1dbdd","labelsColor":"#6a0707","strokeWidth":"medium","areLabelsShown":false,"legendPosition":"custom","legendX":"406.78","legendY":"890.64","legendSize":"medium","legendStatus":"show","scalingPatterns":true,"legendRowsSameColor":true,"legendColumnCount":1}'
    elif region == 'North America':
        st += '","hidden":["Chile","Argentina","Uruguay","Paraguay","Bolivia","Peru","Ecuador","Colombia","Venezuela","Guyana","Suriname","French_Guiana","Brazil","Falkland_Islands"],"background":"#fff","borders":"#000","legendFont":"Century Gothic","legendFontColor":"#000","legendBgColor":"#00000000","legendWidth":150,"areBordersShown":true,"defaultColor":"#d1dbdd","labelsColor":"#6a0707","strokeWidth":"medium","areLabelsShown":false,"legendPosition":"custom","legendX":"957.03","legendY":"320.39","legendSize":"medium","legendStatus":"show","scalingPatterns":true,"legendRowsSameColor":true,"legendColumnCount":1}'
    elif region == 'Central_America':
        st += '","hidden":[],"background":"#fff","borders":"#000","legendFont":"Century Gothic","legendFontColor":"#000","legendBgColor":"#00000000","legendWidth":150,"areBordersShown":true,"defaultColor":"#d1dbdd","labelsColor":"#6a0707","strokeWidth":"medium","areLabelsShown":true,"legendPosition":"custom","legendX":"318.25","legendY":"579.18","legendSize":"small","legendStatus":"show","scalingPatterns":true,"legendRowsSameColor":true,"legendColumnCount":2}'
    elif region == 'Africa':
        st += '","hidden":[],"background":"#fff","borders":"#000","legendFont":"Century Gothic","legendFontColor":"#000","legendBgColor":"#00000000","legendWidth":150,"areBordersShown":true,"defaultColor":"#d1dbdd","labelsColor":"#6a0707","strokeWidth":"medium","areLabelsShown":false,"legendPosition":"custom","legendX":"20.00","legendY":"195.00","legendSize":"large","legendStatus":"show","scalingPatterns":true,"legendRowsSameColor":true,"legendColumnCount":2}'
    elif region == 'Oceania':
        st += '","hidden":[],"background":"#fff","borders":"#000","legendFont":"Century Gothic","legendFontColor":"#000","legendBgColor":"#00000000","legendWidth":150,"areBordersShown":false,"defaultColor":"#d1dbdd","labelsColor":"#6a0707","strokeWidth":"medium","areLabelsShown":true,"legendPosition":"custom","legendX":"859.58","legendY":"434.26","legendSize":"large","legendStatus":"show","scalingPatterns":true,"legendRowsSameColor":true,"legendColumnCount":1}'
    elif region == 'world':
        st += '","hidden":["Prince_Edward_Island_CA","New_Brunswick_CA","Ontario_CA","British_Columbia_CA","Alberta_CA","Saskatchewan_CA","Manitoba_CA","Quebec_CA","Yukon_CA","Nunavut_CA","Newfoundland_and_Labrador_CA","Northwest_Territories_CA","Nova_Scotia_CA","Scotland","Wales","England","Northern_Ireland","USA_Wisconsin","USA_Montana","USA_Minnesota","USA_Washington","USA_Idaho","USA_North_Dakota","USA_Michigan","USA_Maine","USA_Ohio","USA_New_Hampshire","USA_New_York","USA_Vermont","USA_Pennsylvania","USA_Arizona","USA_California","USA_New_Mexico","USA_Texas","USA_Alaska","USA_Louisiana","USA_Mississippi","USA_Alabama","USA_Florida","USA_Georgia","USA_South_Carolina","USA_North_Carolina","USA_Virginia","USA_Washington_DC","USA_Maryland","USA_Delaware","USA_New_Jersey","USA_Connecticut","USA_Rhode_Island","USA_Massachusetts","USA_Oregon","USA_Hawaii","USA_Utah","USA_Wyoming","USA_Nevada","USA_Colorado","USA_South_Dakota","USA_Nebraska","USA_Kansas","USA_Oklahoma","USA_Iowa","USA_Missouri","USA_Illinois","USA_Kentucky","USA_Arkansas","USA_Tennessee","USA_West_Virginia","USA_Indiana"],"background":"#fff","borders":"#000","legendFont":"Century Gothic","legendFontColor":"#000","legendBgColor":"#00000000","legendWidth":150,"areBordersShown":true,"defaultColor":"#d1dbdd","labelsColor":"#6a0707","strokeWidth":"medium","areLabelsShown":false,"usaStatesShown":false,"canadaStatesShown":false,"splitUK":false,"legendPosition":"custom","legendX":"30.00","legendY":"300.00","legendSize":"large","legendStatus":"show","scalingPatterns":true,"legendRowsSameColor":true,"legendColumnCount":2}'

    return st

<br />
<br />
<br />

In [12]:
ls_EU = ['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus', 'Czechia', 'Denmark', 'Estonia', 'Finland', 'France', 'Germany', 'Greece', 'Hungary', 'Iceland',
         'Italy', 'Latvia', 'Lithuania', 'Luxembourg', 'Malta', 'Netherlands', 'Poland', 'Portugal', 'Romania', 'Slovakia', 'Slovenia', 'Spain', 'Sweden']

if SELECTED_YEAR <= 2019:
    ls_EU.append('United Kingdom')

df_EU = df.loc[ls_EU]
mal.min_and_max_values(df_EU, row_center=df.loc['European Union'], shorten=True, nmb=5, max_lng=13)

Number of records: 27

In [13]:
df_EU = filter_df(df, ls_EU, SELECTED_YEAR)

pd.options.display.max_rows=10
df_EU.round(2)

Range: 75.76 – 84.06   (Bulgaria – Sweden)
Number of groups: 10
Number of values: 27

               2024 group_label
Country Name
Sweden        84.06        84.x
Italy         83.95        83.x
Spain         83.89        83.x
Luxembourg    83.20        83.x
France        82.98        82.x
...             ...         ...
Lithuania     77.20        77.x
Hungary       76.72        76.x
Romania       76.46        76.x
Latvia        76.43        76.x
Bulgaria      75.76        75.x

[27 rows x 2 columns]

In [14]:
ls_grouping = []
df_EU.groupby(['group_label'])[['group_label']].apply(extract_indexes).loc[::-1]

              color                                          countries
group_label
84.x         004000                                           [Sweden]
83.x         006000                         [Italy, Spain, Luxembourg]
82.x         008000  [France, Malta, Iceland, Portugal, Finland, Be...
81.x         00a000             [Austria, Netherlands, Greece, Cyprus]
80.x         00c000                                          [Germany]
79.x         00e000                                 [Czechia, Estonia]
78.x         00ff00                        [Croatia, Poland, Slovakia]
77.x         9cff00                                        [Lithuania]
76.x         d8ff00                         [Hungary, Romania, Latvia]
75.x         ffff00                                         [Bulgaria]

In [15]:
st = create_map_code(ls_grouping, region='Europe')
print(st)

{"groups":{"#004000":{"label":"84.x","paths":["Sweden"]},"#006000":{"label":"83.x","paths":["Italy","Spain","Luxembourg"]},"#008000":{"label":"82.x","paths":["France","Malta","Iceland","Portugal","Finland","Belgium","Slovenia","Denmark"]},"#00a000":{"label":"81.x","paths":["Austria","Netherlands","Greece","Cyprus"]},"#00c000":{"label":"80.x","paths":["Germany"]},"#00e000":{"label":"79.x","paths":["Czechia","Estonia"]},"#00ff00":{"label":"78.x","paths":["Croatia","Poland","Slovakia"]},"#9cff00":{"label":"77.x","paths":["Lithuania"]},"#d8ff00":{"label":"76.x","paths":["Hungary","Romania","Latvia"]},"#ffff00":{"label":"75.x","paths":["Bulgaria"]}},"title":"2024","hidden":["Scotland","Wales","England","Northern_Ireland","Kosovo"],"background":"#fff","borders":"#000","legendFont":"Century Gothic","legendFontColor":"#000","legendBgColor":"#00000000","legendWidth":150,"areBordersShown":true,"defaultColor":"#d1dbdd","labelsColor":"#6a0707","strokeWidth":"medium","areLabelsShown":false,"splitUK":false,"legendPosition":"custom","legendX":"140.00","legendY":"100.00","legendSize":"large","legendStatus":"show","scalingPatterns":true,"legendRowsSameColor":true,"legendColumnCount":1}

In [16]:
if WRITE_TO_FILE:
    with open(f'output-map-code/EU-{SELECTED_YEAR}.txt', 'w') as fh:
        fh.write(st)

<br />
<br />
<br />

In [17]:
ls_Europe = ls_EU + ['Albania', 'Armenia', 'Azerbaijan', 'Belarus', 'Bosnia and Herzegovina', 'Georgia', 'Ireland', 'Kazakhstan', 'Liechtenstein',
                     'Moldova', 'Montenegro', 'North Macedonia', 'Norway', 'Russia', 'Serbia', 'Switzerland', 'Türkiye', 'Ukraine']
# in the database there are no data for Andorra, Monaco, San Marino, Vatican City

if SELECTED_YEAR >= 2020:
    ls_EU.append('United Kingdom')

df_Europe = df.loc[ls_Europe]
mal.min_and_max_values(df_Europe, row_center=df.loc['World'], shorten=True, nmb=5, max_lng=13)

Number of records: 45

In [18]:
df_Europe = filter_df(df, ls_Europe, SELECTED_YEAR)

pd.options.display.max_rows=10
df_Europe.round(2)

Range: 71.33 – 84.41   (Moldova – Switzerland)
Number of groups: 14
Number of values: 45

                2024 group_label
Country Name
Switzerland    84.41        84.x
Liechtenstein  84.20        84.x
Sweden         84.06        84.x
Italy          83.95        83.x
Spain          83.89        83.x
...              ...         ...
Azerbaijan     74.58        74.x
Kazakhstan     74.53        74.x
Belarus        74.37        74.x
Russia         73.44        73.x
Moldova        71.33        71.x

[45 rows x 2 columns]

In [19]:
ls_grouping = []
df_Europe.groupby(['group_label'])[['group_label']].apply(extract_indexes).loc[::-1]

              color                                          countries
group_label
84.x         004000               [Switzerland, Liechtenstein, Sweden]
83.x         006000        [Italy, Spain, Luxembourg, Norway, Ireland]
82.x         008000  [France, Malta, Iceland, Portugal, Finland, Be...
81.x         00a000             [Austria, Netherlands, Greece, Cyprus]
80.x         00c000                                          [Germany]
...             ...                                                ...
76.x         d8ff00        [Hungary, North Macedonia, Romania, Latvia]
75.x         ffff00                                 [Serbia, Bulgaria]
74.x         ffe000  [Ukraine, Georgia, Azerbaijan, Kazakhstan, Bel...
73.x         ffc000                                           [Russia]
71.x         ff8000                                          [Moldova]

[13 rows x 2 columns]

In [20]:
st = create_map_code(ls_grouping, region='Europe')
print(st)

{"groups":{"#004000":{"label":"84.x","paths":["Switzerland","Liechtenstein","Sweden"]},"#006000":{"label":"83.x","paths":["Italy","Spain","Luxembourg","Norway","Ireland"]},"#008000":{"label":"82.x","paths":["France","Malta","Iceland","Portugal","Finland","Belgium","Slovenia","Denmark"]},"#00a000":{"label":"81.x","paths":["Austria","Netherlands","Greece","Cyprus"]},"#00c000":{"label":"80.x","paths":["Germany"]},"#00e000":{"label":"79.x","paths":["Czechia","Albania","Estonia"]},"#00ff00":{"label":"78.x","paths":["Croatia","Poland","Slovakia","Armenia","Bosnia_and_Herzegovina"]},"#9cff00":{"label":"77.x","paths":["Montenegro","Türkiye","Lithuania"]},"#d8ff00":{"label":"76.x","paths":["Hungary","North_Macedonia","Romania","Latvia"]},"#ffff00":{"label":"75.x","paths":["Serbia","Bulgaria"]},"#ffe000":{"label":"74.x","paths":["Ukraine","Georgia","Azerbaijan","Kazakhstan","Belarus"]},"#ffc000":{"label":"73.x","paths":["Russia"]},"#ff8000":{"label":"71.x","paths":["Moldova"]}},"title":"2024","hidden":["Scotland","Wales","England","Northern_Ireland","Kosovo"],"background":"#fff","borders":"#000","legendFont":"Century Gothic","legendFontColor":"#000","legendBgColor":"#00000000","legendWidth":150,"areBordersShown":true,"defaultColor":"#d1dbdd","labelsColor":"#6a0707","strokeWidth":"medium","areLabelsShown":false,"splitUK":false,"legendPosition":"custom","legendX":"140.00","legendY":"100.00","legendSize":"large","legendStatus":"show","scalingPatterns":true,"legendRowsSameColor":true,"legendColumnCount":1}

In [21]:
if WRITE_TO_FILE:
    with open(f'output-map-code/Europe-{SELECTED_YEAR}.txt', 'w') as fh:
        fh.write(st)

<br />
<br />
<br />

In [22]:
ls_Europe_plus = ls_Europe + ['Algeria', 'Iran', 'Iraq', 'Israel', 'Jordan', 'Lebanon', 'Morocco', 'Saudi Arabia', 'Syria', 'Tunisia', 'Turkmenistan', 'Uzbekistan']

df_Europe_plus = df.loc[ls_Europe_plus]
mal.min_and_max_values(df_Europe_plus, row_center=df.loc['World'], shorten=True, nmb=5, max_lng=13)

Number of records: 57

In [23]:
df_Europe_plus = filter_df(df, ls_Europe_plus, SELECTED_YEAR)

pd.options.display.max_rows=10
df_Europe_plus.round(2)

Range: 70.20 – 84.41   (Turkmenistan – Switzerland)
Number of groups: 15
Number of values: 57

                2024 group_label
Country Name
Switzerland    84.41        84.x
Liechtenstein  84.20        84.x
Sweden         84.06        84.x
Italy          83.95        83.x
Spain          83.89        83.x
...              ...         ...
Syria          72.56        72.x
Uzbekistan     72.53        72.x
Iraq           72.42        72.x
Moldova        71.33        71.x
Turkmenistan   70.20        70.x

[57 rows x 2 columns]

In [24]:
ls_grouping = []
df_Europe_plus.groupby(['group_label'])[['group_label']].apply(extract_indexes).loc[::-1]

              color                                          countries
group_label
84.x         004000               [Switzerland, Liechtenstein, Sweden]
83.x         006000  [Italy, Spain, Israel, Luxembourg, Norway, Ire...
82.x         008000  [France, Malta, Iceland, Portugal, Finland, Be...
81.x         00a000             [Austria, Netherlands, Greece, Cyprus]
80.x         00c000                                          [Germany]
...             ...                                                ...
74.x         ffe000  [Ukraine, Georgia, Azerbaijan, Kazakhstan, Bel...
73.x         ffc000                                           [Russia]
72.x         ffa000                          [Syria, Uzbekistan, Iraq]
71.x         ff8000                                          [Moldova]
70.x         ff6000                                     [Turkmenistan]

[15 rows x 2 columns]

In [25]:
st = create_map_code(ls_grouping, region='Europe')
print(st)

{"groups":{"#004000":{"label":"84.x","paths":["Switzerland","Liechtenstein","Sweden"]},"#006000":{"label":"83.x","paths":["Italy","Spain","Israel","Luxembourg","Norway","Ireland"]},"#008000":{"label":"82.x","paths":["France","Malta","Iceland","Portugal","Finland","Belgium","Slovenia","Denmark"]},"#00a000":{"label":"81.x","paths":["Austria","Netherlands","Greece","Cyprus"]},"#00c000":{"label":"80.x","paths":["Germany"]},"#00e000":{"label":"79.x","paths":["Czechia","Albania","Estonia"]},"#00ff00":{"label":"78.x","paths":["Saudi_Arabia","Croatia","Poland","Slovakia","Armenia","Bosnia_and_Herzegovina"]},"#9cff00":{"label":"77.x","paths":["Jordan","Lebanon","Montenegro","Iran","Türkiye","Lithuania"]},"#d8ff00":{"label":"76.x","paths":["Hungary","Tunisia","North_Macedonia","Algeria","Romania","Latvia"]},"#ffff00":{"label":"75.x","paths":["Serbia","Bulgaria","Morocco"]},"#ffe000":{"label":"74.x","paths":["Ukraine","Georgia","Azerbaijan","Kazakhstan","Belarus"]},"#ffc000":{"label":"73.x","paths":["Russia"]},"#ffa000":{"label":"72.x","paths":["Syria","Uzbekistan","Iraq"]},"#ff8000":{"label":"71.x","paths":["Moldova"]},"#ff6000":{"label":"70.x","paths":["Turkmenistan"]}},"title":"2024","hidden":["Scotland","Wales","England","Northern_Ireland","Kosovo"],"background":"#fff","borders":"#000","legendFont":"Century Gothic","legendFontColor":"#000","legendBgColor":"#00000000","legendWidth":150,"areBordersShown":true,"defaultColor":"#d1dbdd","labelsColor":"#6a0707","strokeWidth":"medium","areLabelsShown":false,"splitUK":false,"legendPosition":"custom","legendX":"140.00","legendY":"100.00","legendSize":"large","legendStatus":"show","scalingPatterns":true,"legendRowsSameColor":true,"legendColumnCount":1}

In [26]:
if WRITE_TO_FILE:
    with open(f'output-map-code/Europe_plus-{SELECTED_YEAR}.txt', 'w') as fh:
        fh.write(st)

<br />
<br />
<br />

In [27]:
ls_M_East = ['Iran', 'Türkiye', 'Cyprus', 'Egypt', 'Iraq', 'Jordan', 'Syria', 'Oman', 'United Arab Emirates', 'Qatar',
             'Saudi Arabia', 'Yemen', 'Lebanon', 'Bahrain', 'Kuwait', 'Israel', 'Palestinian Territories',
             'Afghanistan', 'Pakistan']

df_M_East = df.loc[ls_M_East]
mal.min_and_max_values(df_M_East, row_center=df.loc['Middle East, North Africa, Afghanistan & Pakistan'], shorten=True, nmb=5, max_lng=13)

Number of records: 19

In [28]:
df_M_East = filter_df(df, ls_M_East, SELECTED_YEAR)

pd.options.display.max_rows=10
df_M_East.round(2)

Range: 66.29 – 84.58   (Afghanistan – Kuwait)
Number of groups: 19
Number of values: 19

                          2024 group_label
Country Name
Kuwait                   84.58        84.x
Israel                   83.20        83.x
United Arab Emirates     83.07        83.x
Qatar                    82.52        82.x
Cyprus                   81.82        81.x
...                        ...         ...
Egypt                    71.81        71.x
Yemen                    69.44        69.x
Palestinian Territories  69.21        69.x
Pakistan                 67.80        67.x
Afghanistan              66.29        66.x

[19 rows x 2 columns]

In [29]:
ls_grouping = []
df_M_East.groupby(['group_label'])[['group_label']].apply(extract_indexes).loc[::-1]

              color                         countries
group_label
84.x         004000                          [Kuwait]
83.x         006000    [Israel, United Arab Emirates]
82.x         008000                           [Qatar]
81.x         00a000                 [Cyprus, Bahrain]
80.x         00c000                            [Oman]
...             ...                               ...
72.x         ffa000                     [Syria, Iraq]
71.x         ff8000                           [Egypt]
69.x         ff4000  [Yemen, Palestinian Territories]
67.x         e00000                        [Pakistan]
66.x         c00000                     [Afghanistan]

[12 rows x 2 columns]

In [30]:
st = create_map_code(ls_grouping, region='Middle East')
print(st)

{"groups":{"#004000":{"label":"84.x","paths":["Kuwait"]},"#006000":{"label":"83.x","paths":["Israel","United_Arab_Emirates"]},"#008000":{"label":"82.x","paths":["Qatar"]},"#00a000":{"label":"81.x","paths":["Cyprus","Bahrain"]},"#00c000":{"label":"80.x","paths":["Oman"]},"#00ff00":{"label":"78.x","paths":["Saudi_Arabia"]},"#9cff00":{"label":"77.x","paths":["Jordan","Lebanon","Iran","Türkiye"]},"#ffa000":{"label":"72.x","paths":["Syria","Iraq"]},"#ff8000":{"label":"71.x","paths":["Egypt"]},"#ff4000":{"label":"69.x","paths":["Yemen","Palestinian_Territories"]},"#e00000":{"label":"67.x","paths":["Pakistan"]},"#c00000":{"label":"66.x","paths":["Afghanistan"]}},"title":"2024","hidden":[],"background":"#fff","borders":"#000","legendFont":"Century Gothic","legendFontColor":"#000","legendBgColor":"#00000000","legendWidth":150,"areBordersShown":true,"defaultColor":"#d1dbdd","labelsColor":"#6a0707","strokeWidth":"medium","areLabelsShown":false,"legendPosition":"custom","legendX":"23.00","legendY":"160.00","legendSize":"large","legendStatus":"show","scalingPatterns":true,"legendRowsSameColor":true,"legendColumnCount":1}

In [31]:
if WRITE_TO_FILE:
    with open(f'output-map-code/Middle_East-{SELECTED_YEAR}.txt', 'w') as fh:
        fh.write(st)

<br />
<br />
<br />

In [32]:
ls_Asia = ['China', 'Iran', 'Saudi Arabia', 'Türkiye', 'Armenia', 'Afghanistan', 'Israel', 'Sri Lanka', 'North Korea', 'Nepal', 'Turkmenistan', 'India',
           'Kyrgyzstan', 'Iraq', 'Thailand', 'Uzbekistan', 'Kazakhstan', 'Mongolia', 'Jordan', 'Syria', 'Oman', 'Bhutan', 'Tajikistan', 'Pakistan', 'Japan', 'South Korea',
           'Azerbaijan', 'East Timor', 'Hong Kong', 'Cambodia', 'Laos', 'Myanmar', 'Bangladesh', 'Georgia', 'Philippines', 'Bahrain', 'United Arab Emirates', 'Qatar',
           'Russia', 'Yemen', 'Malaysia', 'Lebanon', 'Kuwait', 'Indonesia', 'Vietnam', 'Singapore', 'Palestinian Territories', 'Maldives', 'Brunei']  # 'Macao'
# in the database there are no data for Taiwan

df_Asia = df.loc[ls_Asia]
mal.min_and_max_values(df_Asia, row_center=df.loc['World'], shorten=True, nmb=5, max_lng=13)

Number of records: 49

In [33]:
df_Asia = filter_df(df, ls_Asia, SELECTED_YEAR)

pd.options.display.max_rows=10
df_Asia.round(2)

Range: 66.29 – 85.39   (Afghanistan – Hong Kong)
Number of groups: 20
Number of values: 49

                          2024 group_label
Country Name
Hong Kong                85.39        85.x
Kuwait                   84.58        84.x
Japan                    84.04        84.x
South Korea              83.63        83.x
Singapore                83.35        83.x
...                        ...         ...
Palestinian Territories  69.21        69.x
East Timor               67.90        67.x
Pakistan                 67.80        67.x
Myanmar                  67.10        67.x
Afghanistan              66.29        66.x

[49 rows x 2 columns]

In [34]:
ls_grouping = []
df_Asia.groupby(['group_label'])[['group_label']].apply(extract_indexes).loc[::-1]

              color                                          countries
group_label
85.x         002000                                        [Hong Kong]
84.x         004000                                    [Kuwait, Japan]
83.x         006000  [South Korea, Singapore, Israel, United Arab E...
82.x         008000                                            [Qatar]
81.x         00a000                                [Bahrain, Maldives]
...             ...                                                ...
71.x         ff8000                            [Tajikistan, Indonesia]
70.x         ff6000                    [Cambodia, Nepal, Turkmenistan]
69.x         ff4000  [Philippines, Yemen, Laos, Palestinian Territo...
67.x         e00000                    [East Timor, Pakistan, Myanmar]
66.x         c00000                                      [Afghanistan]

[18 rows x 2 columns]

In [35]:
st = create_map_code(ls_grouping, region='Asia')
print(st)

{"groups":{"#002000":{"label":"85.x","paths":["Hong_Kong"]},"#004000":{"label":"84.x","paths":["Kuwait","Japan"]},"#006000":{"label":"83.x","paths":["South_Korea","Singapore","Israel","United_Arab_Emirates"]},"#008000":{"label":"82.x","paths":["Qatar"]},"#00a000":{"label":"81.x","paths":["Bahrain","Maldives"]},"#00c000":{"label":"80.x","paths":["Oman"]},"#00ff00":{"label":"78.x","paths":["Saudi_Arabia","Armenia","China"]},"#9cff00":{"label":"77.x","paths":["Jordan","Lebanon","Iran","Sri_Lanka","Türkiye"]},"#d8ff00":{"label":"76.x","paths":["Malaysia","Thailand"]},"#ffff00":{"label":"75.x","paths":["Brunei"]},"#ffe000":{"label":"74.x","paths":["Bangladesh","Vietnam","Georgia","Azerbaijan","Kazakhstan"]},"#ffc000":{"label":"73.x","paths":["North_Korea","Russia","Bhutan"]},"#ffa000":{"label":"72.x","paths":["Syria","Uzbekistan","Iraq","Kyrgyzstan","Mongolia","India"]},"#ff8000":{"label":"71.x","paths":["Tajikistan","Indonesia"]},"#ff6000":{"label":"70.x","paths":["Cambodia","Nepal","Turkmenistan"]},"#ff4000":{"label":"69.x","paths":["Philippines","Yemen","Laos","Palestinian_Territories"]},"#e00000":{"label":"67.x","paths":["East_Timor","Pakistan","Myanmar"]},"#c00000":{"label":"66.x","paths":["Afghanistan"]}},"title":"2024","hidden":[],"background":"#fff","borders":"#000","legendFont":"Century Gothic","legendFontColor":"#000","legendBgColor":"#00000000","legendWidth":150,"areBordersShown":true,"defaultColor":"#d1dbdd","labelsColor":"#6a0707","strokeWidth":"medium","areLabelsShown":false,"legendPosition":"bottom_left","legendSize":"large","legendStatus":"show","scalingPatterns":true,"legendRowsSameColor":true,"legendColumnCount":2}

In [36]:
if WRITE_TO_FILE:
    with open(f'output-map-code/Asia-{SELECTED_YEAR}.txt', 'w') as fh:
        fh.write(st)

In [37]:
#! East Timor should be added to the map manually - bug of the site

<br />
<br />
<br />

In [38]:
ls_Caribbean = ['Bahamas', 'British Virgin Islands', 'Cayman Islands', 'Turks and Caicos Islands', 'United States', 'Honduras',
                'Puerto Rico', 'US Virgin Islands', 'Venezuela', 'Dominican Republic', 'Saint Martin', 'Sint Maarten', 'Curaçao',
                'Aruba', 'Colombia', 'St Vincent and the Grenadines', 'Belize', 'Mexico', 'Guyana', 'Trinidad and Tobago', 'Grenada', 'Barbados', 'St Lucia',
                'El Salvador', 'Nicaragua', 'Costa Rica', 'Panama', 'Dominica', 'Cuba', 'St Kitts and Nevis', 'Antigua and Barbuda', 'Haiti', 'Jamaica', 'Guatemala']
# in the database there are no data for Anguilla, Montserrat, Guadeloupe, Bonaire, Saint Barthélemy, Martinique

df_Caribbean = df.loc[ls_Caribbean]
mal.min_and_max_values(df_Caribbean, row_center=df.loc['Latin America & Caribbean'], shorten=True, nmb=5, max_lng=13)

Number of records: 34

In [39]:
df_Caribbean = filter_df(df, ls_Caribbean, SELECTED_YEAR)

pd.options.display.max_rows=10
df_Caribbean.round(2)

Range: 65.12 – 81.90   (Haiti – Puerto Rico)
Number of groups: 17
Number of values: 34

                                2024 group_label
Country Name
Puerto Rico                    81.90        81.x
Costa Rica                     81.00        80.x
US Virgin Islands              80.77        80.x
Cayman Islands                 80.54        80.x
Saint Martin                   80.44        80.x
...                              ...         ...
Jamaica                        71.61        71.x
St Vincent and the Grenadines  71.38        71.x
Dominica                       71.29        71.x
Guyana                         70.32        70.x
Haiti                          65.12        65.x

[34 rows x 2 columns]

In [40]:
ls_grouping = []
df_Caribbean.groupby(['group_label'])[['group_label']].apply(extract_indexes).loc[::-1]

              color                                          countries
group_label
81.x         00a000                                      [Puerto Rico]
80.x         00c000  [Costa Rica, US Virgin Islands, Cayman Islands...
79.x         00e000                                           [Panama]
78.x         00ff00    [United States, Cuba, Turks and Caicos Islands]
77.x         9cff00  [Colombia, Antigua and Barbuda, British Virgin...
...             ...                                                ...
73.x         ffc000  [Dominican Republic, Belize, Trinidad and Toba...
72.x         ffa000  [St Lucia, Guatemala, Venezuela, El Salvador, ...
71.x         ff8000  [Jamaica, St Vincent and the Grenadines, Domin...
70.x         ff6000                                           [Guyana]
65.x         a00000                                            [Haiti]

[13 rows x 2 columns]

In [41]:
st = create_map_code(ls_grouping, region='Caribbean')
print(st)

{"groups":{"#00a000":{"label":"81.x","paths":["Puerto_Rico"]},"#00c000":{"label":"80.x","paths":["Costa_Rica","US_Virgin_Islands","Cayman_Islands","Saint_Martin"]},"#00e000":{"label":"79.x","paths":["Panama"]},"#00ff00":{"label":"78.x","paths":["United_States","Cuba","Turks_and_Caicos_Islands"]},"#9cff00":{"label":"77.x","paths":["Colombia","Antigua_and_Barbuda","British_Virgin_Islands"]},"#d8ff00":{"label":"76.x","paths":["Curaçao","Sint_Maarten","Aruba","Barbados"]},"#ffff00":{"label":"75.x","paths":["Grenada","Mexico","Nicaragua"]},"#ffe000":{"label":"74.x","paths":["Bahamas"]},"#ffc000":{"label":"73.x","paths":["Dominican_Republic","Belize","Trinidad_and_Tobago","Honduras"]},"#ffa000":{"label":"72.x","paths":["St_Lucia","Guatemala","Venezuela","El_Salvador","St_Kitts_and_Nevis"]},"#ff8000":{"label":"71.x","paths":["Jamaica","St_Vincent_and_the_Grenadines","Dominica"]},"#ff6000":{"label":"70.x","paths":["Guyana"]},"#a00000":{"label":"65.x","paths":["Haiti"]}},"title":"2024","hidden":[],"background":"#fff","borders":"#000","legendFont":"Century Gothic","legendFontColor":"#000","legendBgColor":"#00000000","legendWidth":150,"areBordersShown":true,"defaultColor":"#d1dbdd","labelsColor":"#6a0707","strokeWidth":"medium","areLabelsShown":false,"legendPosition":"custom","legendX":"810.00","legendY":"0.00","legendSize":"large","legendStatus":"show","scalingPatterns":true,"legendRowsSameColor":true,"legendColumnCount":2}

In [42]:
if WRITE_TO_FILE:
    with open(f'output-map-code/Caribbean-{SELECTED_YEAR}.txt', 'w') as fh:
        fh.write(st)

<br />
<br />
<br />

In [43]:
df.rename(index = {'United States': 'United States of America',
                   'US Virgin Islands': 'Virgin Islands'},
          inplace = True)

In [44]:
ls_Americas = ['Argentina', 'Mexico', 'Peru', 'Ecuador', 'Uruguay', 'Venezuela', 'Colombia', 'El Salvador', 'Bolivia', 'Brazil',
               'Cuba', 'Suriname', 'Jamaica', 'Chile', 'Guyana', 'Guatemala', 'Costa Rica', 'Honduras', 'Belize', 'Trinidad and Tobago',
               'Puerto Rico', 'Haiti', 'Dominican Republic', 'Nicaragua', 'Panama', 'Paraguay', 'United States of America', 'Canada', 'Bermuda',
               'British Virgin Islands', 'Turks and Caicos Islands', 'Virgin Islands', 'Curaçao', 'Aruba',
               'St Vincent and the Grenadines', 'Grenada', 'Barbados', 'St Lucia', 'Dominica', 'St Kitts and Nevis', 'Antigua and Barbuda',
               'Cayman Islands', 'Bahamas', 'Greenland']
# in the database there are no data for Falkland Islands, French Guiana, Montserrat, Guadeloupe, Martinique, St Pierre et Miquelon

df_Americas = df.loc[ls_Americas]
mal.min_and_max_values(df_Americas, row_center=df.loc['World'], shorten=True, nmb=5, max_lng=13)

Number of records: 44

In [45]:
df_Americas = filter_df(df, ls_Americas, SELECTED_YEAR)

pd.options.display.max_rows=10
df_Americas.round(2)

Range: 65.12 – 82.49   (Haiti – Bermuda)
Number of groups: 18
Number of values: 44

               2024 group_label
Country Name
Bermuda       82.49        82.x
Canada        82.11        82.x
Puerto Rico   81.90        81.x
Chile         81.36        81.x
Costa Rica    81.00        80.x
...             ...         ...
Dominica      71.29        71.x
Guyana        70.32        70.x
Greenland     70.27        70.x
Bolivia       68.74        68.x
Haiti         65.12        65.x

[44 rows x 2 columns]

In [46]:
ls_grouping = []
df_Americas.groupby(['group_label'])[['group_label']].apply(extract_indexes).loc[::-1]

              color                                          countries
group_label
82.x         008000                                  [Bermuda, Canada]
81.x         00a000                               [Puerto Rico, Chile]
80.x         00c000       [Costa Rica, Virgin Islands, Cayman Islands]
79.x         00e000                                           [Panama]
78.x         00ff00  [United States of America, Uruguay, Cuba, Turk...
...             ...                                                ...
72.x         ffa000  [St Lucia, Guatemala, Venezuela, El Salvador, ...
71.x         ff8000  [Jamaica, St Vincent and the Grenadines, Domin...
70.x         ff6000                                [Guyana, Greenland]
68.x         ff0000                                          [Bolivia]
65.x         a00000                                            [Haiti]

[15 rows x 2 columns]

In [47]:
st = create_map_code(ls_grouping, region='Americas')
print(st)

{"groups":{"#008000":{"label":"82.x","paths":["Bermuda","Canada"]},"#00a000":{"label":"81.x","paths":["Puerto_Rico","Chile"]},"#00c000":{"label":"80.x","paths":["Costa_Rica","Virgin_Islands","Cayman_Islands"]},"#00e000":{"label":"79.x","paths":["Panama"]},"#00ff00":{"label":"78.x","paths":["United_States_of_America","Uruguay","Cuba","Turks_and_Caicos_Islands"]},"#9cff00":{"label":"77.x","paths":["Peru","Colombia","Antigua_and_Barbuda","Ecuador","Argentina","British_Virgin_Islands"]},"#d8ff00":{"label":"76.x","paths":["Curaçao","Aruba","Barbados","Brazil"]},"#ffff00":{"label":"75.x","paths":["Grenada","Mexico","Nicaragua"]},"#ffe000":{"label":"74.x","paths":["Bahamas"]},"#ffc000":{"label":"73.x","paths":["Paraguay","Dominican_Republic","Suriname","Belize","Trinidad_and_Tobago","Honduras"]},"#ffa000":{"label":"72.x","paths":["St_Lucia","Guatemala","Venezuela","El_Salvador","St_Kitts_and_Nevis"]},"#ff8000":{"label":"71.x","paths":["Jamaica","St_Vincent_and_the_Grenadines","Dominica"]},"#ff6000":{"label":"70.x","paths":["Guyana","Greenland"]},"#ff0000":{"label":"68.x","paths":["Bolivia"]},"#a00000":{"label":"65.x","paths":["Haiti"]}},"title":"2024","hidden":[],"background":"#fff","borders":"#000","legendFont":"Century Gothic","legendFontColor":"#000","legendBgColor":"#00000000","legendWidth":150,"areBordersShown":true,"defaultColor":"#d1dbdd","labelsColor":"#6a0707","strokeWidth":"medium","areLabelsShown":false,"legendPosition":"custom","legendX":"105.00","legendY":"705.00","legendSize":"large","legendStatus":"show","scalingPatterns":true,"legendRowsSameColor":true,"legendColumnCount":1}

In [48]:
if WRITE_TO_FILE:
    with open(f'output-map-code/Americas-{SELECTED_YEAR}.txt', 'w') as fh:
        fh.write(st)

<br />
<br />
<br />

In [49]:
ls_S_America = ['Argentina', 'Peru', 'Ecuador', 'Uruguay', 'Venezuela', 'Colombia', 'Bolivia', 'Brazil', 'Suriname', 'Chile', 'Guyana', 'Paraguay']
# in the database there are no data for Falkland Islands, French Guiana

df_S_America = df.loc[ls_S_America]
mal.min_and_max_values(df_S_America, row_center=df.loc['Latin America & Caribbean'], shorten=True, nmb=5, max_lng=13)

Number of records: 12

In [50]:
df_S_America = filter_df(df, ls_S_America, SELECTED_YEAR)

pd.options.display.max_rows=10
df_S_America.round(2)

Range: 68.74 – 81.36   (Bolivia – Chile)
Number of groups: 14
Number of values: 12

               2024 group_label
Country Name
Chile         81.36        81.x
Uruguay       78.29        78.x
Peru          77.94        77.x
Colombia      77.91        77.x
Ecuador       77.58        77.x
...             ...         ...
Paraguay      73.98        73.x
Suriname      73.76        73.x
Venezuela     72.67        72.x
Guyana        70.32        70.x
Bolivia       68.74        68.x

[12 rows x 2 columns]

In [51]:
ls_grouping = []
df_S_America.groupby(['group_label'])[['group_label']].apply(extract_indexes).loc[::-1]

              color                             countries
group_label
81.x         00a000                               [Chile]
78.x         00ff00                             [Uruguay]
77.x         9cff00  [Peru, Colombia, Ecuador, Argentina]
76.x         d8ff00                              [Brazil]
73.x         ffc000                  [Paraguay, Suriname]
72.x         ffa000                           [Venezuela]
70.x         ff6000                              [Guyana]
68.x         ff0000                             [Bolivia]

In [52]:
st = create_map_code(ls_grouping, region='South America')
print(st)

{"groups":{"#00a000":{"label":"81.x","paths":["Chile"]},"#00ff00":{"label":"78.x","paths":["Uruguay"]},"#9cff00":{"label":"77.x","paths":["Peru","Colombia","Ecuador","Argentina"]},"#d8ff00":{"label":"76.x","paths":["Brazil"]},"#ffc000":{"label":"73.x","paths":["Paraguay","Suriname"]},"#ffa000":{"label":"72.x","paths":["Venezuela"]},"#ff6000":{"label":"70.x","paths":["Guyana"]},"#ff0000":{"label":"68.x","paths":["Bolivia"]}},"title":"2024","hidden":["Greenland","Canada","United_States_of_America","Mexico","Guatemala","Honduras","El_Salvador","Belize","Panama","Nicaragua","Costa_Rica","Curaçao","Grenada","Barbados","St_Vincent_and_the_Grenadines","Cuba","Bahamas","Bermuda","Turks_and_Caicos_Islands","Dominican_Republic","Haiti","Jamaica","Cayman_Islands","Puerto_Rico","Virgin_Islands","British_Virgin_Islands","St_Kitts_and_Nevis","St_Pierre_et_Miquelon","Antigua_and_Barbuda","Guadeloupe","Montserrat","Dominica","St_Lucia","Martinique","Aruba","Trinidad_and_Tobago"],"background":"#fff","borders":"#000","legendFont":"Century Gothic","legendFontColor":"#000","legendBgColor":"#00000000","legendWidth":150,"areBordersShown":true,"defaultColor":"#d1dbdd","labelsColor":"#6a0707","strokeWidth":"medium","areLabelsShown":false,"legendPosition":"custom","legendX":"406.78","legendY":"890.64","legendSize":"medium","legendStatus":"show","scalingPatterns":true,"legendRowsSameColor":true,"legendColumnCount":1}

In [53]:
if WRITE_TO_FILE:
    with open(f'output-map-code/America_South-{SELECTED_YEAR}.txt', 'w') as fh:
        fh.write(st)

<br />
<br />
<br />

In [54]:
ls_N_America = ['Mexico', 'El Salvador', 'Cuba', 'Jamaica', 'Guatemala', 'Costa Rica', 'Honduras', 'Belize', 'Trinidad and Tobago', 'Puerto Rico',
                'Haiti', 'Dominican Republic', 'Nicaragua', 'Panama', 'United States of America', 'Canada', 'Bermuda', 'British Virgin Islands',
                'Turks and Caicos Islands', 'Virgin Islands', 'Curaçao', 'Aruba', 'St Vincent and the Grenadines', 'Grenada', 'Barbados',
                'St Lucia', 'Dominica', 'St Kitts and Nevis', 'Antigua and Barbuda', 'Cayman Islands', 'Bahamas', 'Greenland']
# in the database there are no data for Montserrat, Guadeloupe, Martinique, St Pierre et Miquelon

df_N_America = df.loc[ls_N_America]
mal.min_and_max_values(df_N_America, row_center=df.loc['North America'], shorten=True, nmb=5, max_lng=13)

Number of records: 32

In [55]:
df_N_America = filter_df(df, ls_N_America, SELECTED_YEAR)

pd.options.display.max_rows=10
df_N_America.round(2)

Range: 65.12 – 82.49   (Haiti – Bermuda)
Number of groups: 18
Number of values: 32

                                2024 group_label
Country Name
Bermuda                        82.49        82.x
Canada                         82.11        82.x
Puerto Rico                    81.90        81.x
Costa Rica                     81.00        80.x
Virgin Islands                 80.77        80.x
...                              ...         ...
Jamaica                        71.61        71.x
St Vincent and the Grenadines  71.38        71.x
Dominica                       71.29        71.x
Greenland                      70.27        70.x
Haiti                          65.12        65.x

[32 rows x 2 columns]

In [56]:
ls_grouping = []
df_N_America.groupby(['group_label'])[['group_label']].apply(extract_indexes).loc[::-1]

              color                                          countries
group_label
82.x         008000                                  [Bermuda, Canada]
81.x         00a000                                      [Puerto Rico]
80.x         00c000       [Costa Rica, Virgin Islands, Cayman Islands]
79.x         00e000                                           [Panama]
78.x         00ff00  [United States of America, Cuba, Turks and Cai...
...             ...                                                ...
73.x         ffc000  [Dominican Republic, Belize, Trinidad and Toba...
72.x         ffa000  [St Lucia, Guatemala, El Salvador, St Kitts an...
71.x         ff8000  [Jamaica, St Vincent and the Grenadines, Domin...
70.x         ff6000                                        [Greenland]
65.x         a00000                                            [Haiti]

[14 rows x 2 columns]

In [57]:
st = create_map_code(ls_grouping, region='North America')
print(st)

{"groups":{"#008000":{"label":"82.x","paths":["Bermuda","Canada"]},"#00a000":{"label":"81.x","paths":["Puerto_Rico"]},"#00c000":{"label":"80.x","paths":["Costa_Rica","Virgin_Islands","Cayman_Islands"]},"#00e000":{"label":"79.x","paths":["Panama"]},"#00ff00":{"label":"78.x","paths":["United_States_of_America","Cuba","Turks_and_Caicos_Islands"]},"#9cff00":{"label":"77.x","paths":["Antigua_and_Barbuda","British_Virgin_Islands"]},"#d8ff00":{"label":"76.x","paths":["Curaçao","Aruba","Barbados"]},"#ffff00":{"label":"75.x","paths":["Grenada","Mexico","Nicaragua"]},"#ffe000":{"label":"74.x","paths":["Bahamas"]},"#ffc000":{"label":"73.x","paths":["Dominican_Republic","Belize","Trinidad_and_Tobago","Honduras"]},"#ffa000":{"label":"72.x","paths":["St_Lucia","Guatemala","El_Salvador","St_Kitts_and_Nevis"]},"#ff8000":{"label":"71.x","paths":["Jamaica","St_Vincent_and_the_Grenadines","Dominica"]},"#ff6000":{"label":"70.x","paths":["Greenland"]},"#a00000":{"label":"65.x","paths":["Haiti"]}},"title":"2024","hidden":["Chile","Argentina","Uruguay","Paraguay","Bolivia","Peru","Ecuador","Colombia","Venezuela","Guyana","Suriname","French_Guiana","Brazil","Falkland_Islands"],"background":"#fff","borders":"#000","legendFont":"Century Gothic","legendFontColor":"#000","legendBgColor":"#00000000","legendWidth":150,"areBordersShown":true,"defaultColor":"#d1dbdd","labelsColor":"#6a0707","strokeWidth":"medium","areLabelsShown":false,"legendPosition":"custom","legendX":"957.03","legendY":"320.39","legendSize":"medium","legendStatus":"show","scalingPatterns":true,"legendRowsSameColor":true,"legendColumnCount":1}

In [58]:
if WRITE_TO_FILE:
    with open(f'output-map-code/America_North-{SELECTED_YEAR}.txt', 'w') as fh:
        fh.write(st)

<br />
<br />
<br />

In [59]:
ls_C_America = ['Belize', 'Costa Rica', 'El Salvador', 'Guatemala', 'Honduras', 'Nicaragua', 'Panama',
                'Mexico', 'Cayman Islands', 'Colombia']  # 'Jamaica', 
# 'Cayman Islands' has data only for 2010

df_C_America = df.loc[ls_C_America]
mal.min_and_max_values(df_C_America, row_center=df.loc['Latin America & Caribbean'], shorten=True, nmb=5, max_lng=13)

Number of records: 10

In [60]:
df_C_America = filter_df(df, ls_C_America, SELECTED_YEAR)

pd.options.display.max_rows=10
df_C_America.round(2)

Range: 72.30 – 81.00   (El Salvador – Costa Rica)
Number of groups: 9
Number of values: 10

                 2024 group_label
Country Name
Costa Rica      81.00        80.x
Cayman Islands  80.54        80.x
Panama          79.78        79.x
Colombia        77.91        77.x
Mexico          75.26        75.x
Nicaragua       75.10        75.x
Belize          73.74        73.x
Honduras        73.04        73.x
Guatemala       72.75        72.x
El Salvador     72.30        72.x

In [61]:
ls_grouping = []
df_C_America.groupby(['group_label'])[['group_label']].apply(extract_indexes).loc[::-1]

              color                     countries
group_label
80.x         00c000  [Costa Rica, Cayman Islands]
79.x         00e000                      [Panama]
77.x         9cff00                    [Colombia]
75.x         ffff00           [Mexico, Nicaragua]
73.x         ffc000            [Belize, Honduras]
72.x         ffa000      [Guatemala, El Salvador]

In [62]:
st = create_map_code(ls_grouping, region='Central_America')
print(st)

{"groups":{"#00c000":{"label":"80.x","paths":["Costa_Rica","Cayman_Islands"]},"#00e000":{"label":"79.x","paths":["Panama"]},"#9cff00":{"label":"77.x","paths":["Colombia"]},"#ffff00":{"label":"75.x","paths":["Mexico","Nicaragua"]},"#ffc000":{"label":"73.x","paths":["Belize","Honduras"]},"#ffa000":{"label":"72.x","paths":["Guatemala","El_Salvador"]}},"title":"2024","hidden":[],"background":"#fff","borders":"#000","legendFont":"Century Gothic","legendFontColor":"#000","legendBgColor":"#00000000","legendWidth":150,"areBordersShown":true,"defaultColor":"#d1dbdd","labelsColor":"#6a0707","strokeWidth":"medium","areLabelsShown":true,"legendPosition":"custom","legendX":"318.25","legendY":"579.18","legendSize":"small","legendStatus":"show","scalingPatterns":true,"legendRowsSameColor":true,"legendColumnCount":2}

In [63]:
if WRITE_TO_FILE:
    with open(f'output-map-code/Americas-{SELECTED_YEAR}.txt', 'w') as fh:
        fh.write(st)

<br />
<br />
<br />

Latin America - special issue

In [64]:
ls_L_America = ['Argentina', 'Bolivia', 'Brazil', 'Chile', 'Colombia', 'Costa Rica', 'Cuba', 'Dominican Republic',
                'Ecuador', 'El Salvador', 'Guatemala', 'Haiti', 'Honduras', 'Mexico', 'Nicaragua', 'Panama',
                'Paraguay', 'Peru', 'Puerto Rico', 'Saint Martin', 'Uruguay', 'Venezuela']
# in the database there are no data for French Guiana, Guadeloupe, Martinique, Saint Barthélemy

df_L_America = df.loc[ls_L_America]
mal.min_and_max_values(df_L_America, row_center=df.loc['Latin America & Caribbean'], shorten=True, nmb=5, max_lng=13)

Number of records: 22

In [65]:
df_L_America = filter_df(df, ls_L_America, SELECTED_YEAR)

pd.options.display.max_rows=10
df_L_America.round(2)

Range: 65.12 – 81.90   (Haiti – Puerto Rico)
Number of groups: 17
Number of values: 22

               2024 group_label
Country Name
Puerto Rico   81.90        81.x
Chile         81.36        81.x
Costa Rica    81.00        80.x
Saint Martin  80.44        80.x
Panama        79.78        79.x
...             ...         ...
Guatemala     72.75        72.x
Venezuela     72.67        72.x
El Salvador   72.30        72.x
Bolivia       68.74        68.x
Haiti         65.12        65.x

[22 rows x 2 columns]

In [66]:
ls_grouping = []
df_L_America.groupby(['group_label'])[['group_label']].apply(extract_indexes).loc[::-1]

              color                                 countries
group_label
81.x         00a000                      [Puerto Rico, Chile]
80.x         00c000                [Costa Rica, Saint Martin]
79.x         00e000                                  [Panama]
78.x         00ff00                           [Uruguay, Cuba]
77.x         9cff00      [Peru, Colombia, Ecuador, Argentina]
...             ...                                       ...
75.x         ffff00                       [Mexico, Nicaragua]
73.x         ffc000  [Paraguay, Dominican Republic, Honduras]
72.x         ffa000       [Guatemala, Venezuela, El Salvador]
68.x         ff0000                                 [Bolivia]
65.x         a00000                                   [Haiti]

[11 rows x 2 columns]

In [67]:
def create_map_code_Latin_America(ls_grouping):
    st = '{"groups":{'
    for group_label, color, countries in ls_grouping[::-1]:
        st_ls_countries = '"' + '","'.join(countries) + '"'
        st_ls_countries = st_ls_countries.replace(' ', '_')
        st += f'"#{color}":{{"label":"{group_label}","paths":[{st_ls_countries}]}},'
        # "#ccaa33":{"label":"89.x","paths":["Spain","Portugal"]},

    st = st[:-1] + ',"#aaaaaa":{"label":"no data","paths":["French_Guiana","Guadeloupe","Martinique"]},"#eeeeee":{"label":"","paths":["Falkland_Islands","Suriname","Jamaica","Guyana","Belize","Trinidad_and_Tobago","United_States_of_America","Canada","Bermuda","British_Virgin_Islands","Montserrat","Turks_and_Caicos_Islands","Virgin_Islands","Curaçao","Aruba","St_Vincent_and_the_Grenadines","Grenada","Barbados","St_Lucia","Dominica","St_Kitts_and_Nevis","Antigua_and_Barbuda","St_Pierre_et_Miquelon","Cayman_Islands","Bahamas","Greenland"]}},"title":"' + str(SELECTED_YEAR)
    st += '","hidden":[],"background":"#fff","borders":"#000","legendFont":"Century Gothic","legendFontColor":"#000","legendBgColor":"#00000000","legendWidth":150,"areBordersShown":true,"defaultColor":"#d1dbdd","labelsColor":"#6a0707","strokeWidth":"medium","areLabelsShown":false,"legendPosition":"custom","legendX":"292.66","legendY":"772.17","legendSize":"large","legendStatus":"show","scalingPatterns":true,"legendRowsSameColor":true,"legendColumnCount":1}'
    return st

st = create_map_code_Latin_America(ls_grouping)
print(st)

{"groups":{"#00a000":{"label":"81.x","paths":["Puerto_Rico","Chile"]},"#00c000":{"label":"80.x","paths":["Costa_Rica","Saint_Martin"]},"#00e000":{"label":"79.x","paths":["Panama"]},"#00ff00":{"label":"78.x","paths":["Uruguay","Cuba"]},"#9cff00":{"label":"77.x","paths":["Peru","Colombia","Ecuador","Argentina"]},"#d8ff00":{"label":"76.x","paths":["Brazil"]},"#ffff00":{"label":"75.x","paths":["Mexico","Nicaragua"]},"#ffc000":{"label":"73.x","paths":["Paraguay","Dominican_Republic","Honduras"]},"#ffa000":{"label":"72.x","paths":["Guatemala","Venezuela","El_Salvador"]},"#ff0000":{"label":"68.x","paths":["Bolivia"]},"#a00000":{"label":"65.x","paths":["Haiti"]},"#aaaaaa":{"label":"no data","paths":["French_Guiana","Guadeloupe","Martinique"]},"#eeeeee":{"label":"","paths":["Falkland_Islands","Suriname","Jamaica","Guyana","Belize","Trinidad_and_Tobago","United_States_of_America","Canada","Bermuda","British_Virgin_Islands","Montserrat","Turks_and_Caicos_Islands","Virgin_Islands","Curaçao","Aruba","St_Vincent_and_the_Grenadines","Grenada","Barbados","St_Lucia","Dominica","St_Kitts_and_Nevis","Antigua_and_Barbuda","St_Pierre_et_Miquelon","Cayman_Islands","Bahamas","Greenland"]}},"title":"2024","hidden":[],"background":"#fff","borders":"#000","legendFont":"Century Gothic","legendFontColor":"#000","legendBgColor":"#00000000","legendWidth":150,"areBordersShown":true,"defaultColor":"#d1dbdd","labelsColor":"#6a0707","strokeWidth":"medium","areLabelsShown":false,"legendPosition":"custom","legendX":"292.66","legendY":"772.17","legendSize":"large","legendStatus":"show","scalingPatterns":true,"legendRowsSameColor":true,"legendColumnCount":1}

In [68]:
if WRITE_TO_FILE:
    with open(f'output-map-code/America_Latin-{SELECTED_YEAR}.txt', 'w') as fh:
        fh.write(st)

<br />
<br />
<br />

Oceania - special issue

In [69]:
ls_Oceania = ['Australia', 'Papua New Guinea', 'New Zealand', 'Fiji', 'Solomon Islands', 'Vanuatu',
              'Samoa', 'Kiribati', 'Micronesia', 'Tonga', 'Marshall Islands', 'Nauru', 'Tuvalu',
              'French Polynesia', 'New Caledonia']  # 'Guam'
# other states on the map of Oceanis, for those the WBG database has no data:
# 'Palau' : ['Palau  PW', 'Hatobohei PW']
# 'American Samoa' : ['American Samoa  AS', 'Western AS', 'Eastern AS', 'Manu s AS', 'Rose Atoll AS', 'Swain s Island AS']
# 'Cook Islands' : ['Cook Islands  CK', 'Mangaia CK', 'Mitiaro CK', 'Rarotonga CK', 'Penrhyn CK', 'Mauke CK', 'Atiu CK', 'Aitutaki CK', 'Pukapuka CK', 'Manihiki CK', 'Rakahanga CK', 'Palmerston CK']
# 'Wallis and Futuna' : ['Wallis and Futuna WF', 'Sigave WF', 'Alo WF', 'Uvea WF']
# 'Niue' : ['Niue  NU', 'Niue NU']
# 'Tokelau' : ['Tokelau TK', 'Tokelau  TK']




df_Oceania = df.loc[ls_Oceania]
mal.min_and_max_values(df_Oceania, row_center=df.loc['East Asia & Pacific'], shorten=True, nmb=5, max_lng=13)

Number of records: 15

In [70]:
df_Oceania = filter_df(df, ls_Oceania, SELECTED_YEAR)

pd.options.display.max_rows=10
df_Oceania.round(2)

Range: 62.28 – 84.19   (Nauru – French Polynesia)
Number of groups: 23
Number of values: 15

                   2024 group_label
Country Name
French Polynesia  84.19        84.x
Australia         83.05        83.x
New Zealand       82.01        82.x
New Caledonia     78.92        78.x
Tonga             73.07        73.x
...                 ...         ...
Tuvalu            67.26        67.x
Marshall Islands  67.08        67.x
Kiribati          66.60        66.x
Papua New Guinea  66.26        66.x
Nauru             62.28        62.x

[15 rows x 2 columns]

In [71]:
df_Oceania_territories = pd.DataFrame()
df_Oceania_territories

dd_territories = {
    'Australia' : ['Western Australia AU', 'Northern Territory AU', 'South Australia AU', 'Queensland AU', 'New South Wales AU', 'Jervis Bay Territory AU', 'Victoria AU', 'Macquarie Island AU', 'Tasmania AU', 'Lord Howe Island AU', 'Norfolk Island AU', 'Ashmore and Cartier Islands AU', 'Australian Capital Territory AU'],
    'New Zealand' : ['Auckland Islands NZ', 'Campbell Islands NZ', 'Antipodes Islands NZ', 'The Snares NZ', 'Southland NZ', 'Marlborough District NZ', 'Nelson City NZ', 'Tasman District NZ', 'West Coast NZ', 'Otago NZ', 'Canterbury NZ', 'Auckland NZ', 'Waikato NZ', 'Three Kings Islands NZ', 'Wellington NZ', 'Manawatu-Wanganui NZ', 'Taranaki NZ', 'Northland NZ', 'Bay of Plenty NZ', 'Gisborne District NZ', 'Hawke s Bay NZ', 'Chatham Islands Territory NZ', 'Kermadec Islands NZ'],
    'Papua New Guinea' : ['Sandaun PG', 'Western PG', 'East Sepik PG', 'Madang PG', 'Morobe PG', 'Northern PG', 'Milne Bay PG', 'Central PG', 'National Capital District PG', 'Gulf PG', 'North Solomons PG', 'West New Britain PG', 'East New Britain PG', 'New Ireland PG', 'Manus PG', 'Chimbu PG', 'Enga PG', 'Western Highlands PG', 'Jiwaka PG', 'Southern Highlands PG', 'Hela PG', 'Eastern Highlands PG'],
    'French Polynesia' : ['Tuamotu-Gambier PF', 'Windward Islands PF', 'Leeward Islands PF', 'Austral Islands PF', 'Marquesas Islands PF', 'French Polynesia PF'],
    'New Caledonia' : ['Sud NC', 'Nord NC', 'Îles Loyauté NC'],
    'Fiji' : ['Eastern FJ', 'Western FJ', 'Central FJ', 'Northern FJ', 'Rotuma FJ'],
    'Solomon Islands' : ['Rennell and Bellona SB', 'Makira SB', 'Temotu SB', 'Malaita SB', 'Capital Territory Honiara SB', 'Guadalcanal SB', 'Central SB', 'Western SB', 'Isabel SB', 'Choiseul SB'],
    'Vanuatu' : ['Tafea VU', 'Shefa VU', 'Malampa VU', 'Sanma VU', 'Penama VU', 'Torba VU'],
    'Tuvalu' : ['Tuvalu  TV', 'Tuvalu TV'],
    'Kiribati' : ['Kiribati  KI', 'Kiribati KI'],
    'Micronesia' : ['Federated States of Micronesia  FM', 'Kosrae FM', 'Pohnpei FM', 'Chuuk FM', 'Yap FM'],
    'Samoa' : ['Samoa  WS', 'Gaga emauga WS', 'Gaga ifomauga WS', 'Vaisigano WS', 'Satupa itea WS', 'Palauli WS', 'Fa asaleleaga WS', 'Atua WS', 'Va a-o-Fonoti WS', 'Tuamasaga WS', 'A ana WS', 'Aiga-i-le-Tai WS'],
    'Tonga' : ['Tonga  TO', 'Vava u TO', 'Eua TO', 'Tongatapu TO', 'Ha apai TO', 'Niuas TO'],
    'Marshall Islands' : ['Marshall Islands  MH', 'Railik Chain MH', 'Ratak Chain MH'],
    'Nauru' : ['Nauru  NR', 'Anetan NR', 'Ewa NR', 'Baiti NR', 'Uaboe NR', 'Nibok NR', 'Denigomodu NR', 'Aiwo NR', 'Boe NR', 'Yaren NR', 'Meneng NR', 'Anibare NR', 'Ijuw NR', 'Anabar NR', 'Buada NR']
}


for country, ls_territories in dd_territories.items():
    
    ser_country = df_Oceania.loc[country]
    
    df_temp = pd.concat([ser_country] * len(ls_territories), axis=1, keys=ls_territories).T
    
    # df_Oceania_territories = df_Oceania_territories.append(df_temp)
    df_Oceania_territories = pd.concat([df_Oceania_territories, df_temp], axis=0)


df_Oceania_territories

                           2024 group_label
Western Australia AU   83.05122        83.x
Northern Territory AU  83.05122        83.x
South Australia AU     83.05122        83.x
Queensland AU          83.05122        83.x
New South Wales AU     83.05122        83.x
...                         ...         ...
Meneng NR                62.279        62.x
Anibare NR               62.279        62.x
Ijuw NR                  62.279        62.x
Anabar NR                62.279        62.x
Buada NR                 62.279        62.x

[133 rows x 2 columns]

In [72]:
ls_grouping = []
df_Oceania_territories.groupby(['group_label'])[['group_label']].apply(extract_indexes).loc[::-1]

              color                                          countries
group_label
84.x         004000  [Tuamotu-Gambier PF, Windward Islands PF, Leew...
83.x         006000  [Western Australia AU, Northern Territory AU, ...
82.x         008000  [Auckland Islands NZ, Campbell Islands NZ, Ant...
78.x         00ff00                 [Sud NC, Nord NC, Îles Loyauté NC]
73.x         ffc000  [Tonga  TO, Vava u TO, Eua TO, Tongatapu TO, H...
71.x         ff8000  [Tafea VU, Shefa VU, Malampa VU, Sanma VU, Pen...
70.x         ff6000  [Rennell and Bellona SB, Makira SB, Temotu SB,...
67.x         e00000  [Eastern FJ, Western FJ, Central FJ, Northern ...
66.x         c00000  [Sandaun PG, Western PG, East Sepik PG, Madang...
62.x         200000  [Nauru  NR, Anetan NR, Ewa NR, Baiti NR, Uaboe...

In [73]:
st = create_map_code(ls_grouping, region='Oceania')
print(st)

{"groups":{"#004000":{"label":"84.x","paths":["Tuamotu-Gambier_PF","Windward_Islands_PF","Leeward_Islands_PF","Austral_Islands_PF","Marquesas_Islands_PF","French_Polynesia_PF"]},"#006000":{"label":"83.x","paths":["Western_Australia_AU","Northern_Territory_AU","South_Australia_AU","Queensland_AU","New_South_Wales_AU","Jervis_Bay_Territory_AU","Victoria_AU","Macquarie_Island_AU","Tasmania_AU","Lord_Howe_Island_AU","Norfolk_Island_AU","Ashmore_and_Cartier_Islands_AU","Australian_Capital_Territory_AU"]},"#008000":{"label":"82.x","paths":["Auckland_Islands_NZ","Campbell_Islands_NZ","Antipodes_Islands_NZ","The_Snares_NZ","Southland_NZ","Marlborough_District_NZ","Nelson_City_NZ","Tasman_District_NZ","West_Coast_NZ","Otago_NZ","Canterbury_NZ","Auckland_NZ","Waikato_NZ","Three_Kings_Islands_NZ","Wellington_NZ","Manawatu-Wanganui_NZ","Taranaki_NZ","Northland_NZ","Bay_of_Plenty_NZ","Gisborne_District_NZ","Hawke_s_Bay_NZ","Chatham_Islands_Territory_NZ","Kermadec_Islands_NZ"]},"#00ff00":{"label":"78.x","paths":["Sud_NC","Nord_NC","Îles_Loyauté_NC"]},"#ffc000":{"label":"73.x","paths":["Tonga__TO","Vava_u_TO","Eua_TO","Tongatapu_TO","Ha_apai_TO","Niuas_TO"]},"#ff8000":{"label":"71.x","paths":["Tafea_VU","Shefa_VU","Malampa_VU","Sanma_VU","Penama_VU","Torba_VU","Samoa__WS","Gaga_emauga_WS","Gaga_ifomauga_WS","Vaisigano_WS","Satupa_itea_WS","Palauli_WS","Fa_asaleleaga_WS","Atua_WS","Va_a-o-Fonoti_WS","Tuamasaga_WS","A_ana_WS","Aiga-i-le-Tai_WS"]},"#ff6000":{"label":"70.x","paths":["Rennell_and_Bellona_SB","Makira_SB","Temotu_SB","Malaita_SB","Capital_Territory_Honiara_SB","Guadalcanal_SB","Central_SB","Western_SB","Isabel_SB","Choiseul_SB"]},"#e00000":{"label":"67.x","paths":["Eastern_FJ","Western_FJ","Central_FJ","Northern_FJ","Rotuma_FJ","Tuvalu__TV","Tuvalu_TV","Federated_States_of_Micronesia__FM","Kosrae_FM","Pohnpei_FM","Chuuk_FM","Yap_FM","Marshall_Islands__MH","Railik_Chain_MH","Ratak_Chain_MH"]},"#c00000":{"label":"66.x","paths":["Sandaun_PG","Western_PG","East_Sepik_PG","Madang_PG","Morobe_PG","Northern_PG","Milne_Bay_PG","Central_PG","National_Capital_District_PG","Gulf_PG","North_Solomons_PG","West_New_Britain_PG","East_New_Britain_PG","New_Ireland_PG","Manus_PG","Chimbu_PG","Enga_PG","Western_Highlands_PG","Jiwaka_PG","Southern_Highlands_PG","Hela_PG","Eastern_Highlands_PG","Kiribati__KI","Kiribati_KI"]},"#200000":{"label":"62.x","paths":["Nauru__NR","Anetan_NR","Ewa_NR","Baiti_NR","Uaboe_NR","Nibok_NR","Denigomodu_NR","Aiwo_NR","Boe_NR","Yaren_NR","Meneng_NR","Anibare_NR","Ijuw_NR","Anabar_NR","Buada_NR"]}},"title":"2024","hidden":[],"background":"#fff","borders":"#000","legendFont":"Century Gothic","legendFontColor":"#000","legendBgColor":"#00000000","legendWidth":150,"areBordersShown":false,"defaultColor":"#d1dbdd","labelsColor":"#6a0707","strokeWidth":"medium","areLabelsShown":true,"legendPosition":"custom","legendX":"859.58","legendY":"434.26","legendSize":"large","legendStatus":"show","scalingPatterns":true,"legendRowsSameColor":true,"legendColumnCount":1}

In [74]:
if WRITE_TO_FILE:
    with open(f'output-map-code/Oceania-{SELECTED_YEAR}.txt', 'w') as fh:
        fh.write(st)

<br />
<br />
<br />

In [75]:
dd_legend_Africa = {
    '77.x' : '00bfff',
    '76.x' : '002000',
    '75.x' : '004000',
    '74.x' : '006000',
    '73.x' : '008000',
    '72.x' : '00a000',
    '71.x' : '00c000',
    '70.x' : '00e000',
    '69.x' : '00ff00',
    '68.x' : '9cff00',
    '67.x' : 'd8ff00',
    '66.x' : 'ffff00',
    '65.x' : 'ffe000',
    '64.x' : 'ffc000',
    '63.x' : 'ffa000',
    '62.x' : 'ff8000',
    '61.x' : 'ff6000',
    '60.x' : 'ff4000',
    '59.x' : 'ff0000',
    '58.x' : 'e00000',
    '57.x' : 'c00000',
    '56.x' : 'a00000',
    '55.x' : '800000',
    '54.x' : '600000',
    '53.x' : '400000',
    '52.x' : '200000'}

if CREATE_LEGEND:
    create_legend_code(dd_legend_Africa)

In [76]:
ls_Africa = [
    'DR Congo', 'Tanzania', 'South Africa', 'Central African Republic', 'South Sudan', 'Sudan', 'Nigeria', 'Libya', 'Guinea Bissau', 'Ghana',
    'Madagascar', 'Cote d Ivoire', 'Algeria', 'Cameroon', 'Botswana', 'Kenya', 'Mali', 'Somalia', 'Mozambique', 'Mauritania', 'Morocco',
    'Egypt', 'Lesotho', 'Eswatini', 'Angola', 'Zambia', 'Zimbabwe', 'Congo', 'Gabon', 'Sao Tome and Principe', 'Uganda', 'Ethiopia',
    'Liberia', 'Equatorial Guinea', 'Rwanda', 'Chad', 'Niger', 'Namibia', 'Burkina Faso', 'Benin', 'Guinea', 'Gambia', 'Senegal',
    'Sierra Leone', 'Togo', 'Malawi', 'Tunisia', 'Burundi', 'Djibouti', 'Eritrea', 'Cabo Verde', 'Mauritius', 'Seychelles', 'Comoros']
# in the database there are no data for Western Sahara, Saint Helena, Reunion, Mayotte

df_Africa = df.loc[ls_Africa]
mal.min_and_max_values(df_Africa, row_center=df.loc['Sub-Saharan Africa'], shorten=True, nmb=5, max_lng=13)

Number of records: 54

In [77]:
df_Africa = filter_df(df, ls_Africa, SELECTED_YEAR)

pd.options.display.max_rows=10
df_Africa.round(2)

Range: 54.63 – 76.71   (Nigeria – Tunisia)
Number of groups: 23
Number of values: 54

                           2024 group_label
Country Name
Tunisia                   76.71        76.x
Algeria                   76.47        76.x
Seychelles                76.30        76.x
Cabo Verde                76.22        76.x
Morocco                   75.49        75.x
...                         ...         ...
Lesotho                   57.80        57.x
South Sudan               57.74        57.x
Central African Republic  57.67        57.x
Chad                      55.24        55.x
Nigeria                   54.64        54.x

[54 rows x 2 columns]

In [79]:
ls_grouping = []
df_Africa.groupby(['group_label'])[['group_label']].apply(extract_indexes, dd_legend=dd_legend_Africa).loc[::-1]

              color                                         countries
group_label
76.x         002000        [Tunisia, Algeria, Seychelles, Cabo Verde]
75.x         004000                                         [Morocco]
73.x         008000                                       [Mauritius]
71.x         00c000                                    [Egypt, Libya]
69.x         00ff00                 [Sao Tome and Principe, Botswana]
...             ...                                               ...
60.x         ff4000                             [Benin, Guinea, Mali]
58.x         e00000                                         [Somalia]
57.x         c00000  [Lesotho, South Sudan, Central African Republic]
55.x         800000                                            [Chad]
54.x         600000                                         [Nigeria]

[18 rows x 2 columns]

In [80]:
st = create_map_code(ls_grouping, region='Africa')
print(st)

{"groups":{"#002000":{"label":"76.x","paths":["Tunisia","Algeria","Seychelles","Cabo_Verde"]},"#004000":{"label":"75.x","paths":["Morocco"]},"#008000":{"label":"73.x","paths":["Mauritius"]},"#00c000":{"label":"71.x","paths":["Egypt","Libya"]},"#00ff00":{"label":"69.x","paths":["Sao_Tome_and_Principe","Botswana"]},"#9cff00":{"label":"68.x","paths":["Senegal","Eritrea","Mauritania","Gabon","Uganda","Rwanda"]},"#d8ff00":{"label":"67.x","paths":["Ethiopia","Malawi","Namibia","Tanzania","Comoros"]},"#ffff00":{"label":"66.x","paths":["Zambia","Sudan","South_Africa","Djibouti","Gambia","Congo"]},"#ffe000":{"label":"65.x","paths":["Ghana"]},"#ffc000":{"label":"64.x","paths":["Angola","Eswatini","Guinea_Bissau"]},"#ffa000":{"label":"63.x","paths":["Cameroon","Equatorial_Guinea","Madagascar","Kenya","Burundi","Mozambique","Zimbabwe"]},"#ff8000":{"label":"62.x","paths":["Togo","Liberia","Cote_d_Ivoire","DR_Congo"]},"#ff6000":{"label":"61.x","paths":["Sierra_Leone","Niger","Burkina_Faso"]},"#ff4000":{"label":"60.x","paths":["Benin","Guinea","Mali"]},"#e00000":{"label":"58.x","paths":["Somalia"]},"#c00000":{"label":"57.x","paths":["Lesotho","South_Sudan","Central_African_Republic"]},"#800000":{"label":"55.x","paths":["Chad"]},"#600000":{"label":"54.x","paths":["Nigeria"]}},"title":"2024","hidden":[],"background":"#fff","borders":"#000","legendFont":"Century Gothic","legendFontColor":"#000","legendBgColor":"#00000000","legendWidth":150,"areBordersShown":true,"defaultColor":"#d1dbdd","labelsColor":"#6a0707","strokeWidth":"medium","areLabelsShown":false,"legendPosition":"custom","legendX":"20.00","legendY":"195.00","legendSize":"large","legendStatus":"show","scalingPatterns":true,"legendRowsSameColor":true,"legendColumnCount":2}

In [81]:
if WRITE_TO_FILE:
    with open(f'output-map-code/Africa-{SELECTED_YEAR}.txt', 'w') as fh:
        fh.write(st)

<br />
<br />
<br />

In [82]:
dd_legend_world = {
    '84.00–85.99' : '002000',
    '82.00–83.99' : '006000',
    '80.00–81.99' : '009000',
    '78.00–79.99' : '00b800',
    '76.00–77.99' : '00e000',
    '74.00–75.99' : '00ff00',
    '72.00–73.99' : 'b8ff00',
    '70.00–71.99' : 'ffff00',
    '68.00–69.99' : 'ffe000',
    '66.00–67.99' : 'ffc000',
    '64.00–65.99' : 'ffa000',
    '62.00–63.99' : 'ff8000',
    '60.00–61.99' : 'ff5000',
    '58.00–59.99' : 'ff0000',
    '56.00–57.99' : 'c80000',
    '54.00–55.99' : '900000',
    '52.00–53.99' : '400000'}

if CREATE_LEGEND:
    create_legend_code(dd_legend_world)

In [83]:
def filter_df_2(df, ls, selected_year=SELECTED_YEAR):
    filtered_df = df.loc[ls, [selected_year]]   \
                    .sort_values(by=selected_year, ascending=False) \
                    .dropna()

    filtered_df['group_label'] = filtered_df[selected_year].map(lambda x: f"{x // 2 * 2:.2f}–{x // 2 * 2 + 1.99:.2f}")
    
    min_value = filtered_df[selected_year].min()
    max_value = filtered_df[selected_year].max()
    
    print(f"Range: {min_value:.2f} – {max_value:.2f}   " +
          f"({filtered_df[selected_year].idxmin()} – {filtered_df[selected_year].idxmax()})")
    print(f"Number of groups: {int(max_value) - int(min_value) +1}")
    print(f"Number of values: {len(filtered_df)}")

    return filtered_df

In [84]:
df.rename(index = {'United States of America': 'United States',
                   'Virgin Islands': 'US Virgin Islands',
                   'St Vincent and the Grenadines': 'Saint Vincent and the Grenadines',
                   'St Lucia': 'Saint Lucia',
                   'East Timor': 'Timor Leste',
                   'Sao Tome and Principe': 'São Tomé and Principe'},
          inplace = True)

In [85]:
ls_world = [
    'Mexico', 'Canada', 'United Kingdom', 'Saudi Arabia', 'Liechtenstein', 'Fiji', 'New Caledonia', 'Bahamas', 'Grenada', 'Saint Vincent and the Grenadines', 'Barbados',
    'Saint Lucia', 'Dominica', 'Antigua and Barbuda', 'Mauritius', 'Comoros', 'São Tomé and Principe', 'Cabo Verde', 'Faeroe Islands', 'Samoa', 'Solomon Islands',
    'Vanuatu', 'Peru', 'Ecuador', 'Australia', 'Greenland', 'Uruguay', 'Argentina', 'Venezuela', 'Colombia', 'El Salvador', 'Bolivia', 'Brazil', 'Cuba', 'Suriname',
    'Jamaica', 'Chile', 'Guyana', 'Guatemala', 'Costa Rica', 'Honduras', 'Belize', 'Trinidad and Tobago', 'Puerto Rico', 'Haiti', 'Dominican Republic', 'Nicaragua',
    'Panama', 'Italy', 'Czechia', 'Greece', 'Netherlands', 'Germany', 'Romania', 'Denmark', 'Iceland', 'Portugal', 'Spain', 'Austria', 'Bulgaria', 'Hungary', 'Croatia',
    'Sweden', 'Türkiye', 'Serbia', 'Slovakia', 'Lithuania', 'Latvia', 'Estonia', 'Montenegro', 'Norway', 'Finland', 'Malta', 'Poland', 'Albania', 'Ireland',
    'Bosnia and Herzegovina', 'Armenia', 'France', 'Switzerland', 'Ukraine', 'Belarus', 'Cyprus', 'Luxembourg', 'Moldova', 'Libya', 'Guinea Bissau', 'Ghana',
    'Madagascar', 'Cote d Ivoire', 'Algeria', 'Cameroon', 'Botswana', 'Kenya', 'South Sudan', 'Mali', 'Somalia', 'Mozambique', 'Mauritania', 'Sudan', 'Morocco', 'Egypt',
    'South Africa', 'Lesotho', 'Eswatini', 'Angola', 'Zambia', 'Zimbabwe', 'DR Congo', 'Congo', 'Gabon', 'Uganda', 'Ethiopia', 'Liberia', 'Equatorial Guinea', 'Rwanda',
    'Central African Republic', 'Chad', 'Niger', 'Nigeria', 'Namibia', 'Burkina Faso', 'Tanzania', 'Benin', 'Guinea', 'Gambia', 'Senegal', 'Sierra Leone', 'Togo',
    'Malawi', 'Afghanistan', 'Israel', 'Sri Lanka', 'Palestinian Territories', 'Iran', 'North Korea', 'Tunisia', 'Nepal', 'Turkmenistan', 'India', 'Kyrgyzstan', 'Iraq',
    'Thailand', 'Uzbekistan', 'Kazakhstan', 'Mongolia', 'Jordan', 'Syria', 'Oman', 'Tajikistan', 'Pakistan', 'Japan', 'South Korea', 'Azerbaijan', 'Papua New Guinea',
    'Timor Leste', 'Cambodia', 'Laos', 'Myanmar', 'Bangladesh', 'Georgia', 'Philippines', 'New Zealand', 'Bahrain', 'United Arab Emirates', 'Qatar', 'China', 'Russia',
    'Hong Kong', 'Yemen', 'Brunei', 'Malaysia', 'Lebanon', 'Kuwait', 'Indonesia', 'Vietnam', 'North Macedonia', 'Belgium', 'Slovenia', 'Burundi', 'Djibouti', 'Eritrea',
    'Singapore', 'Paraguay', 'United States', 'Bhutan']

# in the database there are no data for
#   Europe: Andorra, Monaco, San Marino, Vatican City
#   Asia: Taiwan
#   Caribbean: Anguilla, Montserrat, Guadeloupe, Bonaire, Saint Barthélemy, Martinique
#   Americas: Falkland Islands, French Guiana, Montserrat, Guadeloupe, Martinique, St Pierre et Miquelon
#   Africa: Western Sahara, Saint Helena, Reunion / Réunion, Mayotte
#   additional: French Southern and Antarctic Lands, South Georgia and the South Sandwich Islands, American Samoa

# ls_world = list(set(ls_Europe + ls_Asia + ls_Americas + ls_Africa))
# in the database there are no data for 

df_world = df.loc[ls_world]
mal.min_and_max_values(df_world, row_center=df.loc['World'], shorten=True, nmb=5, max_lng=13)

Number of records: 186

In [86]:
df_world = filter_df_2(df, ls_world, SELECTED_YEAR)

pd.options.display.max_rows=10
df_world.round(2)

Range: 54.63 – 85.39   (Nigeria – Hong Kong)
Number of groups: 32
Number of values: 186

                           2024  group_label
Country Name
Hong Kong                 85.39  84.00–85.99
Kuwait                    84.58  84.00–85.99
Switzerland               84.41  84.00–85.99
Liechtenstein             84.20  84.00–85.99
Sweden                    84.06  84.00–85.99
...                         ...          ...
Lesotho                   57.80  56.00–57.99
South Sudan               57.74  56.00–57.99
Central African Republic  57.67  56.00–57.99
Chad                      55.24  54.00–55.99
Nigeria                   54.64  54.00–55.99

[186 rows x 2 columns]

In [88]:
ls_grouping = []
df_world.groupby(['group_label'])[['group_label']].apply(extract_indexes, dd_legend=dd_legend_world).loc[::-1]

              color                                          countries
group_label
84.00–85.99  002000  [Hong Kong, Kuwait, Switzerland, Liechtenstein...
82.00–83.99  006000  [Italy, Spain, South Korea, Singapore, Israel,...
80.00–81.99  009000  [Austria, Netherlands, Puerto Rico, Greece, Cy...
78.00–79.99  00b800  [Czechia, Albania, Panama, Estonia, Saudi Arab...
76.00–77.99  00e000  [Jordan, Lebanon, Peru, Colombia, Montenegro, ...
...             ...                                                ...
62.00–63.99  ff8000  [Cameroon, Equatorial Guinea, Madagascar, Keny...
60.00–61.99  ff5000  [Sierra Leone, Niger, Burkina Faso, Benin, Gui...
58.00–59.99  ff0000                                          [Somalia]
56.00–57.99  c80000   [Lesotho, South Sudan, Central African Republic]
54.00–55.99  900000                                    [Chad, Nigeria]

[16 rows x 2 columns]

In [89]:
st = create_map_code(ls_grouping, region='world')
print(st)

{"groups":{"#002000":{"label":"84.00–85.99","paths":["Hong_Kong","Kuwait","Switzerland","Liechtenstein","Sweden","Japan"]},"#006000":{"label":"82.00–83.99","paths":["Italy","Spain","South_Korea","Singapore","Israel","Luxembourg","Norway","Faeroe_Islands","United_Arab_Emirates","Australia","Ireland","France","Malta","Iceland","Qatar","Portugal","Finland","Belgium","Slovenia","Denmark","Canada","New_Zealand"]},"#009000":{"label":"80.00–81.99","paths":["Austria","Netherlands","Puerto_Rico","Greece","Cyprus","Bahrain","United_Kingdom","Chile","Costa_Rica","Germany","Oman"]},"#00b800":{"label":"78.00–79.99","paths":["Czechia","Albania","Panama","Estonia","Saudi_Arabia","Croatia","New_Caledonia","United_States","Poland","Slovakia","Armenia","Uruguay","Cuba","Bosnia_and_Herzegovina","China"]},"#00e000":{"label":"76.00–77.99","paths":["Jordan","Lebanon","Peru","Colombia","Montenegro","Iran","Antigua_and_Barbuda","Sri_Lanka","Ecuador","Argentina","Türkiye","Lithuania","Malaysia","Hungary","Tunisia","North_Macedonia","Thailand","Algeria","Romania","Latvia","Barbados","Cabo_Verde","Brazil"]},"#00ff00":{"label":"74.00–75.99","paths":["Serbia","Bulgaria","Brunei","Morocco","Grenada","Mexico","Nicaragua","Bangladesh","Vietnam","Bahamas","Ukraine","Georgia","Azerbaijan","Kazakhstan","Belarus"]},"#b8ff00":{"label":"72.00–73.99","paths":["Paraguay","Dominican_Republic","Mauritius","Suriname","North_Korea","Belize","Trinidad_and_Tobago","Russia","Bhutan","Honduras","Saint_Lucia","Guatemala","Venezuela","Syria","Uzbekistan","Iraq","Kyrgyzstan","Mongolia","El_Salvador","India"]},"#ffff00":{"label":"70.00–71.99","paths":["Tajikistan","Samoa","Egypt","Vanuatu","Jamaica","Saint_Vincent_and_the_Grenadines","Moldova","Dominica","Indonesia","Libya","Cambodia","Solomon_Islands","Nepal","Guyana","Greenland","Turkmenistan"]},"#ffe000":{"label":"68.00–69.99","paths":["Philippines","São_Tomé_and_Principe","Yemen","Botswana","Laos","Palestinian_Territories","Senegal","Eritrea","Bolivia","Mauritania","Gabon","Uganda","Rwanda"]},"#ffc000":{"label":"66.00–67.99","paths":["Timor_Leste","Pakistan","Ethiopia","Malawi","Namibia","Fiji","Tanzania","Myanmar","Comoros","Zambia","Sudan","South_Africa","Afghanistan","Papua_New_Guinea","Djibouti","Gambia","Congo"]},"#ffa000":{"label":"64.00–65.99","paths":["Ghana","Haiti","Angola","Eswatini","Guinea_Bissau"]},"#ff8000":{"label":"62.00–63.99","paths":["Cameroon","Equatorial_Guinea","Madagascar","Kenya","Burundi","Mozambique","Zimbabwe","Togo","Liberia","Cote_d_Ivoire","DR_Congo"]},"#ff5000":{"label":"60.00–61.99","paths":["Sierra_Leone","Niger","Burkina_Faso","Benin","Guinea","Mali"]},"#ff0000":{"label":"58.00–59.99","paths":["Somalia"]},"#c80000":{"label":"56.00–57.99","paths":["Lesotho","South_Sudan","Central_African_Republic"]},"#900000":{"label":"54.00–55.99","paths":["Chad","Nigeria"]}},"title":"2024","hidden":["Prince_Edward_Island_CA","New_Brunswick_CA","Ontario_CA","British_Columbia_CA","Alberta_CA","Saskatchewan_CA","Manitoba_CA","Quebec_CA","Yukon_CA","Nunavut_CA","Newfoundland_and_Labrador_CA","Northwest_Territories_CA","Nova_Scotia_CA","Scotland","Wales","England","Northern_Ireland","USA_Wisconsin","USA_Montana","USA_Minnesota","USA_Washington","USA_Idaho","USA_North_Dakota","USA_Michigan","USA_Maine","USA_Ohio","USA_New_Hampshire","USA_New_York","USA_Vermont","USA_Pennsylvania","USA_Arizona","USA_California","USA_New_Mexico","USA_Texas","USA_Alaska","USA_Louisiana","USA_Mississippi","USA_Alabama","USA_Florida","USA_Georgia","USA_South_Carolina","USA_North_Carolina","USA_Virginia","USA_Washington_DC","USA_Maryland","USA_Delaware","USA_New_Jersey","USA_Connecticut","USA_Rhode_Island","USA_Massachusetts","USA_Oregon","USA_Hawaii","USA_Utah","USA_Wyoming","USA_Nevada","USA_Colorado","USA_South_Dakota","USA_Nebraska","USA_Kansas","USA_Oklahoma","USA_Iowa","USA_Missouri","USA_Illinois","USA_Kentucky","USA_Arkansas","USA_Tennessee","USA_West_Virginia","USA_Indiana"],"background":"#fff","borders":"#000","legendFont":"Century Gothic","legendFontColor":"#000","legendBgColor":"#00000000","legendWidth":150,"areBordersShown":true,"defaultColor":"#d1dbdd","labelsColor":"#6a0707","strokeWidth":"medium","areLabelsShown":false,"usaStatesShown":false,"canadaStatesShown":false,"splitUK":false,"legendPosition":"custom","legendX":"30.00","legendY":"300.00","legendSize":"large","legendStatus":"show","scalingPatterns":true,"legendRowsSameColor":true,"legendColumnCount":2}

In [90]:
if WRITE_TO_FILE:
    with open(f'output-map-code/world-{SELECTED_YEAR}.txt', 'w') as fh:
        fh.write(st)

<br />
<br />
<br />

In [91]:
# ls_ = []
# # in the database there are no data for 

# df_ = df.loc[ls_]
# min_and_max(df_)

In [92]:
# df_ = filter_df(df, ls_, SELECTED_YEAR)

# pd.options.display.max_rows=10
# df_.round(2)

In [93]:
# ls_grouping = []
# df_.groupby(['group_label']).apply(extract_indexes).loc[::-1]

In [94]:
# st = create_map_code(ls_grouping, region='')
# print(st)

In [95]:
# if WRITE_TO_FILE:
#     with open(f'output-map-code/-{SELECTED_YEAR}.txt', 'w') as fh:
#         fh.write(st)

<br />
<br />
<br />

<br />
<br />
<br />

---

Creation of code for [Europe map](https://en.wikipedia.org/wiki/List_of_European_countries_by_life_expectancy#Charts_and_maps)

In [96]:
MapLocations = namedtuple('MapLocations', ['country', 'x', 'y', 'ru_name'],
                                        defaults=('-', 0, 0, '-'))

In [97]:
dd_coloring = {
    70: 'ff0000',
    71: 'ff2000',
    72: 'ff4000',
    73: 'ff6000',
    74: 'ff8000',
    75: 'ffa000',
    76: 'ffc000',
    77: 'ffe000',
    78: 'ffff00',
    79: 'e0ff00',
    80: 'c0ff00',
    81: 'a0ff00',
    82: '80ff00',
    83: '60ff00',
    84: '40ff00',
    85: '20ff00',
    86: '00ff00'}

ls_locations = [
    MapLocations(country='Albania', x=0.615, y=0.665, ru_name='Албания'),
    MapLocations(country='Armenia', x=0.92, y=0.58, ru_name='Армения'),
    MapLocations(country='Austria', x=0.545, y=0.555, ru_name='Австрия'),
    MapLocations(country='Azerbaijan', x=0.96, y=0.56, ru_name='Азербайджан'),
    MapLocations(country='Belarus', x=0.67, y=0.45, ru_name='Белоруссия'),
    MapLocations(country='Belgium', x=0.43, y=0.49, ru_name='Бельгия'),
    MapLocations(country='Bosnia and Herzegovina', x=0.57, y=0.61, ru_name='Босния и Герцеговина'),
    MapLocations(country='Bulgaria', x=0.66, y=0.624, ru_name='Болгария'),
    MapLocations(country='Croatia', x=0.56, y=0.594, ru_name='Хорватия'),
    MapLocations(country='Cyprus', x=0.79, y=0.73, ru_name='Республика Кипр'),
    MapLocations(country='Czechia', x=0.545, y=0.518, ru_name='Чехия'),
    MapLocations(country='Denmark', x=0.48, y=0.42, ru_name='Дания'),
    MapLocations(country='Estonia', x=0.625, y=0.37, ru_name='Эстония'),
    MapLocations(country='Finland', x=0.63, y=0.30, ru_name='Финляндия'),
    MapLocations(country='France', x=0.40, y=0.55, ru_name='Франция'),
    MapLocations(country='Georgia', x=0.90, y=0.555, ru_name='Грузия'),
    MapLocations(country='Germany', x=0.495, y=0.496, ru_name='Германия'),
    MapLocations(country='Greece', x=0.64, y=0.68, ru_name='Греция'),
    MapLocations(country='Hungary', x=0.59, y=0.56, ru_name='Венгрия'),
    MapLocations(country='Iceland', x=0.34, y=0.23, ru_name='Исландия'),
    MapLocations(country='Ireland', x=0.34, y=0.43, ru_name='Ирландия'),
    MapLocations(country='Italy', x=0.53, y=0.65, ru_name='Италия'),
    MapLocations(country='Kazakhstan', x=0.97, y=0.39, ru_name='Казахстан'),
    MapLocations(country='Latvia', x=0.625, y=0.4, ru_name='Латвия'),
    MapLocations(country='Lithuania', x=0.625, y=0.43, ru_name='Литва'),
    MapLocations(country='Luxembourg', x=0.45, y=0.51, ru_name='Люксембург'),
    MapLocations(country='Malta', x=0.56, y=0.754, ru_name='Мальта'),
    MapLocations(country='Moldova', x=0.70, y=0.56, ru_name='Молдова'),
    MapLocations(country='Montenegro', x=0.59, y=0.63, ru_name='Черногория'),
    MapLocations(country='Netherlands', x=0.46, y=0.47, ru_name='Нидерланды'),
    MapLocations(country='North Macedonia', x=0.634, y=0.65, ru_name='Северная Македония'),
    MapLocations(country='Norway', x=0.49, y=0.34, ru_name='Норвегия'),
    MapLocations(country='Poland', x=0.58, y=0.48, ru_name='Польша'),
    MapLocations(country='Portugal', x=0.24, y=0.62, ru_name='Португалия'),
    MapLocations(country='Romania', x=0.655, y=0.575, ru_name='Румыния'),
    MapLocations(country='Russia', x=0.76, y=0.38, ru_name='Россия'),
    MapLocations(country='Serbia', x=0.615, y=0.605, ru_name='Сербия'),
    MapLocations(country='Slovakia', x=0.58, y=0.54, ru_name='Словакия'),
    MapLocations(country='Slovenia', x=0.535, y=0.58, ru_name='Словения'),
    MapLocations(country='Spain', x=0.3, y=0.65, ru_name='Испания'),
    MapLocations(country='Sweden', x=0.54, y=0.37, ru_name='Швеция'),
    MapLocations(country='Switzerland', x=0.474, y=0.56, ru_name='Швейцария'),
    MapLocations(country='Turkey', x=0.82, y=0.64, ru_name='Турция'),
    MapLocations(country='Ukraine', x=0.69, y=0.505, ru_name='Украина'),
    MapLocations(country='United Kingdom', x=0.38, y=0.46, ru_name='Великобритания')
]

# small coutries that are not included: 'Channel Islands', 'Faroe Islands', 'Gibraltar', 'Isle of Man'
# MapLocations(country='Liechtenstein', x=0.49, y=0.58, ru_name='Лихтенштейн'),

In [98]:
selected_year = 2024
lang = 'en'

for country, x, y, ru_name in ls_locations:
    if country == 'Turkey':
        country = 'Türkiye'
        
    le = df.loc[country, selected_year].round(1)
    background = dd_coloring[int(le)]
    if country == 'Georgia':
        country = 'Georgia (country)'
    print(f'{{{{Image label small|x={x}|y={y}|scale=700|text=[[{ru_name if lang=="ru" else country}|<span style="background:#{background};color:black">{le}</span>]]}}}}')

{{Image label small|x=0.615|y=0.665|scale=700|text=[[Albania|<span style="background:#e0ff00;color:black">79.8</span>]]}}
{{Image label small|x=0.92|y=0.58|scale=700|text=[[Armenia|<span style="background:#ffff00;color:black">78.3</span>]]}}
{{Image label small|x=0.545|y=0.555|scale=700|text=[[Austria|<span style="background:#80ff00;color:black">82.0</span>]]}}
{{Image label small|x=0.96|y=0.56|scale=700|text=[[Azerbaijan|<span style="background:#ff8000;color:black">74.6</span>]]}}
{{Image label small|x=0.67|y=0.45|scale=700|text=[[Belarus|<span style="background:#ff8000;color:black">74.4</span>]]}}
{{Image label small|x=0.43|y=0.49|scale=700|text=[[Belgium|<span style="background:#80ff00;color:black">82.3</span>]]}}
{{Image label small|x=0.57|y=0.61|scale=700|text=[[Bosnia and Herzegovina|<span style="background:#ffff00;color:black">78.0</span>]]}}
{{Image label small|x=0.66|y=0.624|scale=700|text=[[Bulgaria|<span style="background:#ffa000;color:black">75.8</span>]]}}
{{Image label small|x=0.56|y=0.594|scale=700|text=[[Croatia|<span style="background:#ffff00;color:black">78.9</span>]]}}
{{Image label small|x=0.79|y=0.73|scale=700|text=[[Cyprus|<span style="background:#a0ff00;color:black">81.8</span>]]}}
{{Image label small|x=0.545|y=0.518|scale=700|text=[[Czechia|<span style="background:#c0ff00;color:black">80.0</span>]]}}
{{Image label small|x=0.48|y=0.42|scale=700|text=[[Denmark|<span style="background:#80ff00;color:black">82.3</span>]]}}
{{Image label small|x=0.625|y=0.37|scale=700|text=[[Estonia|<span style="background:#e0ff00;color:black">79.3</span>]]}}
{{Image label small|x=0.63|y=0.3|scale=700|text=[[Finland|<span style="background:#80ff00;color:black">82.3</span>]]}}
{{Image label small|x=0.4|y=0.55|scale=700|text=[[France|<span style="background:#60ff00;color:black">83.0</span>]]}}
{{Image label small|x=0.9|y=0.555|scale=700|text=[[Georgia (country)|<span style="background:#ff8000;color:black">74.7</span>]]}}
{{Image label small|x=0.495|y=0.496|scale=700|text=[[Germany|<span style="background:#c0ff00;color:black">80.8</span>]]}}
{{Image label small|x=0.64|y=0.68|scale=700|text=[[Greece|<span style="background:#a0ff00;color:black">81.8</span>]]}}
{{Image label small|x=0.59|y=0.56|scale=700|text=[[Hungary|<span style="background:#ffc000;color:black">76.7</span>]]}}
{{Image label small|x=0.34|y=0.23|scale=700|text=[[Iceland|<span style="background:#80ff00;color:black">82.8</span>]]}}
{{Image label small|x=0.34|y=0.43|scale=700|text=[[Ireland|<span style="background:#60ff00;color:black">83.0</span>]]}}
{{Image label small|x=0.53|y=0.65|scale=700|text=[[Italy|<span style="background:#40ff00;color:black">84.0</span>]]}}
{{Image label small|x=0.97|y=0.39|scale=700|text=[[Kazakhstan|<span style="background:#ff8000;color:black">74.5</span>]]}}
{{Image label small|x=0.625|y=0.4|scale=700|text=[[Latvia|<span style="background:#ffc000;color:black">76.4</span>]]}}
{{Image label small|x=0.625|y=0.43|scale=700|text=[[Lithuania|<span style="background:#ffe000;color:black">77.2</span>]]}}
{{Image label small|x=0.45|y=0.51|scale=700|text=[[Luxembourg|<span style="background:#60ff00;color:black">83.2</span>]]}}
{{Image label small|x=0.56|y=0.754|scale=700|text=[[Malta|<span style="background:#60ff00;color:black">83.0</span>]]}}
{{Image label small|x=0.7|y=0.56|scale=700|text=[[Moldova|<span style="background:#ff2000;color:black">71.3</span>]]}}
{{Image label small|x=0.59|y=0.63|scale=700|text=[[Montenegro|<span style="background:#ffe000;color:black">77.9</span>]]}}
{{Image label small|x=0.46|y=0.47|scale=700|text=[[Netherlands|<span style="background:#80ff00;color:black">82.0</span>]]}}
{{Image label small|x=0.634|y=0.65|scale=700|text=[[North Macedonia|<span style="background:#ffc000;color:black">76.6</span>]]}}
{{Image label small|x=0.49|y=0.34|scale=700|text=[[Norway|<span style="background:#60ff00;color:black">83.2</span>]]}}
{{Image label small|x=0.58|y=0.48|scale=700|text=[[Poland|<span style="background:#ffff00;color:black">78.4</span>]]}}
{{Image label small|x=0.24|y=0.62|scale=700|text=[[Portugal|<span style="background:#80ff00;color:black">82.4</span>]]}}
{{Image label small|x=0.655|y=0.575|scale=700|text=[[Romania|<span style="background:#ffc000;color:black">76.5</span>]]}}
{{Image label small|x=0.76|y=0.38|scale=700|text=[[Russia|<span style="background:#ff6000;color:black">73.4</span>]]}}
{{Image label small|x=0.615|y=0.605|scale=700|text=[[Serbia|<span style="background:#ffc000;color:black">76.0</span>]]}}
{{Image label small|x=0.58|y=0.54|scale=700|text=[[Slovakia|<span style="background:#ffff00;color:black">78.4</span>]]}}
{{Image label small|x=0.535|y=0.58|scale=700|text=[[Slovenia|<span style="background:#80ff00;color:black">82.3</span>]]}}
{{Image label small|x=0.3|y=0.65|scale=700|text=[[Spain|<span style="background:#60ff00;color:black">83.9</span>]]}}
{{Image label small|x=0.54|y=0.37|scale=700|text=[[Sweden|<span style="background:#40ff00;color:black">84.1</span>]]}}
{{Image label small|x=0.474|y=0.56|scale=700|text=[[Switzerland|<span style="background:#40ff00;color:black">84.4</span>]]}}
{{Image label small|x=0.82|y=0.64|scale=700|text=[[Türkiye|<span style="background:#ffe000;color:black">77.4</span>]]}}
{{Image label small|x=0.69|y=0.505|scale=700|text=[[Ukraine|<span style="background:#ff8000;color:black">74.7</span>]]}}
{{Image label small|x=0.38|y=0.46|scale=700|text=[[United Kingdom|<span style="background:#a0ff00;color:black">81.4</span>]]}}