The World Band > [Life expectancy at birth, total](https://data.worldbank.org/indicator/SP.DYN.LE00.IN)<br />
The World Band > [Life expectancy at birth, male](https://data.worldbank.org/indicator/SP.DYN.LE00.MA.IN)<br />
The World Band > [Life expectancy at birth, female](https://data.worldbank.org/indicator/SP.DYN.LE00.FE.IN)<br />
[World Development Indicators > Life expectancy at birth](https://databank.worldbank.org/reports.aspx?source=2&series=SP.DYN.LE00.IN&country=) *(databank.worldbank.org)*<br />
[OECD stat](https://stats.oecd.org/index.aspx?queryid=30114)

"[List of countries by life expectancy](https://en.wikipedia.org/wiki/List_of_countries_by_life_expectancy)" *([template](https://en.wikipedia.org/wiki/Template:List_of_countries_by_life_expectancy/World_Bank))*/ "[Список стран по ожидаемой продолжительности жизни](https://ru.wikipedia.org/wiki/Список_стран_по_ожидаемой_продолжительности_жизни)"<br />
"[my private space](https://en.wikipedia.org/wiki/User:Lady3mlnm/LE_tables_(backups))" / "[моё личное пространство](https://ru.wikipedia.org/wiki/Участница:Lady3mlnm/Таблицы_ОПЖ_(резервные_копии))"<br />
[Таблица подбора цветов](http://mal-bioit.ru/survey-web-colors)<br />
[Список государств и зависимых территорий по населению](https://ru.wikipedia.org/wiki/Список_государств_и_зависимых_территорий_по_населению)

In [1]:
import pandas as pd
import math
import re

import sys
sys.path.append("..")
import mal_moduls_private.mal_total as mal
from mal_moduls_private.module_french import replacements_fr

In [2]:
pd.options.display.max_rows = 300

DESTINATION_OUTPUT = 'file'  # to where table code should be placed: 'file', 'here', 'print_done'
SORT_COLUMNS = ['total', 'male', 'female'] # columns by those tables are sorted

In [3]:
#build a regular expression from dictionary keys for translation country names to french
# pattern_replacement_fr = re.compile("|".join(re.escape(key) for key in replacements_fr.keys()))

In [4]:
def output_table_code(st, file_name='', destination=DESTINATION_OUTPUT):
    
    if destination == 'file':
        with open('output/'+file_name, 'w', encoding="utf-8") as fh:
            fh.write(st)
        print('Data has written to file')
    elif destination == 'here':
        print(st)
    else:
        print('done')

In [5]:
# create code for placing info in Wikipedia
def create_table(df, lang='en'):

    def if_value(x, prec=2):
        return '—' if math.isnan(x) else \
               f"{x:0.{prec}f}"  if x>=0 else \
               f"−{-x:0.{prec}f}"

    def chval(x, prec=2):  # change_value
        return '"| —' if math.isnan(x) else \
               f'color:darkgreen;"| {x:0.{prec}f}' if x>0 else \
               f'color:crimson;"| −{-x:0.{prec}f}' if x<0 else \
               f'color:darkgray;"| {x:0.{prec}f}'
    
    def chval_bold(x, prec=2):  # change_value
        return '"| —' if math.isnan(x) else \
               f'color:darkgreen;"| \'\'\'{x:0.{prec}f}\'\'\'' if x>0 else \
               f'color:crimson;"| \'\'\'−{-x:0.{prec}f}\'\'\'' if x<0 else \
               f'color:darkgray;"| \'\'\'{x:0.{prec}f}\'\'\''

    if lang=='ru':
        file_header='wbg_stats_header_2024_ru.txt'
        file_footer='wbg_stats_footer_2024_ru.txt'
        ptn_1 = 'флагификация'
        ptn_2 = 'флаг'
        prettify_name = {
            'European Union': '[[Европейский союз]]',
            'Central Europe and the Baltics': '[[Центральная Европа]] и [[Прибалтика]]',
            'Europe & Central Asia': '[[Европа]] и [[Центральная Азия]]',
            'South Asia': '[[Южная Азия]]',
            'East Asia & Pacific': '[[Восточная Азия]] и [[Австралия и Океания|Океания]]',
            'Middle East, North Africa, Afghanistan & Pakistan': '[[Страны MENA|Ближний Восток и Северная Африка]]',
            'Africa Eastern and Southern': '[[Восточная Африка|Восточная]] и [[Южная Африка|Южная]] Африка',
            'Sub-Saharan Africa': '[[Чёрная Африка|Африка к югу от Сахары]]',
            'Africa Western and Central': '[[Западная Африка|Западная]] и [[Центральная Африка|Центральная]] Африка',
            'North America': '[[Северная Америка]]',
            'Latin America & Caribbean': '[[Латинская Америка]] и [[Антильские острова|Карибы]]',
            'Arab World': '[[Арабский мир]]',
            'World': 'Мир',
            'Caribbean small states': '[[Список стран Карибского бассейна|Малые страны Карибского бассейна]]',
            'Pacific island small states': 'Малые страны Тихого океана',
            'Small states': 'Малые страны',
            'Other small states': 'Другие малые страны'
        }
    elif lang=='fr':
        file_header='wbg_stats_header_2024_fr.txt'
        file_footer='wbg_stats_footer_2024_fr.txt'
        ptn_1 = 'Pays'
        ptn_2 = 'Drapeau'
        prettify_name = {
            'European Union': '[[Union européenne]]',
            'Central Europe and the Baltics': '[[Europe centrale]] et les [[pays baltes]]',
            'Europe & Central Asia': '[[Europe]] et [[Asie centrale]]',
            'South Asia': '[[Asie du Sud]]',
            'East Asia & Pacific': '[[Asie-Pacifique]]',
            'Middle East, North Africa, Afghanistan & Pakistan': '[[MENA]]',
            'Africa Eastern and Southern': "[[Afrique de l'Est]] et [[Afrique australe]]",
            'Sub-Saharan Africa': '[[Afrique subsaharienne]]',
            'Africa Western and Central': "[[Afrique de l'Ouest]] et [[Afrique centrale]]",
            'North America': '[[Amérique du Nord]]',
            'Latin America & Caribbean': '[[Amérique latine]] et les [[Caraïbes]]',
            'Arab World': '[[Monde arabe]]',
            'World': 'Monde',
            'Caribbean small states': 'petits États des Caraïbes',
            'Pacific island small states': 'petits États du Pacifique',
            'Small states': 'petits États',
            'Other small states': 'autres petits États'
        }
    else:
        file_header='wbg_stats_header_2024_en.txt'
        file_footer='wbg_stats_footer_2024_en.txt'
        ptn_1 = 'flaglist'
        ptn_2 = 'flagicon'
        prettify_name = {
            'European Union': '[[European Union]]',
            'Central Europe and the Baltics': '[[Central Europe]] & the [[Baltic states|Baltics]]',
            'Europe & Central Asia': '[[Europe]] & [[Central Asia]]',
            'South Asia': '[[South Asia]]',
            'East Asia & Pacific': '[[Asia-Pacific|East Asia & Pacific]]',
            'Middle East, North Africa, Afghanistan & Pakistan': '[[MENA|Middle East & North Africa]]',
            'Africa Eastern and Southern': 'Africa [[East Africa|Eastern]] & [[Southern Africa|Southern]]',
            'Sub-Saharan Africa': '[[Sub-Saharan Africa]]',
            'Africa Western and Central': 'Africa [[West Africa|Western]] & [[Central Africa|Central]]',
            'North America': '[[North America]]',
            'Latin America & Caribbean': '[[Latin America and the Caribbean|Latin America & Caribbean]]',
            'Arab World': '[[Arab world]]',
            'World': 'World'
        }
        
    with open('design/' + file_header, mode='r', encoding="utf-8") as fh:
        st_header = fh.read()
        st_header = st_header.strip()

    with open('design/' + file_footer, mode='r', encoding="utf-8") as fh:
        st_footer = fh.read()

    st = ''
     
    for i in range(len(df)):
        ser = df.iloc[i]
        if ser.name in ['World',
                        'European Union', 'Central Europe and the Baltics',
                        'Europe & Central Asia',
                        'South Asia',
                        'East Asia & Pacific',
                        'Middle East, North Africa, Afghanistan & Pakistan',
                        'Africa Eastern and Southern', 'Sub-Saharan Africa', 'Africa Western and Central',
                        'North America', 'Latin America & Caribbean']:
            st += '\n' + '|-class=static-row-header\n' + \
                  f'|style="text-align:center;"| \'\'\'{prettify_name.get(ser.name, ser.name)}\'\'\' ' + \
                  f'||style="background:#e0ffd8;"| \'\'\'{if_value(ser.total, 2)}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| \'\'\'{if_value(ser.male, 2)}\'\'\' ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{if_value(ser.female, 2)}\'\'\' ' + \
                  f'||style="background:#fff8dc;"| \'\'\'{if_value(ser.gender_gap, 2)}\'\'\' ' + \
                  f'||style="border-left-width:2px;padding-left:1em;"| \'\'\'{if_value(ser["2014_t"], 2)}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2014→2019"], 2)} ' + \
                  f'|| \'\'\'{if_value(ser["2019_t"], 2)}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2019→2020"], 2)} ' + \
                  f'|| \'\'\'{if_value(ser["2020_t"], 2)}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2020→2021"], 2)} ' + \
                  f'|| \'\'\'{if_value(ser["2021_t"], 2)}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2021→2022"], 2)} ' + \
                  f'|| \'\'\'{if_value(ser["2022_t"], 2)}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2022→2023"], 2)} ' + \
                  f'|| \'\'\'{if_value(ser["2023_t"], 2)}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2023→2024"], 2)} ' + \
                  f'||style="background:#e0ffd8;"| \'\'\'{if_value(ser.total, 2)}\'\'\' ' + \
                  f'||style="background:#fffae0;border-left-width:2px;{chval_bold(ser["2019→2024"], 2)} ' + \
                  (f'||style="background:#fffae0;{chval_bold(ser["2014→2024"], 2)} ' if lang=='ru' else '') + \
                  f'||'
        elif ser.name in ['Caribbean small states',
                          'Pacific island small states',
                          'Small states',
                          'Other small states',
                          'Kosovo']:
            st += '\n' + '|-\n' + \
                  f'|style="padding-left:35px;"| {prettify_name.get(ser.name, ser.name)} ' + \
                  f'||style="background:#e0ffd8;"| {if_value(ser.total, 2)} ' + \
                  f'||style="background:#eaf3ff;"| {if_value(ser.male, 2)} ' + \
                  f'||style="background:#fee7f6;"| {if_value(ser.female, 2)} ' + \
                  f'||style="background:#fff8dc;"| {if_value(ser.gender_gap, 2)} ' + \
                  f'||style="border-left-width:2px;padding-left:1em;"| {if_value(ser["2014_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2014→2019"], 2)} ' + \
                  f'|| {if_value(ser["2019_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2019→2020"], 2)} ' + \
                  f'|| {if_value(ser["2020_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2020→2021"], 2)} ' + \
                  f'|| {if_value(ser["2021_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2021→2022"], 2)} ' + \
                  f'|| {if_value(ser["2022_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2022→2023"], 2)} ' + \
                  f'|| {if_value(ser["2023_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2023→2024"], 2)} ' + \
                  f'||style="background:#e0ffd8;"| {if_value(ser.total, 2)} ' + \
                  f'||style="background:#fffae0;border-left-width:2px;{chval(ser["2019→2024"], 2)} ' + \
                  (f'||style="background:#fffae0;{chval(ser["2014→2024"], 2)} ' if lang=='ru' else '') + \
                  f'||'
        else:
            st += '\n' + '|-\n' + \
                  f'| {{{{{ptn_1}|{replacements_fr[ser.name] if lang=='fr' else ser.name}}}}} ' + \
                  f'||style="background:#e0ffd8;"| {if_value(ser.total, 2)} ' + \
                  f'||style="background:#eaf3ff;"| {if_value(ser.male, 2)} ' + \
                  f'||style="background:#fee7f6;"| {if_value(ser.female, 2)} ' + \
                  f'||style="background:#fff8dc;"| {if_value(ser.gender_gap, 2)} ' + \
                  f'||style="border-left-width:2px;padding-left:1em;"| {if_value(ser["2014_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2014→2019"], 2)} ' + \
                  f'|| {if_value(ser["2019_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2019→2020"], 2)} ' + \
                  f'|| {if_value(ser["2020_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2020→2021"], 2)} ' + \
                  f'|| {if_value(ser["2021_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2021→2022"], 2)} ' + \
                  f'|| {if_value(ser["2022_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2022→2023"], 2)} ' + \
                  f'|| {if_value(ser["2023_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2023→2024"], 2)} ' + \
                  f'||style="background:#e0ffd8;"| {if_value(ser.total, 2)} ' + \
                  f'||style="background:#fffae0;border-left-width:2px;{chval(ser["2019→2024"], 2)} ' + \
                  (f'||style="background:#fffae0;{chval(ser["2014→2024"], 2)} ' if lang=='ru' else '') + \
                  f'|| {{{{{ptn_2}|{replacements_fr[ser.name] if lang=='fr' else ser.name}}}}}'
    st += '\n|}'
    
    st = st.replace('color:darkgray;"| 0.00 ', 'color:darkgray;"| 0.00 ')  \
           .replace('color:crimson;"| −0.00 ', 'color:darkgray;"| 0.00 ')  \
           .replace('color:darkgreen;"| 0.00 ', 'color:darkgray;"| 0.00 ')  \
           .replace('color:darkgray;"| \'\'\'0.00\'\'\' ', 'color:darkgray;"| \'\'\'0.00\'\'\' ')  \
           .replace('color:crimson;"| \'\'\'−0.00\'\'\' ', 'color:darkgray;"| \'\'\'0.00\'\'\' ')  \
           .replace('color:darkgreen;"| \'\'\'0.00\'\'\' ', 'color:darkgray;"| \'\'\'0.00\'\'\' ')
           

    # WARNING: be sure that inline styles do not contains numbers with comma
    if (lang == 'ru') | (lang == 'fr'):
        st = re.sub('(?<=\\d)\\.(?=\\d)', ',', st)  # replace . to comma, if this . is between two digits
    
    # resolve issue with specific flag of New Caledonia
    if lang == 'ru':
        st = st.replace('{{флагификация|New Caledonia}}', '{{флагификация|New Caledonia|совмещённый_укороченный}}') \
               .replace('{{флаг|New Caledonia}}', '{{флаг|New Caledonia|совмещённый_укороченный}}')
    elif lang == 'fr':
        st = st.replace('{{Pays|Nouvelle-Calédonie}}', '{{Pays|Nouvelle-Calédonie|merged}}') \
               .replace('{{Drapeau|Nouvelle-Calédonie}}', '{{Drapeau|Nouvelle-Calédonie|merged}}') \
               .replace('| {{Pays|Îles Anglo-Normandes}}', '|style="padding-left:35px;"| [[Îles Anglo-Normandes]]') \
               .replace('|| {{Drapeau|Îles Anglo-Normandes}}', '||')
    else:
        st = st.replace('{{flaglist|New Caledonia}}', '{{flaglist|New Caledonia|merged}}') \
               .replace('{{flagicon|New Caledonia}}', '{{flagicon|New Caledonia|merged}}')
        
    # gray color for missing values
    st = st.replace(';"| —', ';color:silver;"| —') \
           .replace('|| —', '||style="color:silver;"| —')

    st = st_header + st + st_footer
    
    return st

#  background:#eaffea;  - highlighting, used for 2019

In [6]:
def extract_data_for_year(df, year='2024'):
    ls_dropping = [
        # 'Hong Kong SAR, China',     # administrative region of China, population 7,291,000
        # 'Macao SAR, China',         # administrative region of China, population 682,000
        'Kosovo',                   # partially recognised state, population 1,806,000
        # 'West Bank and Gaza',        # Palestine, partially recognised state, population 5,227,000
        # 'New Caledonia',             # French Overseas Territory in Oceania, population 271,000
        # 'Channel Islands',           # archipelago in Europe, consisting of two Crown Dependencies, population 172,000
        # 'Curacao',                   #  constituent country of the Netherlands in S.America, population 149,000, little info about LE
        # 'Virgin Islands (U.S.)',     # unincorporated and organized territory of USA, population 87,000
        # 'Isle of Man',               # self-governing Crown Dependency, Europe, population 84,000
        # 'Dominica',                  # micro-state in N.America, population 72,400
        # 'Marshall Islands',          # micro-state in Oceania, population 62,000
        # 'Faroe Islands',             # autonomous territory of Denmark in Europe, population 54,000
        # 'St. Kitts and Nevis',       # micro-state in N.America, population 47,600
        # 'Turks and Caicos Islands',  # British Overseas Territory in N.America, population 44,000
        # 'Sint Maarten (Dutch part)', # constituent country of the Netherlands in N.America, population 41,500
        # 'Gibraltar',                 # British Overseas Territory in Europe, population 34,000
        # 'St. Martin (French part)',  # French Overseas Territory in N.America, population 32,500
        # 'British Virgin Islands',    # British Overseas Territory in N.America, population 30,000
        # 'Palau',           #  mini-state in Oceania, population 22,000, little info about LE
        # 'Tuvalu',                    # island micro-state in Oceania, population 12,000
        # 'Nauru'                      # micro-state in Oceania, population 11,000
        # Monaco             # micro-state in Europe, population 39,000
        # San Marino         # micro-state in Europe, population 33,500
        # Liechtenstein      # micro-state in Europe, population 38,500
        'Euro area',
        'IBRD only',
        'IDA & IBRD total',
        'IDA total',
        'IDA blend',
        'IDA only',
        'OECD members',
        'Small states',
        'Other small states',
        'Europe & Central Asia (excluding high income)',
        'East Asia & Pacific (excluding high income)',
        'Latin America & Caribbean (excluding high income)',
        'Middle East, North Africa, Afghanistan & Pakistan (excluding high income)',
        'Sub-Saharan Africa (excluding high income)',
        'East Asia & Pacific (IDA & IBRD countries)',
        'Europe & Central Asia (IDA & IBRD countries)',
        'Middle East, North Africa, Afghanistan & Pakistan (IDA & IBRD)',
        'Sub-Saharan Africa (IDA & IBRD countries)',           
        'Latin America & the Caribbean (IDA & IBRD countries)',
        'South Asia (IDA & IBRD)',
        'Heavily indebted poor countries (HIPC)',
        # 'Fragile and conflict affected situations',
        'Least developed countries: UN classification',
        'Early-demographic dividend',
        'Late-demographic dividend',
        'Pre-demographic dividend',
        'Post-demographic dividend',
        'Low income',
        'Lower middle income',
        'Low & middle income',
        'Middle income',
        'Upper middle income',
        'High income'
    ]
    
    ser = df.drop(ls_dropping) \
            [str(year)] \
            .dropna() \
            .rename(index = {'United States':'USA',
                             'Russian Federation': 'Russia',
                             'Korea, Rep.': 'South Korea',
                             'Egypt, Arab Rep.': 'Egypt',
                             'Congo, Dem. Rep.': 'DR Congo',   #'Congo, Democratic Republic of',
                             'Congo, Rep.': 'Congo, Rep.', #'Republic of the Congo', #'Congo Republic',  #'Congo, Republic of',
                             'Yemen, Rep.': 'Yemen',
                             'Micronesia, Fed. Sts.': 'Micronesia',
                             'Gambia, The': 'Gambia',
                             'Iran, Islamic Rep.': 'Iran',
                             "Korea, Dem. People's Rep.": 'North Korea',
                             'Syrian Arab Republic': 'Syria',
                             'Venezuela, RB': 'Venezuela',
                             'Kyrgyz Republic': 'Kyrgyzstan',
                             'Lao PDR': 'Laos',
                             'Czech Republic': 'Czechia',
                             'Slovak Republic': 'Slovakia',
                             'Bahamas, The': 'Bahamas',
                             'Brunei Darussalam': 'Brunei',
                             'Turkiye': 'Turkey',
                             'West Bank and Gaza': 'Palestine',
                             'Sint Maarten (Dutch part)': 'Sint Maarten',
                             'St. Martin (French part)': 'Saint Martin',
                             'Viet Nam': 'Vietnam',
                             'Puerto Rico (US)': 'Puerto Rico',
                             'Somalia, Fed. Rep.': 'Somalia',
                             'Naoero' : 'Nauru'
                            })
    
    return ser

In [7]:
df = pd.read_csv('data/World_Bank_Group-total.csv', skiprows=4, index_col=0)

ser_2024_total = extract_data_for_year(df, 2024)
ser_2024_total.name = '2024_total'

ser_2023_total = extract_data_for_year(df, 2023)
ser_2023_total.name = '2023_total'

ser_2022_total = extract_data_for_year(df, 2022)
ser_2022_total.name = '2022_total'

ser_2021_total = extract_data_for_year(df, 2021)
ser_2021_total.name = '2021_total'

ser_2020_total = extract_data_for_year(df, 2020)
ser_2020_total.name = '2020_total'

ser_2019_total = extract_data_for_year(df, 2019)
ser_2019_total.name = '2019_total'

ser_2014_total = extract_data_for_year(df, 2014)
ser_2014_total.name = '2014_total'

del df

print(f"2024-total: {len(ser_2024_total)} records")
print(f"2023-total: {len(ser_2023_total)} records")
print(f"2022-total: {len(ser_2022_total)} records")
print(f"2021-total: {len(ser_2021_total)} records")
print(f"2020-total: {len(ser_2020_total)} records")
print(f"2019-total: {len(ser_2019_total)} records")
print(f"2014-total: {len(ser_2014_total)} records")

2024-total: 231 records
2023-total: 231 records
2022-total: 231 records
2021-total: 231 records
2020-total: 231 records
2019-total: 231 records
2014-total: 231 records

In [8]:
df = pd.read_csv('data/World_Bank_Group-male.csv', skiprows=4, index_col=0)

ser_2024_male = extract_data_for_year(df, 2024)
ser_2024_male.name = '2024_male'

del df

print(f"2024-male: {len(ser_2024_male)} records")

2024-male: 231 records

In [9]:
df = pd.read_csv('data/World_Bank_Group-female.csv', skiprows=4, index_col=0)

ser_2024_female = extract_data_for_year(df, 2024)
ser_2024_female.name = '2024_female'

del df

print(f"2024-female: {len(ser_2024_female)} records")

2024-female: 231 records

In [10]:
# concate series, removing records without data for last years
df = pd.concat([ser_2024_total, ser_2024_male, ser_2024_female, ser_2023_total, ser_2022_total, ser_2021_total, ser_2020_total, ser_2019_total], axis='columns', join='outer')  \
       .join([ser_2014_total], how='left')

df.index.name = ''

# change order of columls and rename them
df = df[['2024_total', '2024_male', '2024_female', '2014_total', '2019_total', '2020_total', '2021_total', '2022_total', '2023_total']]
df.rename(columns={'2024_total': 'total',
                   '2024_male': 'male',
                   '2024_female': 'female',
                   '2014_total': '2014_t',
                   '2019_total': '2019_t',
                   '2020_total': '2020_t',
                   '2021_total': '2021_t',
                   '2022_total': '2022_t',
                   '2023_total': '2023_t'}, inplace=True)

print(df.shape)
df.loc[['World', 'Russia']].round(3)

(231, 9)

         total    male  female  2014_t  2019_t  2020_t  2021_t  2022_t  2023_t

World   73.482  71.116  75.973  71.776  72.870  72.183  71.216  72.969  73.330
Russia  73.440  68.260  78.880  70.744  73.084  71.339  69.900  72.546  73.255

In [11]:
# calculate difference between some columns and insert result as new columns in dataframe
df.insert(loc=3, column='gender_gap', value=df['female']-df['male'])
df.insert(loc=5, column='2014→2019', value=df['2019_t']-df['2014_t'])
df.insert(loc=7, column='2019→2020', value=df['2020_t']-df['2019_t'])
df.insert(loc=9, column='2020→2021', value=df['2021_t']-df['2020_t'])
df.insert(loc=11, column='2021→2022', value=df['2022_t']-df['2021_t'])
df.insert(loc=13, column='2022→2023', value=df['2023_t']-df['2022_t'])
df.insert(loc=15, column='2023→2024', value=df['total']-df['2023_t'])
df.insert(loc=16, column='2019→2024', value=df['total']-df['2019_t'])
df.insert(loc=17, column='2014→2024', value=df['total']-df['2014_t'])

# sort DataFrame by total life expectancy
df.sort_values(by=SORT_COLUMNS, ascending=False, inplace=True)

print(df.shape)
df.loc[['World', 'Russia']].round(3)

(231, 18)

,total,male,female,gender_gap,2014_t,2014→2019,2019_t,2019→2020,2020_t,2020→2021,2021_t,2021→2022,2022_t,2022→2023,2023_t,2023→2024,2019→2024,2014→2024
,,,,,,,,,,,,,,,,,,
World,73.482,71.116,75.973,4.857,71.776,1.094,72.870,-0.687,72.183,-0.967,71.216,1.753,72.969,0.361,73.330,0.152,0.612,1.705
Russia,73.440,68.260,78.880,10.620,70.744,2.340,73.084,-1.745,71.339,-1.439,69.900,2.645,72.546,0.709,73.255,0.186,0.357,2.697

<br />
<br />
<br />

In [12]:
mal.min_and_max_values(df[['total', 'male', 'female', '2014_t', '2019_t', '2020_t', '2021_t', '2022_t', '2023_t', '2023→2024', '2019→2024', '2014→2024']],
                       row_center=['Spain', 'France', 'World', 'Russia'], shorten=True, nmb=5, max_lng=13)

Number of records: 231

<br />
<br />
<br />

In [13]:
# ls_new = df.index.to_list()
# print(len(ls_new))

# ls_old = ['Japan', 'Singapore', 'South Korea', ...]

# print(len(ls_old))

In [14]:
# [country for country in ls_new if country not in ls_old]

In [15]:
# [country for country in ls_old if country not in ls_new]

In [16]:
def filter_df(df, ls):
    filtered_df = df.loc[ls]   \
                    .sort_values(by=SORT_COLUMNS, ascending=False)
    
    print(f"Total : {filtered_df.total.min() :.2f} – {filtered_df.total.max() :.2f}   ({filtered_df.total.idxmin()} – {filtered_df.total.idxmax()})")
    print(f"Male  : {filtered_df.male.min()  :.2f} – {filtered_df.male.max()  :.2f}   ({filtered_df.male.idxmin()} – {filtered_df.male.idxmax()})")
    print(f"Female: {filtered_df.female.min():.2f} – {filtered_df.female.max():.2f}   ({filtered_df.female.idxmin()} – {filtered_df.female.idxmax()})")
    
    return filtered_df

<br />
<br />
<br />

In [17]:
ls_N_America = ['Antigua and Barbuda', 'Bahamas', 'Barbados', 'Belize', 'Canada', 'Costa Rica',
                'Cuba', 'Dominican Republic', 'El Salvador', 'Grenada', 'Guatemala',
                'Haiti', 'Honduras', 'Jamaica', 'Mexico', 'Nicaragua', 'Panama',
                'St. Lucia', 'St. Vincent and the Grenadines',
                'Trinidad and Tobago', 'USA',
                'World',                
                'Bermuda', 'Puerto Rico', 'Virgin Islands (U.S.)', 'British Virgin Islands', 'Turks and Caicos Islands',
                'Caribbean small states', 'Sint Maarten', 'Saint Martin', 'Dominica', 'St. Kitts and Nevis',
                'Aruba', 'Greenland', 'Cayman Islands', 'Curacao']

df_N_America = filter_df(df, ls_N_America)

df_N_America.round(2).fillna('')

Total : 65.12 – 82.49   (Haiti – Bermuda)
Male  : 61.90 – 80.03   (Haiti – Canada)
Female: 68.49 – 85.87   (Haiti – Bermuda)

,total,male,female,gender_gap,2014_t,2014→2019,2019_t,2019→2020,2020_t,2020→2021,2021_t,2021→2022,2022_t,2022→2023,2023_t,2023→2024,2019→2024,2014→2024
,,,,,,,,,,,,,,,,,,
Bermuda,82.49,79.06,85.87,6.81,80.20,1.05,81.25,0.20,81.46,0.29,81.74,0.32,82.06,0.25,82.31,0.18,1.24,2.29
Canada,82.11,80.03,84.29,4.26,81.78,0.37,82.16,-0.63,81.53,-0.08,81.45,-0.36,81.09,0.53,81.63,0.48,-0.05,0.32
Puerto Rico,81.90,78.28,85.38,7.10,80.04,1.40,81.44,-1.43,80.01,-0.24,79.77,-0.34,79.43,2.26,81.69,0.21,0.46,1.86
Costa Rica,81.00,78.37,83.58,5.21,80.23,0.07,80.30,-0.57,79.72,-1.67,78.05,1.27,79.32,1.48,80.80,0.20,0.70,0.77
Virgin Islands (U.S.),80.77,77.60,84.10,6.50,78.87,0.80,79.67,0.15,79.82,0.25,80.07,0.25,80.32,0.20,80.52,0.25,1.10,1.90
Cayman Islands,80.54,78.20,83.00,4.81,77.86,1.19,79.05,0.18,79.23,0.07,79.30,0.68,79.98,0.37,80.36,0.18,1.49,2.68
Saint Martin,80.44,76.99,83.96,6.98,79.73,0.35,80.08,0.01,80.08,0.12,80.21,0.03,80.24,-0.01,80.22,0.21,0.36,0.71
Panama,79.78,76.88,82.71,5.83,77.36,1.15,78.51,-2.18,76.33,0.67,77.00,2.32,79.32,0.27,79.59,0.18,1.26,2.41
USA,78.89,76.50,81.40,4.90,78.84,-0.05,78.79,-1.81,76.98,-0.65,76.33,1.10,77.43,0.95,78.39,0.50,0.10,0.05
Cuba,78.26,75.86,80.68,4.82,77.82,-0.41,77.41,-0.01,77.41,-4.21,73.20,4.43,77.63,0.46,78.08,0.18,0.85,0.44
Turks and Caicos Islands,78.18,76.01,80.45,4.44,77.21,0.48,77.69,-0.19,77.50,-0.27,77.23,0.68,77.92,0.09,78.01,0.17,0.49,0.97
Antigua and Barbuda,77.77,74.74,80.45,5.70,76.91,0.26,77.17,-0.01,77.16,0.04,77.20,0.29,77.48,0.11,77.60,0.17,0.60,0.85
British Virgin Islands,77.43,74.70,80.19,5.49,76.53,0.32,76.84,0.05,76.89,-1.60,75.30,1.88,77.18,0.10,77.28,0.16,0.59,0.90
Curacao,76.99,72.66,80.96,8.30,76.38,0.11,76.49,0.01,76.50,-0.81,75.69,1.04,76.73,0.07,76.80,0.19,0.50,0.61
Sint Maarten,76.53,73.85,79.66,5.81,75.74,-0.05,75.68,-0.68,75.00,-0.50,74.50,1.68,76.18,0.19,76.37,0.16,0.85,0.79
Aruba,76.50,73.84,78.92,5.07,75.26,0.76,76.02,-0.61,75.41,-1.75,73.66,2.57,76.23,0.13,76.35,0.15,0.48,1.24
Barbados,76.33,73.75,78.76,5.01,75.93,0.57,76.50,0.15,76.65,-0.07,76.58,-0.90,75.68,0.50,76.18,0.15,-0.16,0.41
Grenada,75.37,72.52,78.50,5.98,75.04,-0.07,74.97,0.05,75.02,-0.50,74.52,0.63,75.15,0.05,75.20,0.16,0.40,0.32
Mexico,75.26,72.44,78.00,5.56,74.40,0.13,74.53,-4.08,70.45,-0.70,69.75,4.22,73.97,1.10,75.07,0.19,0.73,0.86
Nicaragua,75.10,72.46,77.58,5.11,72.79,0.97,73.76,-3.00,70.77,-0.29,70.48,3.98,74.46,0.48,74.95,0.15,1.34,2.31
Bahamas,74.71,71.06,78.33,7.27,74.03,-2.62,71.41,1.59,72.99,-2.24,70.75,3.74,74.49,0.06,74.55,0.16,3.30,0.68
Dominican Republic,73.87,70.66,77.10,6.44,73.14,-0.03,73.11,-0.48,72.64,-0.88,71.76,2.45,74.21,-0.49,73.72,0.15,0.76,0.72
Belize,73.74,71.08,76.66,5.58,71.44,1.14,72.58,-1.00,71.58,-0.66,70.92,1.27,72.19,1.38,73.57,0.17,1.16,2.30
Trinidad and Tobago,73.62,70.51,76.82,6.32,72.90,-0.06,72.84,-0.19,72.64,-1.53,71.11,2.22,73.33,0.16,73.49,0.13,0.78,0.72
World,73.48,71.12,75.97,4.86,71.78,1.09,72.87,-0.69,72.18,-0.97,71.22,1.75,72.97,0.36,73.33,0.15,0.61,1.71
Caribbean small states,73.31,70.12,76.60,6.48,71.77,0.36,72.13,-0.19,71.94,-2.02,69.92,2.91,72.83,0.34,73.17,0.14,1.18,1.54
Honduras,73.04,70.49,75.67,5.18,71.03,1.09,72.12,-1.26,70.86,-1.37,69.49,3.22,72.72,0.17,72.88,0.16,0.92,2.01
St. Lucia,72.85,69.45,76.45,7.00,72.68,-0.43,72.25,0.06,72.31,-3.19,69.12,3.55,72.67,0.03,72.70,0.15,0.60,0.17
Guatemala,72.75,70.44,75.04,4.60,70.94,0.70,71.64,-1.67,69.97,-2.11,67.86,3.35,71.21,1.40,72.60,0.14,1.11,1.80
El Salvador,72.30,67.76,76.49,8.73,71.14,0.58,71.72,-1.48,70.24,-0.30,69.94,2.03,71.97,0.13,72.10,0.20,0.58,1.16
St. Kitts and Nevis,72.28,68.69,76.16,7.47,71.23,0.31,71.54,-0.36,71.18,-1.91,69.27,1.04,70.31,1.83,72.14,0.14,0.74,1.05
Jamaica,71.61,69.08,74.15,5.07,72.36,-0.83,71.53,-0.08,71.45,-2.37,69.08,2.40,71.48,-0.00,71.48,0.13,0.07,-0.75
St. Vincent and the Grenadines,71.38,68.78,74.48,5.69,70.36,0.64,70.99,-1.39,69.60,-0.47,69.13,2.06,71.19,0.04,71.23,0.15,0.39,1.03
Dominica,71.29,68.35,74.72,6.37,71.19,0.12,71.31,-0.04,71.27,-1.44,69.83,1.25,71.08,0.05,71.13,0.16,-0.01,0.11
Greenland,70.27,68.41,72.23,3.82,70.51,0.90,71.41,-0.12,71.29,-0.02,71.26,-0.03,71.23,-0.26,70.97,-0.70,-1.14,-0.23
Haiti,65.12,61.90,68.49,6.59,62.97,1.36,64.33,-0.55,63.77,-1.16,62.61,1.34,63.95,0.99,64.94,0.18,0.79,2.15

In [18]:
table_code_N_America = create_table(df_N_America)
output_table_code(table_code_N_America, 'Table code WBG -2024 -America_North -en.txt')

Data has written to file

In [19]:
table_code_N_America = create_table(df_N_America, lang='ru')
output_table_code(table_code_N_America, 'Table code WBG -2024 -America_North -ru.txt')

Data has written to file

<br />
<br />
<br />

In [20]:
ls_S_America = ['Argentina', 'Bolivia', 'Brazil', 'Chile', 'Colombia', 'Ecuador',
                'Guyana', 'Paraguay', 'Peru', 'Suriname', 'Uruguay', 'Venezuela',
                'World']

df_S_America = filter_df(df, ls_S_America)

df_S_America.round(2)

Total : 68.74 – 81.36   (Bolivia – Chile)
Male  : 66.27 – 79.45   (Bolivia – Chile)
Female: 71.32 – 83.23   (Bolivia – Chile)

,total,male,female,gender_gap,2014_t,2014→2019,2019_t,2019→2020,2020_t,2020→2021,2021_t,2021→2022,2022_t,2022→2023,2023_t,2023→2024,2019→2024,2014→2024
,,,,,,,,,,,,,,,,,,
Chile,81.36,79.45,83.23,3.77,79.71,0.61,80.32,-0.97,79.35,-0.47,78.88,0.30,79.18,1.99,81.17,0.19,1.03,1.64
Uruguay,78.29,74.38,82.04,7.66,77.19,0.31,77.50,0.88,78.38,-2.95,75.43,1.03,76.47,1.67,78.14,0.15,0.78,1.09
Peru,77.94,75.63,80.30,4.67,75.26,1.02,76.28,-2.44,73.83,-2.24,71.60,5.24,76.83,0.91,77.74,0.20,1.67,2.68
Colombia,77.91,75.16,80.61,5.45,75.95,0.84,76.79,-2.04,74.76,-2.06,72.70,3.81,76.51,1.22,77.72,0.19,1.12,1.96
Ecuador,77.58,74.88,80.31,5.43,76.14,1.14,77.29,-5.28,72.00,0.74,72.75,3.83,76.58,0.81,77.39,0.19,0.29,1.44
Argentina,77.54,74.98,80.02,5.04,76.27,0.58,76.85,-0.97,75.88,-1.93,73.95,1.86,75.81,1.59,77.40,0.15,0.70,1.28
Brazil,76.02,72.95,79.14,6.19,74.82,0.99,75.81,-1.30,74.51,-1.47,73.04,1.83,74.87,0.98,75.85,0.17,0.21,1.20
Paraguay,73.98,71.01,77.09,6.08,73.42,0.25,73.67,-0.95,72.72,-4.61,68.11,4.21,72.32,1.52,73.84,0.14,0.31,0.57
Suriname,73.76,70.60,76.98,6.38,70.33,1.44,71.77,0.55,72.32,-3.38,68.94,4.31,73.25,0.38,73.63,0.13,1.98,3.43
World,73.48,71.12,75.97,4.86,71.78,1.09,72.87,-0.69,72.18,-0.97,71.22,1.75,72.97,0.36,73.33,0.15,0.61,1.71
Venezuela,72.67,68.89,76.66,7.77,72.84,-0.07,72.77,-0.40,72.37,-0.83,71.54,1.03,72.57,-0.05,72.51,0.16,-0.09,-0.16
Guyana,70.32,66.62,74.09,7.47,67.33,1.73,69.07,-1.32,67.75,-3.43,64.32,5.57,69.89,0.29,70.18,0.14,1.25,2.98
Bolivia,68.74,66.27,71.32,5.06,66.97,0.85,67.82,-4.91,62.91,-1.48,61.43,6.01,67.43,1.15,68.58,0.16,0.92,1.77

In [21]:
table_code_S_America = create_table(df_S_America)
output_table_code(table_code_S_America, 'Table code WBG -2024 -America_South -en.txt')

Data has written to file

In [22]:
table_code_S_America = create_table(df_S_America, lang='ru')
output_table_code(table_code_S_America, 'Table code WBG -2024 -America_South -ru.txt')

Data has written to file

<br />
<br />
<br />

In [23]:
ls_Americas = ls_N_America + ls_S_America + ['Latin America & Caribbean', 'North America']
ls_Americas.remove('World')

df_Americas = filter_df(df, ls_Americas)

df_Americas.round(2).fillna('')

Total : 65.12 – 82.49   (Haiti – Bermuda)
Male  : 61.90 – 80.03   (Haiti – Canada)
Female: 68.49 – 85.87   (Haiti – Bermuda)

,total,male,female,gender_gap,2014_t,2014→2019,2019_t,2019→2020,2020_t,2020→2021,2021_t,2021→2022,2022_t,2022→2023,2023_t,2023→2024,2019→2024,2014→2024
,,,,,,,,,,,,,,,,,,
Bermuda,82.49,79.06,85.87,6.81,80.20,1.05,81.25,0.20,81.46,0.29,81.74,0.32,82.06,0.25,82.31,0.18,1.24,2.29
Canada,82.11,80.03,84.29,4.26,81.78,0.37,82.16,-0.63,81.53,-0.08,81.45,-0.36,81.09,0.53,81.63,0.48,-0.05,0.32
Puerto Rico,81.90,78.28,85.38,7.10,80.04,1.40,81.44,-1.43,80.01,-0.24,79.77,-0.34,79.43,2.26,81.69,0.21,0.46,1.86
Chile,81.36,79.45,83.23,3.77,79.71,0.61,80.32,-0.97,79.35,-0.47,78.88,0.30,79.18,1.99,81.17,0.19,1.03,1.64
Costa Rica,81.00,78.37,83.58,5.21,80.23,0.07,80.30,-0.57,79.72,-1.67,78.05,1.27,79.32,1.48,80.80,0.20,0.70,0.77
Virgin Islands (U.S.),80.77,77.60,84.10,6.50,78.87,0.80,79.67,0.15,79.82,0.25,80.07,0.25,80.32,0.20,80.52,0.25,1.10,1.90
Cayman Islands,80.54,78.20,83.00,4.81,77.86,1.19,79.05,0.18,79.23,0.07,79.30,0.68,79.98,0.37,80.36,0.18,1.49,2.68
Saint Martin,80.44,76.99,83.96,6.98,79.73,0.35,80.08,0.01,80.08,0.12,80.21,0.03,80.24,-0.01,80.22,0.21,0.36,0.71
Panama,79.78,76.88,82.71,5.83,77.36,1.15,78.51,-2.18,76.33,0.67,77.00,2.32,79.32,0.27,79.59,0.18,1.26,2.41
North America,79.24,76.88,81.72,4.84,79.14,-0.00,79.13,-1.68,77.45,-0.59,76.86,0.96,77.82,0.91,78.73,0.51,0.11,0.10
USA,78.89,76.50,81.40,4.90,78.84,-0.05,78.79,-1.81,76.98,-0.65,76.33,1.10,77.43,0.95,78.39,0.50,0.10,0.05
Uruguay,78.29,74.38,82.04,7.66,77.19,0.31,77.50,0.88,78.38,-2.95,75.43,1.03,76.47,1.67,78.14,0.15,0.78,1.09
Cuba,78.26,75.86,80.68,4.82,77.82,-0.41,77.41,-0.01,77.41,-4.21,73.20,4.43,77.63,0.46,78.08,0.18,0.85,0.44
Turks and Caicos Islands,78.18,76.01,80.45,4.44,77.21,0.48,77.69,-0.19,77.50,-0.27,77.23,0.68,77.92,0.09,78.01,0.17,0.49,0.97
Peru,77.94,75.63,80.30,4.67,75.26,1.02,76.28,-2.44,73.83,-2.24,71.60,5.24,76.83,0.91,77.74,0.20,1.67,2.68
Colombia,77.91,75.16,80.61,5.45,75.95,0.84,76.79,-2.04,74.76,-2.06,72.70,3.81,76.51,1.22,77.72,0.19,1.12,1.96
Antigua and Barbuda,77.77,74.74,80.45,5.70,76.91,0.26,77.17,-0.01,77.16,0.04,77.20,0.29,77.48,0.11,77.60,0.17,0.60,0.85
Ecuador,77.58,74.88,80.31,5.43,76.14,1.14,77.29,-5.28,72.00,0.74,72.75,3.83,76.58,0.81,77.39,0.19,0.29,1.44
Argentina,77.54,74.98,80.02,5.04,76.27,0.58,76.85,-0.97,75.88,-1.93,73.95,1.86,75.81,1.59,77.40,0.15,0.70,1.28
British Virgin Islands,77.43,74.70,80.19,5.49,76.53,0.32,76.84,0.05,76.89,-1.60,75.30,1.88,77.18,0.10,77.28,0.16,0.59,0.90
Curacao,76.99,72.66,80.96,8.30,76.38,0.11,76.49,0.01,76.50,-0.81,75.69,1.04,76.73,0.07,76.80,0.19,0.50,0.61
Sint Maarten,76.53,73.85,79.66,5.81,75.74,-0.05,75.68,-0.68,75.00,-0.50,74.50,1.68,76.18,0.19,76.37,0.16,0.85,0.79
Aruba,76.50,73.84,78.92,5.07,75.26,0.76,76.02,-0.61,75.41,-1.75,73.66,2.57,76.23,0.13,76.35,0.15,0.48,1.24
Barbados,76.33,73.75,78.76,5.01,75.93,0.57,76.50,0.15,76.65,-0.07,76.58,-0.90,75.68,0.50,76.18,0.15,-0.16,0.41
Brazil,76.02,72.95,79.14,6.19,74.82,0.99,75.81,-1.30,74.51,-1.47,73.04,1.83,74.87,0.98,75.85,0.17,0.21,1.20
Latin America & Caribbean,75.82,72.95,78.69,5.74,74.56,0.64,75.20,-2.02,73.19,-1.37,71.81,2.83,74.65,1.00,75.64,0.17,0.61,1.26
Grenada,75.37,72.52,78.50,5.98,75.04,-0.07,74.97,0.05,75.02,-0.50,74.52,0.63,75.15,0.05,75.20,0.16,0.40,0.32
Mexico,75.26,72.44,78.00,5.56,74.40,0.13,74.53,-4.08,70.45,-0.70,69.75,4.22,73.97,1.10,75.07,0.19,0.73,0.86
Nicaragua,75.10,72.46,77.58,5.11,72.79,0.97,73.76,-3.00,70.77,-0.29,70.48,3.98,74.46,0.48,74.95,0.15,1.34,2.31
Bahamas,74.71,71.06,78.33,7.27,74.03,-2.62,71.41,1.59,72.99,-2.24,70.75,3.74,74.49,0.06,74.55,0.16,3.30,0.68
Paraguay,73.98,71.01,77.09,6.08,73.42,0.25,73.67,-0.95,72.72,-4.61,68.11,4.21,72.32,1.52,73.84,0.14,0.31,0.57
Dominican Republic,73.87,70.66,77.10,6.44,73.14,-0.03,73.11,-0.48,72.64,-0.88,71.76,2.45,74.21,-0.49,73.72,0.15,0.76,0.72
Suriname,73.76,70.60,76.98,6.38,70.33,1.44,71.77,0.55,72.32,-3.38,68.94,4.31,73.25,0.38,73.63,0.13,1.98,3.43
Belize,73.74,71.08,76.66,5.58,71.44,1.14,72.58,-1.00,71.58,-0.66,70.92,1.27,72.19,1.38,73.57,0.17,1.16,2.30
Trinidad and Tobago,73.62,70.51,76.82,6.32,72.90,-0.06,72.84,-0.19,72.64,-1.53,71.11,2.22,73.33,0.16,73.49,0.13,0.78,0.72
World,73.48,71.12,75.97,4.86,71.78,1.09,72.87,-0.69,72.18,-0.97,71.22,1.75,72.97,0.36,73.33,0.15,0.61,1.71
Caribbean small states,73.31,70.12,76.60,6.48,71.77,0.36,72.13,-0.19,71.94,-2.02,69.92,2.91,72.83,0.34,73.17,0.14,1.18,1.54
Honduras,73.04,70.49,75.67,5.18,71.03,1.09,72.12,-1.26,70.86,-1.37,69.49,3.22,72.72,0.17,72.88,0.16,0.92,2.01
St. Lucia,72.85,69.45,76.45,7.00,72.68,-0.43,72.25,0.06,72.31,-3.19,69.12,3.55,72.67,0.03,72.70,0.15,0.60,0.17
Guatemala,72.75,70.44,75.04,4.60,70.94,0.70,71.64,-1.67,69.97,-2.11,67.86,3.35,71.21,1.40,72.60,0.14,1.11,1.80
Venezuela,72.67,68.89,76.66,7.77,72.84,-0.07,72.77,-0.40,72.37,-0.83,71.54,1.03,72.57,-0.05,72.51,0.16,-0.09,-0.16
El Salvador,72.30,67.76,76.49,8.73,71.14,0.58,71.72,-1.48,70.24,-0.30,69.94,2.03,71.97,0.13,72.10,0.20,0.58,1.16
St. Kitts and Nevis,72.28,68.69,76.16,7.47,71.23,0.31,71.54,-0.36,71.18,-1.91,69.27,1.04,70.31,1.83,72.14,0.14,0.74,1.05
Jamaica,71.61,69.08,74.15,5.07,72.36,-0.83,71.53,-0.08,71.45,-2.37,69.08,2.40,71.48,-0.00,71.48,0.13,0.07,-0.75
St. Vincent and the Grenadines,71.38,68.78,74.48,5.69,70.36,0.64,70.99,-1.39,69.60,-0.47,69.13,2.06,71.19,0.04,71.23,0.15,0.39,1.03
Dominica,71.29,68.35,74.72,6.37,71.19,0.12,71.31,-0.04,71.27,-1.44,69.83,1.25,71.08,0.05,71.13,0.16,-0.01,0.11
Guyana,70.32,66.62,74.09,7.47,67.33,1.73,69.07,-1.32,67.75,-3.43,64.32,5.57,69.89,0.29,70.18,0.14,1.25,2.98
Greenland,70.27,68.41,72.23,3.82,70.51,0.90,71.41,-0.12,71.29,-0.02,71.26,-0.03,71.23,-0.26,70.97,-0.70,-1.14,-0.23
Bolivia,68.74,66.27,71.32,5.06,66.97,0.85,67.82,-4.91,62.91,-1.48,61.43,6.01,67.43,1.15,68.58,0.16,0.92,1.77
Haiti,65.12,61.90,68.49,6.59,62.97,1.36,64.33,-0.55,63.77,-1.16,62.61,1.34,63.95,0.99,64.94,0.18,0.79,2.15

In [24]:
table_code_Americas = create_table(df_Americas)
output_table_code(table_code_Americas, 'Table code WBG -2024 -Americas -en.txt')

Data has written to file

In [25]:
table_code_Americas = create_table(df_Americas, lang='ru')
output_table_code(table_code_Americas, 'Table code WBG -2024 -Americas -ru.txt')

Data has written to file

<br />
<br />
<br />

In [26]:
ls_Asia = ['Afghanistan', 'Armenia', 'Azerbaijan', 'Bahrain', 'Bangladesh', 'Bhutan', 'Brunei', 'Cambodia', 'China', 'Cyprus', 'Egypt',
           'Georgia', 'India', 'Indonesia', 'Iran', 'Iraq', 'Israel', 'Japan', 'Jordan', 'Kazakhstan', 'North Korea', 'South Korea',
           'Kuwait', 'Kyrgyzstan', 'Laos', 'Lebanon', 'Malaysia', 'Maldives', 'Mongolia', 'Myanmar', 'Nepal', 'Oman', 'Pakistan',
           'Philippines', 'Qatar', 'Russia', 'Saudi Arabia', 'Singapore', 'Sri Lanka', 'Syria', 'Tajikistan', 'Thailand', 'Timor-Leste',
           'Turkey', 'Turkmenistan', 'United Arab Emirates', 'Uzbekistan', 'Vietnam', 'Yemen', 'Palestine',
           'Hong Kong SAR, China', 'Macao SAR, China',
           'World']  # 'Europe & Central Asia', 'South Asia', 'East Asia & Pacific', 'Middle East, North Africa, Afghanistan & Pakistan'

df_Asia = filter_df(df, ls_Asia)

df_Asia.round(2)

Total : 66.29 – 85.39   (Afghanistan – Hong Kong SAR, China)
Male  : 63.99 – 83.80   (Myanmar – Kuwait)
Female: 67.81 – 88.22   (Afghanistan – Hong Kong SAR, China)

,total,male,female,gender_gap,2014_t,2014→2019,2019_t,2019→2020,2020_t,2020→2021,2021_t,2021→2022,2022_t,2022→2023,2023_t,2023→2024,2019→2024,2014→2024
,,,,,,,,,,,,,,,,,,
"Hong Kong SAR, China",85.39,82.70,88.22,5.52,83.94,1.22,85.16,0.34,85.50,0.04,85.53,-1.87,83.66,1.59,85.25,0.15,0.24,1.46
Kuwait,84.58,83.80,85.40,1.60,79.08,2.89,81.97,-3.21,78.76,-0.02,78.74,1.85,80.59,2.60,83.19,1.39,2.61,5.50
Japan,84.04,81.09,87.13,6.04,83.59,0.77,84.36,0.20,84.56,-0.11,84.45,-0.45,84.00,0.04,84.04,-0.00,-0.32,0.45
South Korea,83.63,80.80,86.60,5.80,81.72,1.50,83.23,0.20,83.43,0.10,83.53,-0.85,82.68,0.75,83.43,0.20,0.40,1.91
Singapore,83.35,81.20,85.60,4.40,82.50,1.10,83.60,-0.05,83.54,-0.45,83.09,-0.20,82.90,0.20,83.10,0.25,-0.25,0.85
"Macao SAR, China",83.33,80.60,86.20,5.60,83.02,0.91,83.93,0.20,84.13,-0.40,83.73,-0.65,83.08,0.10,83.18,0.15,-0.60,0.31
Israel,83.20,81.10,85.40,4.30,82.15,0.65,82.80,-0.16,82.65,-0.15,82.50,0.20,82.70,0.50,83.20,0.00,0.39,1.04
United Arab Emirates,83.07,82.17,84.32,2.15,81.99,0.61,82.60,-0.66,81.94,-2.85,79.08,1.40,80.49,2.42,82.91,0.16,0.47,1.08
Qatar,82.52,81.78,83.48,1.70,81.40,1.55,82.94,-2.54,80.41,0.67,81.08,0.77,81.86,0.51,82.37,0.15,-0.42,1.13
Cyprus,81.82,79.84,83.80,3.96,81.34,0.12,81.45,-0.22,81.23,-0.66,80.57,-0.14,80.43,1.21,81.65,0.17,0.37,0.48
Bahrain,81.42,80.86,82.13,1.27,80.21,0.26,80.47,-1.79,78.68,-0.60,78.08,2.91,80.99,0.29,81.28,0.14,0.95,1.21
Maldives,81.28,79.95,83.00,3.05,78.19,1.52,79.71,-0.99,78.71,-0.66,78.05,2.71,80.76,0.28,81.04,0.24,1.58,3.10
Oman,80.25,78.72,82.05,3.33,79.03,0.92,79.95,-2.18,77.76,-1.79,75.97,1.94,77.91,2.12,80.03,0.21,0.30,1.22
Saudi Arabia,78.98,77.33,81.33,4.00,77.12,1.20,78.31,-0.72,77.60,-0.51,77.09,0.22,77.31,1.42,78.73,0.25,0.67,1.87
Armenia,78.32,75.10,81.70,6.60,74.87,1.35,76.22,-2.85,73.38,-1.10,72.28,2.49,74.77,2.70,77.47,0.85,2.10,3.45
China,78.02,75.25,80.97,5.72,76.71,1.23,77.94,0.08,78.02,0.10,78.12,0.08,78.20,-0.25,77.95,0.06,0.08,1.30
Jordan,77.98,75.89,80.33,4.44,74.61,2.26,76.86,-1.28,75.58,-1.38,74.20,2.88,77.09,0.73,77.81,0.17,1.12,3.38
Lebanon,77.94,75.88,79.86,3.98,78.15,0.06,78.21,-1.91,76.30,-2.65,73.65,4.35,78.00,-0.19,77.82,0.13,-0.26,-0.20
Iran,77.85,76.00,79.81,3.81,75.64,1.22,76.86,-2.71,74.14,-0.39,73.75,3.05,76.80,0.85,77.65,0.20,1.00,2.22
Sri Lanka,77.67,74.45,80.75,6.30,75.76,0.94,76.70,0.23,76.93,-0.65,76.28,1.02,77.30,0.18,77.48,0.19,0.97,1.91
Turkey,77.42,74.62,80.34,5.72,76.45,1.28,77.74,-1.21,76.53,-0.80,75.72,1.87,77.59,-0.43,77.16,0.27,-0.32,0.97
Malaysia,76.82,74.45,79.52,5.07,75.34,0.56,75.90,0.16,76.06,-2.14,73.92,1.53,75.44,1.21,76.66,0.16,0.92,1.48
Thailand,76.56,72.34,80.98,8.64,76.28,0.92,77.20,0.13,77.33,0.27,77.61,-2.31,75.29,1.12,76.41,0.15,-0.63,0.28
Brunei,75.50,73.49,77.73,4.24,74.86,0.19,75.05,0.06,75.11,-0.25,74.87,-1.95,72.92,2.41,75.33,0.17,0.45,0.64
Bangladesh,74.93,73.30,76.67,3.36,70.02,2.61,72.62,-1.20,71.42,-0.32,71.10,3.16,74.26,0.41,74.67,0.26,2.31,4.91
Vietnam,74.74,70.05,79.38,9.33,73.89,0.33,74.21,1.17,75.38,-1.24,74.14,0.36,74.50,0.09,74.59,0.15,0.53,0.85
Georgia,74.66,69.75,79.23,9.49,73.10,1.06,74.17,-0.66,73.51,-1.87,71.64,2.51,74.14,0.35,74.50,0.16,0.49,1.55
Azerbaijan,74.58,71.71,77.28,5.58,71.93,1.36,73.29,-2.98,70.31,0.69,71.00,3.13,74.12,0.30,74.43,0.15,1.29,2.65
Kazakhstan,74.53,70.27,78.52,8.25,71.42,2.24,73.66,-2.46,71.19,-1.06,70.13,3.37,73.50,0.90,74.40,0.13,0.87,3.12
North Korea,73.74,71.55,75.88,4.33,72.45,0.48,72.93,-0.14,72.78,0.65,73.44,0.20,73.64,0.00,73.64,0.10,0.81,1.29
World,73.48,71.12,75.97,4.86,71.78,1.09,72.87,-0.69,72.18,-0.97,71.22,1.75,72.97,0.36,73.33,0.15,0.61,1.71
Russia,73.44,68.26,78.88,10.62,70.74,2.34,73.08,-1.75,71.34,-1.44,69.90,2.65,72.55,0.71,73.25,0.19,0.36,2.70
Bhutan,73.26,71.57,75.27,3.70,70.50,1.50,72.00,0.25,72.25,0.19,72.45,0.31,72.75,0.22,72.97,0.29,1.26,2.76
Syria,72.56,70.21,74.92,4.71,65.49,5.48,70.97,0.97,71.94,0.47,72.42,0.37,72.79,-0.67,72.12,0.44,1.59,7.07
Uzbekistan,72.53,69.56,75.55,5.98,70.97,1.12,72.09,-0.63,71.46,0.22,71.68,0.47,72.15,0.24,72.39,0.14,0.44,1.56
Iraq,72.42,70.50,74.18,3.68,69.68,1.57,71.24,-1.59,69.65,1.05,70.70,1.33,72.04,0.29,72.32,0.10,1.18,2.75
Kyrgyzstan,72.40,68.40,76.60,8.20,70.40,1.20,71.60,0.20,71.80,0.10,71.90,0.15,72.05,0.20,72.25,0.15,0.80,2.00
Mongolia,72.40,67.92,77.10,9.18,70.58,0.47,71.05,0.30,71.35,0.30,71.65,0.26,71.90,0.22,72.12,0.28,1.34,1.81
India,72.24,70.73,73.86,3.13,68.93,1.81,70.75,-0.59,70.16,-2.87,67.28,4.42,71.70,0.31,72.00,0.23,1.49,3.30
Tajikistan,71.93,69.68,74.14,4.46,69.70,1.27,70.96,-2.36,68.60,0.99,69.59,1.97,71.56,0.23,71.79,0.14,0.97,2.23
Egypt,71.81,69.65,74.01,4.36,69.91,1.30,71.21,-1.42,69.79,-0.81,68.98,2.03,71.01,0.62,71.63,0.17,0.59,1.89
Indonesia,71.29,69.16,73.43,4.27,69.29,1.06,70.35,-1.53,68.82,-1.36,67.45,3.47,70.92,0.22,71.15,0.14,0.94,2.00
Cambodia,70.82,68.15,73.36,5.21,69.12,1.01,70.13,-0.07,70.06,-0.76,69.30,1.23,70.53,0.14,70.67,0.15,0.69,1.70
Nepal,70.64,69.09,72.14,3.05,67.81,1.49,69.30,-0.19,69.11,-0.72,68.39,1.70,70.09,0.27,70.35,0.28,1.34,2.82
Turkmenistan,70.20,67.00,73.01,6.01,69.00,0.40,69.40,-0.56,68.85,0.51,69.35,0.56,69.91,0.16,70.07,0.13,0.80,1.20
Philippines,69.95,66.99,72.96,5.97,69.31,0.37,69.68,0.42,70.10,-3.42,66.68,2.80,69.47,0.36,69.83,0.11,0.27,0.63
Yemen,69.44,67.37,71.55,4.18,68.00,-1.44,66.57,-0.13,66.44,-0.42,66.02,1.93,67.95,1.34,69.30,0.14,2.87,1.44
Laos,69.22,67.02,71.53,4.51,66.35,1.56,67.91,0.43,68.34,-0.53,67.81,0.91,68.72,0.25,68.96,0.26,1.31,2.88
Palestine,69.21,65.22,74.25,9.03,72.78,3.03,75.81,-0.81,75.00,-1.11,73.89,2.77,76.66,-11.49,65.17,4.04,-6.60,-3.57
Timor-Leste,67.90,66.26,69.67,3.41,65.03,1.47,66.50,0.42,66.92,-0.72,66.20,1.17,67.37,0.32,67.69,0.22,1.41,2.88
Pakistan,67.80,65.46,70.32,4.86,65.37,1.36,66.73,-1.03,65.70,0.07,65.77,1.64,67.42,0.23,67.65,0.15,1.07,2.43
Myanmar,67.10,63.99,70.38,6.39,64.99,1.46,66.46,0.16,66.61,-1.06,65.55,0.95,66.51,0.38,66.89,0.21,0.64,2.10
Afghanistan,66.29,64.70,67.81,3.11,62.26,0.68,62.94,-1.49,61.45,-1.04,60.42,5.20,65.62,0.42,66.04,0.25,3.35,4.03

In [27]:
table_code_Asia = create_table(df_Asia)
output_table_code(table_code_Asia, 'Table code WBG -2024 -Asia -en.txt')

Data has written to file

In [28]:
table_code_Asia = create_table(df_Asia, lang='ru')
output_table_code(table_code_Asia, 'Table code WBG -2024 -Asia -ru.txt')

Data has written to file

<br />
<br />
<br />

In [29]:
ls_Europe = ['Albania', 'Armenia', 'Austria', 'Azerbaijan', 'Belarus', 'Belgium', 'Bosnia and Herzegovina', 'Bulgaria', 'Croatia', 'Cyprus',
             'Czechia', 'Denmark', 'Estonia', 'Finland', 'France', 'Georgia', 'Germany', 'Greece', 'Hungary', 'Iceland', 'Ireland', 'Italy',
             'Kazakhstan', 'Latvia', 'Lithuania', 'Luxembourg', 'Malta', 'Moldova', 'Montenegro', 'Netherlands', 'North Macedonia', 'Norway',
             'Poland', 'Portugal', 'Romania', 'Russia', 'Serbia', 'Slovakia', 'Slovenia', 'Spain', 'Sweden', 'Switzerland',
             'Turkey', 'Ukraine', 'United Kingdom', 'Liechtenstein',
             'World',
             'Channel Islands', 'Faroe Islands', 'Gibraltar', 'Isle of Man',
             'Monaco', 'San Marino', 'Andorra']  # 'European Union', 'Central Europe and the Baltics', 'Europe & Central Asia']
# Database does not contain data for Vatican City

df_Europe = filter_df(df, ls_Europe)

df_Europe.round(2)

Total : 71.33 – 86.50   (Moldova – Monaco)
Male  : 66.70 – 84.56   (Moldova – Monaco)
Female: 75.67 – 88.63   (Moldova – Monaco)

,total,male,female,gender_gap,2014_t,2014→2019,2019_t,2019→2020,2020_t,2020→2021,2021_t,2021→2022,2022_t,2022→2023,2023_t,2023→2024,2019→2024,2014→2024
,,,,,,,,,,,,,,,,,,
Monaco,86.50,84.56,88.63,4.07,85.09,1.06,86.15,-0.06,86.09,-0.98,85.11,0.63,85.75,0.63,86.37,0.12,0.35,1.40
San Marino,85.82,84.32,87.22,2.90,84.39,0.86,85.26,-2.61,82.65,0.89,83.54,2.17,85.71,-0.00,85.71,0.11,0.56,1.42
Switzerland,84.41,82.70,86.20,3.50,83.20,0.71,83.90,-0.90,83.00,0.75,83.75,-0.15,83.60,0.55,84.16,0.25,0.50,1.21
Liechtenstein,84.20,82.20,86.30,4.10,82.07,2.09,84.16,-2.50,81.66,2.74,84.40,-0.28,84.12,0.47,84.60,-0.40,0.04,2.13
Andorra,84.19,82.26,86.24,3.98,84.48,-0.39,84.10,-4.68,79.42,2.91,82.33,1.69,84.02,0.02,84.04,0.15,0.09,-0.30
Sweden,84.06,82.60,85.60,3.00,82.25,0.86,83.11,-0.75,82.36,0.70,83.06,0.00,83.06,0.25,83.31,0.75,0.95,1.81
Italy,83.95,82.00,86.00,4.00,83.09,0.41,83.50,-1.30,82.20,0.45,82.65,0.05,82.70,0.65,83.35,0.60,0.45,0.86
Spain,83.89,81.40,86.50,5.10,83.23,0.60,83.83,-1.60,82.23,0.95,83.18,-0.04,83.13,0.80,83.93,-0.05,0.06,0.66
Gibraltar,83.63,81.03,86.19,5.16,82.64,0.54,83.18,-0.11,83.07,-2.80,80.27,3.24,83.52,0.04,83.55,0.08,0.45,0.99
Luxembourg,83.20,81.00,85.50,4.50,82.23,0.41,82.64,-0.50,82.14,0.45,82.60,0.35,82.95,0.36,83.31,-0.11,0.56,0.97
Norway,83.16,81.60,84.80,3.20,82.10,0.86,82.96,0.25,83.21,-0.05,83.16,-0.65,82.51,0.50,83.01,0.15,0.20,1.06
Faroe Islands,83.08,81.34,84.91,3.58,81.59,0.80,82.39,0.14,82.53,0.14,82.68,0.14,82.82,0.14,82.95,0.13,0.69,1.49
Ireland,83.01,81.40,84.70,3.30,81.35,1.35,82.70,-0.25,82.46,-0.20,82.25,0.26,82.51,0.30,82.81,0.20,0.31,1.66
France,82.98,80.20,85.90,5.70,82.72,0.11,82.83,-0.65,82.18,0.15,82.32,-0.20,82.13,0.70,82.83,0.15,0.15,0.26
Malta,82.96,81.20,84.80,3.60,81.90,0.76,82.66,-0.56,82.10,0.16,82.26,0.04,82.30,1.06,83.36,-0.40,0.30,1.06
Iceland,82.81,81.20,84.50,3.30,82.86,0.30,83.16,-0.10,83.06,0.10,83.17,-1.05,82.12,0.34,82.46,0.35,-0.35,-0.05
Portugal,82.38,79.70,85.20,5.50,81.12,0.55,81.68,-0.35,81.33,0.05,81.38,0.25,81.63,0.70,82.33,0.05,0.71,1.26
Finland,82.34,79.80,85.00,5.20,81.18,0.80,81.98,-0.05,81.93,-0.05,81.89,-0.70,81.19,0.40,81.59,0.75,0.35,1.16
Belgium,82.30,80.30,84.40,4.10,81.29,0.71,82.00,-1.30,80.70,1.10,81.79,-0.04,81.75,0.65,82.40,-0.10,0.30,1.01
Slovenia,82.29,79.70,85.00,5.30,81.08,0.45,81.53,-1.00,80.53,0.14,80.68,0.61,81.28,0.65,81.93,0.36,0.76,1.21
Denmark,82.25,80.40,84.20,3.80,80.70,0.75,81.45,0.15,81.60,-0.20,81.40,-0.10,81.30,0.45,81.75,0.50,0.80,1.55
Austria,82.00,79.80,84.30,4.50,81.49,0.40,81.90,-0.70,81.19,-0.00,81.19,0.10,81.30,0.50,81.79,0.20,0.10,0.50
Netherlands,81.97,80.60,83.40,2.80,81.71,0.40,82.11,-0.75,81.36,-0.05,81.31,0.30,81.61,0.25,81.86,0.10,-0.15,0.26
Greece,81.84,79.40,84.40,5.00,81.39,0.25,81.64,-0.35,81.29,-1.20,80.08,0.70,80.79,0.95,81.74,0.10,0.20,0.45
Cyprus,81.82,79.84,83.80,3.96,81.34,0.12,81.45,-0.22,81.23,-0.66,80.57,-0.14,80.43,1.21,81.65,0.17,0.37,0.48
United Kingdom,81.39,79.54,83.32,3.78,81.30,0.06,81.37,-1.04,80.33,0.32,80.65,0.36,81.01,0.23,81.24,0.15,0.02,0.08
Channel Islands,81.20,79.10,83.30,4.20,81.60,-0.40,81.20,-0.30,80.90,-0.60,80.30,0.70,81.00,0.10,81.10,0.10,0.00,-0.40
Isle of Man,81.09,79.04,83.20,4.16,80.20,0.54,80.74,-0.15,80.59,-0.17,80.42,0.54,80.96,0.04,81.00,0.09,0.35,0.89
Germany,80.79,78.50,83.20,4.70,81.09,0.20,81.29,-0.25,81.04,-0.25,80.79,-0.18,80.61,0.43,81.04,-0.25,-0.50,-0.30
Czechia,79.98,77.10,83.00,5.90,78.82,0.40,79.23,-1.00,78.23,-1.00,77.22,1.71,78.93,0.90,79.83,0.15,0.75,1.15
Albania,79.78,77.92,81.59,3.67,78.03,1.44,79.47,-1.64,77.82,-0.98,76.84,1.93,78.77,0.83,79.60,0.17,0.31,1.75
Estonia,79.30,75.10,83.70,8.60,77.03,1.61,78.65,-0.05,78.60,-1.65,76.94,0.90,77.84,0.95,78.79,0.50,0.65,2.26
Croatia,78.93,76.10,81.90,5.80,77.72,0.50,78.22,-0.70,77.52,-1.10,76.42,1.15,77.58,0.90,78.47,0.46,0.70,1.20
Poland,78.41,74.80,82.20,7.40,77.60,0.30,77.90,-1.50,76.40,-1.05,75.35,1.80,77.16,1.10,78.26,0.15,0.50,0.81
Slovakia,78.37,75.20,81.70,6.50,76.81,0.85,77.67,-0.80,76.87,-2.25,74.61,2.35,76.97,1.15,78.12,0.25,0.70,1.56
Armenia,78.32,75.10,81.70,6.60,74.87,1.35,76.22,-2.85,73.38,-1.10,72.28,2.49,74.77,2.70,77.47,0.85,2.10,3.45
Bosnia and Herzegovina,78.04,74.65,81.07,6.42,77.09,0.31,77.39,-1.35,76.04,-1.47,74.57,2.21,76.78,1.07,77.85,0.19,0.65,0.95
Montenegro,77.89,75.50,80.40,4.90,76.34,0.34,76.68,-0.75,75.93,-2.11,73.82,2.36,76.19,1.40,77.59,0.30,1.21,1.55
Turkey,77.42,74.62,80.34,5.72,76.45,1.28,77.74,-1.21,76.53,-0.80,75.72,1.87,77.59,-0.43,77.16,0.27,-0.32,0.97
Lithuania,77.20,73.00,81.60,8.60,74.52,1.77,76.28,-1.25,75.03,-0.99,74.04,1.61,75.64,1.65,77.29,-0.10,0.91,2.68
Hungary,76.72,73.70,79.90,6.20,75.76,0.56,76.32,-0.90,75.42,-1.35,74.07,1.80,75.87,0.70,76.57,0.15,0.40,0.96
North Macedonia,76.62,74.48,78.86,4.38,75.45,1.15,76.60,-2.21,74.40,-1.15,73.25,1.18,74.42,0.89,75.32,1.30,0.01,1.17
Romania,76.46,72.80,80.30,7.50,74.91,0.70,75.61,-1.35,74.25,-1.44,72.81,2.34,75.15,1.25,76.40,0.05,0.85,1.55
Latvia,76.43,71.60,81.50,9.90,74.12,1.26,75.39,-0.20,75.19,-2.20,72.98,1.30,74.28,1.15,75.43,1.00,1.04,2.30
Serbia,75.97,73.70,78.35,4.65,75.34,0.60,75.94,-1.46,74.48,-1.70,72.78,2.46,75.24,0.90,76.14,-0.17,0.03,0.63
Bulgaria,75.76,72.20,79.50,7.30,74.47,0.65,75.11,-1.76,73.36,-2.14,71.21,2.95,74.16,1.60,75.76,0.00,0.65,1.30
Ukraine,74.69,69.79,79.39,9.61,71.80,2.12,73.92,-0.64,73.28,-1.65,71.63,1.03,72.66,0.76,73.42,1.27,0.77,2.89
Georgia,74.66,69.75,79.23,9.49,73.10,1.06,74.17,-0.66,73.51,-1.87,71.64,2.51,74.14,0.35,74.50,0.16,0.49,1.55
Azerbaijan,74.58,71.71,77.28,5.58,71.93,1.36,73.29,-2.98,70.31,0.69,71.00,3.13,74.12,0.30,74.43,0.15,1.29,2.65
Kazakhstan,74.53,70.27,78.52,8.25,71.42,2.24,73.66,-2.46,71.19,-1.06,70.13,3.37,73.50,0.90,74.40,0.13,0.87,3.12
Belarus,74.37,69.74,79.22,9.48,72.97,1.26,74.23,-2.09,72.14,-0.07,72.07,2.03,74.10,0.08,74.18,0.18,0.14,1.39
World,73.48,71.12,75.97,4.86,71.78,1.09,72.87,-0.69,72.18,-0.97,71.22,1.75,72.97,0.36,73.33,0.15,0.61,1.71
Russia,73.44,68.26,78.88,10.62,70.74,2.34,73.08,-1.75,71.34,-1.44,69.90,2.65,72.55,0.71,73.25,0.19,0.36,2.70
Moldova,71.33,66.70,75.67,8.97,70.24,-0.06,70.18,-0.27,69.91,-0.92,68.99,2.56,71.55,-0.35,71.20,0.13,1.15,1.09

In [30]:
table_code_Europe = create_table(df_Europe)
output_table_code(table_code_Europe, 'Table code WBG -2024 -Europe -en.txt')

Data has written to file

In [31]:
table_code_Europe = create_table(df_Europe, lang='ru')
output_table_code(table_code_Europe, 'Table code WBG -2024 -Europe -ru.txt')

Data has written to file

<br />
<br />
<br />

In [32]:
ls_Africa = ['Algeria', 'Angola', 'Benin', 'Botswana', 'Burkina Faso', 'Burundi', 'Cameroon', 'Cabo Verde',
             "Cote d'Ivoire", 'Central African Republic', 'Chad', 'Comoros', 'DR Congo',
             'Congo, Rep.', 'Djibouti', 'Egypt', 'Equatorial Guinea', 'Eritrea', 'Eswatini',
             'Ethiopia', 'Gabon', 'Gambia', 'Ghana', 'Guinea', 'Guinea-Bissau', 'Kenya',
             'Lesotho', 'Liberia', 'Libya', 'Madagascar', 'Malawi', 'Mali', 'Mauritania', 'Mauritius',
             'Morocco', 'Mozambique', 'Namibia', 'Niger', 'Nigeria', 'Rwanda', 'Sao Tome and Principe',
             'Senegal', 'Seychelles', 'Sierra Leone', 'Somalia', 'South Africa', 'South Sudan', 'Sudan',
             'Tanzania', 'Togo', 'Tunisia', 'Uganda', 'Zambia', 'Zimbabwe',
             'World']  # 'Middle East, North Africa, Afghanistan & Pakistan', 'Africa Eastern and Southern', 'Sub-Saharan Africa', 'Africa Western and Central'

df_Africa = filter_df(df, ls_Africa)

df_Africa.round(2)

Total : 54.63 – 76.71   (Nigeria – Tunisia)
Male  : 53.36 – 75.10   (Chad – Algeria)
Female: 54.94 – 80.70   (Nigeria – Seychelles)

,total,male,female,gender_gap,2014_t,2014→2019,2019_t,2019→2020,2020_t,2020→2021,2021_t,2021→2022,2022_t,2022→2023,2023_t,2023→2024,2019→2024,2014→2024
,,,,,,,,,,,,,,,,,,
Tunisia,76.71,74.13,79.33,5.20,74.78,0.81,75.60,-0.59,75.00,-2.11,72.89,3.16,76.05,0.46,76.51,0.20,1.11,1.93
Algeria,76.47,75.10,77.91,2.82,74.99,0.69,75.68,-2.42,73.26,1.95,75.21,0.92,76.13,0.13,76.26,0.21,0.79,1.48
Seychelles,76.30,72.10,80.70,8.60,73.23,0.82,74.05,3.19,77.24,-3.84,73.40,1.11,74.51,0.91,75.42,0.88,2.25,3.07
Cabo Verde,76.22,73.05,79.37,6.32,73.79,1.66,75.45,-1.63,73.82,0.61,74.42,1.48,75.91,0.15,76.06,0.17,0.78,2.44
Morocco,75.49,73.35,77.78,4.43,72.52,1.72,74.24,-1.11,73.13,0.25,73.39,1.78,75.16,0.15,75.31,0.18,1.25,2.97
Mauritius,73.79,70.35,77.40,7.05,74.19,0.04,74.24,-0.06,74.18,-0.50,73.68,-0.17,73.51,-0.10,73.41,0.38,-0.45,-0.41
World,73.48,71.12,75.97,4.86,71.78,1.09,72.87,-0.69,72.18,-0.97,71.22,1.75,72.97,0.36,73.33,0.15,0.61,1.71
Egypt,71.81,69.65,74.01,4.36,69.91,1.30,71.21,-1.42,69.79,-0.81,68.98,2.03,71.01,0.62,71.63,0.17,0.59,1.89
Libya,71.12,69.62,72.68,3.05,71.30,1.64,72.94,-0.55,72.39,-0.33,72.06,2.40,74.46,-5.12,69.34,1.78,-1.82,-0.18
Sao Tome and Principe,69.90,66.41,73.91,7.50,65.48,2.57,68.04,-0.06,67.98,0.05,68.03,1.21,69.24,0.48,69.72,0.19,1.86,4.43
Botswana,69.29,66.78,71.85,5.07,62.17,5.00,67.17,0.48,67.64,-4.34,63.30,5.45,68.75,0.41,69.16,0.13,2.13,7.13
Senegal,68.92,67.01,71.01,4.01,66.00,1.67,67.67,-0.17,67.50,-0.63,66.87,0.92,67.79,0.90,68.68,0.24,1.26,2.92
Eritrea,68.89,66.76,70.94,4.19,65.52,1.79,67.31,-0.33,66.98,-0.04,66.94,0.85,67.79,0.83,68.62,0.27,1.59,3.38
Mauritania,68.71,66.70,70.73,4.03,66.21,1.43,67.64,-0.85,66.79,-0.03,66.76,1.52,68.28,0.20,68.48,0.23,1.07,2.51
Gabon,68.51,66.06,71.24,5.18,66.07,1.27,67.34,-0.26,67.07,-0.00,67.07,0.64,67.71,0.62,68.34,0.17,1.17,2.44
Uganda,68.49,65.49,71.36,5.88,63.06,3.30,66.35,0.06,66.41,0.04,66.45,1.22,67.68,0.58,68.25,0.23,2.13,5.43
Rwanda,68.02,65.71,70.14,4.43,65.09,1.60,66.69,0.26,66.95,-0.10,66.85,0.68,67.53,0.26,67.78,0.23,1.33,2.93
Ethiopia,67.60,64.36,71.02,6.67,62.93,2.81,65.74,0.23,65.97,-0.64,65.33,1.57,66.90,0.42,67.32,0.29,1.86,4.68
Malawi,67.56,64.27,70.77,6.50,61.65,3.34,65.00,0.22,65.22,-0.43,64.78,1.26,66.04,1.32,67.35,0.21,2.57,5.91
Namibia,67.52,63.45,71.48,8.02,59.31,4.23,63.55,0.52,64.07,-3.22,60.85,3.34,64.19,3.20,67.39,0.13,3.97,8.21
Tanzania,67.21,64.40,70.00,5.60,63.36,2.64,66.01,0.76,66.77,-0.64,66.13,0.75,66.88,0.12,67.00,0.22,1.20,3.85
Comoros,67.02,65.02,69.20,4.18,64.14,1.52,65.66,0.09,65.76,-0.56,65.20,1.28,66.48,0.30,66.78,0.25,1.36,2.88
Zambia,66.53,64.10,68.87,4.77,60.11,2.80,62.91,0.45,63.36,-1.00,62.36,2.92,65.28,1.07,66.35,0.18,3.61,6.42
Sudan,66.52,63.45,69.82,6.38,63.99,1.81,65.80,-0.68,65.12,-0.66,64.46,1.23,65.69,0.64,66.33,0.19,0.72,2.53
South Africa,66.31,62.78,69.79,7.01,63.18,2.89,66.07,-0.92,65.15,-3.14,62.01,3.44,65.45,0.69,66.14,0.17,0.24,3.13
Djibouti,66.20,63.73,68.74,5.02,62.43,1.95,64.38,-0.18,64.20,-0.37,63.83,1.71,65.54,0.45,65.99,0.22,1.82,3.77
Gambia,66.06,64.35,67.75,3.40,62.58,1.85,64.43,-0.01,64.42,-0.57,63.85,1.01,64.86,1.00,65.86,0.20,1.63,3.48
"Congo, Rep.",66.00,64.33,67.72,3.39,63.35,-0.20,63.15,1.24,64.39,-0.20,64.19,0.81,65.00,0.77,65.77,0.23,2.85,2.65
Ghana,65.69,63.31,68.16,4.85,62.83,1.62,64.46,-0.15,64.31,-0.02,64.29,0.96,65.25,0.25,65.50,0.20,1.24,2.86
Angola,64.81,62.28,67.34,5.07,60.40,2.66,63.05,0.06,63.12,-0.16,62.96,1.29,64.25,0.37,64.62,0.19,1.75,4.41
Eswatini,64.26,61.32,67.11,5.79,53.49,6.36,59.85,0.01,59.86,-1.63,58.23,4.80,63.03,1.10,64.12,0.14,4.41,10.77
Guinea-Bissau,64.25,61.82,66.55,4.73,59.48,2.69,62.16,-0.82,61.34,0.31,61.65,1.95,63.60,0.48,64.08,0.17,2.09,4.78
Cameroon,63.97,61.78,66.22,4.45,59.13,2.56,61.70,-0.02,61.67,-0.53,61.15,1.30,62.44,1.26,63.70,0.27,2.27,4.84
Equatorial Guinea,63.91,62.22,65.89,3.66,60.23,2.07,62.30,-0.16,62.14,0.31,62.45,0.91,63.36,0.35,63.71,0.20,1.61,3.68
Madagascar,63.84,62.12,65.60,3.48,63.26,0.24,63.50,-0.80,62.71,-0.19,62.52,0.55,63.07,0.56,63.63,0.20,0.33,0.57
Kenya,63.83,61.64,66.12,4.48,61.99,0.95,62.94,-1.34,61.60,-0.37,61.22,2.32,63.55,0.10,63.65,0.19,0.90,1.84
Burundi,63.82,61.75,65.88,4.13,59.76,2.42,62.18,0.39,62.57,-0.47,62.10,0.78,62.88,0.77,63.65,0.17,1.64,4.05
Mozambique,63.80,60.49,66.74,6.26,57.96,3.34,61.31,0.08,61.39,-1.12,60.27,2.74,63.01,0.60,63.61,0.19,2.49,5.83
Zimbabwe,63.06,60.49,65.31,4.82,58.11,2.95,61.06,0.47,61.53,-1.40,60.14,2.23,62.36,0.41,62.78,0.29,2.00,4.96
Togo,62.94,62.70,63.15,0.46,58.78,2.28,61.06,0.08,61.14,0.20,61.34,0.95,62.29,0.45,62.74,0.20,1.87,4.16
Liberia,62.32,61.02,63.63,2.61,59.21,2.02,61.23,0.04,61.27,-0.10,61.17,0.77,61.93,0.23,62.16,0.16,1.09,3.11
Cote d'Ivoire,62.11,60.17,64.31,4.14,57.77,2.50,60.27,-0.13,60.14,0.15,60.29,1.27,61.56,0.38,61.94,0.17,1.84,4.34
DR Congo,62.07,59.96,64.23,4.27,58.24,2.01,60.24,0.19,60.43,-0.38,60.04,0.94,60.98,0.92,61.90,0.18,1.83,3.84
Sierra Leone,61.96,60.23,63.70,3.47,54.28,5.31,59.59,0.10,59.69,0.57,60.26,1.02,61.28,0.51,61.79,0.18,2.37,7.68
Niger,61.43,60.49,62.40,1.92,58.69,1.34,60.03,-0.14,59.89,-0.35,59.54,0.86,60.40,0.78,61.18,0.25,1.40,2.74
Burkina Faso,61.29,59.11,63.43,4.32,58.33,1.85,60.18,0.27,60.45,-0.41,60.05,0.65,60.70,0.39,61.09,0.20,1.11,2.96
Benin,60.96,59.52,62.42,2.90,59.01,0.88,59.89,0.27,60.15,-0.54,59.61,0.87,60.48,0.30,60.77,0.19,1.07,1.95
Guinea,60.90,59.66,62.08,2.43,57.58,1.80,59.38,-0.03,59.35,0.02,59.37,1.06,60.43,0.31,60.74,0.16,1.53,3.32
Mali,60.68,59.25,62.15,2.90,57.48,1.73,59.22,-0.36,58.86,0.26,59.12,0.92,60.04,0.40,60.44,0.24,1.46,3.19
Somalia,58.97,56.49,61.55,5.06,54.44,2.81,57.25,-0.15,57.10,-1.39,55.70,-1.77,53.93,4.89,58.82,0.15,1.72,4.52
Lesotho,57.80,55.03,60.44,5.41,50.79,4.46,55.25,-0.12,55.13,-0.92,54.21,2.60,56.81,0.56,57.38,0.42,2.55,7.01
South Sudan,57.74,54.76,60.75,5.99,45.62,12.50,58.13,-0.48,57.65,-0.60,57.05,0.16,57.20,0.41,57.62,0.12,-0.39,12.11
Central African Republic,57.67,55.51,59.56,4.05,40.26,-8.74,31.53,19.07,50.60,-10.32,40.28,-21.46,18.82,38.59,57.41,0.26,26.14,17.41
Chad,55.24,53.36,57.19,3.83,51.14,1.85,52.99,0.09,53.08,0.05,53.14,1.39,54.53,0.54,55.07,0.17,2.24,4.10
Nigeria,54.64,54.33,54.94,0.61,51.94,1.07,53.01,0.06,53.07,0.38,53.46,0.62,54.08,0.38,54.46,0.17,1.63,2.70

In [33]:
table_code_Africa = create_table(df_Africa)
output_table_code(table_code_Africa, 'Table code WBG -2024 -Africa -en.txt')

Data has written to file

In [34]:
table_code_Africa = create_table(df_Africa, lang='ru')
output_table_code(table_code_Africa, 'Table code WBG -2024 -Africa -ru.txt')

Data has written to file

<br />
<br />
<br />

In [35]:
ls_Oceania = ['Australia', 'Papua New Guinea', 'New Zealand', 'Fiji', 'Solomon Islands', 'Vanuatu',
              'Samoa', 'Kiribati', 'Micronesia', 'Tonga', 'Marshall Islands', 'Nauru', 'Tuvalu',
              'French Polynesia', 'New Caledonia', 'Guam', 'Pacific island small states',
              'Palau', 'American Samoa', 'Northern Mariana Islands',
              'World']

df_Oceania = filter_df(df, ls_Oceania)

df_Oceania.round(2)

Total : 62.28 – 84.19   (Nauru – French Polynesia)
Male  : 60.41 – 81.90   (Nauru – French Polynesia)
Female: 64.19 – 86.62   (Nauru – French Polynesia)

,total,male,female,gender_gap,2014_t,2014→2019,2019_t,2019→2020,2020_t,2020→2021,2021_t,2021→2022,2022_t,2022→2023,2023_t,2023→2024,2019→2024,2014→2024
,,,,,,,,,,,,,,,,,,
French Polynesia,84.19,81.90,86.62,4.72,82.15,1.04,83.20,-0.74,82.46,-2.89,79.57,4.29,83.86,0.21,84.07,0.12,1.00,2.04
Australia,83.05,81.10,85.10,4.00,82.30,0.60,82.90,0.30,83.20,0.10,83.30,-0.10,83.20,-0.15,83.05,0.00,0.15,0.75
New Zealand,82.01,80.40,83.70,3.30,81.46,0.60,82.06,0.20,82.26,-0.05,82.21,-0.25,81.96,-0.20,81.76,0.25,-0.05,0.55
Northern Mariana Islands,78.95,77.28,80.87,3.59,77.38,0.47,77.84,0.19,78.03,0.13,78.16,0.37,78.53,0.28,78.81,0.14,1.10,1.57
New Caledonia,78.92,76.46,81.41,4.95,77.05,0.21,77.26,-0.21,77.05,0.06,77.11,0.58,77.70,1.07,78.77,0.16,1.66,1.87
Guam,77.42,73.66,81.59,7.93,76.42,0.22,76.64,-1.12,75.53,-0.09,75.43,1.67,77.10,0.11,77.21,0.21,0.78,1.00
World,73.48,71.12,75.97,4.86,71.78,1.09,72.87,-0.69,72.18,-0.97,71.22,1.75,72.97,0.36,73.33,0.15,0.61,1.71
Tonga,73.07,69.50,76.54,7.04,71.72,0.57,72.29,0.09,72.38,-0.25,72.13,0.51,72.64,0.26,72.90,0.17,0.78,1.35
American Samoa,72.99,70.32,75.99,5.67,72.69,0.06,72.75,-0.08,72.67,0.04,72.71,0.04,72.75,0.10,72.85,0.14,0.24,0.31
Samoa,71.83,69.96,73.82,3.86,71.14,-0.87,70.27,0.46,70.73,0.37,71.10,0.45,71.55,0.15,71.70,0.13,1.56,0.68
Vanuatu,71.65,69.58,74.11,4.53,70.04,0.74,70.78,-0.40,70.39,-0.43,69.95,1.35,71.30,0.17,71.48,0.18,0.87,1.61
Solomon Islands,70.69,69.36,72.18,2.82,68.98,1.00,69.98,-0.72,69.26,-0.37,68.89,1.52,70.41,0.12,70.53,0.17,0.71,1.71
Pacific island small states,69.44,67.53,71.50,3.96,68.04,0.60,68.64,-0.29,68.36,-0.88,67.48,1.62,69.10,0.17,69.27,0.17,0.80,1.40
Palau,69.38,67.25,71.94,4.69,69.06,-0.08,68.98,-0.29,68.69,-0.13,68.56,0.36,68.92,0.35,69.27,0.11,0.40,0.32
Fiji,67.46,65.47,69.54,4.07,66.58,0.43,67.01,-0.08,66.92,-2.02,64.90,2.24,67.15,0.17,67.32,0.15,0.45,0.88
Micronesia,67.36,63.63,71.28,7.65,65.29,0.90,66.20,-0.32,65.88,0.27,66.15,0.81,66.96,0.24,67.20,0.16,1.16,2.06
Tuvalu,67.26,63.91,70.86,6.95,65.28,0.83,66.11,0.25,66.36,-0.53,65.82,1.03,66.85,0.25,67.10,0.15,1.15,1.98
Marshall Islands,67.08,65.03,69.48,4.45,65.11,0.94,66.05,-0.66,65.39,0.03,65.42,1.30,66.72,0.22,66.94,0.13,1.03,1.97
Kiribati,66.60,64.69,68.32,3.64,65.87,-0.00,65.87,-0.66,65.20,-1.06,64.15,2.12,66.27,0.20,66.47,0.13,0.73,0.73
Papua New Guinea,66.26,63.84,69.21,5.38,64.20,1.13,65.33,-0.26,65.08,-0.72,64.36,0.92,65.27,0.86,66.13,0.12,0.92,2.06
Nauru,62.28,60.41,64.19,3.77,60.83,0.56,61.39,0.13,61.53,-0.20,61.33,0.60,61.93,0.18,62.11,0.17,0.89,1.45

In [36]:
table_code_Oceania = create_table(df_Oceania)
output_table_code(table_code_Oceania, 'Table code WBG -2024 -Oceania -en.txt')

Data has written to file

In [37]:
table_code_Oceania = create_table(df_Oceania, lang='ru')
output_table_code(table_code_Oceania, 'Table code WBG -2024 -Oceania -ru.txt')

Data has written to file

<br />
<br />
<br />

[Demographics of the European Union](https://en.wikipedia.org/wiki/Demographics_of_the_European_Union)<br>
[Население стран Европейского союза](https://ru.wikipedia.org/wiki/Население_стран_Европейского_союза)

In [38]:
ls_EU =  ['Germany', 'France', 'Italy', 'Spain', 'Poland', 'Romania', 'Netherlands', 'Belgium', 'Czechia',
          'Sweden', 'Greece', 'Portugal', 'Hungary', 'Austria', 'Bulgaria', 'Denmark', 'Finland', 'Slovakia',
          'Ireland', 'Croatia', 'Lithuania', 'Slovenia', 'Latvia', 'Estonia', 'Luxembourg', 'Malta', 'Cyprus',
          'European Union', 'World']  # 'United Kingdom' - left EU 2020 January 31

df_EU = filter_df(df, ls_EU)

df_EU.round(2)

Total : 73.48 – 84.06   (World – Sweden)
Male  : 71.12 – 82.60   (World – Sweden)
Female: 75.97 – 86.50   (World – Spain)

,total,male,female,gender_gap,2014_t,2014→2019,2019_t,2019→2020,2020_t,2020→2021,2021_t,2021→2022,2022_t,2022→2023,2023_t,2023→2024,2019→2024,2014→2024
,,,,,,,,,,,,,,,,,,
Sweden,84.06,82.60,85.60,3.00,82.25,0.86,83.11,-0.75,82.36,0.70,83.06,0.00,83.06,0.25,83.31,0.75,0.95,1.81
Italy,83.95,82.00,86.00,4.00,83.09,0.41,83.50,-1.30,82.20,0.45,82.65,0.05,82.70,0.65,83.35,0.60,0.45,0.86
Spain,83.89,81.40,86.50,5.10,83.23,0.60,83.83,-1.60,82.23,0.95,83.18,-0.04,83.13,0.80,83.93,-0.05,0.06,0.66
Luxembourg,83.20,81.00,85.50,4.50,82.23,0.41,82.64,-0.50,82.14,0.45,82.60,0.35,82.95,0.36,83.31,-0.11,0.56,0.97
Ireland,83.01,81.40,84.70,3.30,81.35,1.35,82.70,-0.25,82.46,-0.20,82.25,0.26,82.51,0.30,82.81,0.20,0.31,1.66
France,82.98,80.20,85.90,5.70,82.72,0.11,82.83,-0.65,82.18,0.15,82.32,-0.20,82.13,0.70,82.83,0.15,0.15,0.26
Malta,82.96,81.20,84.80,3.60,81.90,0.76,82.66,-0.56,82.10,0.16,82.26,0.04,82.30,1.06,83.36,-0.40,0.30,1.06
Portugal,82.38,79.70,85.20,5.50,81.12,0.55,81.68,-0.35,81.33,0.05,81.38,0.25,81.63,0.70,82.33,0.05,0.71,1.26
Finland,82.34,79.80,85.00,5.20,81.18,0.80,81.98,-0.05,81.93,-0.05,81.89,-0.70,81.19,0.40,81.59,0.75,0.35,1.16
Belgium,82.30,80.30,84.40,4.10,81.29,0.71,82.00,-1.30,80.70,1.10,81.79,-0.04,81.75,0.65,82.40,-0.10,0.30,1.01
Slovenia,82.29,79.70,85.00,5.30,81.08,0.45,81.53,-1.00,80.53,0.14,80.68,0.61,81.28,0.65,81.93,0.36,0.76,1.21
Denmark,82.25,80.40,84.20,3.80,80.70,0.75,81.45,0.15,81.60,-0.20,81.40,-0.10,81.30,0.45,81.75,0.50,0.80,1.55
Austria,82.00,79.80,84.30,4.50,81.49,0.40,81.90,-0.70,81.19,-0.00,81.19,0.10,81.30,0.50,81.79,0.20,0.10,0.50
Netherlands,81.97,80.60,83.40,2.80,81.71,0.40,82.11,-0.75,81.36,-0.05,81.31,0.30,81.61,0.25,81.86,0.10,-0.15,0.26
Greece,81.84,79.40,84.40,5.00,81.39,0.25,81.64,-0.35,81.29,-1.20,80.08,0.70,80.79,0.95,81.74,0.10,0.20,0.45
Cyprus,81.82,79.84,83.80,3.96,81.34,0.12,81.45,-0.22,81.23,-0.66,80.57,-0.14,80.43,1.21,81.65,0.17,0.37,0.48
European Union,81.56,79.04,84.22,5.18,80.88,0.44,81.32,-0.88,80.44,-0.13,80.31,0.41,80.71,0.71,81.42,0.14,0.24,0.68
Germany,80.79,78.50,83.20,4.70,81.09,0.20,81.29,-0.25,81.04,-0.25,80.79,-0.18,80.61,0.43,81.04,-0.25,-0.50,-0.30
Czechia,79.98,77.10,83.00,5.90,78.82,0.40,79.23,-1.00,78.23,-1.00,77.22,1.71,78.93,0.90,79.83,0.15,0.75,1.15
Estonia,79.30,75.10,83.70,8.60,77.03,1.61,78.65,-0.05,78.60,-1.65,76.94,0.90,77.84,0.95,78.79,0.50,0.65,2.26
Croatia,78.93,76.10,81.90,5.80,77.72,0.50,78.22,-0.70,77.52,-1.10,76.42,1.15,77.58,0.90,78.47,0.46,0.70,1.20
Poland,78.41,74.80,82.20,7.40,77.60,0.30,77.90,-1.50,76.40,-1.05,75.35,1.80,77.16,1.10,78.26,0.15,0.50,0.81
Slovakia,78.37,75.20,81.70,6.50,76.81,0.85,77.67,-0.80,76.87,-2.25,74.61,2.35,76.97,1.15,78.12,0.25,0.70,1.56
Lithuania,77.20,73.00,81.60,8.60,74.52,1.77,76.28,-1.25,75.03,-0.99,74.04,1.61,75.64,1.65,77.29,-0.10,0.91,2.68
Hungary,76.72,73.70,79.90,6.20,75.76,0.56,76.32,-0.90,75.42,-1.35,74.07,1.80,75.87,0.70,76.57,0.15,0.40,0.96
Romania,76.46,72.80,80.30,7.50,74.91,0.70,75.61,-1.35,74.25,-1.44,72.81,2.34,75.15,1.25,76.40,0.05,0.85,1.55
Latvia,76.43,71.60,81.50,9.90,74.12,1.26,75.39,-0.20,75.19,-2.20,72.98,1.30,74.28,1.15,75.43,1.00,1.04,2.30
Bulgaria,75.76,72.20,79.50,7.30,74.47,0.65,75.11,-1.76,73.36,-2.14,71.21,2.95,74.16,1.60,75.76,0.00,0.65,1.30
World,73.48,71.12,75.97,4.86,71.78,1.09,72.87,-0.69,72.18,-0.97,71.22,1.75,72.97,0.36,73.33,0.15,0.61,1.71

In [39]:
table_code_EU = create_table(df_EU)
output_table_code(table_code_EU, 'Table code WBG -2024 -EU -en.txt')

Data has written to file

In [40]:
table_code_EU = create_table(df_EU, lang='ru')
output_table_code(table_code_EU, 'Table code WBG -2024 -EU -ru.txt')

Data has written to file

<br />
<br />
<br />

In [41]:
# create code for placing info in Wikipedia
def create_table_simlified(df, lang='en'):

    def if_value(x, prec=2):
        return '—' if math.isnan(x) else \
               f"{x:0.{prec}f}"  if x>=0 else \
               f"−{-x:0.{prec}f}"

    def chval(x, prec=2):  # change_value
        return '"| —' if math.isnan(x) else \
               f'color:darkgreen;"| {x:0.{prec}f}' if x>0 else \
               f'color:crimson;"| −{-x:0.{prec}f}' if x<0 else \
               f'color:darkgray;"| {x:0.{prec}f}'
    
    def chval_bold(x, prec=2):  # change_value
        return '"| —' if math.isnan(x) else \
               f'color:darkgreen;"| \'\'\'{x:0.{prec}f}\'\'\'' if x>0 else \
               f'color:crimson;"| \'\'\'−{-x:0.{prec}f}\'\'\'' if x<0 else \
               f'color:darkgray;"| \'\'\'{x:0.{prec}f}\'\'\''

    if lang=='ru':
        file_header='wbg_stats_header_2024_ru-simlified.txt'
        ptn_1 = 'флагификация'
        ptn_2 = 'флаг'
        prettify_name = {
            'European Union': '[[Европейский союз]]',
            'Central Europe and the Baltics': '[[Центральная Европа]] и [[Прибалтика]]',
            'Europe & Central Asia': '[[Европа]] и [[Центральная Азия]]',
            'South Asia': '[[Южная Азия]]',
            'East Asia & Pacific': '[[Восточная Азия]] и [[Австралия и Океания|Океания]]',
            'Middle East, North Africa, Afghanistan & Pakistan': '[[Страны MENA|Ближний Восток и Северная Африка]]',
            'Africa Eastern and Southern': '[[Восточная Африка|Восточная]] и [[Южная Африка|Южная]] Африка',
            'Sub-Saharan Africa': '[[Чёрная Африка|Африка к югу от Сахары]]',
            'Africa Western and Central': '[[Западная Африка|Западная]] и [[Центральная Африка|Центральная]] Африка',
            'North America': '[[Северная Америка]]',
            'Latin America & Caribbean': '[[Латинская Америка]] и [[Антильские острова|Карибы]]',
            'Arab World': '[[Арабский мир]]',
            'World': 'Мир',
            'Caribbean small states': '[[Список стран Карибского бассейна|Малые страны Карибского бассейна]]',
            'Pacific island small states': 'Малые страны Тихого океана',
            'Small states': 'Малые страны',
            'Other small states': 'Другие малые страны'
        }
    else:
        file_header='wbg_stats_header_2024_en-simlified.txt'
        ptn_1 = 'flaglist'
        ptn_2 = 'flagicon'
        prettify_name = {
            'European Union': '[[European Union]]',
            'Central Europe and the Baltics': '[[Central Europe]] & the [[Baltic states|Baltics]]',
            'Europe & Central Asia': '[[Europe]] & [[Central Asia]]',
            'South Asia': '[[South Asia]]',
            'East Asia & Pacific': '[[Asia-Pacific|East Asia & Pacific]]',
            'Middle East, North Africa, Afghanistan & Pakistan': '[[MENA|Middle East & North Africa]]',
            'Africa Eastern and Southern': 'Africa [[East Africa|Eastern]] & [[Southern Africa|Southern]]',
            'Sub-Saharan Africa': '[[Sub-Saharan Africa]]',
            'Africa Western and Central': 'Africa [[West Africa|Western]] & [[Central Africa|Central]]',
            'North America': '[[North America]]',
            'Latin America & Caribbean': '[[Latin America and the Caribbean|Latin America & Caribbean]]',
            'Arab World': '[[Arab world]]',
            'World': 'World'
        }
        
    with open('design/' + file_header, mode='r', encoding="utf-8") as fh:
        st_header = fh.read()
        
    st_header = st_header.strip()
    st = ''
        
    for i in range(len(df)):
        ser = df.iloc[i]
        if ser.name in ['World',
                        'European Union', 'Central Europe and the Baltics',
                        'Europe & Central Asia',
                        'South Asia',
                        'East Asia & Pacific',
                        'Middle East, North Africa, Afghanistan & Pakistan',
                        'Africa Eastern and Southern', 'Sub-Saharan Africa', 'Africa Western and Central',
                        'North America', 'Latin America & Caribbean']:
            st += '\n' + '|-class=static-row-header\n' + \
                  f'|style="text-align:center;"| \'\'\'{prettify_name.get(ser.name, ser.name)}\'\'\' ' + \
                  f'||style="background:#e0ffd8;"| \'\'\'{if_value(ser.total, 2)}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| \'\'\'{if_value(ser.male, 2)}\'\'\' ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{if_value(ser.female, 2)}\'\'\' ' + \
                  f'||style="background:#fff8dc;"| \'\'\'{if_value(ser.gender_gap, 2)}\'\'\' ' + \
                  f'||style="border-left-width:2px;padding-left:1em;"| \'\'\'{if_value(ser["2014_t"], 2)}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2014→2019"], 2)} ' + \
                  f'|| \'\'\'{if_value(ser["2019_t"], 2)}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2019→2020"], 2)} ' + \
                  f'|| \'\'\'{if_value(ser["2020_t"], 2)}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2020→2021"], 2)} ' + \
                  f'|| \'\'\'{if_value(ser["2021_t"], 2)}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2021→2022"], 2)} ' + \
                  f'|| \'\'\'{if_value(ser["2022_t"], 2)}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2022→2023"], 2)} ' + \
                  f'|| \'\'\'{if_value(ser["2023_t"], 2)}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2023→2024"], 2)} ' + \
                  f'||style="background:#e0ffd8;"| \'\'\'{if_value(ser.total, 2)}\'\'\' ' + \
                  f'||style="background:#fffae0;border-left-width:2px;{chval_bold(ser["2019→2024"], 2)}' + \
                  (f' ||style="background:#fffae0;{chval_bold(ser["2014→2024"], 2)}' if lang=='ru' else '')
        elif ser.name in ['Caribbean small states',
                          'Pacific island small states',
                          'Small states',
                          'Other small states',
                          'Kosove']:
            st += '\n' + '|-\n' + \
                  f'|style="padding-left:35px;"|{prettify_name.get(ser.name, ser.name)} ' + \
                  f'||style="background:#e0ffd8;"| {if_value(ser.total, 2)} ' + \
                  f'||style="background:#eaf3ff;"| {if_value(ser.male, 2)} ' + \
                  f'||style="background:#fee7f6;"| {if_value(ser.female, 2)} ' + \
                  f'||style="background:#fff8dc;"| {if_value(ser.gender_gap, 2)} ' + \
                  f'||style="border-left-width:2px;padding-left:1em;"| {if_value(ser["2014_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2014→2019"], 2)} ' + \
                  f'|| {if_value(ser["2019_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2019→2020"], 2)} ' + \
                  f'|| {if_value(ser["2020_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2020→2021"], 2)} ' + \
                  f'|| {if_value(ser["2021_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2021→2022"], 2)} ' + \
                  f'|| {if_value(ser["2022_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2022→2023"], 2)} ' + \
                  f'|| {if_value(ser["2023_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2023→2024"], 2)} ' + \
                  f'||style="background:#e0ffd8;"| {if_value(ser.total, 2)} ' + \
                  f'||style="background:#fffae0;border-left-width:2px;{chval(ser["2019→2024"], 2)}' + \
                  (f' ||style="background:#fffae0;{chval(ser["2014→2024"], 2)}' if lang=='ru' else '')
        else:
            st += '\n' + '|-\n' + \
                  f'| {{{{{ptn_1}|{ser.name}}}}} ' + \
                  f'||style="background:#e0ffd8;"| {if_value(ser.total, 2)} ' + \
                  f'||style="background:#eaf3ff;"| {if_value(ser.male, 2)} ' + \
                  f'||style="background:#fee7f6;"| {if_value(ser.female, 2)} ' + \
                  f'||style="background:#fff8dc;"| {if_value(ser.gender_gap, 2)} ' + \
                  f'||style="border-left-width:2px; padding-left:1em;"| {if_value(ser["2014_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2014→2019"], 2)} ' + \
                  f'|| {if_value(ser["2019_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2019→2020"], 2)} ' + \
                  f'|| {if_value(ser["2020_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2020→2021"], 2)} ' + \
                  f'|| {if_value(ser["2021_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2021→2022"], 2)} ' + \
                  f'|| {if_value(ser["2022_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2022→2023"], 2)} ' + \
                  f'|| {if_value(ser["2023_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2023→2024"], 2)} ' + \
                  f'||style="background:#e0ffd8;"| {if_value(ser.total, 2)} ' + \
                  f'||style="background:#fffae0;border-left-width:2px;{chval(ser["2019→2024"], 2)}' + \
                  (f' ||style="background:#fffae0;{chval(ser["2014→2024"], 2)}' if lang=='ru' else '')
    st += '\n|}'
    
    st = st.replace('color:darkgray;"| 0.00 ', 'color:darkgray;"| 0.00 ')  \
           .replace('color:crimson;"| −0.00 ', 'color:darkgray;"| 0.00 ')  \
           .replace('color:darkgreen;"| 0.00 ', 'color:darkgray;"| 0.00 ')  \
           .replace('color:darkgray;"| \'\'\'0.00\'\'\' ', 'color:darkgray;"| \'\'\'0.00\'\'\' ')  \
           .replace('color:crimson;"| \'\'\'−0.00\'\'\' ', 'color:darkgray;"| \'\'\'0.00\'\'\' ')  \
           .replace('color:darkgreen;"| \'\'\'0.00\'\'\' ', 'color:darkgray;"| \'\'\'0.00\'\'\' ')
    
    # WARNING: be sure that inline styles do not contains numbers with comma
    if (lang == 'ru') | (lang == 'fr'):
        st = re.sub('(?<=\\d)\\.(?=\\d)', ',', st)  # replace . to comma, if this . is between two digits

    # gray color for missing values
    st = st.replace(';"| —', ';color:silver;"| —') \
           .replace('|| —', '||style="color:silver;"| —')

    st = st_header + st
    
    return st

In [42]:
ls_CIS = ['Armenia', 'Azerbaijan', 'Belarus', 'Kazakhstan', 'Kyrgyzstan', 'Moldova',
          'Russia', 'Tajikistan', 'Uzbekistan', 'Turkmenistan']  # 'Georgia', 'Ukraine'

df_CIS = filter_df(df, ls_CIS)

df_CIS.round(2)

Total : 70.20 – 78.32   (Turkmenistan – Armenia)
Male  : 66.70 – 75.10   (Moldova – Armenia)
Female: 73.01 – 81.70   (Turkmenistan – Armenia)

,total,male,female,gender_gap,2014_t,2014→2019,2019_t,2019→2020,2020_t,2020→2021,2021_t,2021→2022,2022_t,2022→2023,2023_t,2023→2024,2019→2024,2014→2024
,,,,,,,,,,,,,,,,,,
Armenia,78.32,75.10,81.70,6.60,74.87,1.35,76.22,-2.85,73.38,-1.10,72.28,2.49,74.77,2.70,77.47,0.85,2.10,3.45
Azerbaijan,74.58,71.71,77.28,5.58,71.93,1.36,73.29,-2.98,70.31,0.69,71.00,3.13,74.12,0.30,74.43,0.15,1.29,2.65
Kazakhstan,74.53,70.27,78.52,8.25,71.42,2.24,73.66,-2.46,71.19,-1.06,70.13,3.37,73.50,0.90,74.40,0.13,0.87,3.12
Belarus,74.37,69.74,79.22,9.48,72.97,1.26,74.23,-2.09,72.14,-0.07,72.07,2.03,74.10,0.08,74.18,0.18,0.14,1.39
Russia,73.44,68.26,78.88,10.62,70.74,2.34,73.08,-1.75,71.34,-1.44,69.90,2.65,72.55,0.71,73.25,0.19,0.36,2.70
Uzbekistan,72.53,69.56,75.55,5.98,70.97,1.12,72.09,-0.63,71.46,0.22,71.68,0.47,72.15,0.24,72.39,0.14,0.44,1.56
Kyrgyzstan,72.40,68.40,76.60,8.20,70.40,1.20,71.60,0.20,71.80,0.10,71.90,0.15,72.05,0.20,72.25,0.15,0.80,2.00
Tajikistan,71.93,69.68,74.14,4.46,69.70,1.27,70.96,-2.36,68.60,0.99,69.59,1.97,71.56,0.23,71.79,0.14,0.97,2.23
Moldova,71.33,66.70,75.67,8.97,70.24,-0.06,70.18,-0.27,69.91,-0.92,68.99,2.56,71.55,-0.35,71.20,0.13,1.15,1.09
Turkmenistan,70.20,67.00,73.01,6.01,69.00,0.40,69.40,-0.56,68.85,0.51,69.35,0.56,69.91,0.16,70.07,0.13,0.80,1.20

In [43]:
# table_code_CIS = create_table_simlified(df_CIS)
# output_table_code(table_code_CIS, 'Table code WBG -2024 -CIS -en.txt')

In [44]:
# table_code_CIS = create_table_simlified(df_CIS, lang='ru')
# output_table_code(table_code_CIS, 'Table code WBG -2024 -CIS -ru.txt')

<br />
<br />
<br />

In [45]:
ls_Caribbean = ['Antigua and Barbuda', 'Aruba', 'Bahamas', 'Barbados', 'Virgin Islands (U.S.)', 'British Virgin Islands',
                'Cuba', 'Dominica', 'Dominican Republic', 'Grenada', 'Haiti', 'Jamaica', 'Puerto Rico',
                'St. Kitts and Nevis', 'St. Lucia', 'Saint Martin', 'St. Vincent and the Grenadines',
                'Sint Maarten', 'Trinidad and Tobago', 'Turks and Caicos Islands', 'Caribbean small states', 'World',
                'Cayman Islands', 'Curacao'
                ]
# Database does not contain data for Anguilla, Bonaire, Federal Dependencies of Venezuela, Guadeloupe,
# Martinique, Montserrat, Navassa Island, Nueva Esparta, Saba, San Andrés and Providencia, Saint Barthélemy, Sint Eustatius

#TODO: check

df_Caribbean = filter_df(df, ls_Caribbean)

df_Caribbean.round(2).fillna('')

Total : 65.12 – 81.90   (Haiti – Puerto Rico)
Male  : 61.90 – 78.28   (Haiti – Puerto Rico)
Female: 68.49 – 85.38   (Haiti – Puerto Rico)

,total,male,female,gender_gap,2014_t,2014→2019,2019_t,2019→2020,2020_t,2020→2021,2021_t,2021→2022,2022_t,2022→2023,2023_t,2023→2024,2019→2024,2014→2024
,,,,,,,,,,,,,,,,,,
Puerto Rico,81.90,78.28,85.38,7.10,80.04,1.40,81.44,-1.43,80.01,-0.24,79.77,-0.34,79.43,2.26,81.69,0.21,0.46,1.86
Virgin Islands (U.S.),80.77,77.60,84.10,6.50,78.87,0.80,79.67,0.15,79.82,0.25,80.07,0.25,80.32,0.20,80.52,0.25,1.10,1.90
Cayman Islands,80.54,78.20,83.00,4.81,77.86,1.19,79.05,0.18,79.23,0.07,79.30,0.68,79.98,0.37,80.36,0.18,1.49,2.68
Saint Martin,80.44,76.99,83.96,6.98,79.73,0.35,80.08,0.01,80.08,0.12,80.21,0.03,80.24,-0.01,80.22,0.21,0.36,0.71
Cuba,78.26,75.86,80.68,4.82,77.82,-0.41,77.41,-0.01,77.41,-4.21,73.20,4.43,77.63,0.46,78.08,0.18,0.85,0.44
Turks and Caicos Islands,78.18,76.01,80.45,4.44,77.21,0.48,77.69,-0.19,77.50,-0.27,77.23,0.68,77.92,0.09,78.01,0.17,0.49,0.97
Antigua and Barbuda,77.77,74.74,80.45,5.70,76.91,0.26,77.17,-0.01,77.16,0.04,77.20,0.29,77.48,0.11,77.60,0.17,0.60,0.85
British Virgin Islands,77.43,74.70,80.19,5.49,76.53,0.32,76.84,0.05,76.89,-1.60,75.30,1.88,77.18,0.10,77.28,0.16,0.59,0.90
Curacao,76.99,72.66,80.96,8.30,76.38,0.11,76.49,0.01,76.50,-0.81,75.69,1.04,76.73,0.07,76.80,0.19,0.50,0.61
Sint Maarten,76.53,73.85,79.66,5.81,75.74,-0.05,75.68,-0.68,75.00,-0.50,74.50,1.68,76.18,0.19,76.37,0.16,0.85,0.79
Aruba,76.50,73.84,78.92,5.07,75.26,0.76,76.02,-0.61,75.41,-1.75,73.66,2.57,76.23,0.13,76.35,0.15,0.48,1.24
Barbados,76.33,73.75,78.76,5.01,75.93,0.57,76.50,0.15,76.65,-0.07,76.58,-0.90,75.68,0.50,76.18,0.15,-0.16,0.41
Grenada,75.37,72.52,78.50,5.98,75.04,-0.07,74.97,0.05,75.02,-0.50,74.52,0.63,75.15,0.05,75.20,0.16,0.40,0.32
Bahamas,74.71,71.06,78.33,7.27,74.03,-2.62,71.41,1.59,72.99,-2.24,70.75,3.74,74.49,0.06,74.55,0.16,3.30,0.68
Dominican Republic,73.87,70.66,77.10,6.44,73.14,-0.03,73.11,-0.48,72.64,-0.88,71.76,2.45,74.21,-0.49,73.72,0.15,0.76,0.72
Trinidad and Tobago,73.62,70.51,76.82,6.32,72.90,-0.06,72.84,-0.19,72.64,-1.53,71.11,2.22,73.33,0.16,73.49,0.13,0.78,0.72
World,73.48,71.12,75.97,4.86,71.78,1.09,72.87,-0.69,72.18,-0.97,71.22,1.75,72.97,0.36,73.33,0.15,0.61,1.71
Caribbean small states,73.31,70.12,76.60,6.48,71.77,0.36,72.13,-0.19,71.94,-2.02,69.92,2.91,72.83,0.34,73.17,0.14,1.18,1.54
St. Lucia,72.85,69.45,76.45,7.00,72.68,-0.43,72.25,0.06,72.31,-3.19,69.12,3.55,72.67,0.03,72.70,0.15,0.60,0.17
St. Kitts and Nevis,72.28,68.69,76.16,7.47,71.23,0.31,71.54,-0.36,71.18,-1.91,69.27,1.04,70.31,1.83,72.14,0.14,0.74,1.05
Jamaica,71.61,69.08,74.15,5.07,72.36,-0.83,71.53,-0.08,71.45,-2.37,69.08,2.40,71.48,-0.00,71.48,0.13,0.07,-0.75
St. Vincent and the Grenadines,71.38,68.78,74.48,5.69,70.36,0.64,70.99,-1.39,69.60,-0.47,69.13,2.06,71.19,0.04,71.23,0.15,0.39,1.03
Dominica,71.29,68.35,74.72,6.37,71.19,0.12,71.31,-0.04,71.27,-1.44,69.83,1.25,71.08,0.05,71.13,0.16,-0.01,0.11
Haiti,65.12,61.90,68.49,6.59,62.97,1.36,64.33,-0.55,63.77,-1.16,62.61,1.34,63.95,0.99,64.94,0.18,0.79,2.15

In [46]:
table_code_Caribbean = create_table_simlified(df_Caribbean)
output_table_code(table_code_Caribbean, 'Table code WBG -2024 -Caribbean -en.txt')

Data has written to file

In [47]:
table_code_Caribbean = create_table_simlified(df_Caribbean, lang='ru')
output_table_code(table_code_Caribbean, 'Table code WBG -2024 -Caribbean -ru.txt')

Data has written to file

<br />
<br />
<br />

In [48]:
ls_C_America = ['Belize', 'Costa Rica', 'El Salvador', 'Guatemala', 'Honduras', 'Nicaragua', 'Panama',
                'Mexico', 'Colombia',
                'World']

df_C_America = filter_df(df, ls_C_America)

df_C_America.round(2)

Total : 72.30 – 81.00   (El Salvador – Costa Rica)
Male  : 67.76 – 78.37   (El Salvador – Costa Rica)
Female: 75.04 – 83.58   (Guatemala – Costa Rica)

,total,male,female,gender_gap,2014_t,2014→2019,2019_t,2019→2020,2020_t,2020→2021,2021_t,2021→2022,2022_t,2022→2023,2023_t,2023→2024,2019→2024,2014→2024
,,,,,,,,,,,,,,,,,,
Costa Rica,81.00,78.37,83.58,5.21,80.23,0.07,80.30,-0.57,79.72,-1.67,78.05,1.27,79.32,1.48,80.80,0.20,0.70,0.77
Panama,79.78,76.88,82.71,5.83,77.36,1.15,78.51,-2.18,76.33,0.67,77.00,2.32,79.32,0.27,79.59,0.18,1.26,2.41
Colombia,77.91,75.16,80.61,5.45,75.95,0.84,76.79,-2.04,74.76,-2.06,72.70,3.81,76.51,1.22,77.72,0.19,1.12,1.96
Mexico,75.26,72.44,78.00,5.56,74.40,0.13,74.53,-4.08,70.45,-0.70,69.75,4.22,73.97,1.10,75.07,0.19,0.73,0.86
Nicaragua,75.10,72.46,77.58,5.11,72.79,0.97,73.76,-3.00,70.77,-0.29,70.48,3.98,74.46,0.48,74.95,0.15,1.34,2.31
Belize,73.74,71.08,76.66,5.58,71.44,1.14,72.58,-1.00,71.58,-0.66,70.92,1.27,72.19,1.38,73.57,0.17,1.16,2.30
World,73.48,71.12,75.97,4.86,71.78,1.09,72.87,-0.69,72.18,-0.97,71.22,1.75,72.97,0.36,73.33,0.15,0.61,1.71
Honduras,73.04,70.49,75.67,5.18,71.03,1.09,72.12,-1.26,70.86,-1.37,69.49,3.22,72.72,0.17,72.88,0.16,0.92,2.01
Guatemala,72.75,70.44,75.04,4.60,70.94,0.70,71.64,-1.67,69.97,-2.11,67.86,3.35,71.21,1.40,72.60,0.14,1.11,1.80
El Salvador,72.30,67.76,76.49,8.73,71.14,0.58,71.72,-1.48,70.24,-0.30,69.94,2.03,71.97,0.13,72.10,0.20,0.58,1.16

In [49]:
table_code_C_America = create_table_simlified(df_C_America)
output_table_code(table_code_C_America, 'Table code WBG -2024 -America_Central -en.txt')

Data has written to file

In [50]:
table_code_C_America = create_table_simlified(df_C_America, lang='ru')
output_table_code(table_code_C_America, 'Table code WBG -2024 -America_Central -ru.txt')

Data has written to file

<br />
<br />
<br />

In [51]:
ls_L_America = ['Argentina', 'Bolivia', 'Brazil', 'Chile', 'Colombia', 'Costa Rica', 'Cuba', 'Dominican Republic',
                'Ecuador', 'El Salvador', 'Guatemala', 'Haiti', 'Honduras', 'Mexico', 'Nicaragua', 'Panama',
                'Paraguay', 'Peru', 'Puerto Rico', 'Saint Martin', 'Uruguay', 'Venezuela',
                'World']
# Database does not contain data for French Guiana, Guadeloupe, Martinique, Saint Barthélemy

df_L_America = filter_df(df, ls_L_America)

df_L_America.round(2)

Total : 65.12 – 81.90   (Haiti – Puerto Rico)
Male  : 61.90 – 79.45   (Haiti – Chile)
Female: 68.49 – 85.38   (Haiti – Puerto Rico)

,total,male,female,gender_gap,2014_t,2014→2019,2019_t,2019→2020,2020_t,2020→2021,2021_t,2021→2022,2022_t,2022→2023,2023_t,2023→2024,2019→2024,2014→2024
,,,,,,,,,,,,,,,,,,
Puerto Rico,81.90,78.28,85.38,7.10,80.04,1.40,81.44,-1.43,80.01,-0.24,79.77,-0.34,79.43,2.26,81.69,0.21,0.46,1.86
Chile,81.36,79.45,83.23,3.77,79.71,0.61,80.32,-0.97,79.35,-0.47,78.88,0.30,79.18,1.99,81.17,0.19,1.03,1.64
Costa Rica,81.00,78.37,83.58,5.21,80.23,0.07,80.30,-0.57,79.72,-1.67,78.05,1.27,79.32,1.48,80.80,0.20,0.70,0.77
Saint Martin,80.44,76.99,83.96,6.98,79.73,0.35,80.08,0.01,80.08,0.12,80.21,0.03,80.24,-0.01,80.22,0.21,0.36,0.71
Panama,79.78,76.88,82.71,5.83,77.36,1.15,78.51,-2.18,76.33,0.67,77.00,2.32,79.32,0.27,79.59,0.18,1.26,2.41
Uruguay,78.29,74.38,82.04,7.66,77.19,0.31,77.50,0.88,78.38,-2.95,75.43,1.03,76.47,1.67,78.14,0.15,0.78,1.09
Cuba,78.26,75.86,80.68,4.82,77.82,-0.41,77.41,-0.01,77.41,-4.21,73.20,4.43,77.63,0.46,78.08,0.18,0.85,0.44
Peru,77.94,75.63,80.30,4.67,75.26,1.02,76.28,-2.44,73.83,-2.24,71.60,5.24,76.83,0.91,77.74,0.20,1.67,2.68
Colombia,77.91,75.16,80.61,5.45,75.95,0.84,76.79,-2.04,74.76,-2.06,72.70,3.81,76.51,1.22,77.72,0.19,1.12,1.96
Ecuador,77.58,74.88,80.31,5.43,76.14,1.14,77.29,-5.28,72.00,0.74,72.75,3.83,76.58,0.81,77.39,0.19,0.29,1.44
Argentina,77.54,74.98,80.02,5.04,76.27,0.58,76.85,-0.97,75.88,-1.93,73.95,1.86,75.81,1.59,77.40,0.15,0.70,1.28
Brazil,76.02,72.95,79.14,6.19,74.82,0.99,75.81,-1.30,74.51,-1.47,73.04,1.83,74.87,0.98,75.85,0.17,0.21,1.20
Mexico,75.26,72.44,78.00,5.56,74.40,0.13,74.53,-4.08,70.45,-0.70,69.75,4.22,73.97,1.10,75.07,0.19,0.73,0.86
Nicaragua,75.10,72.46,77.58,5.11,72.79,0.97,73.76,-3.00,70.77,-0.29,70.48,3.98,74.46,0.48,74.95,0.15,1.34,2.31
Paraguay,73.98,71.01,77.09,6.08,73.42,0.25,73.67,-0.95,72.72,-4.61,68.11,4.21,72.32,1.52,73.84,0.14,0.31,0.57
Dominican Republic,73.87,70.66,77.10,6.44,73.14,-0.03,73.11,-0.48,72.64,-0.88,71.76,2.45,74.21,-0.49,73.72,0.15,0.76,0.72
World,73.48,71.12,75.97,4.86,71.78,1.09,72.87,-0.69,72.18,-0.97,71.22,1.75,72.97,0.36,73.33,0.15,0.61,1.71
Honduras,73.04,70.49,75.67,5.18,71.03,1.09,72.12,-1.26,70.86,-1.37,69.49,3.22,72.72,0.17,72.88,0.16,0.92,2.01
Guatemala,72.75,70.44,75.04,4.60,70.94,0.70,71.64,-1.67,69.97,-2.11,67.86,3.35,71.21,1.40,72.60,0.14,1.11,1.80
Venezuela,72.67,68.89,76.66,7.77,72.84,-0.07,72.77,-0.40,72.37,-0.83,71.54,1.03,72.57,-0.05,72.51,0.16,-0.09,-0.16
El Salvador,72.30,67.76,76.49,8.73,71.14,0.58,71.72,-1.48,70.24,-0.30,69.94,2.03,71.97,0.13,72.10,0.20,0.58,1.16
Bolivia,68.74,66.27,71.32,5.06,66.97,0.85,67.82,-4.91,62.91,-1.48,61.43,6.01,67.43,1.15,68.58,0.16,0.92,1.77
Haiti,65.12,61.90,68.49,6.59,62.97,1.36,64.33,-0.55,63.77,-1.16,62.61,1.34,63.95,0.99,64.94,0.18,0.79,2.15

In [52]:
table_code_L_America = create_table_simlified(df_L_America)
output_table_code(table_code_L_America, 'Table code WBG -2024 -America_Latin -en.txt')

Data has written to file

In [53]:
table_code_L_America = create_table_simlified(df_L_America, lang='ru')
output_table_code(table_code_L_America, 'Table code WBG -2024 -America_Latin -ru.txt')

Data has written to file

<br />
<br />
<br />

In [54]:
ls_Middle_East = ['Bahrain', 'Cyprus', 'Egypt', 'Iran', 'Iraq', 'Israel', 'Jordan', 'Kuwait', 'Lebanon', 'Oman',
                  'Palestine', 'Qatar', 'Saudi Arabia', 'Syria', 'Turkey', 'United Arab Emirates', 'Yemen',
                  'World']
# Database does not contain data for 'Akrotiri and Dhekelia'

df_Middle_East = filter_df(df, ls_Middle_East)

df_Middle_East.round(2)

Total : 69.21 – 84.58   (Palestine – Kuwait)
Male  : 65.22 – 83.80   (Palestine – Kuwait)
Female: 71.55 – 85.40   (Yemen – Kuwait)

,total,male,female,gender_gap,2014_t,2014→2019,2019_t,2019→2020,2020_t,2020→2021,2021_t,2021→2022,2022_t,2022→2023,2023_t,2023→2024,2019→2024,2014→2024
,,,,,,,,,,,,,,,,,,
Kuwait,84.58,83.80,85.40,1.60,79.08,2.89,81.97,-3.21,78.76,-0.02,78.74,1.85,80.59,2.60,83.19,1.39,2.61,5.50
Israel,83.20,81.10,85.40,4.30,82.15,0.65,82.80,-0.16,82.65,-0.15,82.50,0.20,82.70,0.50,83.20,0.00,0.39,1.04
United Arab Emirates,83.07,82.17,84.32,2.15,81.99,0.61,82.60,-0.66,81.94,-2.85,79.08,1.40,80.49,2.42,82.91,0.16,0.47,1.08
Qatar,82.52,81.78,83.48,1.70,81.40,1.55,82.94,-2.54,80.41,0.67,81.08,0.77,81.86,0.51,82.37,0.15,-0.42,1.13
Cyprus,81.82,79.84,83.80,3.96,81.34,0.12,81.45,-0.22,81.23,-0.66,80.57,-0.14,80.43,1.21,81.65,0.17,0.37,0.48
Bahrain,81.42,80.86,82.13,1.27,80.21,0.26,80.47,-1.79,78.68,-0.60,78.08,2.91,80.99,0.29,81.28,0.14,0.95,1.21
Oman,80.25,78.72,82.05,3.33,79.03,0.92,79.95,-2.18,77.76,-1.79,75.97,1.94,77.91,2.12,80.03,0.21,0.30,1.22
Saudi Arabia,78.98,77.33,81.33,4.00,77.12,1.20,78.31,-0.72,77.60,-0.51,77.09,0.22,77.31,1.42,78.73,0.25,0.67,1.87
Jordan,77.98,75.89,80.33,4.44,74.61,2.26,76.86,-1.28,75.58,-1.38,74.20,2.88,77.09,0.73,77.81,0.17,1.12,3.38
Lebanon,77.94,75.88,79.86,3.98,78.15,0.06,78.21,-1.91,76.30,-2.65,73.65,4.35,78.00,-0.19,77.82,0.13,-0.26,-0.20
Iran,77.85,76.00,79.81,3.81,75.64,1.22,76.86,-2.71,74.14,-0.39,73.75,3.05,76.80,0.85,77.65,0.20,1.00,2.22
Turkey,77.42,74.62,80.34,5.72,76.45,1.28,77.74,-1.21,76.53,-0.80,75.72,1.87,77.59,-0.43,77.16,0.27,-0.32,0.97
World,73.48,71.12,75.97,4.86,71.78,1.09,72.87,-0.69,72.18,-0.97,71.22,1.75,72.97,0.36,73.33,0.15,0.61,1.71
Syria,72.56,70.21,74.92,4.71,65.49,5.48,70.97,0.97,71.94,0.47,72.42,0.37,72.79,-0.67,72.12,0.44,1.59,7.07
Iraq,72.42,70.50,74.18,3.68,69.68,1.57,71.24,-1.59,69.65,1.05,70.70,1.33,72.04,0.29,72.32,0.10,1.18,2.75
Egypt,71.81,69.65,74.01,4.36,69.91,1.30,71.21,-1.42,69.79,-0.81,68.98,2.03,71.01,0.62,71.63,0.17,0.59,1.89
Yemen,69.44,67.37,71.55,4.18,68.00,-1.44,66.57,-0.13,66.44,-0.42,66.02,1.93,67.95,1.34,69.30,0.14,2.87,1.44
Palestine,69.21,65.22,74.25,9.03,72.78,3.03,75.81,-0.81,75.00,-1.11,73.89,2.77,76.66,-11.49,65.17,4.04,-6.60,-3.57

In [55]:
table_code_Middle_East = create_table_simlified(df_Middle_East)
output_table_code(table_code_Middle_East, 'Table code WBG -2024 -Middle_East -en.txt')

Data has written to file

In [56]:
table_code_Middle_East = create_table_simlified(df_Middle_East, lang='ru')
output_table_code(table_code_Middle_East, 'Table code WBG -2024 -Middle_East -ru.txt')

Data has written to file

<br />
<br />
<br />

All countries (excluding small territories):

In [57]:
ls_regions = [
    'European Union', 'Central Europe and the Baltics',
    'Europe & Central Asia',
    'South Asia',
    'East Asia & Pacific',
    'Middle East, North Africa, Afghanistan & Pakistan',
    'Africa Eastern and Southern', 'Sub-Saharan Africa', 'Africa Western and Central',
    'North America', 'Latin America & Caribbean',
    'Arab World'
]

# exclude countries with population <50,000
ls_small_territories = ['Liechtenstein', 'St. Kitts and Nevis', 'Turks and Caicos Islands', 'Gibraltar',
                        'Saint Martin', 'British Virgin Islands', 'Tuvalu', 'Nauru',
                        'Monaco', 'San Marino', 'American Samoa', 'Palau', 'Marshall Islands'
                       ]

In [58]:
ls_all_countries = [country for country in df.index.to_list() if country not in ls_regions + ls_small_territories]
len(ls_all_countries)

206

In [59]:
df_all_countries = filter_df(df, ls_all_countries)
df_all_countries.head(2).round(2)

Total : 54.63 – 85.39   (Nigeria – Hong Kong SAR, China)
Male  : 53.36 – 83.80   (Chad – Kuwait)
Female: 54.94 – 88.22   (Nigeria – Hong Kong SAR, China)

,total,male,female,gender_gap,2014_t,2014→2019,2019_t,2019→2020,2020_t,2020→2021,2021_t,2021→2022,2022_t,2022→2023,2023_t,2023→2024,2019→2024,2014→2024
,,,,,,,,,,,,,,,,,,
"Hong Kong SAR, China",85.39,82.7,88.22,5.52,83.94,1.22,85.16,0.34,85.50,0.04,85.53,-1.87,83.66,1.59,85.25,0.15,0.24,1.46
Kuwait,84.58,83.8,85.40,1.60,79.08,2.89,81.97,-3.21,78.76,-0.02,78.74,1.85,80.59,2.60,83.19,1.39,2.61,5.50

In [60]:
table_code_all_countries = create_table(df_all_countries)
output_table_code(table_code_all_countries, 'Table code WBG -2024 -all_countries -en.txt')

Data has written to file

In [61]:
table_code_all_countries = create_table(df_all_countries, lang='ru')
output_table_code(table_code_all_countries, 'Table code WBG -2024 -all_countries -ru.txt')

Data has written to file

In [62]:
table_code_all_countries = create_table(df_all_countries, lang='fr')
output_table_code(table_code_all_countries, 'Table code WBG -2024 -all_countries -fr.txt')

Data has written to file

In [63]:
# for name in df_all_countries.index:
#     print(f"    '{name}' : '',")

<br />
<br />
<br />

[List of world regions by life expectancy](https://en.wikipedia.org/wiki/List_of_world_regions_by_life_expectancy)<br />
[Список регионов мира по ожидаемой продолжительности жизни](https://ru.wikipedia.org/wiki/Список_регионов_мира_по_ожидаемой_продолжительности_жизни)

In [64]:
# create code for placing info in Wikipedia
def create_table_for_regions(df, lang='en'):

    def if_value(x, prec=2):
        return '—' if math.isnan(x) else \
               f"{x:0.{prec}f}"  if x>=0 else \
               f"−{-x:0.{prec}f}"

    def chval(x, prec=2):  # change_value
        return '"| —' if math.isnan(x) else \
               f'color:darkgreen;"| {x:0.{prec}f}' if x>0 else \
               f'color:crimson;"| −{-x:0.{prec}f}' if x<0 else \
               f'color:darkgray;"| {x:0.{prec}f}'
    
    def chval_bold(x, prec=2):  # change_value
        return '"| —' if math.isnan(x) else \
               f'color:darkgreen;"| \'\'\'{x:0.{prec}f}\'\'\'' if x>0 else \
               f'color:crimson;"| \'\'\'−{-x:0.{prec}f}\'\'\'' if x<0 else \
               f'color:darkgray;"| \'\'\'{x:0.{prec}f}\'\'\''

    if lang=='ru':
        file_header='wbg_stats_header_2024_ru-simlified.txt'
        ptn_1 = 'флагификация'
        ptn_2 = 'флаг'
        prettify_name = {
            'European Union': '[[Европейский союз]]',
            'Central Europe and the Baltics': '[[Центральная Европа]] и [[Прибалтика]]',
            'Europe & Central Asia': '[[Европа]] и [[Центральная Азия]]',
            'South Asia': '[[Южная Азия]]',
            'East Asia & Pacific': '[[Восточная Азия]] и [[Австралия и Океания|Океания]]',
            'Middle East, North Africa, Afghanistan & Pakistan': '[[Страны MENA|Ближний Восток и Северная Африка]]',
            'Africa Eastern and Southern': '[[Восточная Африка|Восточная]] и [[Южная Африка|Южная]] Африка',
            'Sub-Saharan Africa': '[[Чёрная Африка|Африка к югу от Сахары]]',
            'Africa Western and Central': '[[Западная Африка|Западная]] и [[Центральная Африка|Центральная]] Африка',
            'North America': '[[Северная Америка]]',
            'Latin America & Caribbean': '[[Латинская Америка]] и [[Антильские острова|Карибы]]',
            'Arab World': '[[Арабский мир]]',
            'World': 'Мир'
        }
    else:
        file_header='wbg_stats_header_2024_en-simlified.txt'
        ptn_1 = 'flaglist'
        ptn_2 = 'flagicon'
        prettify_name = {
            'European Union': '[[European Union]]',
            'Central Europe and the Baltics': '[[Central Europe]] & the [[Baltic states|Baltics]]',
            'Europe & Central Asia': '[[Europe]] & [[Central Asia]]',
            'South Asia': '[[South Asia]]',
            'East Asia & Pacific': '[[Asia-Pacific|East Asia & Pacific]]',
            'Middle East, North Africa, Afghanistan & Pakistan': '[[MENA|Middle East & North Africa]]',
            'Africa Eastern and Southern': 'Africa [[East Africa|Eastern]] & [[Southern Africa|Southern]]',
            'Sub-Saharan Africa': '[[Sub-Saharan Africa]]',
            'Africa Western and Central': 'Africa [[West Africa|Western]] & [[Central Africa|Central]]',
            'North America': '[[North America]]',
            'Latin America & Caribbean': '[[Latin America and the Caribbean|Latin America & Caribbean]]',
            'Arab World': '[[Arab world]]',
            'World': 'World'
        }
        
    with open('design/' + file_header, mode='r', encoding="utf-8") as fh:
        st_header = fh.read()
        
    st_header = st_header.strip()
    st = ''
        
    for i in range(len(df)):
        ser = df.iloc[i]
        if ser.name in ['World']:
            st += '\n' + '|-class=static-row-header\n' + \
                  f'|style="text-align:center;"| \'\'\'{prettify_name.get(ser.name, ser.name)}\'\'\' ' + \
                  f'||style="background:#e0ffd8;"| \'\'\'{if_value(ser.total, 2)}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| \'\'\'{if_value(ser.male, 2)}\'\'\' ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{if_value(ser.female, 2)}\'\'\' ' + \
                  f'||style="background:#fff8dc;"| \'\'\'{if_value(ser.gender_gap, 2)}\'\'\' ' + \
                  f'||style="border-left-width:2px; padding-left:1em;"| \'\'\'{if_value(ser["2014_t"], 2)}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2014→2019"], 2)} ' + \
                  f'|| \'\'\'{if_value(ser["2019_t"], 2)}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2019→2020"], 2)} ' + \
                  f'|| \'\'\'{if_value(ser["2020_t"], 2)}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2020→2021"], 2)} ' + \
                  f'|| \'\'\'{if_value(ser["2021_t"], 2)}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2021→2022"], 2)} ' + \
                  f'|| \'\'\'{if_value(ser["2022_t"], 2)}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2022→2023"], 2)} ' + \
                  f'|| \'\'\'{if_value(ser["2023_t"], 2)}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2023→2024"], 2)} ' + \
                  f'||style="background:#e0ffd8;"| \'\'\'{if_value(ser.total, 2)}\'\'\' ' + \
                  f'||style="background:#fffae0;border-left-width:2px;{chval_bold(ser["2019→2024"], 2)}' + \
                  (f' ||style="background:#fffae0;{chval_bold(ser["2014→2024"], 2)}' if lang=='ru' else '')
        else:
            st += '\n' + '|-\n' + \
                  f'| {prettify_name.get(ser.name, ser.name)} ' + \
                  f'||style="background:#e0ffd8;"| {if_value(ser.total, 2)} ' + \
                  f'||style="background:#eaf3ff;"| {if_value(ser.male, 2)} ' + \
                  f'||style="background:#fee7f6;"| {if_value(ser.female, 2)} ' + \
                  f'||style="background:#fff8dc;"| {if_value(ser.gender_gap, 2)} ' + \
                  f'||style="border-left-width:2px; padding-left:1em;"| {if_value(ser["2014_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2014→2019"], 2)} ' + \
                  f'|| {if_value(ser["2019_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2019→2020"], 2)} ' + \
                  f'|| {if_value(ser["2020_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2020→2021"], 2)} ' + \
                  f'|| {if_value(ser["2021_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2021→2022"], 2)} ' + \
                  f'|| {if_value(ser["2022_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2022→2023"], 2)} ' + \
                  f'|| {if_value(ser["2023_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2023→2024"], 2)} ' + \
                  f'||style="background:#e0ffd8;"| {if_value(ser.total, 2)} ' + \
                  f'||style="background:#fffae0;border-left-width:2px;{chval(ser["2019→2024"], 2)}' + \
                  (f' ||style="background:#fffae0;{chval(ser["2014→2024"], 2)}' if lang=='ru' else '')
    st += '\n|}'
    
    st = st.replace('color:darkgray;"| 0.00 ', 'color:darkgray;"| 0.00 ')  \
           .replace('color:crimson;"| −0.00 ', 'color:darkgray;"| 0.00 ')  \
           .replace('color:darkgreen;"| 0.00 ', 'color:darkgray;"| 0.00 ')  \
           .replace('color:darkgray;"| \'\'\'0.00\'\'\' ', 'color:darkgray;"| \'\'\'0.00\'\'\' ')  \
           .replace('color:crimson;"| \'\'\'−0.00\'\'\' ', 'color:darkgray;"| \'\'\'0.00\'\'\' ')  \
           .replace('color:darkgreen;"| \'\'\'0.00\'\'\' ', 'color:darkgray;"| \'\'\'0.00\'\'\' ')

    # WARNING: be sure that inline styles do not contains numbers with comma
    if (lang == 'ru') | (lang == 'fr'):
        st = re.sub('(?<=\\d)\\.(?=\\d)', ',', st)  # replace . to comma, if this . is between two digits
        
    st = st_header + st

    return st

In [65]:
df_regions = filter_df(df, ls_regions + ['World'])

df_regions.round(2)

Total : 59.04 – 81.56   (Africa Western and Central – European Union)
Male  : 57.91 – 79.04   (Africa Western and Central – European Union)
Female: 60.21 – 84.22   (Africa Western and Central – European Union)

,total,male,female,gender_gap,2014_t,2014→2019,2019_t,2019→2020,2020_t,2020→2021,2021_t,2021→2022,2022_t,2022→2023,2023_t,2023→2024,2019→2024,2014→2024
,,,,,,,,,,,,,,,,,,
European Union,81.56,79.04,84.22,5.18,80.88,0.44,81.32,-0.88,80.44,-0.13,80.31,0.41,80.71,0.71,81.42,0.14,0.24,0.68
North America,79.24,76.88,81.72,4.84,79.14,-0.00,79.13,-1.68,77.45,-0.59,76.86,0.96,77.82,0.91,78.73,0.51,0.11,0.10
Europe & Central Asia,78.60,75.57,81.79,6.22,77.35,0.95,78.30,-1.13,77.18,-0.45,76.73,1.11,77.83,0.56,78.39,0.21,0.29,1.24
Central Europe and the Baltics,77.92,74.48,81.54,7.06,76.69,0.58,77.27,-1.25,76.02,-1.29,74.72,1.93,76.65,1.11,77.76,0.16,0.65,1.23
East Asia & Pacific,76.74,73.92,79.70,5.78,75.56,1.02,76.59,-0.04,76.54,-0.39,76.15,0.52,76.68,-0.02,76.66,0.08,0.15,1.17
Latin America & Caribbean,75.82,72.95,78.69,5.74,74.56,0.64,75.20,-2.02,73.19,-1.37,71.81,2.83,74.65,1.00,75.64,0.17,0.61,1.26
World,73.48,71.12,75.97,4.86,71.78,1.09,72.87,-0.69,72.18,-0.97,71.22,1.75,72.97,0.36,73.33,0.15,0.61,1.71
Arab World,72.72,70.90,74.70,3.80,70.54,1.30,71.84,-1.11,70.73,-0.32,70.40,1.47,71.88,0.57,72.44,0.28,0.88,2.19
South Asia,72.56,71.01,74.22,3.22,69.12,1.88,71.00,-0.64,70.36,-2.54,67.82,4.19,72.01,0.31,72.32,0.24,1.56,3.44
"Middle East, North Africa, Afghanistan & Pakistan",72.32,70.42,74.34,3.92,69.99,1.25,71.24,-1.33,69.91,-0.20,69.71,1.98,71.69,0.39,72.08,0.23,1.07,2.33
Africa Eastern and Southern,65.35,62.59,68.13,5.54,61.25,2.61,63.86,-0.09,63.77,-0.79,62.98,1.51,64.49,0.66,65.15,0.20,1.49,4.10
Sub-Saharan Africa,62.80,60.68,64.96,4.28,58.99,2.14,61.13,0.04,61.17,-0.46,60.70,1.15,61.86,0.75,62.60,0.20,1.67,3.82
Africa Western and Central,59.04,57.91,60.21,2.30,55.69,1.45,57.14,0.21,57.36,-0.00,57.36,0.62,57.98,0.87,58.85,0.19,1.90,3.35

In [66]:
table_code_regions = create_table_for_regions(df_regions)
table_code_regions = table_code_regions.replace('Countries &<br>territories', 'Macroregions')

output_table_code(table_code_regions, 'Table code WBG -2024 -z_regions -en.txt')

Data has written to file

In [67]:
table_code_regions = create_table_for_regions(df_regions, lang='ru')
table_code_regions = table_code_regions.replace('Страны и<br>территории', 'Макрорегионы')

output_table_code(table_code_regions, 'Table code WBG -2024 -z_regions -ru.txt')

Data has written to file

<br />
<br />
<br />

---
Check section

In [68]:
# check that all countries are considered for local tables
ls_all_countries = sorted(df.index.to_list())
print(len(ls_all_countries))

231

In [69]:
# combine all local lists into one

import itertools
all_local_lists = sorted(set(itertools.chain(
                      ls_N_America, ls_S_America, ls_Asia, ls_Europe, ls_Africa, ls_Oceania, ls_regions
                  )))
print(len(all_local_lists))

231

In [70]:
ls_check_1 = [country for country in ls_all_countries if country not in all_local_lists]

assert ls_check_1 == [], f"In total list there are countries that are not in local lists:\n{', '.join(ls_check_1)}"
ls_check_1

[]

In [71]:
ls_check_2 = [country for country in all_local_lists if country not in ls_all_countries]

assert ls_check_2 == [], f"In local lists there are countries that are not in total list:\n{', '.join(ls_check_2)}\nIt is very strange"
ls_check_2

[]

<br />
<br />
<br />

---

Creation of code for [Europe map](https://en.wikipedia.org/wiki/List_of_European_countries_by_life_expectancy)

In [72]:
from collections import namedtuple

In [73]:
MapLocations = namedtuple('MapLocations', ['country', 'x', 'y', 'ru_name'],
                                        defaults=('-', 0, 0, '-'))

In [74]:
dd_coloring = {
    70: 'ff0000',
    71: 'ff2000',
    72: 'ff4000',
    73: 'ff6000',
    74: 'ff8000',
    75: 'ffa000',
    76: 'ffc000',
    77: 'ffe000',
    78: 'ffff00',
    79: 'e0ff00',
    80: 'c0ff00',
    81: 'a0ff00',
    82: '80ff00',
    83: '60ff00',
    84: '40ff00',
    85: '20ff00',
    86: '00ff00'}

ls_locations = [
    MapLocations(country='Albania', x=0.615, y=0.665, ru_name='Албания'),
    MapLocations(country='Armenia', x=0.92, y=0.58, ru_name='Армения'),
    MapLocations(country='Austria', x=0.545, y=0.555, ru_name='Австрия'),
    MapLocations(country='Azerbaijan', x=0.96, y=0.56, ru_name='Азербайджан'),
    MapLocations(country='Belarus', x=0.67, y=0.45, ru_name='Белоруссия'),
    MapLocations(country='Belgium', x=0.43, y=0.49, ru_name='Бельгия'),
    MapLocations(country='Bosnia and Herzegovina', x=0.57, y=0.61, ru_name='Босния и Герцеговина'),
    MapLocations(country='Bulgaria', x=0.66, y=0.624, ru_name='Болгария'),
    MapLocations(country='Croatia', x=0.56, y=0.594, ru_name='Хорватия'),
    MapLocations(country='Cyprus', x=0.79, y=0.73, ru_name='Республика Кипр'),
    MapLocations(country='Czechia', x=0.545, y=0.518, ru_name='Чехия'),
    MapLocations(country='Denmark', x=0.48, y=0.42, ru_name='Дания'),
    MapLocations(country='Estonia', x=0.625, y=0.37, ru_name='Эстония'),
    MapLocations(country='Finland', x=0.63, y=0.30, ru_name='Финляндия'),
    MapLocations(country='France', x=0.40, y=0.55, ru_name='Франция'),
    MapLocations(country='Georgia', x=0.90, y=0.555, ru_name='Грузия'),
    MapLocations(country='Germany', x=0.495, y=0.496, ru_name='Германия'),
    MapLocations(country='Greece', x=0.64, y=0.68, ru_name='Греция'),
    MapLocations(country='Hungary', x=0.59, y=0.56, ru_name='Венгрия'),
    MapLocations(country='Iceland', x=0.34, y=0.23, ru_name='Исландия'),
    MapLocations(country='Ireland', x=0.34, y=0.43, ru_name='Ирландия'),
    MapLocations(country='Italy', x=0.53, y=0.65, ru_name='Италия'),
    MapLocations(country='Kazakhstan', x=0.97, y=0.39, ru_name='Казахстан'),
    MapLocations(country='Latvia', x=0.625, y=0.4, ru_name='Латвия'),
    MapLocations(country='Lithuania', x=0.625, y=0.43, ru_name='Литва'),
    MapLocations(country='Luxembourg', x=0.45, y=0.51, ru_name='Люксембург'),
    MapLocations(country='Malta', x=0.56, y=0.754, ru_name='Мальта'),
    MapLocations(country='Moldova', x=0.70, y=0.56, ru_name='Молдова'),
    MapLocations(country='Montenegro', x=0.59, y=0.63, ru_name='Черногория'),
    MapLocations(country='Netherlands', x=0.46, y=0.47, ru_name='Нидерланды'),
    MapLocations(country='North Macedonia', x=0.634, y=0.65, ru_name='Северная Македония'),
    MapLocations(country='Norway', x=0.49, y=0.34, ru_name='Норвегия'),
    MapLocations(country='Poland', x=0.58, y=0.48, ru_name='Польша'),
    MapLocations(country='Portugal', x=0.24, y=0.62, ru_name='Португалия'),
    MapLocations(country='Romania', x=0.655, y=0.575, ru_name='Румыния'),
    MapLocations(country='Russia', x=0.76, y=0.38, ru_name='Россия'),
    MapLocations(country='Serbia', x=0.615, y=0.605, ru_name='Сербия'),
    MapLocations(country='Slovakia', x=0.58, y=0.54, ru_name='Словакия'),
    MapLocations(country='Slovenia', x=0.535, y=0.58, ru_name='Словения'),
    MapLocations(country='Spain', x=0.3, y=0.65, ru_name='Испания'),
    MapLocations(country='Sweden', x=0.54, y=0.37, ru_name='Швеция'),
    MapLocations(country='Switzerland', x=0.474, y=0.56, ru_name='Швейцария'),
    MapLocations(country='Turkey', x=0.82, y=0.64, ru_name='Турция'),
    MapLocations(country='Ukraine', x=0.69, y=0.505, ru_name='Украина'),
    MapLocations(country='United Kingdom', x=0.38, y=0.46, ru_name='Великобритания')
]

# small coutries that are not included: 'Channel Islands', 'Faroe Islands', 'Gibraltar', 'Isle of Man'
# MapLocations(country='Liechtenstein', x=0.49, y=0.58, ru_name='Лихтенштейн'),

In [75]:
selected_year = 'total'
lang = 'ru'

for country, x, y, ru_name in ls_locations:
    le = df.loc[country, selected_year].round(1)
    background = dd_coloring[int(le)]
    if country == 'Georgia':
        country = 'Georgia (country)'
    print(f'{{{{Image label small|x={x}|y={y}|scale=700|text=[[{ru_name if lang=="ru" else country}|<span style="background:#{background};color:black">{le}</span>]]}}}}')

{{Image label small|x=0.615|y=0.665|scale=700|text=[[Албания|<span style="background:#e0ff00;color:black">79.8</span>]]}}
{{Image label small|x=0.92|y=0.58|scale=700|text=[[Армения|<span style="background:#ffff00;color:black">78.3</span>]]}}
{{Image label small|x=0.545|y=0.555|scale=700|text=[[Австрия|<span style="background:#80ff00;color:black">82.0</span>]]}}
{{Image label small|x=0.96|y=0.56|scale=700|text=[[Азербайджан|<span style="background:#ff8000;color:black">74.6</span>]]}}
{{Image label small|x=0.67|y=0.45|scale=700|text=[[Белоруссия|<span style="background:#ff8000;color:black">74.4</span>]]}}
{{Image label small|x=0.43|y=0.49|scale=700|text=[[Бельгия|<span style="background:#80ff00;color:black">82.3</span>]]}}
{{Image label small|x=0.57|y=0.61|scale=700|text=[[Босния и Герцеговина|<span style="background:#ffff00;color:black">78.0</span>]]}}
{{Image label small|x=0.66|y=0.624|scale=700|text=[[Болгария|<span style="background:#ffa000;color:black">75.8</span>]]}}
{{Image label small|x=0.56|y=0.594|scale=700|text=[[Хорватия|<span style="background:#ffff00;color:black">78.9</span>]]}}
{{Image label small|x=0.79|y=0.73|scale=700|text=[[Республика Кипр|<span style="background:#a0ff00;color:black">81.8</span>]]}}
{{Image label small|x=0.545|y=0.518|scale=700|text=[[Чехия|<span style="background:#c0ff00;color:black">80.0</span>]]}}
{{Image label small|x=0.48|y=0.42|scale=700|text=[[Дания|<span style="background:#80ff00;color:black">82.3</span>]]}}
{{Image label small|x=0.625|y=0.37|scale=700|text=[[Эстония|<span style="background:#e0ff00;color:black">79.3</span>]]}}
{{Image label small|x=0.63|y=0.3|scale=700|text=[[Финляндия|<span style="background:#80ff00;color:black">82.3</span>]]}}
{{Image label small|x=0.4|y=0.55|scale=700|text=[[Франция|<span style="background:#60ff00;color:black">83.0</span>]]}}
{{Image label small|x=0.9|y=0.555|scale=700|text=[[Грузия|<span style="background:#ff8000;color:black">74.7</span>]]}}
{{Image label small|x=0.495|y=0.496|scale=700|text=[[Германия|<span style="background:#c0ff00;color:black">80.8</span>]]}}
{{Image label small|x=0.64|y=0.68|scale=700|text=[[Греция|<span style="background:#a0ff00;color:black">81.8</span>]]}}
{{Image label small|x=0.59|y=0.56|scale=700|text=[[Венгрия|<span style="background:#ffc000;color:black">76.7</span>]]}}
{{Image label small|x=0.34|y=0.23|scale=700|text=[[Исландия|<span style="background:#80ff00;color:black">82.8</span>]]}}
{{Image label small|x=0.34|y=0.43|scale=700|text=[[Ирландия|<span style="background:#60ff00;color:black">83.0</span>]]}}
{{Image label small|x=0.53|y=0.65|scale=700|text=[[Италия|<span style="background:#40ff00;color:black">84.0</span>]]}}
{{Image label small|x=0.97|y=0.39|scale=700|text=[[Казахстан|<span style="background:#ff8000;color:black">74.5</span>]]}}
{{Image label small|x=0.625|y=0.4|scale=700|text=[[Латвия|<span style="background:#ffc000;color:black">76.4</span>]]}}
{{Image label small|x=0.625|y=0.43|scale=700|text=[[Литва|<span style="background:#ffe000;color:black">77.2</span>]]}}
{{Image label small|x=0.45|y=0.51|scale=700|text=[[Люксембург|<span style="background:#60ff00;color:black">83.2</span>]]}}
{{Image label small|x=0.56|y=0.754|scale=700|text=[[Мальта|<span style="background:#60ff00;color:black">83.0</span>]]}}
{{Image label small|x=0.7|y=0.56|scale=700|text=[[Молдова|<span style="background:#ff2000;color:black">71.3</span>]]}}
{{Image label small|x=0.59|y=0.63|scale=700|text=[[Черногория|<span style="background:#ffe000;color:black">77.9</span>]]}}
{{Image label small|x=0.46|y=0.47|scale=700|text=[[Нидерланды|<span style="background:#80ff00;color:black">82.0</span>]]}}
{{Image label small|x=0.634|y=0.65|scale=700|text=[[Северная Македония|<span style="background:#ffc000;color:black">76.6</span>]]}}
{{Image label small|x=0.49|y=0.34|scale=700|text=[[Норвегия|<span style="background:#60ff00;color:black">83.2</span>]]}}
{{Image label small|x=0.58|y=0.48|scale=700|text=[[Польша|<span style="background:#ffff00;color:black">78.4</span>]]}}
{{Image label small|x=0.24|y=0.62|scale=700|text=[[Португалия|<span style="background:#80ff00;color:black">82.4</span>]]}}
{{Image label small|x=0.655|y=0.575|scale=700|text=[[Румыния|<span style="background:#ffc000;color:black">76.5</span>]]}}
{{Image label small|x=0.76|y=0.38|scale=700|text=[[Россия|<span style="background:#ff6000;color:black">73.4</span>]]}}
{{Image label small|x=0.615|y=0.605|scale=700|text=[[Сербия|<span style="background:#ffc000;color:black">76.0</span>]]}}
{{Image label small|x=0.58|y=0.54|scale=700|text=[[Словакия|<span style="background:#ffff00;color:black">78.4</span>]]}}
{{Image label small|x=0.535|y=0.58|scale=700|text=[[Словения|<span style="background:#80ff00;color:black">82.3</span>]]}}
{{Image label small|x=0.3|y=0.65|scale=700|text=[[Испания|<span style="background:#60ff00;color:black">83.9</span>]]}}
{{Image label small|x=0.54|y=0.37|scale=700|text=[[Швеция|<span style="background:#40ff00;color:black">84.1</span>]]}}
{{Image label small|x=0.474|y=0.56|scale=700|text=[[Швейцария|<span style="background:#40ff00;color:black">84.4</span>]]}}
{{Image label small|x=0.82|y=0.64|scale=700|text=[[Турция|<span style="background:#ffe000;color:black">77.4</span>]]}}
{{Image label small|x=0.69|y=0.505|scale=700|text=[[Украина|<span style="background:#ff8000;color:black">74.7</span>]]}}
{{Image label small|x=0.38|y=0.46|scale=700|text=[[Великобритания|<span style="background:#a0ff00;color:black">81.4</span>]]}}

<br />
<br />
<br />

[List of Chinese administrative divisions by life expectancy](https://en.wikipedia.org/wiki/List_of_Chinese_administrative_divisions_by_life_expectancy) / [Продолжительность жизни в регионах Китая](https://ru.wikipedia.org/wiki/Продолжительность_жизни_в_регионах_Китая)

In [76]:
# create code for placing info in Wikipedia
def create_table_China(df, lang='en'):

    def if_value(x, prec=2):
        return '—' if math.isnan(x) else \
               f"{x:0.{prec}f}"  if x>=0 else \
               f"−{-x:0.{prec}f}"

    def chval(x, prec=2):  # change_value
        return '"| —' if math.isnan(x) else \
               f'color:darkgreen;"| {x:0.{prec}f}' if x>0 else \
               f'color:crimson;"| −{-x:0.{prec}f}' if x<0 else \
               f'color:darkgray;"| {x:0.{prec}f}'
    
    def chval_bold(x, prec=2):  # change_value
        return '"| —' if math.isnan(x) else \
               f'color:darkgreen;"| \'\'\'{x:0.{prec}f}\'\'\'' if x>0 else \
               f'color:crimson;"| \'\'\'−{-x:0.{prec}f}\'\'\'' if x<0 else \
               f'color:darkgray;"| \'\'\'{x:0.{prec}f}\'\'\''

    if lang=='ru':
        file_header='wbg_stats_header_2024_ru-simlified.txt'
        ptn_1 = 'флагификация'
        ptn_2 = 'флаг'
        prettify_name = {
            'China': 'Китай в среднем'
        }
    else:
        file_header='wbg_stats_header_2024_en-simlified.txt'
        ptn_1 = 'flaglist'
        ptn_2 = 'flagicon'
        prettify_name = {
             'China': 'China on average'
        }
        
    with open('design/' + file_header, mode='r', encoding="utf-8") as fh:
        st_header = fh.read()
        
    st_header = st_header.strip()
    st = ''
        
    for i in range(len(df)):
        ser = df.iloc[i]
        if ser.name in ['China']:
            st += '\n' + '|-class=static-row-header\n' + \
                  f'|style="text-align:center;"| \'\'\'{prettify_name.get(ser.name, ser.name)}\'\'\' ' + \
                  f'||style="background:#e0ffd8;"| \'\'\'{if_value(ser.total, 2)}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| \'\'\'{if_value(ser.male, 2)}\'\'\' ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{if_value(ser.female, 2)}\'\'\' ' + \
                  f'||style="background:#fff8dc;"| \'\'\'{if_value(ser.gender_gap, 2)}\'\'\' ' + \
                  f'||style="border-left-width:2px;padding-left:1em;"| \'\'\'{if_value(ser["2014_t"], 2)}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2014→2019"], 2)} ' + \
                  f'|| \'\'\'{if_value(ser["2019_t"], 2)}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2019→2020"], 2)} ' + \
                  f'|| \'\'\'{if_value(ser["2020_t"], 2)}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2020→2021"], 2)} ' + \
                  f'|| \'\'\'{if_value(ser["2021_t"], 2)}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2021→2022"], 2)} ' + \
                  f'|| \'\'\'{if_value(ser["2022_t"], 2)}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2022→2023"], 2)} ' + \
                  f'|| \'\'\'{if_value(ser["2023_t"], 2)}\'\'\' ' + \
                  f'||style="background:#fffae0;{chval_bold(ser["2023→2024"], 2)} ' + \
                  f'||style="background:#e0ffd8;"| \'\'\'{if_value(ser.total, 2)}\'\'\' ' + \
                  f'||style="background:#fffae0;border-left-width:2px;{chval_bold(ser["2019→2024"], 2)}' + \
                  (f' ||style="background:#fffae0;{chval_bold(ser["2014→2024"], 2)}' if lang=='ru' else '')
        else:
            st += '\n' + '|-\n' + \
                  f'| {{{{{ptn_1}|{ser.name}}}}} ' + \
                  f'||style="background:#e0ffd8;"| {if_value(ser.total, 2)} ' + \
                  f'||style="background:#eaf3ff;"| {if_value(ser.male, 2)} ' + \
                  f'||style="background:#fee7f6;"| {if_value(ser.female, 2)} ' + \
                  f'||style="background:#fff8dc;"| {if_value(ser.gender_gap, 2)} ' + \
                  f'||style="border-left-width:2px;padding-left:1em;"| {if_value(ser["2014_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2014→2019"], 2)} ' + \
                  f'|| {if_value(ser["2019_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2019→2020"], 2)} ' + \
                  f'|| {if_value(ser["2020_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2020→2021"], 2)} ' + \
                  f'|| {if_value(ser["2021_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2021→2022"], 2)} ' + \
                  f'|| {if_value(ser["2022_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2022→2023"], 2)} ' + \
                  f'|| {if_value(ser["2023_t"], 2)} ' + \
                  f'||style="background:#fffae0;{chval(ser["2023→2024"], 2)} ' + \
                  f'||style="background:#e0ffd8;"| {if_value(ser.total, 2)} ' + \
                  f'||style="background:#fffae0;border-left-width:2px;{chval(ser["2019→2024"], 2)} ' + \
                  (f' ||style="background:#fffae0;{chval(ser["2014→2024"], 2)}' if lang=='ru' else '')
    st += '\n|}'
    
    # WARNING: be sure that inline styles do not contains numbers with comma
    if (lang == 'ru') | (lang == 'fr'):
        st = re.sub('(?<=\\d)\\.(?=\\d)', ',', st)  # replace . to comma, if this . is between two digits
        
    st = st_header + st
    
    return st

In [77]:
ls_China = ['China', 'Hong Kong SAR, China', 'Macao SAR, China']

df_China = filter_df(df, ls_China)

df_China.round(2)

Total : 78.02 – 85.39   (China – Hong Kong SAR, China)
Male  : 75.25 – 82.70   (China – Hong Kong SAR, China)
Female: 80.97 – 88.22   (China – Hong Kong SAR, China)

,total,male,female,gender_gap,2014_t,2014→2019,2019_t,2019→2020,2020_t,2020→2021,2021_t,2021→2022,2022_t,2022→2023,2023_t,2023→2024,2019→2024,2014→2024
,,,,,,,,,,,,,,,,,,
"Hong Kong SAR, China",85.39,82.70,88.22,5.52,83.94,1.22,85.16,0.34,85.50,0.04,85.53,-1.87,83.66,1.59,85.25,0.15,0.24,1.46
"Macao SAR, China",83.33,80.60,86.20,5.60,83.02,0.91,83.93,0.20,84.13,-0.40,83.73,-0.65,83.08,0.10,83.18,0.15,-0.60,0.31
China,78.02,75.25,80.97,5.72,76.71,1.23,77.94,0.08,78.02,0.10,78.12,0.08,78.20,-0.25,77.95,0.06,0.08,1.30

In [78]:
table_code_China = create_table_China(df_China, lang='ru')
output_table_code(table_code_China, 'Table code WBG -2024 -China -ru.txt')

Data has written to file

In [79]:
table_code_China = create_table_China(df_China, lang='en')
output_table_code(table_code_China, 'Table code WBG -2024 -China -en.txt')

Data has written to file

<br>
<br>

In [80]:
# just for interest, look at average values for the 20 best and the 20 worst countries
pd.concat([df.dropna(how='any').head(20).mean(), df.loc['World', :], df.dropna(how='any').tail(20).mean()], axis='columns').T.round(2)

,total,male,female,gender_gap,2014_t,2014→2019,2019_t,2019→2020,2020_t,2020→2021,2021_t,2021→2022,2022_t,2022→2023,2023_t,2023→2024,2019→2024,2014→2024
0,84.09,82.01,86.26,4.25,82.73,0.94,83.67,-0.89,82.78,0.11,82.89,0.47,83.37,0.52,83.89,0.20,0.42,1.36
World,73.48,71.12,75.97,4.86,71.78,1.09,72.87,-0.69,72.18,-0.97,71.22,1.75,72.97,0.36,73.33,0.15,0.61,1.71
1,60.30,58.55,62.03,3.48,55.36,2.14,57.50,0.98,58.48,-0.77,57.71,-0.23,57.48,2.61,60.09,0.20,2.80,4.94