[List of Italian provinces by life expectancy](https://en.wikipedia.org/wiki/List_of_Italian_provinces_by_life_expectancy) <i>([alternative](https://en.wikipedia.org/wiki/User:Lady3mlnm/List_of_Italian_provinces_by_life_expectancy_(alternative)))</i> / [Продолжительность жизни в провинциях Италии](https://ru.wikipedia.org/wiki/Продолжительность_жизни_в_провинциях_Италии)<br />
[Administrative divisions of Italy](https://en.wikipedia.org/wiki/Italy#Administrative_divisions) / 
[Административное деление Италии](https://ru.wikipedia.org/wiki/Административное_деление_Италии)<br />
source of data: [ISTAT](https://demo.istat.it/tavole/?t=indicatori)<br>
[MapChart](https://www.mapchart.net/italy.html) -for modern JSONs, [old_mapbuilder_at_web.archive.org](https://web.archive.org/web/20200524110112/https://www.mapchart.net/italy.html) -for old JSONs

In [3]:
import pandas as pd
from collections import namedtuple

import sys
sys.path.append("..")
import mal_moduls_private.mal_total as mal

In [4]:
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [5]:
pd.options.display.min_rows = 4
# pd.options.display.max_rows = 50

In [6]:
SORT_COLUMNS = ['2024', '2023'] # used only for intermediate processing of data and does not influence to final result
SELECTED_YEAR = '2024'
CREATE_LEGEND_CODE = True

In [7]:
# Due to two administrative reforms in Sardinia islands and limitation of flexibility of the MapChart map generator,
# some provinces can be set on the map correctly.
# But old version of the map generator at web.archive.org can place them.
# This options determines instruction to don't place these provinces in the generated JSONs.
# Set this option as True this option in case of using the current MapChart map generator
#     (some provinces will be not placed to the maps but the rest of the maps will be correct).
# Set this option as False in case of using vertion at web.archive.org.
#     (but this archived tool can't place title of provinces to the maps).
REMOVE_CONFUSING_PROVINCES = True

In [8]:
CountryGroup = namedtuple('CountryGroup', ['group_label', 'color', 'countries'])

In [9]:
# load stats about longevity
df = pd.read_excel('data/Indicatori_demografici -2024.xls', sheet_name='speranza_di_vita', skiprows=4, header=None, index_col=0)
df.index.name=''

df.dropna(how='all', inplace=True)

df

,1,2,3,4,5,6,7,8,9,10,...,129,130,131,132,133,134,135,136,137,138
,,,,,,,,,,,,,,,,,,,,,
Torino,77.4,17.0,83.1,20.9,80.2,19.0,77.2,16.7,82.8,20.6,...,85.4,22.5,83.4,21.1,81.9,20.0,85.9,22.9,83.9,21.4
Vercelli,76.3,16.6,81.3,20.0,78.7,18.3,76.1,16.3,81.4,20.1,...,84.4,22.2,82.0,20.5,80.4,19.2,84.8,22.5,82.6,20.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ISOLE,76.8,16.8,82.1,20.1,79.4,18.5,76.8,16.7,81.9,19.8,...,84.1,21.5,81.9,20.1,80.5,19.3,84.7,22.2,82.5,20.8
ITALIA,77.2,16.9,83.0,20.8,80.0,18.9,77.2,16.8,82.8,20.5,...,85.1,22.3,83.0,20.9,81.5,19.9,85.6,22.7,83.5,21.3

In [10]:
ls_cols = []
for year in list(range(2002, 2025)):
    ls_cols.extend([f'm_{year}', f'm65_{year}', f'f_{year}', f'f65_{year}', f'{year}', f't65_{year}'])

df.columns = ls_cols
df

,m_2002,m65_2002,f_2002,f65_2002,2002,t65_2002,m_2003,m65_2003,f_2003,f65_2003,...,f_2023,f65_2023,2023,t65_2023,m_2024,m65_2024,f_2024,f65_2024,2024,t65_2024
,,,,,,,,,,,,,,,,,,,,,
Torino,77.4,17.0,83.1,20.9,80.2,19.0,77.2,16.7,82.8,20.6,...,85.4,22.5,83.4,21.1,81.9,20.0,85.9,22.9,83.9,21.4
Vercelli,76.3,16.6,81.3,20.0,78.7,18.3,76.1,16.3,81.4,20.1,...,84.4,22.2,82.0,20.5,80.4,19.2,84.8,22.5,82.6,20.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ISOLE,76.8,16.8,82.1,20.1,79.4,18.5,76.8,16.7,81.9,19.8,...,84.1,21.5,81.9,20.1,80.5,19.3,84.7,22.2,82.5,20.8
ITALIA,77.2,16.9,83.0,20.8,80.0,18.9,77.2,16.8,82.8,20.5,...,85.1,22.3,83.0,20.9,81.5,19.9,85.6,22.7,83.5,21.3

<br />
<br />

In [12]:
# LE in Italy as a whole for interest:
# df.loc['ITALIA', map(str, range(2010, 2025))]
# LE in Italy as a whole for interest:
# df.loc['ITALIA', [f"{prefix}{year}" for year in range(2010, 2024) for prefix in ('', 'm_', 'f_')]]
df_preview = pd.concat([df.loc['ITALIA', [f"m_{year}" for year in range(2010, 2025)]].rename(index=lambda st: st[2:]),
                        df.loc['ITALIA', map(str, range(2010, 2025))],
                        df.loc['ITALIA', [f"f_{year}" for year in range(2010, 2025)]].rename(index=lambda st: st[2:]),
                       ], axis='columns')
df_preview.columns = ['male', 'overall', 'female']
df_preview

      male  overall  female
2010  79.3     81.8    84.3
2011  79.6     82.0    84.5
2012  79.7     82.0    84.5
2013  80.0     82.3    84.8
2014  80.3     82.6    85.0
2015  80.1     82.3    84.5
2016  80.6     82.8    85.1
2017  80.5     82.6    84.9
2018  80.8     82.9    85.2
2019  81.1     83.2    85.4
2020  79.8     82.1    84.5
2021  80.3     82.5    84.8
2022  80.6     82.6    84.8
2023  81.0     83.0    85.1
2024  81.5     83.5    85.6

<br />
<br />

In [14]:
cols_to_table = ['2014', '2019', '2020', '2021', '2022', '2023', '2024',
                 'm_2014', 'm_2019', 'm_2024', 'f_2014', 'f_2019', 'f_2024']

df = df.loc[:, cols_to_table]

df

,2014,2019,2020,2021,2022,2023,2024,m_2014,m_2019,m_2024,f_2014,f_2019,f_2024
,,,,,,,,,,,,,
Torino,83.0,83.3,81.8,82.8,82.8,83.4,83.9,80.9,81.2,81.9,85.2,85.5,85.9
Vercelli,81.7,82.4,80.2,81.6,81.7,82.0,82.6,79.0,80.6,80.4,84.5,84.2,84.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
ISOLE,81.8,82.2,81.7,81.5,81.5,81.9,82.5,79.6,80.1,80.5,84.1,84.4,84.7
ITALIA,82.6,83.2,82.1,82.5,82.6,83.0,83.5,80.3,81.1,81.5,85.0,85.4,85.6

In [15]:
regions = ["Piemonte", "Valle d'Aosta", "Lombardia", "Trentino-Alto Adige", "Veneto", "Friuli-Venezia Giulia",
           "Liguria", "Emilia-Romagna", "Toscana", "Umbria", "Marche", "Lazio", "Abruzzo", "Molise", "Campania",
           "Puglia", "Basilicata", "Calabria", "Sicilia", "Sardegna"]

macro_regions = ["NORD", "NORD-OVEST", "NORD-EST", "CENTRO", "MEZZOGIORNO", "SUD", "ISOLE"]

<br />
<br />
<br />

<hr>
<h3>Maps for regions</h3>

In [17]:
df_regions = df.loc[regions, :]

df_regions.sort_values(by=SORT_COLUMNS, ascending=False, inplace=True)

print(len(df_regions))
df_regions.head()

20

,2014,2019,2020,2021,2022,2023,2024,m_2014,m_2019,m_2024,f_2014,f_2019,f_2024
,,,,,,,,,,,,,
Trentino-Alto Adige,83.5,84.2,82.8,83.6,83.8,84.4,84.7,81.2,81.9,82.8,85.9,86.5,86.8
Marche,83.3,84.0,83.0,83.1,83.3,83.9,84.3,81.1,81.9,82.4,85.7,86.1,86.2
Veneto,83.2,83.8,82.9,83.3,83.4,83.8,84.3,80.7,81.7,82.4,85.8,86.1,86.4
Lombardia,83.2,83.6,81.4,83.1,83.2,83.8,84.1,80.9,81.5,82.2,85.6,85.9,86.1
Toscana,83.2,83.6,83.1,83.2,83.3,83.8,84.1,81.1,81.7,82.3,85.5,85.7,85.9

<br />
<br />

In [19]:
# Some inner statistics for interest:
mal.min_and_max_values(df_regions.loc[:, '2014':'2024'],
                       row_center=df.loc['ITALIA', '2014':'2024'], nmb=3, max_lng=17)

Number of records: 20

In [20]:
mal.min_and_max_values(df_regions.loc[:, 'm_2014':'f_2024'],
                       row_center=df.loc['ITALIA', 'm_2014':'f_2024'], nmb=3, max_lng=17)

Number of records: 20

<br />
<br />

<h4>maps for regions: overall</h4>

In [22]:
df_regions.rename(index={
    "Puglia" : "Apulia",
    "Sicilia" : "Sicily",
    "Valle d'Aosta" : "Valle d Aosta"
}, inplace=True)

df_regions.head(3)

,2014,2019,2020,2021,2022,2023,2024,m_2014,m_2019,m_2024,f_2014,f_2019,f_2024
,,,,,,,,,,,,,
Trentino-Alto Adige,83.5,84.2,82.8,83.6,83.8,84.4,84.7,81.2,81.9,82.8,85.9,86.5,86.8
Marche,83.3,84.0,83.0,83.1,83.3,83.9,84.3,81.1,81.9,82.4,85.7,86.1,86.2
Veneto,83.2,83.8,82.9,83.3,83.4,83.8,84.3,80.7,81.7,82.4,85.8,86.1,86.4

In [23]:
dd_legend_main = {
    '85.5⩾' : '007800',
    '85.0–85.4' : '009800',
    '84.5–84.9' : '00b800',
    '84.0–84.4' : '00e000',
    '83.5–83.9' : '00ff00',
    '83.0–83.4' : 'b8ff00',
    '82.5–82.9' : 'ffff00',
    '82.0–82.4' : 'ffe000',
    '81.5–81.9' : 'ffbc00',
    '81.0–81.4' : 'ff9c00',
    '80.5–80.9' : 'ff7400',
    '80.0–80.4' : 'ff0000',
	'79.5–79.9' : 'c70000',
	'79.0–79.4' : '9e0000',
	'78.5–78.9' : '790000',
	'78.0–78.4' : '580000'
}

def fn_create_legend_code(dd_legend):
    for k, v in dd_legend.items():
        print(f"{{{{Legend|#{v}|{k}}}}}")  

if CREATE_LEGEND_CODE:
    fn_create_legend_code(dd_legend_main)

{{Legend|#007800|85.5⩾}}
{{Legend|#009800|85.0–85.4}}
{{Legend|#00b800|84.5–84.9}}
{{Legend|#00e000|84.0–84.4}}
{{Legend|#00ff00|83.5–83.9}}
{{Legend|#b8ff00|83.0–83.4}}
{{Legend|#ffff00|82.5–82.9}}
{{Legend|#ffe000|82.0–82.4}}
{{Legend|#ffbc00|81.5–81.9}}
{{Legend|#ff9c00|81.0–81.4}}
{{Legend|#ff7400|80.5–80.9}}
{{Legend|#ff0000|80.0–80.4}}
{{Legend|#c70000|79.5–79.9}}
{{Legend|#9e0000|79.0–79.4}}
{{Legend|#790000|78.5–78.9}}
{{Legend|#580000|78.0–78.4}}

<br />
<br />

In [25]:
def filter_df(df, selected_year=SELECTED_YEAR):
    filtered_df = df.loc[:, [selected_year]]   \
                    .sort_values(by=selected_year, ascending=False) \
                    .dropna()

    filtered_df['group_label'] = filtered_df[selected_year].map(lambda x: f"{x * 4 // 2 / 2:.1f}–{x * 4 // 2 / 2 + 0.4:.1f}")
    
    filtered_df['group_label'] = filtered_df['group_label']
    
    min_value = filtered_df[selected_year].min()
    max_value = filtered_df[selected_year].max()
    
    print(f"           ——— {selected_year} ———")
    print(f"Range: {min_value:.1f} – {max_value:.1f}   " +
          f"({filtered_df[selected_year].idxmin()} – {filtered_df[selected_year].idxmax()})")
    print(f"Number of groups: {filtered_df['group_label'].nunique()}")
    print(f"Number of values: {len(filtered_df)}")

    return filtered_df

df_sel_year = filter_df(df_regions, SELECTED_YEAR)
df_sel_year

           ——— 2024 ———
Range: 81.8 – 84.7   (Campania – Trentino-Alto Adige)
Number of groups: 7
Number of values: 20

                       2024 group_label

Trentino-Alto Adige    84.7   84.5–84.9
Marche                 84.3   84.0–84.4
Veneto                 84.3   84.0–84.4
Lombardia              84.1   84.0–84.4
Toscana                84.1   84.0–84.4
Emilia-Romagna         84.1   84.0–84.4
Umbria                 84.0   84.0–84.4
Friuli-Venezia Giulia  83.9   83.5–83.9
Liguria                83.6   83.5–83.9
Abruzzo                83.5   83.5–83.9
Piemonte               83.5   83.5–83.9
Lazio                  83.4   83.0–83.4
Apulia                 83.3   83.0–83.4
Basilicata             83.2   83.0–83.4
Sardegna               83.0   83.0–83.4
Valle d Aosta          82.8   82.5–82.9
Calabria               82.6   82.5–82.9
Molise                 82.5   82.5–82.9
Sicily                 82.4   82.0–82.4
Campania               81.8   81.5–81.9

In [26]:
def extract_indexes(subdf, dd_legend):
    group_label = subdf['group_label'].iloc[0]
    countries = subdf.index.to_list()
    color = (dd_legend[group_label])
    
    ls_grouping.append(CountryGroup(group_label=group_label, countries=countries, color=color))

    return pd.Series([color, countries], index=['color', 'regions'])


ls_grouping = []
df_grouped = df_sel_year.groupby(['group_label']).apply(extract_indexes, dd_legend = dd_legend_main).loc[::-1]

df_grouped

              color                                            regions
group_label
84.5–84.9    00b800                              [Trentino-Alto Adige]
84.0–84.4    00e000  [Marche, Veneto, Lombardia, Toscana, Emilia-Ro...
83.5–83.9    00ff00  [Friuli-Venezia Giulia, Liguria, Abruzzo, Piem...
83.0–83.4    b8ff00              [Lazio, Apulia, Basilicata, Sardegna]
82.5–82.9    ffff00                  [Valle d Aosta, Calabria, Molise]
82.0–82.4    ffe000                                           [Sicily]
81.5–81.9    ffbc00                                         [Campania]

In [27]:
def create_map_code_regions(ls_grouping, title='', legend_color='#000'):  # (ls_grouping, title='', legend_color='#000'):
    false, true = False, True

    jo = {
        "groups": { },
        "title": title,
        "hidden": [],
        "background": "#ffffff",
        "borders": "#000",
        "legendFont": "Century Gothic",
        "legendFontColor": "#000",
        "legendBorderColor": "#00000000",
        "legendBgColor": "#00000000",
        "legendWidth": 125,
        "legendBoxShape": "square",
        "areBordersShown": true,
        "defaultColor": "#d1dbdd",
        "labelsColor": "#6a0707",
        "labelsFont": "Arial",
        "strokeWidth": "medium",
        "areLabelsShown": true,
        "uncoloredScriptColor": "#ffff33",
        "v6": true,
        "page": "italy",
        "levelsVisibility": [
            "show",
            "show",
            "transparent"
        ],
        "legendPosition": "custom",
        "legendX": 850,
        "legendY": 30,
        "legendSize": "large",
        "legendTranslateX": "0.00",
        "legendStatus": "show",
        "scalingPatterns": true,
        "legendRowsSameColor": true,
        "legendColumnCount": 1
    }
    for group_label, color, regions in ls_grouping[::-1]:
        jo["groups"][f"#{color}"] = {"label": group_label.replace('–', ' - '),
                                     "paths": [region.replace(' ', '_') for region in regions]}       

    return jo


jo = create_map_code_regions(ls_grouping, title=f'{SELECTED_YEAR}', legend_color='#333333')

pretty_jo = json.dumps(jo, indent=2, ensure_ascii=False)

with open(f"output/map_JSON -regions -{SELECTED_YEAR}.txt", 'w', encoding="utf-8") as fh:
    fh.write(pretty_jo)

<br />
<br />

<h4>maps for regions: male</h4>

In [29]:
dd_legend_male = {
    '83.0–83.4' : '020f19',
	'82.5–82.9' : '062f4c',
	'82.0–82.4' : '08436e',
	'81.5–81.9' : '0b578d',
	'81.0–81.4' : '0d68a9',
	'80.5–80.9' : '107ac6',
	'80.0–80.4' : '128be1',
	'79.5–79.9' : '2e9eee',
	'79.0–79.4' : '51aef0',
	'78.5–78.9' : '6ebcf3',
	'78.0–78.4' : '92ccf6',
	'77.5–77.9' : 'b3dbf8',
	'77.0–77.4' : 'd4ebfb',
	'76.5–76.9' : 'edf7fd',
	'76.0–76.4' : 'f8fbfe'
}

if CREATE_LEGEND_CODE:
    fn_create_legend_code(dd_legend_male)

{{Legend|#020f19|83.0–83.4}}
{{Legend|#062f4c|82.5–82.9}}
{{Legend|#08436e|82.0–82.4}}
{{Legend|#0b578d|81.5–81.9}}
{{Legend|#0d68a9|81.0–81.4}}
{{Legend|#107ac6|80.5–80.9}}
{{Legend|#128be1|80.0–80.4}}
{{Legend|#2e9eee|79.5–79.9}}
{{Legend|#51aef0|79.0–79.4}}
{{Legend|#6ebcf3|78.5–78.9}}
{{Legend|#92ccf6|78.0–78.4}}
{{Legend|#b3dbf8|77.5–77.9}}
{{Legend|#d4ebfb|77.0–77.4}}
{{Legend|#edf7fd|76.5–76.9}}
{{Legend|#f8fbfe|76.0–76.4}}

In [30]:
df_sel_year = filter_df(df_regions, f"m_{SELECTED_YEAR}")
df_sel_year

           ——— m_2024 ———
Range: 79.8 – 82.8   (Campania – Trentino-Alto Adige)
Number of groups: 7
Number of values: 20

                       m_2024 group_label

Trentino-Alto Adige      82.8   82.5–82.9
Marche                   82.4   82.0–82.4
Veneto                   82.4   82.0–82.4
Emilia-Romagna           82.4   82.0–82.4
Toscana                  82.3   82.0–82.4
Umbria                   82.3   82.0–82.4
Lombardia                82.2   82.0–82.4
Friuli-Venezia Giulia    81.8   81.5–81.9
Liguria                  81.6   81.5–81.9
Lazio                    81.5   81.5–81.9
Abruzzo                  81.5   81.5–81.9
Piemonte                 81.5   81.5–81.9
Apulia                   81.3   81.0–81.4
Basilicata               81.1   81.0–81.4
Valle d Aosta            80.9   80.5–80.9
Sardegna                 80.5   80.5–80.9
Sicily                   80.5   80.5–80.9
Calabria                 80.4   80.0–80.4
Molise                   80.0   80.0–80.4
Campania                 79.8   79.5–79.9

In [31]:
ls_grouping = []
df_grouped = df_sel_year.groupby(['group_label']).apply(extract_indexes, dd_legend = dd_legend_male).loc[::-1]

In [32]:
jo = create_map_code_regions(ls_grouping, title=f'{SELECTED_YEAR}: ♂', legend_color='#333333')  # legend_color='#0000bf'

pretty_jo = json.dumps(jo, indent=2, ensure_ascii=False)

with open(f"output/map_JSON -regions -{SELECTED_YEAR}, male.txt", 'w', encoding="utf-8") as fh:
    fh.write(pretty_jo)

<br />
<br />

<h4>maps for regions: female</h4>

In [34]:
dd_legend_female = {
	'88.0–88.4' : '1e0204',
	'87.5–87.9' : '60070f',
	'87.0–87.4' : 'a30d19',
	'86.5–86.9' : 'd81132',
	'86.0–86.4' : 'ef3b59',
	'85.5–85.9' : 'f2657d',
	'85.0–85.4' : 'f58698',
	'84.5–84.9' : 'f7a5b2',
	'84.0–84.4' : 'f9bfc6',
	'83.5–83.9' : 'fbd8db',
	'83.0–83.4' : 'fdebed',
	'82.5–82.9' : 'fef8f9',
}

if CREATE_LEGEND_CODE:
    fn_create_legend_code(dd_legend_female)

{{Legend|#1e0204|88.0–88.4}}
{{Legend|#60070f|87.5–87.9}}
{{Legend|#a30d19|87.0–87.4}}
{{Legend|#d81132|86.5–86.9}}
{{Legend|#ef3b59|86.0–86.4}}
{{Legend|#f2657d|85.5–85.9}}
{{Legend|#f58698|85.0–85.4}}
{{Legend|#f7a5b2|84.5–84.9}}
{{Legend|#f9bfc6|84.0–84.4}}
{{Legend|#fbd8db|83.5–83.9}}
{{Legend|#fdebed|83.0–83.4}}
{{Legend|#fef8f9|82.5–82.9}}

In [35]:
df_sel_year = filter_df(df_regions, f"f_{SELECTED_YEAR}")
df_sel_year

           ——— f_2024 ———
Range: 84.0 – 86.8   (Campania – Trentino-Alto Adige)
Number of groups: 6
Number of values: 20

                       f_2024 group_label

Trentino-Alto Adige      86.8   86.5–86.9
Veneto                   86.4   86.0–86.4
Marche                   86.2   86.0–86.4
Lombardia                86.1   86.0–86.4
Friuli-Venezia Giulia    86.1   86.0–86.4
Toscana                  85.9   85.5–85.9
Emilia-Romagna           85.9   85.5–85.9
Umbria                   85.9   85.5–85.9
Liguria                  85.8   85.5–85.9
Sardegna                 85.6   85.5–85.9
Abruzzo                  85.6   85.5–85.9
Lazio                    85.5   85.5–85.9
Basilicata               85.5   85.5–85.9
Piemonte                 85.5   85.5–85.9
Apulia                   85.4   85.0–85.4
Molise                   85.0   85.0–85.4
Calabria                 84.9   84.5–84.9
Valle d Aosta            84.7   84.5–84.9
Sicily                   84.4   84.0–84.4
Campania                 84.0   84.0–84.4

In [36]:
ls_grouping = []
df_grouped = df_sel_year.groupby(['group_label']).apply(extract_indexes, dd_legend = dd_legend_female).loc[::-1]

In [37]:
jo = create_map_code_regions(ls_grouping, title=f'{SELECTED_YEAR}: ♀', legend_color='#333333')  # legend_color='#c20000'

pretty_jo = json.dumps(jo, indent=2, ensure_ascii=False)

with open(f"output/map_JSON -regions -{SELECTED_YEAR}, female.txt", 'w', encoding="utf-8") as fh:
    fh.write(pretty_jo)

<br />
<br />
<br />

<hr>
<h3>maps for provinces</h3>

In [39]:
df_provinces = df.drop(regions + macro_regions + ['ITALIA'])

# df_provinces = df_provinces.drop(['Cagliari', 'Sud Sardegna', 'Nuoro', 'Sassari'])

print(len(df_provinces))
df_provinces.head()

107

,2014,2019,2020,2021,2022,2023,2024,m_2014,m_2019,m_2024,f_2014,f_2019,f_2024
,,,,,,,,,,,,,
Torino,83.0,83.3,81.8,82.8,82.8,83.4,83.9,80.9,81.2,81.9,85.2,85.5,85.9
Vercelli,81.7,82.4,80.2,81.6,81.7,82.0,82.6,79.0,80.6,80.4,84.5,84.2,84.8
Biella,82.1,82.8,81.3,82.2,82.4,82.7,83.1,80.0,80.5,81.3,84.4,85.2,85.1
Verbano-Cusio-Ossola,82.2,83.1,81.9,83.0,82.4,83.0,83.2,79.8,80.7,81.2,84.7,85.6,85.4
Novara,82.8,83.0,81.6,82.8,82.7,83.6,83.8,80.4,81.0,82.0,85.2,85.1,85.6

In [40]:
mal.min_and_max_values(df_provinces, row_center=df.loc['ITALIA'], nmb=3, max_lng=11)

Number of records: 107

In [41]:
# Some inner statistics for interest:
mal.min_and_max_values(df_provinces.loc[:, '2014':'2024'],
                       row_center=df.loc['ITALIA', '2014':'2024'], nmb=5, max_lng=21)

Number of records: 107

In [42]:
mal.min_and_max_values(df_provinces.loc[:, 'm_2014':'f_2024'],
                       row_center=df.loc['ITALIA', 'm_2014':'f_2024'], nmb=5, max_lng=21)

Number of records: 107

<br />
<br />

<br />
<br />

<h4>maps for provinces: overall</h4>

In [45]:
print(f"number of provinces before removal: {len(df_provinces)}")
if REMOVE_CONFUSING_PROVINCES:
    df_provinces.drop(index=['Sassari', 'Nuoro', 'Sud Sardegna', 'Cagliari'], inplace=True)
print(f"number of provinces after removal : {len(df_provinces)}")

number of provinces before removal: 107
number of provinces after removal : 103

In [46]:
df_provinces.rename(index={
    "L'Aquila" : "L Aquila",
    "Pesaro e Urbino" : "Pesaro Urbino",
    "Reggio nell'Emilia" : "Reggio Emilia",
    "Forli'" : "Forli_Cesena_",
    "Verbano-Cusio-Ossola" : "Verbano Cusio Ossola",
    "Barletta-Andria-Trani" : "Barletta Andria Trani",
    "Reggio di Calabria" : "Reggio Calabria",
    "Monza e della Brianza" : "Monza and Brianza",
    "Massa-Carrara" : "Massa and Carrara",
    "Campobasso" : "Campobasso_",
    "Ascoli Piceno" : "Ascoli_Piceno_",
    "Barletta-Andria-Trani" : "Barletta_Andria_Trani_"    
}, inplace=True)

df_provinces.head(3)

,2014,2019,2020,2021,2022,2023,2024,m_2014,m_2019,m_2024,f_2014,f_2019,f_2024
,,,,,,,,,,,,,
Torino,83.0,83.3,81.8,82.8,82.8,83.4,83.9,80.9,81.2,81.9,85.2,85.5,85.9
Vercelli,81.7,82.4,80.2,81.6,81.7,82.0,82.6,79.0,80.6,80.4,84.5,84.2,84.8
Biella,82.1,82.8,81.3,82.2,82.4,82.7,83.1,80.0,80.5,81.3,84.4,85.2,85.1

In [47]:
df_sel_year = filter_df(df_provinces, SELECTED_YEAR)
df_sel_year

           ——— 2024 ———
Range: 81.5 – 85.0   (Caserta – Treviso)
Number of groups: 8
Number of values: 103

          2024 group_label

Treviso   85.0   85.0–85.4
Lecco     84.9   84.5–84.9
...        ...         ...
Siracusa  81.6   81.5–81.9
Caserta   81.5   81.5–81.9

[103 rows x 2 columns]

In [48]:
ls_grouping = []
df_grouped = df_sel_year.groupby(['group_label']).apply(extract_indexes, dd_legend = dd_legend_main).loc[::-1]

df_grouped

              color                                            regions
group_label
85.0–85.4    009800                                          [Treviso]
84.5–84.9    00b800  [Lecco, Monza and Brianza, Firenze, Vicenza, V...
84.0–84.4    00e000  [Brescia, Perugia, Ravenna, Bologna, Como, Reg...
83.5–83.9    00ff00  [Torino, Genova, Savona, Matera, Barletta_Andr...
83.0–83.4    b8ff00  [Lecce, Mantova, Ragusa, Vibo Valentia, Bellun...
82.5–82.9    ffff00  [Frosinone, Trieste, Taranto, Foggia, Enna, Or...
82.0–82.4    ffe000  [Messina, Benevento, Cosenza, Agrigento, Isern...
81.5–81.9    ffbc00                        [Napoli, Siracusa, Caserta]

In [49]:
def create_map_code_provinces(ls_grouping, title='', legend_color='#000'):  # (ls_grouping, title='', legend_color='#000'):
    false, true = False, True

    jo = {
        "groups": { },
        "title": title,
        "hidden": [],
        "background": "#ffffff",
        "borders": "#000",
        "legendFont": "Century Gothic",
        "legendFontColor": "#000",
        "legendBorderColor": "#00000000",
        "legendBgColor": "#00000000",
        "legendWidth": 125,
        "legendBoxShape": "square",
        "areBordersShown": true,
        "defaultColor": "#d1dbdd",
        "labelsColor": "#6a0707",
        "labelsFont": "Arial",
        "strokeWidth": "medium",
        "areLabelsShown": true,
        "uncoloredScriptColor": "#ffff33",
        "v6": true,
        "page": "italy",
        "levelsVisibility": [
            "show",
            "hide",
            "transparent"
        ],
        "legendPosition": "custom",
        "legendX": 850,
        "legendY": 30,
        "legendSize": "large",
        "legendTranslateX": "0.00",
        "legendStatus": "show",
        "scalingPatterns": true,
        "legendRowsSameColor": true,
        "legendColumnCount": 1
    }
    for group_label, color, regions in ls_grouping[::-1]:
        jo["groups"][f"#{color}"] = {"label": group_label.replace('–', ' - '),
                                     "paths": [region.replace(' ', '_') for region in regions]}       

    return jo

In [50]:
# code for older version of MapChart
def create_map_code_provinces_old(ls_grouping, title='', legend_color='#000'):
    false, true = False, True

    jo = {
        "groups": { },
        "title": title,
        "hidden": [],
        "background": "#ffffff",
        "borders": "#000000"
    }
    for i, (group_label, color, regions) in enumerate(ls_grouping[::-1]):
        jo["groups"][f"#{color}"] = {"div": f"#box{i}",
                                     "label": group_label.replace('–', ' - '),
                                     "paths": [region.replace(' ', '_') for region in regions]}       

    return jo

<br>

In [52]:
if REMOVE_CONFUSING_PROVINCES:
    jo = create_map_code_provinces(ls_grouping, title=f'{SELECTED_YEAR}', legend_color='#333333')
    
    pretty_jo = json.dumps(jo, indent=2, ensure_ascii=False)
    
    with open(f"output/map_JSON -provinces -{SELECTED_YEAR}.txt", 'w', encoding="utf-8") as fh:
        fh.write(pretty_jo)
else:
    jo = create_map_code_provinces_old(ls_grouping, title=f'{SELECTED_YEAR}', legend_color='#333333')
    
    pretty_jo = json.dumps(jo, indent=2, ensure_ascii=False)
    
    with open(f"output/map_JSON -provinces -{SELECTED_YEAR}, old.txt", 'w', encoding="utf-8") as fh:
        fh.write(pretty_jo)

<br />
<br />

<h4>maps for provinces: male</h4>

In [54]:
df_sel_year = filter_df(df_provinces, f"m_{SELECTED_YEAR}")
df_sel_year

           ——— m_2024 ———
Range: 79.3 – 83.4   (Caserta – Lecco)
Number of groups: 9
Number of values: 103

                   m_2024 group_label

Lecco                83.4   83.0–83.4
Monza and Brianza    83.1   83.0–83.4
...                   ...         ...
Napoli               79.6   79.5–79.9
Caserta              79.3   79.0–79.4

[103 rows x 2 columns]

In [55]:
ls_grouping = []
df_grouped = df_sel_year.groupby(['group_label']).apply(extract_indexes, dd_legend = dd_legend_male).loc[::-1]

In [56]:
if REMOVE_CONFUSING_PROVINCES:
    jo = create_map_code_provinces(ls_grouping, title=f'{SELECTED_YEAR}: ♂', legend_color='#333333')  # legend_color='#0000bf'
    
    pretty_jo = json.dumps(jo, indent=2, ensure_ascii=False)
    
    with open(f"output/map_JSON -provinces -{SELECTED_YEAR}, male.txt", 'w', encoding="utf-8") as fh:
        fh.write(pretty_jo)
else:
    jo = create_map_code_provinces_old(ls_grouping, title=f'{SELECTED_YEAR}: ♂', legend_color='#333333')  # legend_color='#0000bf'
    
    pretty_jo = json.dumps(jo, indent=2, ensure_ascii=False)
    
    with open(f"output/map_JSON -provinces -{SELECTED_YEAR}, male, old.txt", 'w', encoding="utf-8") as fh:
        fh.write(pretty_jo)

<br />
<br />

<h4>maps for provinces: female</h4>

In [58]:
df_sel_year = filter_df(df_provinces, f"f_{SELECTED_YEAR}")
df_sel_year

           ——— f_2024 ———
Range: 83.5 – 87.0   (Siracusa – Treviso)
Number of groups: 8
Number of values: 103

          f_2024 group_label

Treviso     87.0   87.0–87.4
Trento      86.9   86.5–86.9
...          ...         ...
Napoli      83.6   83.5–83.9
Siracusa    83.5   83.5–83.9

[103 rows x 2 columns]

In [59]:
ls_grouping = []
df_grouped = df_sel_year.groupby(['group_label']).apply(extract_indexes, dd_legend = dd_legend_female).loc[::-1]

In [60]:
if REMOVE_CONFUSING_PROVINCES:
    jo = create_map_code_provinces(ls_grouping, title=f'{SELECTED_YEAR}: ♀', legend_color='#333333')  # legend_color='#c20000'
    
    pretty_jo = json.dumps(jo, indent=2, ensure_ascii=False)
    
    with open(f"output/map_JSON -provinces -{SELECTED_YEAR}, female.txt", 'w', encoding="utf-8") as fh:
        fh.write(pretty_jo)
else:
    jo = create_map_code_provinces_old(ls_grouping, title=f'{SELECTED_YEAR}: ♀', legend_color='#333333')  # legend_color='#c20000'
    
    pretty_jo = json.dumps(jo, indent=2, ensure_ascii=False)
    
    with open(f"output/map_JSON -provinces -{SELECTED_YEAR}, female, old.txt", 'w', encoding="utf-8") as fh:
        fh.write(pretty_jo)