source of data: [Instituto Nacional de Estadística](https://www.ine.es/jaxiT3/Tabla.htm?t=1448&L=1), [CountryEconomy.com](https://countryeconomy.com/demography/life-expectancy/spain-autonomous-communities)<br>
wiki > [List of Spanish provinces by life expectancy](https://en.wikipedia.org/wiki/List_of_Spanish_provinces_by_life_expectancy), [Political divisions of Spain](https://en.wikipedia.org/wiki/Political_divisions_of_Spain), [Provinces of Spain](https://en.wikipedia.org/wiki/Provinces_of_Spain)<br>
wiki > [Продолжительность жизни в провинциях Испании](https://ru.wikipedia.org/wiki/Продолжительность_жизни_в_провинциях_Испании), [Административное деление Испании](https://ru.wikipedia.org/wiki/Административное_деление_Испании), [Провинции Испании](https://ru.wikipedia.org/wiki/Провинции_Испании)<br>
[MapChart](https://www.mapchart.net/spain.html)<br>
[Languages of Spain](https://en.wikipedia.org/wiki/Languages_of_Spain)

In [2]:
import pandas as pd
from collections import namedtuple

import sys
sys.path.append("..")
import mal_moduls_private.mal_total as mal

In [3]:
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [4]:
pd.options.display.min_rows = 6
pd.options.display.max_rows = 50

In [5]:
SORT_COLUMNS = ['2024', '2023'] # used only for intermediate processing of data and does not influence to final result
SELECTED_YEAR = '2024'
CREATE_LEGEND_CODE = True

In [6]:
CountryGroup = namedtuple('CountryGroup', ['group_label', 'color', 'countries'])

docs: [standard-encodings](https://docs.python.org/3/library/codecs.html#standard-encodings)<br>
docs: [docs: error-handlers](https://docs.python.org/3/library/codecs.html#error-handlers)

<br>

In [8]:
# load stats about longevity per year
df = pd.read_csv('data/Life expectancy in Spain -ac.csv', sep='\t', encoding='mbcs')  # , encoding='mbcs', encoding_errors='replace'

df.head(2)

  Autonomous Communities and Cities           Sex  Period  Total
0                      01 Andalucía  Both genders    2024  82.82
1                      01 Andalucía  Both genders    2023  82.49

In [9]:
# remove numbers before provinces names
df['Autonomous Communities and Cities'] = df['Autonomous Communities and Cities'].map(lambda st:st[3:])

# set provinces names as index
df.set_index('Autonomous Communities and Cities', drop=True, inplace=True)
df.index.name = ''

df.head()

                    Sex  Period  Total

Andalucía  Both genders    2024  82.82
Andalucía  Both genders    2023  82.49
Andalucía  Both genders    2022  81.86
Andalucía  Both genders    2021  81.46
Andalucía  Both genders    2020  81.51

In [10]:
df = pd.concat([df[(df.Sex == 'Both genders') & (df.Period == 2014)].Total,
                df[(df.Sex == 'Both genders') & (df.Period == 2019)].Total,
                df[(df.Sex == 'Both genders') & (df.Period == 2020)].Total,
                df[(df.Sex == 'Both genders') & (df.Period == 2021)].Total,
                df[(df.Sex == 'Both genders') & (df.Period == 2022)].Total,
                df[(df.Sex == 'Both genders') & (df.Period == 2023)].Total,
                df[(df.Sex == 'Both genders') & (df.Period == 2024)].Total,
                df[(df.Sex == 'Males') & (df.Period == 2014)].Total,
                df[(df.Sex == 'Males') & (df.Period == 2019)].Total,
                df[(df.Sex == 'Males') & (df.Period == 2023)].Total,
                df[(df.Sex == 'Males') & (df.Period == 2024)].Total,
                df[(df.Sex == 'Females') & (df.Period == 2014)].Total,
                df[(df.Sex == 'Females') & (df.Period == 2019)].Total,
                df[(df.Sex == 'Females') & (df.Period == 2023)].Total,
                df[(df.Sex == 'Females') & (df.Period == 2024)].Total
               ],
                  axis='columns',
                  keys=['2014', '2019', '2020', '2021', '2022', '2023', '2024',
                        'm_2014', 'm_2019', 'm_2023', 'm_2024', 'f_2014', 'f_2019', 'f_2023', 'f_2024'])

df.sort_values(by=SORT_COLUMNS, ascending=False, inplace=True)

df.rename(index = {
    'Andalucía' : 'Andalusia',
    'Aragón' : 'Aragon',
    'Asturias, Principado de' : 'Asturias',
    'Balears, Illes' : 'Balearic Islands',
    'Canarias' : 'Canary Islands',
    'Castilla - La Mancha' : 'Castilla La Mancha',
    'Castilla y León' : 'Castile and León',
    'Cataluña' : 'Catalonia',
    'Comunitat Valenciana' : 'Comunidad Valenciana',
    'Extremadura' : 'Estremadura',
    'Madrid, Comunidad de' : 'Madrid',
    'Murcia, Región de' : 'Murcia',
    'Navarra, Comunidad Foral de' : 'Navarre',
    'País Vasco' : 'Basque Country',
    'Rioja, La' : 'La Rioja'
}, inplace=True)

print(len(df))
df.head()

19

,2014,2019,2020,2021,2022,2023,2024,m_2014,m_2019,m_2023,m_2024,f_2014,f_2019,f_2023,f_2024
,,,,,,,,,,,,,,,
Madrid,84.20,84.93,82.27,84.56,84.76,85.39,85.58,81.44,82.33,82.92,83.07,86.59,87.19,87.51,87.74
Castile and León,83.60,84.20,82.53,83.94,83.68,84.54,84.67,80.82,81.52,81.95,82.08,86.44,86.94,87.15,87.28
Navarre,83.45,84.55,83.33,84.26,83.85,84.79,84.66,80.63,82.10,82.27,81.96,86.26,86.92,87.24,87.33
Basque Country,83.35,83.98,83.18,83.70,83.49,84.42,84.64,80.38,81.05,81.65,81.91,86.12,86.76,87.02,87.20
Aragon,82.85,83.88,82.38,83.25,83.06,84.07,84.24,80.03,81.26,81.24,81.71,85.72,86.48,86.89,86.72

<br />
<br />
<br />

Just for general interest, compare life expectancy in provinces with overall life expectancy in Spain:<br>
[all](https://www.ine.es/consul/serie.do?d=true&s=TM2177), [male](https://www.ine.es/consul/serie.do?d=true&s=TM1449), [female](https://www.ine.es/consul/serie.do?d=true&s=TM721)

In [12]:
df_country_all = pd.read_csv('data/Life expectancy in Spain as a whole -all.csv',
                             sep='\t', usecols=['PERIOD', 'VALUE'], index_col='PERIOD').round(3)
ser_country_all = df_country_all.loc[:, 'VALUE'].loc[[2014, 2019, 2020, 2021, 2022, 2023, 2024]]
ser_country_all.index = ser_country_all.index.map(lambda year: str(year))

df_country_m = pd.read_csv('data/Life expectancy in Spain as a whole -male.csv',
                             sep='\t', usecols=['PERIOD', 'VALUE'], index_col='PERIOD').round(3)
ser_country_m = df_country_m.loc[:, 'VALUE'].loc[[2014, 2019, 2023, 2024]]
ser_country_m.index = ser_country_m.index.map(lambda year: f"m_{year}")

df_country_f = pd.read_csv('data/Life expectancy in Spain as a whole -female.csv',
                             sep='\t', usecols=['PERIOD', 'VALUE'], index_col='PERIOD').round(3)

ser_country_f = df_country_f.loc[:, 'VALUE'].loc[[2014, 2019, 2023, 2024]]
ser_country_f.index = ser_country_f.index.map(lambda year: f"f_{year}")

ser_country = pd.concat([ser_country_all, ser_country_m, ser_country_f])
ser_country.index.name = ''
ser_country.name = 'Spain'

pd.DataFrame(ser_country).T

,2014,2019,2020,2021,2022,2023,2024,m_2014,m_2019,m_2023,m_2024,f_2014,f_2019,f_2023,f_2024
Spain,82.906,83.534,82.284,83.026,83.081,83.774,84.01,80.096,80.783,81.112,81.385,85.631,86.195,86.339,86.528

<br />

In [14]:
# Some inner statistics for interest:
mal.min_and_max_values(df.loc[:, '2014':'2024'], row_center=ser_country.loc['2014':'2024'], nmb=3, max_lng=11)

Number of records: 19

In [15]:
mal.min_and_max_values(df.loc[:, 'm_2014':'f_2023'], row_center=ser_country.loc['m_2014':'f_2023'], nmb=3, max_lng=11)

Number of records: 19

<br />
<br />

In [17]:
# renaming of provinces according to requirement of the online-service 'MapChart'
df.rename(index={
    'Asturias' : 'Asturias_ac',
    'Balearic Islands' : 'Balearic_Islands',
    'Basque Country' : 'Basque_Country',
    'Canary Islands' : 'Canary_Islands',
    'Cantabria' : 'Cantabria_ac',
    'Castile and León' : 'Castile_and_León',
    'Castilla La Mancha' : 'Castilla-La_Mancha',
    'Ceuta' : 'Ceuta_ac',
    'Comunidad Valenciana' : 'Valencia_ac',
    'Estremadura' : 'Extremadura',
    'La Rioja' : 'La_Rioja_ac',
    'Madrid' : 'Madrid_ac',
    'Melilla' : 'Melilla_ac',
    'Murcia' : 'Murcia_ac'
}, inplace=True)

df.head(3)

,2014,2019,2020,2021,2022,2023,2024,m_2014,m_2019,m_2023,m_2024,f_2014,f_2019,f_2023,f_2024
,,,,,,,,,,,,,,,
Madrid_ac,84.20,84.93,82.27,84.56,84.76,85.39,85.58,81.44,82.33,82.92,83.07,86.59,87.19,87.51,87.74
Castile_and_León,83.60,84.20,82.53,83.94,83.68,84.54,84.67,80.82,81.52,81.95,82.08,86.44,86.94,87.15,87.28
Navarre,83.45,84.55,83.33,84.26,83.85,84.79,84.66,80.63,82.10,82.27,81.96,86.26,86.92,87.24,87.33

<br />
<br />

<h4>Overall statistics</h4>

In [19]:
dd_legend_main = {
    '85.75–85.99' : '006a00',
    '85.50–85.74' : '007800',
    '85.25–85.49' : '008800',
    '85.00–85.24' : '009800',
    '84.75–84.99' : '00a700',
    '84.50–84.74' : '00b800',
    '84.25–84.49' : '00cb00',
    '84.00–84.24' : '00e000',
    '83.75–83.99' : '00f000',
    '83.50–83.74' : '00ff00',
    '83.25–83.49' : '88ff00',
    '83.00–83.24' : 'b8ff00',
    '82.75–82.99' : 'deff00',
    '82.50–82.74' : 'ffff00',
    '82.25–82.49' : 'ffef00',
    '82.00–82.24' : 'ffe000',
    '81.75–81.99' : 'ffce00',
    '81.50–81.74' : 'ffbc00',
    '81.25–81.49' : 'ffac00',
    '81.00–81.24' : 'ff9c00',
    '80.75–80.99' : 'ff8700',
    '80.50–80.74' : 'ff7400',
    '80.25–80.49' : 'ff5200',
    '80.00–80.24' : 'ff0000',
    '79.75–79.99' : 'e10000',
	'79.50–79.74' : 'c70000',
	'79.25–79.49' : 'af0000',
	'79.00–79.24' : '9e0000',
	'78.75–78.99' : '8b0000',
	'78.50–78.74' : '790000',
	'78.25–78.49' : '670000',
	'78.00–78.24' : '580000'
}

def fn_create_legend_code(dd_legend):
    for k, v in dd_legend.items():
        print(f"{{{{Legend|#{v}|{k}}}}}")  

if CREATE_LEGEND_CODE:
    fn_create_legend_code(dd_legend_main)

{{Legend|#006a00|85.75–85.99}}
{{Legend|#007800|85.50–85.74}}
{{Legend|#008800|85.25–85.49}}
{{Legend|#009800|85.00–85.24}}
{{Legend|#00a700|84.75–84.99}}
{{Legend|#00b800|84.50–84.74}}
{{Legend|#00cb00|84.25–84.49}}
{{Legend|#00e000|84.00–84.24}}
{{Legend|#00f000|83.75–83.99}}
{{Legend|#00ff00|83.50–83.74}}
{{Legend|#88ff00|83.25–83.49}}
{{Legend|#b8ff00|83.00–83.24}}
{{Legend|#deff00|82.75–82.99}}
{{Legend|#ffff00|82.50–82.74}}
{{Legend|#ffef00|82.25–82.49}}
{{Legend|#ffe000|82.00–82.24}}
{{Legend|#ffce00|81.75–81.99}}
{{Legend|#ffbc00|81.50–81.74}}
{{Legend|#ffac00|81.25–81.49}}
{{Legend|#ff9c00|81.00–81.24}}
{{Legend|#ff8700|80.75–80.99}}
{{Legend|#ff7400|80.50–80.74}}
{{Legend|#ff5200|80.25–80.49}}
{{Legend|#ff0000|80.00–80.24}}
{{Legend|#e10000|79.75–79.99}}
{{Legend|#c70000|79.50–79.74}}
{{Legend|#af0000|79.25–79.49}}
{{Legend|#9e0000|79.00–79.24}}
{{Legend|#8b0000|78.75–78.99}}
{{Legend|#790000|78.50–78.74}}
{{Legend|#670000|78.25–78.49}}
{{Legend|#580000|78.00–78.24}}

In [20]:
def filter_df(df, selected_year=SELECTED_YEAR):
    filtered_df = df.loc[:, [selected_year]]   \
                    .sort_values(by=selected_year, ascending=False) \
                    .dropna()

    filtered_df['group_label'] = filtered_df[selected_year].map(lambda x: f"{x * 8 // 2 / 4:.2f}–{x * 8 // 2 / 4 + 0.24:.2f}")
    
    filtered_df['group_label'] = filtered_df['group_label']
    
    min_value = filtered_df[selected_year].min()
    max_value = filtered_df[selected_year].max()
    
    print(f"           ——— {selected_year} ———")
    print(f"Range: {min_value:.2f} – {max_value:.2f}   " +
          f"({filtered_df[selected_year].idxmin()} – {filtered_df[selected_year].idxmax()})")
    print(f"Number of groups: {filtered_df['group_label'].nunique()}")
    print(f"Number of values: {len(filtered_df)}")

    return filtered_df

df_sel_year = filter_df(df, SELECTED_YEAR)
df_sel_year

           ——— 2024 ———
Range: 81.60 – 85.58   (Ceuta_ac – Madrid_ac)
Number of groups: 9
Number of values: 19

                     2024  group_label

Madrid_ac           85.58  85.50–85.74
Castile_and_León    84.67  84.50–84.74
Navarre             84.66  84.50–84.74
Basque_Country      84.64  84.50–84.74
Aragon              84.24  84.00–84.24
Catalonia           84.24  84.00–84.24
Galicia             84.09  84.00–84.24
La_Rioja_ac         83.90  83.75–83.99
Cantabria_ac        83.89  83.75–83.99
Castilla-La_Mancha  83.85  83.75–83.99
Balearic_Islands    83.46  83.25–83.49
Valencia_ac         83.40  83.25–83.49
Murcia_ac           83.39  83.25–83.49
Asturias_ac         83.32  83.25–83.49
Extremadura         83.13  83.00–83.24
Andalusia           82.82  82.75–82.99
Canary_Islands      82.79  82.75–82.99
Melilla_ac          82.66  82.50–82.74
Ceuta_ac            81.60  81.50–81.74

In [21]:
def extract_indexes(subdf, dd_legend):
    group_label = subdf['group_label'].iloc[0]
    countries = subdf.index.to_list()
    color = (dd_legend[group_label])
    
    ls_grouping.append(CountryGroup(group_label=group_label, countries=countries, color=color))

    return pd.Series([color, countries], index=['color', 'regions'])


ls_grouping = []
df_grouped = df_sel_year.groupby(['group_label']).apply(extract_indexes, dd_legend = dd_legend_main).loc[::-1]
                        # .rename(index={'78.0–79.99': '<80'})

# if ls_grouping[0].group_label == '78.0–79.99':
#     ls_grouping[0] = ls_grouping[0]._replace(group_label = '<80')

df_grouped

              color                                            regions
group_label
85.50–85.74  007800                                        [Madrid_ac]
84.50–84.74  00b800        [Castile_and_León, Navarre, Basque_Country]
84.00–84.24  00e000                       [Aragon, Catalonia, Galicia]
83.75–83.99  00f000    [La_Rioja_ac, Cantabria_ac, Castilla-La_Mancha]
83.25–83.49  88ff00  [Balearic_Islands, Valencia_ac, Murcia_ac, Ast...
83.00–83.24  b8ff00                                      [Extremadura]
82.75–82.99  deff00                        [Andalusia, Canary_Islands]
82.50–82.74  ffff00                                       [Melilla_ac]
81.50–81.74  ffbc00                                         [Ceuta_ac]

In [22]:
def create_map_code(ls_grouping, title='', legend_color='#000'):  # (ls_grouping, title='', legend_color='#000'):
    false, true = False, True

    jo = {
        "groups": { },
        "title": title,
        "hidden": [],
        "background": "#ffffff",
        "borders": "#000",
        "legendFont": "Century Gothic",
        "legendFontColor": "#000",
        "legendBorderColor": "#00000000",
        "legendBgColor": "#00000000",
        "legendWidth": 100,
        "legendBoxShape": "square",
        "areBordersShown": true,
        "defaultColor": "#d1dbdd",
        "labelsColor": "#6a0707",
        "labelsFont": "Arial",
        "strokeWidth": "medium",
        "areLabelsShown": true,
        "uncoloredScriptColor": "#ffff33",
        "v6": true,
        "page": "spain",
        "levelsVisibility": [
            "show",
            "show",
            "transparent"
        ],
        "legendPosition": "custom",
        "legendX": 150,
        "legendY": 440,
        "legendSize": "large",
        "legendTranslateX": "0.00",
        "legendStatus": "show",
        "scalingPatterns": true,
        "legendRowsSameColor": true,
        "legendColumnCount": 1
    }

    for group_label, color, regions in ls_grouping[::-1]:
        jo["groups"][f"#{color}"] = {"label": group_label.replace('.00', '.0').replace('.25', '¼').replace('.50', '.5').replace('.75', '¾').replace('–', ' - '),
                                     "paths": [region.replace(' ', '_') for region in regions]}       

    return jo


jo = create_map_code(ls_grouping, title=f'{SELECTED_YEAR}', legend_color='#333333')

pretty_jo = json.dumps(jo, indent=2, ensure_ascii=False)

with open(f"output/map_JSON -{SELECTED_YEAR}.txt", 'w', encoding="utf-8") as fh:
    fh.write(pretty_jo)

<br />
<br />

<h4>Statistics for males</h4>

In [24]:
dd_legend_male = {
    '83.00–83.24' : '020f19',
	'82.75–82.99' : '042136',
	'82.50–82.74' : '062f4c',
	'82.25–82.49' : '073a5e',
	'82.00–82.24' : '08436e',
	'81.75–81.99' : '0a4e7f',
	'81.50–81.74' : '0b578d',
	'81.25–81.49' : '0c609c',
	'81.00–81.24' : '0d68a9',
	'80.75–80.99' : '0e71b7',
	'80.50–80.74' : '107ac6',
	'80.25–80.49' : '1182d4',
	'80.00–80.24' : '128be1',
	'79.75–79.99' : '1c95ec',
	'79.50–79.74' : '2e9eee',
	'79.25–79.49' : '40a6ef',
	'79.00–79.24' : '51aef0',
	'78.75–78.99' : '61b5f2',
	'78.50–78.74' : '6ebcf3',
	'78.25–78.49' : '80c4f4',
	'78.00–78.24' : '92ccf6',
	'77.75–77.99' : 'a2d4f7',
	'77.50–77.74' : 'b3dbf8',
	'77.25–77.49' : 'c2e3fa',
	'77.00–77.24' : 'd4ebfb',
	'76.75–76.99' : 'e4f2fc',
	'76.50–76.74' : 'edf7fd',
	'76.25–76.49' : 'f4fafe',
	'76.00–76.24' : 'f8fbfe'
}

if CREATE_LEGEND_CODE:
    fn_create_legend_code(dd_legend_male)

{{Legend|#020f19|83.00–83.24}}
{{Legend|#042136|82.75–82.99}}
{{Legend|#062f4c|82.50–82.74}}
{{Legend|#073a5e|82.25–82.49}}
{{Legend|#08436e|82.00–82.24}}
{{Legend|#0a4e7f|81.75–81.99}}
{{Legend|#0b578d|81.50–81.74}}
{{Legend|#0c609c|81.25–81.49}}
{{Legend|#0d68a9|81.00–81.24}}
{{Legend|#0e71b7|80.75–80.99}}
{{Legend|#107ac6|80.50–80.74}}
{{Legend|#1182d4|80.25–80.49}}
{{Legend|#128be1|80.00–80.24}}
{{Legend|#1c95ec|79.75–79.99}}
{{Legend|#2e9eee|79.50–79.74}}
{{Legend|#40a6ef|79.25–79.49}}
{{Legend|#51aef0|79.00–79.24}}
{{Legend|#61b5f2|78.75–78.99}}
{{Legend|#6ebcf3|78.50–78.74}}
{{Legend|#80c4f4|78.25–78.49}}
{{Legend|#92ccf6|78.00–78.24}}
{{Legend|#a2d4f7|77.75–77.99}}
{{Legend|#b3dbf8|77.50–77.74}}
{{Legend|#c2e3fa|77.25–77.49}}
{{Legend|#d4ebfb|77.00–77.24}}
{{Legend|#e4f2fc|76.75–76.99}}
{{Legend|#edf7fd|76.50–76.74}}
{{Legend|#f4fafe|76.25–76.49}}
{{Legend|#f8fbfe|76.00–76.24}}

In [25]:
df_sel_year = filter_df(df, f"m_{SELECTED_YEAR}")
df_sel_year

           ——— m_2024 ———
Range: 79.63 – 83.07   (Ceuta_ac – Madrid_ac)
Number of groups: 11
Number of values: 19

                    m_2024  group_label

Madrid_ac            83.07  83.00–83.24
Castile_and_León     82.08  82.00–82.24
Navarre              81.96  81.75–81.99
Basque_Country       81.91  81.75–81.99
Aragon               81.71  81.50–81.74
Catalonia            81.64  81.50–81.74
Castilla-La_Mancha   81.43  81.25–81.49
La_Rioja_ac          81.30  81.25–81.49
Galicia              81.23  81.00–81.24
Balearic_Islands     81.06  81.00–81.24
Cantabria_ac         81.01  81.00–81.24
Valencia_ac          80.89  80.75–80.99
Murcia_ac            80.88  80.75–80.99
Canary_Islands       80.54  80.50–80.74
Extremadura          80.36  80.25–80.49
Asturias_ac          80.35  80.25–80.49
Andalusia            80.18  80.00–80.24
Melilla_ac           80.07  80.00–80.24
Ceuta_ac             79.63  79.50–79.74

In [26]:
ls_grouping = []
df_grouped = df_sel_year.groupby(['group_label']).apply(extract_indexes, dd_legend = dd_legend_male).loc[::-1]

In [27]:
if SELECTED_YEAR not in ['2020', '2021', '2022']:
    jo = create_map_code(ls_grouping, title=f'{SELECTED_YEAR}: ♂', legend_color='#333333')  # legend_color='#0000bf'
    
    pretty_jo = json.dumps(jo, indent=2, ensure_ascii=False)
    
    with open(f"output/map_JSON -{SELECTED_YEAR}, male.txt", 'w', encoding="utf-8") as fh:
        fh.write(pretty_jo)

<br />
<br />

<h4>Statistics for females</h4>

In [29]:
dd_legend_female = {
	'88.00–88.24' : '1e0204',
	'87.75–87.99' : '41050a',
	'87.50–87.74' : '60070f',
	'87.25–87.49' : '840a14',
	'87.00–87.24' : 'a30d19',
	'86.75–86.99' : 'bd0f25',
	'86.50–86.74' : 'd81132',
	'86.25–86.49' : 'ec183b',
	'86.00–86.24' : 'ef3b59',
	'85.75–85.99' : 'f1536e',
	'85.50–85.74' : 'f2657d',
	'85.25–85.49' : 'f3768b',
	'85.00–85.24' : 'f58698',
	'84.75–84.99' : 'f696a6',
	'84.50–84.74' : 'f7a5b2',
	'84.25–84.49' : 'f8b3be',
	'84.00–84.24' : 'f9bfc6',
	'83.75–83.99' : 'facdd3',
	'83.50–83.74' : 'fbd8db',
	'83.25–83.49' : 'fce2e4',
	'83.00–83.24' : 'fdebed',
	'82.75–82.99' : 'fef3f4',
	'82.50–82.74' : 'fef8f9',
	'82.25–82.49' : 'fefafa'
}

if CREATE_LEGEND_CODE:
    fn_create_legend_code(dd_legend_female)

{{Legend|#1e0204|88.00–88.24}}
{{Legend|#41050a|87.75–87.99}}
{{Legend|#60070f|87.50–87.74}}
{{Legend|#840a14|87.25–87.49}}
{{Legend|#a30d19|87.00–87.24}}
{{Legend|#bd0f25|86.75–86.99}}
{{Legend|#d81132|86.50–86.74}}
{{Legend|#ec183b|86.25–86.49}}
{{Legend|#ef3b59|86.00–86.24}}
{{Legend|#f1536e|85.75–85.99}}
{{Legend|#f2657d|85.50–85.74}}
{{Legend|#f3768b|85.25–85.49}}
{{Legend|#f58698|85.00–85.24}}
{{Legend|#f696a6|84.75–84.99}}
{{Legend|#f7a5b2|84.50–84.74}}
{{Legend|#f8b3be|84.25–84.49}}
{{Legend|#f9bfc6|84.00–84.24}}
{{Legend|#facdd3|83.75–83.99}}
{{Legend|#fbd8db|83.50–83.74}}
{{Legend|#fce2e4|83.25–83.49}}
{{Legend|#fdebed|83.00–83.24}}
{{Legend|#fef3f4|82.75–82.99}}
{{Legend|#fef8f9|82.50–82.74}}
{{Legend|#fefafa|82.25–82.49}}

In [30]:
df_sel_year = filter_df(df, f"f_{SELECTED_YEAR}")
df_sel_year

           ——— f_2024 ———
Range: 83.51 – 87.74   (Ceuta_ac – Madrid_ac)
Number of groups: 12
Number of values: 19

                    f_2024  group_label

Madrid_ac            87.74  87.50–87.74
Navarre              87.33  87.25–87.49
Castile_and_León     87.28  87.25–87.49
Basque_Country       87.20  87.00–87.24
Galicia              86.86  86.75–86.99
Aragon               86.72  86.50–86.74
Catalonia            86.69  86.50–86.74
Cantabria_ac         86.62  86.50–86.74
La_Rioja_ac          86.51  86.50–86.74
Castilla-La_Mancha   86.33  86.25–86.49
Asturias_ac          86.14  86.00–86.24
Extremadura          85.99  85.75–85.99
Murcia_ac            85.87  85.75–85.99
Valencia_ac          85.84  85.75–85.99
Balearic_Islands     85.81  85.75–85.99
Andalusia            85.42  85.25–85.49
Melilla_ac           85.20  85.00–85.24
Canary_Islands       84.99  84.75–84.99
Ceuta_ac             83.51  83.50–83.74

In [31]:
ls_grouping = []
df_grouped = df_sel_year.groupby(['group_label']).apply(extract_indexes, dd_legend = dd_legend_female).loc[::-1]

In [32]:
if SELECTED_YEAR not in ['2020', '2021', '2022']:
    jo = create_map_code(ls_grouping, title=f'{SELECTED_YEAR}: ♀', legend_color='#333333')  # legend_color='#c20000'
    
    pretty_jo = json.dumps(jo, indent=2, ensure_ascii=False)
    
    with open(f"output/map_JSON -{SELECTED_YEAR}, female.txt", 'w', encoding="utf-8") as fh:
        fh.write(pretty_jo)