WHO > [The Global Health Observatory: Explore a world of health data](https://www.who.int/data/gho/data/themes/topics/indicator-groups/indicator-group-details/GHO/life-expectancy-and-healthy-life-expectancy)<br />
WHO > [Life expectancy at birth](https://www.who.int/data/gho/data/indicators/indicator-details/GHO/life-expectancy-at-birth-(years))<br />
WHO > [Healthy life expectancy (HALE) at birth](https://www.who.int/data/gho/data/indicators/indicator-details/GHO/gho-ghe-hale-healthy-life-expectancy-at-birth)<br />

Lists of countries by life expectancy: [world](https://en.wikipedia.org/wiki/List_of_countries_by_life_expectancy) <i>([template](https://en.wikipedia.org/wiki/Template:List_of_countries_by_life_expectancy/World_Health_Organization))</i>, [Europe](https://en.wikipedia.org/wiki/List_of_European_countries_by_life_expectancy), [Asia](https://en.wikipedia.org/wiki/List_of_Asian_countries_by_life_expectancy), [North America](https://en.wikipedia.org/wiki/List_of_North_American_countries_by_life_expectancy), [South America](https://en.wikipedia.org/wiki/List_of_South_American_countries_by_life_expectancy), [Americas (combined)](https://en.wikipedia.org/wiki/List_of_countries_in_the_Americas_by_life_expectancy), [Africa](https://en.wikipedia.org/wiki/List_of_African_countries_by_life_expectancy), [regions](https://en.wikipedia.org/wiki/List_of_world_regions_by_life_expectancy), [EU](https://en.wikipedia.org/wiki/Demographics_of_the_European_Union#Life_expectancy)<br />
[my private wiki-page for exploration](https://en.wikipedia.org/wiki/User:Lady3mlnm/HALE)<br>
Списки стран по ожидаемой продолжительности жизни: [мир в целом](https://ru.wikipedia.org/wiki/Список_стран_по_ожидаемой_продолжительности_жизни), [Европа](https://ru.wikipedia.org/wiki/Список_стран_Европы_по_ожидаемой_продолжительности_жизни), [Азия](https://ru.wikipedia.org/wiki/Список_стран_Азии_по_ожидаемой_продолжительности_жизни), [Северная Америка](https://ru.wikipedia.org/wiki/Список_стран_Южной_Америки_по_ожидаемой_продолжительности_жизни), [Северная Америка](https://ru.wikipedia.org/wiki/Список_стран_Южной_Америки_по_ожидаемой_продолжительности_жизни),  [Африка](https://ru.wikipedia.org/wiki/Список_стран_Африки_по_ожидаемой_продолжительности_жизни), [регионы](https://ru.wikipedia.org/wiki/Список_регионов_мира_по_ожидаемой_продолжительности_жизни), [ЕС](https://ru.wikipedia.org/wiki/Население_стран_Европейского_союза#Продолжительность_жизни), [СНГ](https://ru.wikipedia.org/wiki/Содружество_Независимых_Государств#Социальное_развитие_стран_СНГ)<br />
[Список государств и зависимых территорий по населению](https://ru.wikipedia.org/wiki/Список_государств_и_зависимых_территорий_по_населению)

In [2]:
import pandas as pd
import math
import re

In [3]:
pd.options.display.max_rows = 100
pd.options.display.min_rows = 6
pd.options.display.max_columns = 50
pd.options.display.float_format = '{:.2f}'.format

DESTINATION_OUTPUT = 'file'  # to where table code should be placed: 'file', 'write_here' or, otherwise, just print 'Done'
YEAR_SELECTED = 2019

In [4]:
# list of countries that should be ignored during processing (it is needed when WBG made correction for only some countries.
# So processing of countries without correction is redundant.
LS_IGNORE = \
    ['occupied Palestinian territory']

LS_COUNTRIES_EXAMPLES = ['Russia', 'USA', 'France', 'Spain', 'Japan', 'Switzerland', 'South Korea', 'World']

In [5]:
LS_WHO_REGIONS = ['Africa', 'Americas', 'Eastern Mediterranean', 'Europe', 'South-East Asia', 'Western Pacific']
LS_INCOME_GROUPS = ['High-income', 'Upper-middle-income', 'Lower-middle-income', 'Low-income']

In [6]:
def output_table_code(st, file_name='', destination=''):
    if not destination:
        destination = DESTINATION_OUTPUT
        
    if destination == 'file':
        with open('output-tables/'+file_name, 'w', encoding="utf-8") as fh:
            fh.write(st)
        print('Data has written to file')
    elif destination == 'write_here':
        print(st)
    else:
        print('done')

In [7]:
dd_countries_renaming = {
	'Bolivia (Plurinational State of)': 'Bolivia',
	'Brunei Darussalam': 'Brunei',
	'Cabo Verde': 'Cape Verde',
	"Democratic People's Republic of Korea": 'North Korea',
	'Democratic Republic of the Congo': 'Congo DR',
    'Congo': 'Congo Republic',
	'Iran (Islamic Republic of)': 'Iran',
	"Lao People's Democratic Republic": 'Laos',
	'Micronesia (Federated States of)': 'Micronesia',
	'Netherlands (Kingdom of the)': 'Netherlands',
	'Republic of Korea': 'South Korea',
	'Republic of Moldova': 'Moldova',
	'Russian Federation': 'Russia',
	'Syrian Arab Republic': 'Syria',
    'Türkiye': 'Turkey',
	'United Kingdom of Great Britain and Northern Ireland': 'United Kingdom',
	'United Republic of Tanzania': 'Tanzania',
	'United States of America': 'USA',
	'Venezuela (Bolivarian Republic of)': 'Venezuela',
    'Viet Nam': 'Vietnam',
    'Saint Vincent and the Grenadines': 'St. Vincent and the Grenadines',
	'occupied Palestinian territory, including east Jerusalem': 'occupied Palestinian territory',
    'Global': 'World'
}

In [8]:
def load_data_from_csv(file_name_core, selected_indicator, selected_years, prefix_for_cols):

    def load_single_csv(file_name):
        return pd.read_csv(f"data/{file_name}", usecols=['Indicator', 'Location', 'Period', 'Dim1', 'FactValueNumeric'])

    def get_pretty_df_for_sex(df, selected_sex, prefix_for_cols_with_sex):
        df_sex = df[df.sex == selected_sex] \
                   .drop(columns='sex') \
                   .pivot(index='country', columns='year', values='value')
        df_sex.columns = [f'{prefix_for_cols_with_sex}_{df_sex.columns[0]}', f'{prefix_for_cols_with_sex}']
        df_sex.index.name = ''
        return df_sex


    df = pd.concat([load_single_csv(f"{file_name_core} -countries.csv"),
                    load_single_csv(f"{file_name_core} -global.csv"),
                    load_single_csv(f"{file_name_core} -regions.csv"),
                    load_single_csv(f"{file_name_core} -income_groups.csv")])
    
    
    df.rename(columns={'Location': 'country',
                       'Period': 'year',
                       'Dim1': 'sex',
                       'FactValueNumeric': 'value'}, inplace=True)
    
    df = df[(df.Indicator == selected_indicator) & (df.year.isin(selected_years))] \
              .drop(columns='Indicator')
            
    df['country'] = df['country'].replace(dd_countries_renaming)
    
    return pd.concat([get_pretty_df_for_sex(df, 'Both sexes', f'{prefix_for_cols}_o'),
                      get_pretty_df_for_sex(df, 'Male', f'{prefix_for_cols}_m'),
                      get_pretty_df_for_sex(df, 'Female', f'{prefix_for_cols}_f')],
                          axis='columns')



df_le_birth = load_data_from_csv(file_name_core="Life expectancy at birth",
                                 selected_indicator="Life expectancy at birth (years)",
                                 selected_years=[2000, 2019], prefix_for_cols='LE_birth')
df_le_birth.loc[LS_COUNTRIES_EXAMPLES].sort_values(by='LE_birth_o', ascending=False)

,LE_birth_o_2000,LE_birth_o,LE_birth_m_2000,LE_birth_m,LE_birth_f_2000,LE_birth_f
,,,,,,
Japan,81.53,84.47,78.08,81.70,84.80,87.15
South Korea,75.86,83.69,72.24,80.56,79.35,86.56
Switzerland,79.71,83.48,76.90,81.76,82.34,85.12
Spain,79.09,83.14,75.69,80.54,82.48,85.66
France,78.91,82.53,75.24,79.77,82.52,85.15
USA,76.66,78.74,74.16,76.53,79.06,80.98
Russia,65.16,73.22,58.83,68.17,72.14,78.00
World,66.77,73.12,64.39,70.61,69.22,75.70

In [9]:
df_le_60 = load_data_from_csv(file_name_core="Life expectancy at birth",
                              selected_indicator="Life expectancy at age 60 (years)",
                              selected_years=[2000, 2019], prefix_for_cols='LE_60')
df_le_60.loc[LS_COUNTRIES_EXAMPLES].sort_values(by='LE_60_o', ascending=False)

,LE_60_o_2000,LE_60_o,LE_60_m_2000,LE_60_m,LE_60_f_2000,LE_60_f
,,,,,,
Japan,24.63,26.66,21.82,24.28,27.06,28.86
South Korea,20.33,26.13,17.90,23.55,22.23,28.30
France,23.01,25.69,20.39,23.63,25.29,27.51
Switzerland,22.99,25.45,20.84,24.09,24.80,26.68
Spain,22.70,25.39,20.34,23.28,24.82,27.33
USA,21.34,23.24,19.80,21.99,22.65,24.41
World,18.87,21.03,17.23,19.41,20.36,22.54
Russia,16.39,19.93,13.29,16.80,18.71,22.19

In [10]:
df_hale_birth = load_data_from_csv(file_name_core="Healthy life expectancy (HALE) at birth",
                                   selected_indicator="Healthy life expectancy (HALE) at birth (years)",
                                   selected_years=[2000, 2019], prefix_for_cols='HALE_birth')
df_hale_birth.loc[LS_COUNTRIES_EXAMPLES].sort_values(by='HALE_birth_o', ascending=False)

,HALE_birth_o_2000,HALE_birth_o,HALE_birth_m_2000,HALE_birth_m,HALE_birth_f_2000,HALE_birth_f
,,,,,,
Japan,71.11,73.58,68.96,72.09,73.11,75.01
South Korea,66.55,72.50,64.04,70.62,68.96,74.19
Spain,68.89,71.69,67.05,70.90,70.70,72.42
Switzerland,68.35,71.53,67.04,71.33,69.54,71.67
France,67.98,70.72,66.21,69.78,69.70,71.60
USA,65.32,66.02,64.19,65.13,66.38,66.93
Russia,56.71,63.72,51.90,60.41,62.01,66.84
World,58.12,63.45,56.96,62.33,59.32,64.59

In [11]:
df_hale_60 = load_data_from_csv(file_name_core="Healthy life expectancy (HALE) at birth",
                                selected_indicator="Healthy life expectancy (HALE) at age 60 (years)",
                                selected_years=[2000, 2019], prefix_for_cols='HALE_60')
df_hale_60.loc[LS_COUNTRIES_EXAMPLES].sort_values(by='HALE_60_o', ascending=False)

,HALE_60_o_2000,HALE_60_o,HALE_60_m_2000,HALE_60_m,HALE_60_f_2000,HALE_60_f
,,,,,,
Japan,18.85,20.42,16.78,18.79,20.65,21.95
South Korea,15.53,19.66,13.72,17.88,16.96,21.16
France,17.37,19.26,15.69,18.07,18.83,20.33
Spain,17.40,19.18,15.83,17.94,18.82,20.33
Switzerland,17.38,19.12,16.03,18.46,18.52,19.73
USA,15.67,16.59,14.70,15.82,16.50,17.31
World,14.28,15.80,13.27,14.87,15.20,16.67
Russia,12.28,14.92,9.99,12.75,13.99,16.49

In [12]:
df = pd.concat([df_le_birth['LE_birth_o'],
                df_le_birth['LE_birth_m'],
                df_le_birth['LE_birth_f'],
                (df_le_birth['LE_birth_f'] - df_le_birth['LE_birth_m']).round(2),
                (df_le_birth['LE_birth_o'] - df_le_birth['LE_birth_o_2000']).round(2),

                df_hale_birth['HALE_birth_o'],
                df_hale_birth['HALE_birth_m'],
                df_hale_birth['HALE_birth_f'],
                (df_hale_birth['HALE_birth_f'] - df_hale_birth['HALE_birth_m']).round(2),
                (df_hale_birth['HALE_birth_o'] - df_hale_birth['HALE_birth_o_2000']).round(2),

                100 * df_hale_birth['HALE_birth_o_2000'] / df_le_birth['LE_birth_o_2000'],
                100 * df_hale_birth['HALE_birth_o'] / df_le_birth['LE_birth_o'],

                df_le_60['LE_60_o'],
                df_le_60['LE_60_m'],
                df_le_60['LE_60_f'],
                (df_le_60['LE_60_f'] - df_le_60['LE_60_m']).round(2),
                (df_le_60['LE_60_o'] - df_le_60['LE_60_o_2000']).round(2),

                df_hale_60['HALE_60_o'],
                df_hale_60['HALE_60_m'],
                df_hale_60['HALE_60_f'],
                (df_hale_60['HALE_60_f'] - df_hale_60['HALE_60_m']).round(2),
                (df_hale_60['HALE_60_o'] - df_hale_60['HALE_60_o_2000']).round(2),

                100 * df_hale_60['HALE_60_o_2000'] / df_le_60['LE_60_o_2000'],
                100 * df_hale_60['HALE_60_o'] / df_le_60['LE_60_o'],
               ], axis='columns') \
                   .rename(columns = {0 : 'LE_birth_fΔm',
                                      1 : 'LE_birth_Δ_2000',
                                      2 : 'HALE_birth_fΔm',
                                      3 : 'HALE_birth_Δ_2000',
                                      4 : 'ratio_birth_2000',
                                      5 : 'ratio_birth',
                                      6 : 'LE_60_fΔm',
                                      7 : 'LE_60_Δ_2000',
                                      8 : 'HALE_60_fΔm',
                                      9 : 'HALE_60_Δ_2000',
                                      10: 'ratio_60_2000',
                                      11: 'ratio_60',
                                     }) \
                   .sort_values(by=['LE_birth_o', 'HALE_birth_o'], ascending=False)

df.insert(loc=11, value=df['ratio_birth']-df['ratio_birth_2000'], column='ratio_birth_Δ')
df.insert(loc=24, value=df['ratio_60']-df['ratio_60_2000'], column='ratio_60_Δ')

df.loc[LS_COUNTRIES_EXAMPLES].sort_values(by=['LE_birth_o', 'HALE_birth_o'], ascending=False)

,LE_birth_o,LE_birth_m,LE_birth_f,LE_birth_fΔm,LE_birth_Δ_2000,HALE_birth_o,HALE_birth_m,HALE_birth_f,HALE_birth_fΔm,HALE_birth_Δ_2000,ratio_birth_2000,ratio_birth_Δ,ratio_birth,LE_60_o,LE_60_m,LE_60_f,LE_60_fΔm,LE_60_Δ_2000,HALE_60_o,HALE_60_m,HALE_60_f,HALE_60_fΔm,HALE_60_Δ_2000,ratio_60_2000,ratio_60_Δ,ratio_60
,,,,,,,,,,,,,,,,,,,,,,,,,,
Japan,84.47,81.70,87.15,5.45,2.94,73.58,72.09,75.01,2.92,2.47,87.22,-0.11,87.11,26.66,24.28,28.86,4.58,2.03,20.42,18.79,21.95,3.16,1.57,76.53,0.06,76.59
South Korea,83.69,80.56,86.56,6.00,7.83,72.50,70.62,74.19,3.57,5.95,87.73,-1.10,86.63,26.13,23.55,28.30,4.75,5.80,19.66,17.88,21.16,3.28,4.13,76.39,-1.15,75.24
Switzerland,83.48,81.76,85.12,3.36,3.77,71.53,71.33,71.67,0.34,3.18,85.75,-0.06,85.69,25.45,24.09,26.68,2.59,2.46,19.12,18.46,19.73,1.27,1.74,75.60,-0.47,75.13
Spain,83.14,80.54,85.66,5.12,4.05,71.69,70.90,72.42,1.52,2.80,87.10,-0.88,86.23,25.39,23.28,27.33,4.05,2.69,19.18,17.94,20.33,2.39,1.78,76.65,-1.11,75.54
France,82.53,79.77,85.15,5.38,3.62,70.72,69.78,71.60,1.82,2.74,86.15,-0.46,85.69,25.69,23.63,27.51,3.88,2.68,19.26,18.07,20.33,2.26,1.89,75.49,-0.52,74.97
USA,78.74,76.53,80.98,4.45,2.08,66.02,65.13,66.93,1.80,0.70,85.21,-1.36,83.85,23.24,21.99,24.41,2.42,1.90,16.59,15.82,17.31,1.49,0.92,73.43,-2.04,71.39
Russia,73.22,68.17,78.00,9.83,8.06,63.72,60.41,66.84,6.43,7.01,87.03,-0.01,87.03,19.93,16.80,22.19,5.39,3.54,14.92,12.75,16.49,3.74,2.64,74.92,-0.06,74.86
World,73.12,70.61,75.70,5.09,6.35,63.45,62.33,64.59,2.26,5.33,87.05,-0.27,86.78,21.03,19.41,22.54,3.13,2.16,15.80,14.87,16.67,1.80,1.52,75.68,-0.54,75.13

<br>
<br>

In [14]:
# create code for placing info about countries in Wikipedia (for countries)
def create_table_countries(df, lang='en', file_header=None):

    def if_value(x, prec=2):
        return '—' if math.isnan(x) else \
               f"{x:0.{prec}f}"  if x>=0 else \
               f"−{-x:0.{prec}f}"

    if lang=='ru':
        file_header = file_header if file_header else 'who_stats_header_countries_ru.txt'
        ptn_1 = 'флагификация'
        ptn_2 = 'флаг'
        prettify_name = {
            "World": "\'\'\'Мир\'\'\'",
            "Europe": "\'\'\'Европа\'\'\'<ref>{{cite web|title=ВОЗ: Европа |publisher=Всемирная организация здравоохранения |url=https://www.who.int/europe/ru/ |access-date=2025-10-12}}</ref>",
            "Eastern Mediterranean": "\'\'\'Восточное Средиземноморье\'\'\'<ref>{{cite web|title=WHO: Eastern Mediterranean: Countries |lang=en |publisher=Всемирная организация здравоохранения |url=http://www.emro.who.int/countries.html |access-date=2025-10-12}}</ref>",
            "South-East Asia": "\'\'\'[[Юго-Восточная Азия]]\'\'\'<ref>{{cite web|title=WHO: South-East Asia: Where we work |lang=en |publisher=Всемирная организация здравоохранения |url=https://www.who.int/southeastasia/about/where-we-work |access-date=2025-10-12}}</ref>",
            "Western Pacific": "\'\'\'Западно-тихоокеанский регион\'\'\'<ref>{{cite web|title=WHO: Western Pacific: Where we work |lang=en |publisher=Всемирная организация здравоохранения |url=https://www.who.int/westernpacific/about/where-we-work |access-date=2025-10-12}}</ref>",
            "Americas": "\'\'\'[[Америка]]\'\'\'<ref>{{cite web|title=WHO: PAHO: Countries and Centers |lang=en |publisher=Всемирная организация здравоохранения |url=https://www.paho.org/en/countries-and-centers |access-date=2025-10-12}}</ref>",
            "Africa": "\'\'\'Африка\'\'\'<ref>{{cite web|title=WHO: Africa: Countries |lang=en |publisher=Всемирная организация здравоохранения |url=https://www.afro.who.int/countries |access-date=2025-10-12}}</ref>", 
        }
    else:
        file_header = file_header if file_header else 'who_stats_header_countries_en.txt'
        ptn_1 = 'flaglist'
        ptn_2 = 'flagicon'
        prettify_name = {
            "World": "\'\'\'World\'\'\'",
            "Europe": "\'\'\'Europe\'\'\'<ref>{{cite web|title=WHO: Europe |publisher=World Health Organization |url=https://www.who.int/europe |access-date=12 November 2025}}</ref>",
            "Eastern Mediterranean": "\'\'\'[[Eastern Mediterranean]]\'\'\'<ref>{{cite web|title=WHO: Eastern Mediterranean: Countries |publisher=World Health Organization |url=http://www.emro.who.int/countries.html |access-date=12 November 2025}}</ref>",
            "South-East Asia": "\'\'\'[[South-East Asia]]\'\'\'<ref>{{cite web|title=WHO: South-East Asia: Where we work |language=en |publisher=World Health Organization |url=https://www.who.int/southeastasia/about/where-we-work |access-date=12 November 2025}}</ref>",
            "Western Pacific": "\'\'\'Western Pacific\'\'\'<ref>{{cite web|title=WHO: Western Pacific: Where we work |publisher=World Health Organization |url=https://www.who.int/westernpacific/about/where-we-work |access-date=12 November 2025}}</ref>",
            "Americas": "\'\'\'[[Americas]]\'\'\'<ref>{{cite web|title=WHO: PAHO: Countries and Centers |publisher=World Health Organization |url=https://www.paho.org/en/countries-and-centers |access-date=12 November 2025}}</ref>",
            "Africa": "\'\'\'Africa\'\'\'<ref>{{cite web|title=WHO: Africa: Countries |language=en |publisher=World Health Organization |url=https://www.afro.who.int/countries |access-date=12 November 2025}}</ref>",
        }
            

    with open('design/' + file_header, mode='r', encoding="utf-8") as fh:
        st_header = fh.read()
        
    st_header = st_header.strip()
    st = ''
        
    for i in range(len(df)):
        ser = df.iloc[i]
        
        comp_LE_birth = ser.LE_birth_Δ_2000
        comp_HALE_birth = ser.HALE_birth_Δ_2000
        comp_LE_60 = ser.LE_60_Δ_2000
        comp_HALE_60 = ser.HALE_60_Δ_2000
        
        if ser.name in ['World', 'Europe', 'Eastern Mediterranean', 'South-East Asia', 'Western Pacific', 'Americas', 'Africa']:
            st += '\n' + '|-class=static-row-header\n' + \
                  f'|style="text-align:center"| {prettify_name.get(ser.name, ser.name)} ' + \
                  f'||style="background:#e0ffd8;"| \'\'\'{ser.LE_birth_o:0.2f}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| \'\'\'{ser.LE_birth_m:0.2f}\'\'\' ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{ser.LE_birth_f:0.2f}\'\'\' ' + \
                  f'|| \'\'\'{if_value(ser.LE_birth_fΔm, 2)}\'\'\' ' + \
                  f'||style="background:#fff8dc;"| \'\'\'{if_value(comp_LE_birth, 2)}\'\'\' ' + \
                  f'||style="background:#e0ffd8; border-left-width:2px;"| \'\'\'{ser.HALE_birth_o:0.2f}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| \'\'\'{ser.HALE_birth_m:0.2f}\'\'\' ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{ser.HALE_birth_f:0.2f}\'\'\' ' + \
                  f'|| \'\'\'{if_value(ser.HALE_birth_fΔm, 2)}\'\'\' ' + \
                  f'||style="background:#fff8dc;"| \'\'\'{if_value(comp_HALE_birth, 2)}\'\'\' ' + \
                  f'||style="background:#e0ffd8; border-left-width:3px;"| \'\'\'{ser.LE_60_o:0.2f}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| \'\'\'{ser.LE_60_m:0.2f}\'\'\' ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{ser.LE_60_f:0.2f}\'\'\' ' + \
                  f'|| \'\'\'{if_value(ser.LE_60_fΔm, 2)}\'\'\' ' + \
                  f'||style="background:#fff8dc;"| \'\'\'{if_value(comp_LE_60, 2)}\'\'\' ' + \
                  f'||style="background:#e0ffd8; border-left-width:2px;"| \'\'\'{ser.HALE_60_o:0.2f}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| \'\'\'{ser.HALE_60_m:0.2f}\'\'\' ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{ser.HALE_60_f:0.2f}\'\'\' ' + \
                  f'|| \'\'\'{if_value(ser.HALE_60_fΔm, 2)}\'\'\' ' + \
                  f'||style="background:#fff8dc;"| \'\'\'{if_value(comp_HALE_60, 2)}\'\'\' ' + \
                  f'||'
        else:
            st += '\n' + '|-\n' + \
                  f'| {{{{{ptn_1}|{ser.name}}}}} ' + \
                  f'||style="background:#e0ffd8;"| {ser.LE_birth_o:0.2f} ' + \
                  f'||style="background:#eaf3ff;"| {ser.LE_birth_m:0.2f} ' + \
                  f'||style="background:#fee7f6;"| {ser.LE_birth_f:0.2f} ' + \
                  f'|| {if_value(ser.LE_birth_fΔm, 2)} ' + \
                  f'||style="background:#fff8dc;| {if_value(comp_LE_birth, 2)} ' + \
                  f'||style="background:#e0ffd8;border-left-width:2px;"| {ser.HALE_birth_o:0.2f} ' + \
                  f'||style="background:#eaf3ff;"| {ser.HALE_birth_m:0.2f} ' + \
                  f'||style="background:#fee7f6;"| {ser.HALE_birth_f:0.2f} ' + \
                  f'|| {if_value(ser.HALE_birth_fΔm, 2)} ' + \
                  f'||style="background:#fff8dc;| {if_value(comp_HALE_birth, 2)} ' + \
                  f'||style="background:#e0ffd8;border-left-width:3px;"| {ser.LE_60_o:0.2f} ' + \
                  f'||style="background:#eaf3ff;"| {ser.LE_60_m:0.2f} ' + \
                  f'||style="background:#fee7f6;"| {ser.LE_60_f:0.2f} ' + \
                  f'|| {if_value(ser.LE_60_fΔm, 2)} ' + \
                  f'||style="background:#fff8dc;| {if_value(comp_LE_60, 2)} ' + \
                  f'||style="background:#e0ffd8;border-left-width:2px;"| {ser.HALE_60_o:0.2f} ' + \
                  f'||style="background:#eaf3ff;"| {ser.HALE_60_m:0.2f} ' + \
                  f'||style="background:#fee7f6;"| {ser.HALE_60_f:0.2f} ' + \
                  f'|| {if_value(ser.HALE_60_fΔm, 2)} ' + \
                  f'||style="background:#fff8dc;| {if_value(comp_HALE_60, 2)} ' + \
                  f'|| {{{{{ptn_2}|{ser.name}}}}}'
    st += '\n|}'
    
    # WARNING: be sure that inline styles do not contains numbers with comma
    if lang == 'ru':
        st = re.sub('(?<=\\d)\\.(?=\\d)', ',', st)  # replace . to comma, if this . is between two digits
        
    st = st_header + st

    return st

In [15]:
df_all_countries = df.drop(LS_WHO_REGIONS + LS_INCOME_GROUPS + LS_IGNORE)

print("Number of records for all countries:", len(df_all_countries))

df_all_countries

Number of records for all countries: 185

,LE_birth_o,LE_birth_m,LE_birth_f,LE_birth_fΔm,LE_birth_Δ_2000,HALE_birth_o,HALE_birth_m,HALE_birth_f,HALE_birth_fΔm,HALE_birth_Δ_2000,ratio_birth_2000,ratio_birth_Δ,ratio_birth,LE_60_o,LE_60_m,LE_60_f,LE_60_fΔm,LE_60_Δ_2000,HALE_60_o,HALE_60_m,HALE_60_f,HALE_60_fΔm,HALE_60_Δ_2000,ratio_60_2000,ratio_60_Δ,ratio_60
,,,,,,,,,,,,,,,,,,,,,,,,,,
Japan,84.47,81.70,87.15,5.45,2.94,73.58,72.09,75.01,2.92,2.47,87.22,-0.11,87.11,26.66,24.28,28.86,4.58,2.03,20.42,18.79,21.95,3.16,1.57,76.53,0.06,76.59
Singapore,83.90,81.81,85.98,4.17,5.38,73.80,72.66,74.89,2.23,4.39,88.40,-0.44,87.96,25.83,24.05,27.51,3.46,4.35,20.21,18.98,21.38,2.40,3.41,78.21,0.03,78.24
South Korea,83.69,80.56,86.56,6.00,7.83,72.50,70.62,74.19,3.57,5.95,87.73,-1.10,86.63,26.13,23.55,28.30,4.75,5.80,19.66,17.88,21.16,3.28,4.13,76.39,-1.15,75.24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Somalia,55.21,52.87,57.75,4.88,5.93,48.65,47.28,50.14,2.86,5.24,88.09,0.03,88.12,13.52,12.42,14.59,2.17,1.17,10.41,9.72,11.08,1.36,0.88,77.17,-0.17,77.00
Central African Republic,52.93,50.31,55.89,5.58,8.70,45.97,44.41,47.75,3.34,7.67,86.59,0.26,86.85,12.61,11.19,14.27,3.08,1.48,9.42,8.44,10.56,2.12,1.15,74.30,0.40,74.70
Lesotho,51.78,48.96,54.91,5.95,4.40,45.04,43.39,46.88,3.49,3.22,88.27,-1.28,86.98,12.71,10.80,14.33,3.53,-0.41,9.52,8.24,10.59,2.35,-0.61,77.21,-2.31,74.90

In [16]:
table_code_all = create_table_countries(df_all_countries, lang='en', file_header='who_stats_header_countries_en_inFrame.txt')
output_table_code(table_code_all, 'Table code WHO -all_countries -en.txt', destination=DESTINATION_OUTPUT)

Data has written to file

In [17]:
table_code_all = create_table_countries(df_all_countries, lang='ru')
output_table_code(table_code_all, 'Table code WHO -all_countries -ru.txt', destination=DESTINATION_OUTPUT)

Data has written to file

<br />
<br />

In [19]:
ls_Europe = ['Albania', 'Armenia', 'Austria', 'Azerbaijan', 'Belarus', 'Belgium', 'Bosnia and Herzegovina', 'Bulgaria', 'Croatia',
             'Cyprus', 'Czechia', 'Denmark', 'Estonia', 'Finland', 'France', 'Georgia', 'Germany', 'Greece', 'Hungary', 'Iceland',
             'Ireland', 'Italy', 'Kazakhstan', 'Latvia', 'Lithuania', 'Luxembourg', 'Malta', 'Moldova', 'Montenegro', 'Netherlands',
             'North Macedonia', 'Norway', 'Poland', 'Portugal', 'Romania', 'Russia', 'Serbia', 'Slovakia', 'Slovenia', 'Spain',
             'Sweden', 'Switzerland', 'Turkey', 'Ukraine', 'United Kingdom',
             'World', 'Europe']

# small countries: Andorra, Liechtenstein, Monaco, San Marino, Vatican City
# main countries: France, Germany, Italy, Russia, Spain, United Kingdom

print("Number of records for Europe:", len(ls_Europe))

df_Europe = df.loc[ls_Europe]   \
              .sort_values(by=['LE_birth_o', 'HALE_birth_o', 'LE_60_o', 'HALE_60_o'], ascending=False)
df_Europe

Number of records for Europe: 47

,LE_birth_o,LE_birth_m,LE_birth_f,LE_birth_fΔm,LE_birth_Δ_2000,HALE_birth_o,HALE_birth_m,HALE_birth_f,HALE_birth_fΔm,HALE_birth_Δ_2000,ratio_birth_2000,ratio_birth_Δ,ratio_birth,LE_60_o,LE_60_m,LE_60_f,LE_60_fΔm,LE_60_Δ_2000,HALE_60_o,HALE_60_m,HALE_60_f,HALE_60_fΔm,HALE_60_Δ_2000,ratio_60_2000,ratio_60_Δ,ratio_60
,,,,,,,,,,,,,,,,,,,,,,,,,,
Switzerland,83.48,81.76,85.12,3.36,3.77,71.53,71.33,71.67,0.34,3.18,85.75,-0.06,85.69,25.45,24.09,26.68,2.59,2.46,19.12,18.46,19.73,1.27,1.74,75.60,-0.47,75.13
Spain,83.14,80.54,85.66,5.12,4.05,71.69,70.90,72.42,1.52,2.80,87.10,-0.88,86.23,25.39,23.28,27.33,4.05,2.69,19.18,17.94,20.33,2.39,1.78,76.65,-1.11,75.54
Italy,82.99,80.94,84.91,3.97,3.62,71.43,70.85,71.92,1.07,3.04,86.17,-0.10,86.07,25.14,23.53,26.56,3.03,2.60,18.95,18.03,19.78,1.75,1.94,75.47,-0.09,75.38
Luxembourg,82.80,80.83,84.74,3.91,4.38,71.46,70.98,71.89,0.91,3.61,86.52,-0.22,86.30,24.73,23.13,26.22,3.09,2.85,18.83,17.97,19.64,1.67,2.10,76.46,-0.32,76.14
Sweden,82.71,81.17,84.24,3.07,3.14,71.41,71.33,71.46,0.13,2.15,87.04,-0.71,86.34,24.78,23.57,25.91,2.34,2.36,18.80,18.26,19.32,1.06,1.57,76.85,-0.98,75.87
Norway,82.66,81.12,84.16,3.04,4.12,71.18,71.04,71.28,0.24,3.35,86.36,-0.25,86.11,24.72,23.57,25.78,2.21,2.75,18.66,18.09,19.20,1.11,2.02,75.74,-0.25,75.49
France,82.53,79.77,85.15,5.38,3.62,70.72,69.78,71.60,1.82,2.74,86.15,-0.46,85.69,25.69,23.63,27.51,3.88,2.68,19.26,18.07,20.33,2.26,1.89,75.49,-0.52,74.97
Iceland,82.47,81.10,83.90,2.80,2.78,71.39,71.30,71.46,0.16,2.25,86.76,-0.20,86.56,24.82,23.96,25.67,1.71,2.20,19.07,18.68,19.45,0.77,1.70,76.79,0.04,76.83
Netherlands,82.34,80.85,83.76,2.91,4.33,71.08,71.05,71.07,0.02,2.98,87.30,-0.97,86.32,24.65,23.43,25.76,2.33,3.33,18.64,18.07,19.16,1.09,2.16,77.30,-1.68,75.62
Cyprus,82.18,80.20,84.16,3.96,3.35,71.13,70.69,71.55,0.86,2.66,86.86,-0.30,86.55,24.36,22.91,25.77,2.86,2.53,18.56,17.79,19.31,1.52,1.93,76.18,0.01,76.19
Malta,82.15,80.31,83.98,3.67,4.33,71.16,70.80,71.43,0.63,3.14,87.41,-0.78,86.62,24.59,23.06,26.03,2.97,3.77,18.91,18.07,19.70,1.63,2.66,78.05,-1.15,76.90
Ireland,81.94,80.27,83.60,3.33,5.52,70.48,70.25,70.71,0.46,4.16,86.78,-0.77,86.01,24.26,23.00,25.48,2.48,4.07,18.53,17.90,19.14,1.24,2.97,77.07,-0.69,76.38
Austria,81.65,79.45,83.78,4.33,3.47,70.44,69.73,71.10,1.37,2.81,86.51,-0.23,86.27,24.09,22.43,25.60,3.17,2.14,18.18,17.17,19.10,1.93,1.56,75.72,-0.25,75.47
Finland,81.65,79.11,84.15,5.04,4.06,70.19,69.05,71.29,2.24,3.33,86.17,-0.21,85.96,24.36,22.49,26.06,3.57,2.76,18.28,17.09,19.37,2.28,2.08,75.00,0.04,75.04
Belgium,81.61,79.50,83.66,4.16,3.94,70.10,69.61,70.55,0.94,2.89,86.53,-0.64,85.90,24.23,22.60,25.72,3.12,2.59,18.18,17.34,18.96,1.62,1.73,76.02,-0.99,75.03
Portugal,81.37,78.38,84.15,5.77,4.78,70.06,68.81,71.20,2.39,4.01,86.24,-0.14,86.10,24.20,21.97,26.15,4.18,2.98,18.40,17.04,19.60,2.56,2.25,76.11,-0.07,76.03
Slovenia,81.29,78.57,84.04,5.47,5.24,70.23,68.78,71.69,2.91,4.25,86.76,-0.36,86.39,23.82,21.84,25.64,3.80,3.34,17.69,16.41,18.88,2.47,2.44,74.46,-0.20,74.27
Denmark,81.28,79.49,83.06,3.57,4.35,70.31,69.86,70.75,0.89,3.65,86.65,-0.15,86.50,23.55,22.18,24.85,2.67,2.92,18.10,17.33,18.84,1.51,2.30,76.59,0.27,76.86
United Kingdom,81.22,79.50,82.92,3.42,3.36,69.74,69.38,70.07,0.69,2.46,86.41,-0.55,85.87,24.12,22.91,25.25,2.34,2.81,18.25,17.64,18.82,1.18,1.96,76.44,-0.78,75.66
Germany,80.97,78.75,83.19,4.44,2.86,69.44,69.00,69.86,0.86,1.97,86.38,-0.62,85.76,23.57,21.86,25.17,3.31,1.81,17.62,16.74,18.45,1.71,1.09,75.97,-1.21,74.76
Greece,80.91,78.80,83.01,4.21,2.49,69.82,69.14,70.47,1.33,2.08,86.38,-0.09,86.29,23.71,22.42,24.94,2.52,1.90,18.09,17.31,18.84,1.53,1.43,76.39,-0.09,76.30
Czechia,79.14,76.30,81.93,5.63,4.11,68.49,66.92,70.01,3.09,3.18,87.05,-0.50,86.54,22.08,19.93,24.00,4.07,2.75,16.32,14.87,17.62,2.75,1.92,74.50,-0.58,73.91
Estonia,78.89,74.69,82.61,7.92,7.92,68.37,65.80,70.59,4.79,6.52,87.15,-0.48,86.66,22.50,19.20,24.96,5.76,3.89,16.93,14.66,18.63,3.97,2.87,75.55,-0.31,75.24
Croatia,78.60,75.58,81.59,6.01,3.85,68.38,66.66,70.07,3.41,3.15,87.26,-0.27,87.00,21.87,19.71,23.79,4.08,2.50,16.34,14.92,17.61,2.69,1.79,75.12,-0.40,74.71
Europe,78.10,74.99,81.13,6.14,5.70,67.58,66.07,69.04,2.97,4.69,86.86,-0.33,86.53,22.47,20.48,24.18,3.70,2.91,16.92,15.69,17.98,2.29,2.11,75.72,-0.42,75.30
Albania,77.94,76.17,79.87,3.70,4.26,68.41,67.48,69.43,1.95,3.93,87.51,0.26,87.77,20.92,20.08,21.89,1.81,1.82,16.24,15.66,16.90,1.24,1.50,77.17,0.46,77.63
Poland,77.73,73.94,81.50,7.56,4.03,67.56,65.08,70.01,4.93,3.39,87.07,-0.15,86.92,21.80,19.23,24.00,4.77,2.60,16.31,14.49,17.86,3.37,1.98,74.64,0.18,74.82
Turkey,77.62,75.09,80.13,5.04,4.31,67.24,66.63,67.80,1.17,3.61,86.80,-0.17,86.63,21.26,19.46,22.85,3.39,0.94,16.03,15.03,16.93,1.90,0.61,75.89,-0.49,75.40
Slovakia,77.61,74.23,80.90,6.67,4.29,67.48,65.48,69.41,3.93,3.62,87.10,-0.15,86.95,21.43,18.97,23.51,4.54,2.92,15.99,14.32,17.42,3.10,2.20,74.50,0.11,74.62
Bosnia and Herzegovina,77.10,74.64,79.56,4.92,1.64,67.01,65.67,68.35,2.68,1.43,86.91,0.01,86.91,20.54,18.85,22.07,3.22,0.75,15.37,14.26,16.37,2.11,0.48,75.24,-0.41,74.83
Montenegro,76.84,73.89,79.73,5.84,3.41,67.25,65.61,68.85,3.24,2.82,87.74,-0.22,87.52,20.25,18.04,22.24,4.20,1.31,15.39,13.89,16.74,2.85,0.91,76.45,-0.45,76.00
Hungary,76.34,72.98,79.52,6.54,4.98,66.59,64.67,68.39,3.72,4.37,87.19,0.04,87.23,20.21,17.72,22.27,4.55,2.25,15.17,13.48,16.56,3.08,1.84,74.22,0.84,75.06
Lithuania,76.25,71.45,80.82,9.37,4.25,66.23,63.10,69.17,6.07,3.67,86.89,-0.03,86.86,21.22,17.87,23.80,5.93,1.79,15.84,13.41,17.70,4.29,1.29,74.88,-0.24,74.65
North Macedonia,76.15,76.25,76.92,0.67,3.20,66.65,67.25,66.65,-0.60,2.75,87.59,-0.07,87.52,19.32,20.37,19.23,-1.14,1.54,14.61,15.47,14.42,-1.05,1.15,75.70,-0.08,75.62
Serbia,75.92,73.26,78.46,5.20,4.42,66.55,65.08,67.94,2.86,3.65,87.97,-0.31,87.66,19.73,17.93,21.23,3.30,2.62,14.96,13.76,15.97,2.21,1.87,76.50,-0.68,75.82
Azerbaijan,75.80,73.38,78.09,4.71,10.57,66.62,65.57,67.63,2.06,8.81,88.62,-0.74,87.89,20.86,19.55,21.95,2.40,4.86,16.15,15.49,16.72,1.23,3.54,78.81,-1.39,77.42
Latvia,75.68,71.05,79.97,8.92,5.47,66.02,63.05,68.74,5.69,4.82,87.17,0.07,87.24,20.77,17.44,23.26,5.82,2.46,15.60,13.24,17.37,4.13,1.87,74.99,0.12,75.11
Armenia,75.67,70.82,79.79,8.97,4.05,66.48,63.56,68.96,5.40,3.51,87.92,-0.07,87.86,20.10,16.81,22.61,5.80,2.12,15.45,13.30,17.09,3.79,1.56,77.25,-0.39,76.87
Romania,75.46,71.78,79.23,7.45,4.32,66.18,63.77,68.64,4.87,3.89,87.56,0.14,87.70,20.21,17.74,22.37,4.63,2.02,15.45,13.64,17.04,3.40,1.53,76.53,-0.08,76.45
Bulgaria,75.00,71.52,78.62,7.10,3.36,65.67,63.46,67.95,4.49,2.91,87.60,-0.04,87.56,19.70,17.24,21.92,4.68,2.10,14.99,13.25,16.55,3.30,1.58,76.19,-0.10,76.09
Belarus,74.82,69.73,79.66,9.93,6.03,65.44,62.14,68.56,6.42,5.23,87.53,-0.06,87.46,19.67,16.07,22.49,6.42,2.55,14.88,12.30,16.90,4.60,1.93,75.64,0.01,75.65
Georgia,73.85,69.10,78.44,9.34,2.78,64.85,61.61,67.98,6.37,2.08,88.32,-0.51,87.81,19.05,16.01,21.50,5.49,0.98,14.60,12.47,16.31,3.84,0.51,77.97,-1.33,76.64
Moldova,73.32,69.32,77.17,7.85,7.66,64.43,62.01,66.75,4.74,6.41,88.36,-0.49,87.88,19.02,16.63,20.92,4.29,4.09,14.49,12.87,15.79,2.92,3.01,76.89,-0.71,76.18
Russia,73.22,68.17,78.00,9.83,8.06,63.72,60.41,66.84,6.43,7.01,87.03,-0.01,87.03,19.93,16.80,22.19,5.39,3.54,14.92,12.75,16.49,3.74,2.64,74.92,-0.06,74.86
Kazakhstan,73.20,68.84,77.20,8.36,8.85,63.97,61.26,66.45,5.19,7.60,87.60,-0.21,87.39,19.15,16.43,21.16,4.73,3.25,14.49,12.75,15.77,3.02,2.39,76.10,-0.43,75.67
World,73.12,70.61,75.70,5.09,6.35,63.45,62.33,64.59,2.26,5.33,87.05,-0.27,86.78,21.03,19.41,22.54,3.13,2.16,15.80,14.87,16.67,1.80,1.52,75.68,-0.54,75.13
Ukraine,73.00,67.99,77.81,9.82,5.45,63.47,60.10,66.70,6.60,4.68,87.03,-0.09,86.95,19.49,16.43,21.73,5.30,2.72,14.66,12.53,16.21,3.68,2.14,74.66,0.56,75.22

In [20]:
table_code_Europe = create_table_countries(df_Europe, lang='en')
output_table_code(table_code_Europe, 'Table code WHO -Europe -en.txt', destination=DESTINATION_OUTPUT)

Data has written to file

In [21]:
table_code_Europe = create_table_countries(df_Europe, lang='ru')
output_table_code(table_code_Europe, 'Table code WHO -Europe -ru.txt', destination=DESTINATION_OUTPUT)

Data has written to file

<br />
<br />

In [23]:
ls_Asia = ['Afghanistan', 'Armenia', 'Azerbaijan', 'Bahrain', 'Bangladesh', 'Bhutan', 'Brunei', 'Cambodia', 'China', 'Cyprus', 'Egypt',
           'Georgia', 'India', 'Indonesia', 'Iran', 'Iraq', 'Israel', 'Japan', 'Jordan', 'Kazakhstan', 'Kuwait', 'Kyrgyzstan', 'Laos',
           'Lebanon', 'Malaysia', 'Maldives', 'Mongolia', 'Myanmar', 'Nepal', 'North Korea', 'Oman', 'Pakistan', 'Philippines', 'Qatar',
           'Russia', 'Saudi Arabia', 'Singapore', 'South Korea', 'Sri Lanka', 'Syria', 'Tajikistan', 'Thailand', 'Timor-Leste', 'Turkey',
           'Turkmenistan', 'United Arab Emirates', 'Uzbekistan', 'Vietnam', 'Yemen',
           'World', 'Western Pacific', 'South-East Asia', 'Eastern Mediterranean']

# main countries: China, India, Indonesia, Israel, Japan, South Korea, Pakistan, Russia   # Bangladesh, Saudi Arabia

print("Number of records for Asia:", len(ls_Asia))

df_Asia = df.loc[ls_Asia]   \
            .sort_values(by=['LE_birth_o', 'HALE_birth_o', 'LE_60_o', 'HALE_60_o'], ascending=False)
df_Asia

Number of records for Asia: 53

,LE_birth_o,LE_birth_m,LE_birth_f,LE_birth_fΔm,LE_birth_Δ_2000,HALE_birth_o,HALE_birth_m,HALE_birth_f,HALE_birth_fΔm,HALE_birth_Δ_2000,ratio_birth_2000,ratio_birth_Δ,ratio_birth,LE_60_o,LE_60_m,LE_60_f,LE_60_fΔm,LE_60_Δ_2000,HALE_60_o,HALE_60_m,HALE_60_f,HALE_60_fΔm,HALE_60_Δ_2000,ratio_60_2000,ratio_60_Δ,ratio_60
,,,,,,,,,,,,,,,,,,,,,,,,,,
Japan,84.47,81.70,87.15,5.45,2.94,73.58,72.09,75.01,2.92,2.47,87.22,-0.11,87.11,26.66,24.28,28.86,4.58,2.03,20.42,18.79,21.95,3.16,1.57,76.53,0.06,76.59
Singapore,83.90,81.81,85.98,4.17,5.38,73.80,72.66,74.89,2.23,4.39,88.40,-0.44,87.96,25.83,24.05,27.51,3.46,4.35,20.21,18.98,21.38,2.40,3.41,78.21,0.03,78.24
South Korea,83.69,80.56,86.56,6.00,7.83,72.50,70.62,74.19,3.57,5.95,87.73,-1.10,86.63,26.13,23.55,28.30,4.75,5.80,19.66,17.88,21.16,3.28,4.13,76.39,-1.15,75.24
Israel,82.57,80.74,84.32,3.58,4.03,71.51,71.17,71.78,0.61,3.17,87.01,-0.41,86.61,24.88,23.61,26.02,2.41,2.93,18.91,18.29,19.47,1.18,2.13,76.45,-0.44,76.00
Kuwait,82.50,80.27,86.43,6.16,4.92,70.48,69.73,71.79,2.06,3.23,86.68,-1.25,85.43,25.47,23.77,28.37,4.60,3.34,18.66,17.64,20.36,2.72,2.04,75.10,-1.84,73.26
Cyprus,82.18,80.20,84.16,3.96,3.35,71.13,70.69,71.55,0.86,2.66,86.86,-0.30,86.55,24.36,22.91,25.77,2.86,2.53,18.56,17.79,19.31,1.52,1.93,76.18,0.01,76.19
United Arab Emirates,81.41,80.98,82.29,1.31,3.29,69.69,70.24,68.69,-1.55,2.24,86.34,-0.74,85.60,23.55,23.52,23.68,0.16,2.17,17.29,17.59,16.95,-0.64,1.39,74.37,-0.95,73.42
Jordan,79.79,79.73,80.34,0.61,7.07,68.36,69.59,67.32,-2.27,5.11,86.98,-1.30,85.67,23.48,24.08,23.36,-0.72,4.75,17.33,18.03,16.95,-1.08,3.17,75.60,-1.79,73.81
Lebanon,79.29,76.92,81.47,4.55,3.57,67.41,66.73,68.03,1.30,2.41,85.84,-0.83,85.02,23.18,21.46,24.66,3.20,2.46,16.93,15.83,17.88,2.05,1.40,74.95,-1.91,73.04
Qatar,78.90,78.49,79.84,1.35,8.52,67.91,68.37,66.54,-1.83,6.15,87.75,-1.68,86.07,21.83,21.76,21.86,0.10,6.65,15.83,16.07,15.34,-0.73,4.41,75.23,-2.72,72.51
Iran,77.78,76.36,79.40,3.04,4.29,66.56,66.60,66.60,0.00,3.33,86.04,-0.46,85.57,22.19,21.79,22.71,0.92,1.64,16.46,16.44,16.59,0.15,0.98,75.33,-1.15,74.18
Turkey,77.62,75.09,80.13,5.04,4.31,67.24,66.63,67.80,1.17,3.61,86.80,-0.17,86.63,21.26,19.46,22.85,3.39,0.94,16.03,15.03,16.93,1.90,0.61,75.89,-0.49,75.40
Western Pacific,77.49,74.51,80.70,6.19,5.53,68.35,66.70,70.13,3.43,4.53,88.69,-0.48,88.20,21.75,19.68,23.84,4.16,2.73,16.64,15.38,17.90,2.52,1.90,77.50,-0.99,76.51
Sri Lanka,77.45,74.32,80.33,6.01,5.94,67.09,65.35,68.69,3.34,4.69,87.26,-0.64,86.62,21.76,19.93,23.19,3.26,2.58,16.05,14.97,16.90,1.93,1.66,75.03,-1.27,73.76
China,77.31,74.58,80.36,5.78,6.47,68.45,66.99,70.08,3.09,5.32,89.12,-0.58,88.54,20.98,19.09,22.98,3.89,3.02,16.06,14.98,17.21,2.23,2.08,77.84,-1.29,76.55
Saudi Arabia,76.93,76.45,77.75,1.30,6.36,66.15,66.37,65.63,-0.74,4.94,86.74,-0.75,85.99,20.65,20.67,20.69,0.02,3.38,15.16,15.22,15.09,-0.13,2.28,74.58,-1.17,73.41
Thailand,76.92,73.30,80.64,7.34,5.91,67.14,64.85,69.50,4.65,4.93,87.61,-0.32,87.29,23.43,21.99,24.74,2.75,2.71,17.68,16.82,18.46,1.64,1.94,75.97,-0.51,75.46
Brunei,76.68,75.25,78.16,2.91,1.17,67.08,66.34,67.82,1.48,0.79,87.79,-0.31,87.48,20.92,20.07,21.72,1.65,1.34,15.82,15.20,16.39,1.19,0.96,75.89,-0.27,75.62
Bahrain,76.03,75.39,76.86,1.47,6.34,65.80,66.30,64.72,-1.58,4.75,87.60,-1.06,86.54,19.06,18.58,19.58,1.00,4.21,14.03,13.94,14.08,0.14,2.78,75.76,-2.15,73.61
Azerbaijan,75.80,73.38,78.09,4.71,10.57,66.62,65.57,67.63,2.06,8.81,88.62,-0.74,87.89,20.86,19.55,21.95,2.40,4.86,16.15,15.49,16.72,1.23,3.54,78.81,-1.39,77.42
Armenia,75.67,70.82,79.79,8.97,4.05,66.48,63.56,68.96,5.40,3.51,87.92,-0.07,87.86,20.10,16.81,22.61,5.80,2.12,15.45,13.30,17.09,3.79,1.56,77.25,-0.39,76.87
Maldives,75.45,74.41,76.86,2.45,5.63,66.93,66.91,66.89,-0.02,5.54,87.93,0.78,88.71,17.90,17.32,18.64,1.32,0.84,14.08,13.82,14.41,0.59,0.86,77.49,1.17,78.66
Oman,75.29,73.09,78.85,5.76,3.63,65.53,64.58,66.76,2.18,2.99,87.27,-0.24,87.04,19.51,17.83,21.90,4.07,1.78,14.56,13.49,16.09,2.60,1.26,75.01,-0.39,74.63
Malaysia,74.68,72.71,76.99,4.28,1.67,65.49,64.68,66.47,1.79,1.36,87.84,-0.14,87.69,19.80,18.97,20.79,1.82,1.48,14.90,14.50,15.42,0.92,1.07,75.49,-0.24,75.25
Bangladesh,73.95,72.64,75.26,2.62,8.59,63.98,64.12,63.86,-0.26,7.32,86.69,-0.17,86.52,20.56,19.92,21.18,1.26,3.18,15.42,15.35,15.49,0.14,2.32,75.37,-0.37,75.00
Bhutan,73.93,72.87,75.13,2.26,7.94,64.13,64.19,64.04,-0.15,6.89,86.74,0.00,86.74,20.12,19.66,20.61,0.95,1.88,15.20,15.15,15.25,0.10,1.37,75.82,-0.28,75.55
Georgia,73.85,69.10,78.44,9.34,2.78,64.85,61.61,67.98,6.37,2.08,88.32,-0.51,87.81,19.05,16.01,21.50,5.49,0.98,14.60,12.47,16.31,3.84,0.51,77.97,-1.33,76.64
Tajikistan,73.81,72.28,75.37,3.09,8.16,64.91,64.42,65.42,1.00,7.12,88.03,-0.09,87.94,20.10,19.57,20.62,1.05,2.73,15.67,15.54,15.80,0.26,2.07,78.30,-0.34,77.96
Vietnam,73.71,69.51,78.00,8.49,1.84,65.39,62.68,68.16,5.48,1.65,88.69,0.02,88.71,19.55,16.82,21.96,5.14,0.64,15.12,13.28,16.74,3.46,0.40,77.84,-0.50,77.34
Kyrgyzstan,73.59,69.92,77.14,7.22,7.66,64.84,62.68,66.93,4.25,6.73,88.14,-0.03,88.11,19.46,17.19,21.40,4.21,2.91,15.13,13.69,16.37,2.68,2.29,77.58,0.17,77.75
Russia,73.22,68.17,78.00,9.83,8.06,63.72,60.41,66.84,6.43,7.01,87.03,-0.01,87.03,19.93,16.80,22.19,5.39,3.54,14.92,12.75,16.49,3.74,2.64,74.92,-0.06,74.86
Kazakhstan,73.20,68.84,77.20,8.36,8.85,63.97,61.26,66.45,5.19,7.60,87.60,-0.21,87.39,19.15,16.43,21.16,4.73,3.25,14.49,12.75,15.77,3.02,2.39,76.10,-0.43,75.67
World,73.12,70.61,75.70,5.09,6.35,63.45,62.33,64.59,2.26,5.33,87.05,-0.27,86.78,21.03,19.41,22.54,3.13,2.16,15.80,14.87,16.67,1.80,1.52,75.68,-0.54,75.13
Iraq,72.90,70.26,75.37,5.11,3.42,62.41,61.17,63.52,2.35,2.72,85.91,-0.30,85.61,19.63,18.02,20.91,2.89,0.65,14.50,13.42,15.36,1.94,0.26,75.03,-1.16,73.87
North Korea,72.32,69.34,75.30,5.96,9.80,64.51,62.89,66.15,3.26,8.63,89.38,-0.18,89.20,18.86,17.04,20.39,3.35,2.37,14.71,13.64,15.64,2.00,1.83,78.11,-0.11,78.00
Uzbekistan,72.27,70.15,74.28,4.13,10.59,63.62,62.85,64.32,1.47,8.92,88.68,-0.65,88.03,17.82,16.51,18.89,2.38,4.45,13.80,13.06,14.40,1.34,3.30,78.53,-1.09,77.44
Egypt,71.59,68.97,74.30,5.33,2.44,62.52,61.66,63.40,1.74,2.10,87.38,-0.04,87.33,17.18,15.30,18.94,3.64,-0.66,13.02,11.93,14.05,2.12,-0.65,76.63,-0.84,75.79
Indonesia,71.40,69.55,73.26,3.71,4.19,63.29,62.48,64.09,1.61,3.86,88.42,0.22,88.64,18.06,16.96,19.04,2.08,0.71,13.79,13.17,14.34,1.17,0.55,76.31,0.05,76.36
South-East Asia,71.37,69.61,73.23,3.62,7.30,61.82,61.38,62.28,0.90,6.48,86.37,0.24,86.62,18.90,17.88,19.89,2.01,1.37,14.03,13.58,14.46,0.88,1.10,73.76,0.47,74.23
Nepal,71.36,69.56,73.10,3.54,5.99,61.53,61.01,62.08,1.07,5.47,85.76,0.47,86.22,18.60,17.64,19.51,1.87,0.81,13.73,13.32,14.12,0.80,0.73,73.07,0.74,73.82
Mongolia,70.75,66.27,75.47,9.20,7.55,62.00,58.89,65.28,6.39,6.36,88.04,-0.41,87.63,18.49,16.11,20.52,4.41,3.34,14.21,12.55,15.62,3.07,2.45,77.62,-0.77,76.85
India,70.73,69.18,72.41,3.23,7.53,60.88,60.70,61.08,0.38,6.75,85.65,0.43,86.07,18.52,17.60,19.44,1.84,1.01,13.60,13.27,13.94,0.67,0.90,72.53,0.90,73.43
Eastern Mediterranean,70.18,68.70,71.75,3.05,4.73,60.52,60.34,60.69,0.35,3.84,86.60,-0.37,86.24,18.88,18.24,19.48,1.24,1.27,14.06,13.85,14.26,0.41,0.78,75.41,-0.94,74.47
Cambodia,69.56,66.87,72.16,5.29,10.46,61.25,59.77,62.68,2.91,9.47,87.61,0.44,88.05,17.32,15.72,18.57,2.85,2.00,13.16,12.16,13.93,1.77,1.49,76.17,-0.19,75.98
Philippines,69.43,66.05,73.22,7.17,-0.54,61.26,59.28,63.47,4.19,0.01,87.54,0.70,88.23,17.48,15.45,19.52,4.07,-1.39,13.34,12.06,14.63,2.57,-0.90,75.46,0.85,76.32
Syria,69.17,65.37,73.49,8.12,-1.92,59.66,57.46,62.21,4.75,-2.42,87.33,-1.07,86.25,18.71,18.19,19.31,1.12,1.40,14.19,14.05,14.41,0.36,0.86,77.01,-1.17,75.84
Turkmenistan,69.14,65.70,72.54,6.84,3.57,61.13,59.04,63.20,4.16,3.30,88.20,0.22,88.41,18.23,16.33,19.79,3.46,0.97,14.24,13.02,15.23,2.21,0.75,78.16,-0.04,78.11
Myanmar,68.81,65.69,72.04,6.35,9.43,60.66,58.83,62.56,3.73,8.24,88.28,-0.12,88.16,17.92,16.06,19.61,3.55,3.12,13.61,12.42,14.69,2.27,2.29,76.49,-0.54,75.95
Timor-Leste,68.50,67.02,70.08,3.06,5.63,59.97,58.96,61.07,2.11,5.99,85.86,1.69,87.55,17.96,17.25,18.65,1.40,0.02,13.55,13.14,13.95,0.81,0.25,74.14,1.31,75.45
Laos,68.36,66.14,70.72,4.58,10.08,60.60,59.43,61.84,2.41,8.87,88.76,-0.11,88.65,17.48,16.35,18.63,2.28,2.76,13.53,12.88,14.19,1.31,2.06,77.92,-0.52,77.40
Pakistan,67.03,66.30,67.79,1.49,5.62,57.80,58.12,57.50,-0.62,4.61,86.61,-0.38,86.23,18.01,17.90,18.11,0.21,1.67,13.28,13.51,13.07,-0.44,1.12,74.42,-0.68,73.74
Yemen,66.90,63.95,70.01,6.06,3.82,57.36,56.40,58.35,1.95,3.21,85.84,-0.10,85.74,17.98,17.01,18.81,1.80,1.12,13.56,13.17,13.90,0.73,0.76,75.92,-0.50,75.42
Afghanistan,61.22,60.04,62.55,2.51,7.40,52.31,51.87,52.84,0.97,6.28,85.53,-0.08,85.45,15.16,15.41,14.99,-0.42,2.02,11.03,11.31,10.84,-0.47,1.17,75.04,-2.28,72.76

In [24]:
table_code_Asia = create_table_countries(df_Asia, lang='en')
output_table_code(table_code_Asia, 'Table code WHO -Asia -en.txt', destination=DESTINATION_OUTPUT)

Data has written to file

In [25]:
table_code_Asia = create_table_countries(df_Asia, lang='ru')
output_table_code(table_code_Asia, 'Table code WHO -Asia -ru.txt', destination=DESTINATION_OUTPUT)

Data has written to file

<br />
<br />

In [27]:
ls_Oceania = ['Australia', 'Fiji', 'Kiribati', 'Micronesia', 'New Zealand', 'Papua New Guinea',
              'Samoa', 'Solomon Islands', 'Tonga', 'Vanuatu',
              'World', 'Western Pacific']

# WHO list does not contain 'Marshall Islands', 'Nauru', 'Tuvalu', 'French Polynesia', 'New Caledonia', 'Guam'

print("Number of records for Oceania:", len(ls_Oceania))

df_Oceania = df.loc[ls_Oceania]   \
              .sort_values(by=['LE_birth_o', 'HALE_birth_o', 'LE_60_o', 'HALE_60_o'], ascending=False)
df_Oceania

Number of records for Oceania: 12

,LE_birth_o,LE_birth_m,LE_birth_f,LE_birth_fΔm,LE_birth_Δ_2000,HALE_birth_o,HALE_birth_m,HALE_birth_f,HALE_birth_fΔm,HALE_birth_Δ_2000,ratio_birth_2000,ratio_birth_Δ,ratio_birth,LE_60_o,LE_60_m,LE_60_f,LE_60_fΔm,LE_60_Δ_2000,HALE_60_o,HALE_60_m,HALE_60_f,HALE_60_fΔm,HALE_60_Δ_2000,ratio_60_2000,ratio_60_Δ,ratio_60
,,,,,,,,,,,,,,,,,,,,,,,,,,
Australia,82.64,80.72,84.57,3.85,2.94,70.26,69.68,70.84,1.16,2.15,85.46,-0.44,85.02,25.35,24.05,26.60,2.55,2.24,18.81,18.08,19.53,1.45,1.45,75.12,-0.92,74.20
New Zealand,81.81,80.16,83.43,3.27,3.23,69.74,69.50,69.98,0.48,2.47,85.61,-0.36,85.25,24.72,23.60,25.77,2.17,2.34,18.52,17.95,19.07,1.12,1.62,75.51,-0.59,74.92
Western Pacific,77.49,74.51,80.70,6.19,5.53,68.35,66.70,70.13,3.43,4.53,88.69,-0.48,88.20,21.75,19.68,23.84,4.16,2.73,16.64,15.38,17.90,2.52,1.90,77.50,-0.99,76.51
World,73.12,70.61,75.70,5.09,6.35,63.45,62.33,64.59,2.26,5.33,87.05,-0.27,86.78,21.03,19.41,22.54,3.13,2.16,15.80,14.87,16.67,1.80,1.52,75.68,-0.54,75.13
Tonga,72.94,70.38,75.60,5.22,1.99,64.05,62.97,65.21,2.24,1.34,88.39,-0.57,87.81,19.04,17.41,20.65,3.24,1.15,14.44,13.55,15.32,1.77,0.70,76.80,-0.96,75.84
Samoa,69.99,68.77,71.31,2.54,0.39,61.42,61.11,61.77,0.66,0.16,88.02,-0.26,87.76,17.64,17.22,18.06,0.84,0.56,13.30,13.20,13.41,0.21,0.32,76.00,-0.60,75.40
Fiji,67.87,65.78,70.09,4.31,2.04,59.67,58.64,60.77,2.13,1.54,88.30,-0.39,87.92,16.01,14.71,17.27,2.56,1.47,11.96,11.13,12.76,1.63,0.94,75.79,-1.09,74.70
Vanuatu,67.13,64.12,70.64,6.52,2.20,59.38,57.62,61.43,3.81,1.89,88.54,-0.09,88.46,16.18,15.05,17.63,2.58,0.93,12.47,11.80,13.31,1.51,0.67,77.38,-0.31,77.07
Papua New Guinea,66.67,65.57,67.92,2.35,3.31,58.47,58.09,58.92,0.83,2.90,87.71,-0.00,87.70,16.77,16.34,17.28,0.94,0.75,12.68,12.48,12.92,0.44,0.51,75.97,-0.36,75.61
Micronesia,65.94,63.28,68.81,5.53,2.38,58.15,56.69,59.74,3.05,1.87,88.55,-0.36,88.19,16.04,15.04,16.98,1.94,0.83,12.13,11.61,12.63,1.02,0.46,76.73,-1.10,75.62
Solomon Islands,65.67,63.37,68.29,4.92,2.27,58.12,57.03,59.34,2.31,1.82,88.80,-0.30,88.50,15.50,14.67,16.42,1.75,0.86,11.87,11.52,12.24,0.72,0.52,77.53,-0.95,76.58
Kiribati,62.14,58.90,65.32,6.42,2.06,54.66,52.72,56.58,3.86,1.80,87.98,-0.02,87.96,15.14,13.78,16.16,2.38,0.93,11.40,10.59,12.01,1.42,0.63,75.79,-0.49,75.30

In [28]:
table_code_Oceania = create_table_countries(df_Oceania, lang='en')
output_table_code(table_code_Oceania, 'Table code WHO -Oceania -en.txt', destination=DESTINATION_OUTPUT)

Data has written to file

In [29]:
table_code_Oceania = create_table_countries(df_Oceania, lang='ru')
output_table_code(table_code_Oceania, 'Table code WHO -Oceania -ru.txt', destination=DESTINATION_OUTPUT)

Data has written to file

<br />
<br />

In [31]:
ls_N_America = ['Antigua and Barbuda', 'Bahamas', 'Barbados', 'Belize', 'Canada', 'Costa Rica',
                'Cuba', 'Dominican Republic', 'El Salvador', 'Grenada', 'Guatemala', 'Haiti',
                'Honduras', 'Jamaica', 'Mexico', 'Nicaragua', 'Panama', 'Puerto Rico',
                'Saint Lucia', 'St. Vincent and the Grenadines', 'Trinidad and Tobago', 'USA',
                'World', 'Americas']

# small countries: Dominica, Saint Kitts and Nevis

print("Number of records for North America:", len(ls_N_America))

df_N_America = df.loc[ls_N_America]   \
                 .sort_values(by=['LE_birth_o', 'HALE_birth_o', 'LE_60_o', 'HALE_60_o'], ascending=False)
df_N_America

Number of records for North America: 24

,LE_birth_o,LE_birth_m,LE_birth_f,LE_birth_fΔm,LE_birth_Δ_2000,HALE_birth_o,HALE_birth_m,HALE_birth_f,HALE_birth_fΔm,HALE_birth_Δ_2000,ratio_birth_2000,ratio_birth_Δ,ratio_birth,LE_60_o,LE_60_m,LE_60_f,LE_60_fΔm,LE_60_Δ_2000,HALE_60_o,HALE_60_m,HALE_60_f,HALE_60_fΔm,HALE_60_Δ_2000,ratio_60_2000,ratio_60_Δ,ratio_60
,,,,,,,,,,,,,,,,,,,,,,,,,,
Canada,82.02,80.12,83.90,3.78,2.93,70.30,69.66,70.91,1.25,1.76,86.66,-0.95,85.71,24.99,23.66,26.23,2.57,2.52,18.66,17.89,19.38,1.49,1.58,76.01,-1.34,74.67
Puerto Rico,80.50,76.86,84.04,7.18,4.25,69.44,67.20,71.62,4.42,3.24,86.82,-0.56,86.26,25.32,23.46,26.98,3.52,3.21,19.07,17.74,20.26,2.52,2.17,76.44,-1.12,75.32
Costa Rica,80.30,77.93,82.71,4.78,2.13,69.21,68.09,70.35,2.26,1.38,86.77,-0.58,86.19,24.52,23.11,25.85,2.74,1.97,18.37,17.49,19.20,1.71,1.25,75.92,-1.00,74.92
Panama,78.97,76.20,81.86,5.66,2.82,68.31,66.89,69.79,2.90,2.06,87.00,-0.50,86.50,23.98,22.14,25.80,3.66,1.85,18.08,16.88,19.26,2.38,1.18,76.37,-0.97,75.40
Nicaragua,78.87,76.30,81.27,4.97,2.69,67.68,66.26,69.00,2.74,2.39,85.70,0.11,85.81,24.50,23.23,25.51,2.28,0.46,18.19,17.38,18.83,1.45,0.22,74.75,-0.51,74.24
USA,78.74,76.53,80.98,4.45,2.08,66.02,65.13,66.93,1.80,0.70,85.21,-1.36,83.85,23.24,21.99,24.41,2.42,1.90,16.59,15.82,17.31,1.49,0.92,73.43,-2.04,71.39
Cuba,77.66,75.30,80.12,4.82,0.91,67.80,66.74,68.88,2.14,0.78,87.32,-0.02,87.30,21.57,19.96,23.15,3.19,-0.04,16.55,15.53,17.55,2.02,-0.17,77.37,-0.64,76.73
Americas,77.07,74.42,79.76,5.34,2.98,65.76,64.51,67.01,2.50,2.19,85.80,-0.48,85.33,22.64,21.23,23.92,2.69,1.62,16.61,15.74,17.40,1.66,0.96,74.45,-1.09,73.37
Saint Lucia,76.12,72.53,79.93,7.40,2.90,65.71,63.71,67.84,4.13,2.18,86.77,-0.44,86.32,22.16,19.63,24.67,5.04,2.18,16.73,14.96,18.49,3.53,1.51,76.18,-0.68,75.50
Barbados,76.04,74.33,77.61,3.28,1.43,66.29,65.76,66.76,1.00,1.00,87.51,-0.33,87.18,20.94,19.97,21.74,1.77,0.30,16.07,15.48,16.56,1.08,0.05,77.62,-0.87,76.74
Mexico,75.83,72.80,78.89,6.09,1.61,65.46,63.92,67.02,3.10,1.36,86.36,-0.04,86.32,22.20,21.03,23.30,2.27,0.76,16.53,15.86,17.16,1.30,0.60,74.30,0.16,74.46
Antigua and Barbuda,75.66,74.05,77.07,3.02,1.27,65.78,65.16,66.31,1.15,0.89,87.23,-0.29,86.94,20.14,19.28,20.79,1.51,0.20,15.35,14.74,15.80,1.06,-0.04,77.18,-0.97,76.22
Belize,74.87,72.55,77.38,4.83,4.77,65.19,64.05,66.45,2.40,3.59,87.87,-0.80,87.07,21.69,20.81,22.65,1.84,3.17,16.68,16.13,17.28,1.15,2.17,78.35,-1.45,76.90
El Salvador,74.28,69.48,78.73,9.25,2.63,64.39,60.89,67.62,6.73,2.37,86.56,0.13,86.69,22.01,20.20,23.48,3.28,1.18,16.68,15.34,17.77,2.43,0.74,76.52,-0.74,75.78
Trinidad and Tobago,74.09,70.71,77.54,6.83,3.67,64.07,62.06,66.11,4.05,2.68,87.18,-0.70,86.48,21.44,19.58,23.05,3.47,2.60,16.17,14.85,17.31,2.46,1.73,76.65,-1.23,75.42
Dominican Republic,73.91,70.87,77.18,6.31,0.51,64.14,62.41,66.01,3.60,0.38,86.87,-0.09,86.78,22.60,21.24,23.94,2.70,0.11,17.23,16.31,18.13,1.82,-0.09,77.01,-0.77,76.24
World,73.12,70.61,75.70,5.09,6.35,63.45,62.33,64.59,2.26,5.33,87.05,-0.27,86.78,21.03,19.41,22.54,3.13,2.16,15.80,14.87,16.67,1.80,1.52,75.68,-0.54,75.13
St. Vincent and the Grenadines,73.11,70.76,75.82,5.06,1.45,63.49,62.21,64.98,2.77,0.95,87.27,-0.43,86.84,20.51,19.45,21.71,2.26,1.05,15.52,14.74,16.39,1.65,0.58,76.77,-1.10,75.67
Grenada,72.73,70.46,75.32,4.86,1.14,63.36,62.26,64.67,2.41,0.72,87.50,-0.38,87.12,18.39,16.72,20.26,3.54,0.95,14.05,12.87,15.37,2.50,0.56,77.35,-0.95,76.40
Guatemala,72.71,70.19,75.20,5.01,4.40,62.54,61.18,63.88,2.70,3.84,85.93,0.08,86.01,20.65,19.76,21.45,1.69,0.89,15.39,14.84,15.89,1.05,0.51,75.30,-0.78,74.53
Jamaica,72.24,69.48,75.14,5.66,-0.01,63.55,62.11,65.08,2.97,-0.06,88.04,-0.07,87.97,18.66,16.94,20.39,3.45,0.04,14.57,13.37,15.78,2.41,-0.06,78.57,-0.49,78.08
Honduras,71.44,69.99,72.90,2.91,1.68,62.35,61.85,62.85,1.00,1.60,87.08,0.19,87.28,18.13,17.36,18.84,1.48,-1.17,13.76,13.26,14.23,0.97,-0.96,76.27,-0.37,75.90
Bahamas,70.74,68.08,73.26,5.18,-0.23,61.78,60.38,63.11,2.73,-0.44,87.67,-0.34,87.33,20.20,18.68,21.50,2.82,0.15,15.54,14.48,16.44,1.96,-0.04,77.71,-0.78,76.93
Haiti,63.66,63.18,64.16,0.98,6.93,55.00,55.56,54.47,-1.09,5.84,86.66,-0.26,86.40,16.25,16.28,16.24,-0.04,1.06,12.35,12.54,12.20,-0.34,0.70,76.70,-0.70,76.00

In [32]:
table_code_N_America = create_table_countries(df_N_America, lang='en')
output_table_code(table_code_N_America, 'Table code WHO -N_America -en.txt', destination=DESTINATION_OUTPUT)

Data has written to file

In [33]:
table_code_N_America = create_table_countries(df_N_America, lang='ru')
output_table_code(table_code_N_America, 'Table code WHO -N_America -ru.txt', destination=DESTINATION_OUTPUT)

Data has written to file

<br />
<br />

In [35]:
ls_S_America = ['Argentina', 'Bolivia', 'Brazil', 'Chile', 'Colombia', 'Ecuador',
                'Guyana', 'Paraguay', 'Peru', 'Suriname', 'Uruguay', 'Venezuela',
                'World', 'Americas']

# main countries: Brazil, Colombia, Argentina, Peru, Chile  # Venezuela

print("Number of records for South America:", len(ls_S_America))

df_S_America = df.loc[ls_S_America]   \
                 .sort_values(by=['LE_birth_o', 'HALE_birth_o', 'LE_60_o', 'HALE_60_o'], ascending=False)
df_S_America

Number of records for South America: 14

,LE_birth_o,LE_birth_m,LE_birth_f,LE_birth_fΔm,LE_birth_Δ_2000,HALE_birth_o,HALE_birth_m,HALE_birth_f,HALE_birth_fΔm,HALE_birth_Δ_2000,ratio_birth_2000,ratio_birth_Δ,ratio_birth,LE_60_o,LE_60_m,LE_60_f,LE_60_fΔm,LE_60_Δ_2000,HALE_60_o,HALE_60_m,HALE_60_f,HALE_60_fΔm,HALE_60_Δ_2000,ratio_60_2000,ratio_60_Δ,ratio_60
,,,,,,,,,,,,,,,,,,,,,,,,,,
Chile,81.03,78.66,83.34,4.68,4.23,69.37,68.65,70.05,1.40,3.11,86.28,-0.67,85.61,24.57,23.01,25.97,2.96,3.25,18.34,17.48,19.10,1.62,2.11,76.13,-1.48,74.64
Peru,78.29,76.69,79.88,3.19,3.17,68.41,67.97,68.86,0.89,2.99,87.09,0.29,87.38,23.37,22.59,24.10,1.51,0.56,18.02,17.65,18.37,0.72,0.47,76.94,0.17,77.11
Colombia,77.95,75.33,80.55,5.22,5.41,67.90,66.44,69.34,2.90,4.58,87.29,-0.18,87.11,22.69,21.20,24.03,2.83,2.40,17.41,16.42,18.31,1.89,1.80,76.93,-0.20,76.73
Ecuador,77.75,75.32,80.23,4.91,5.16,67.62,66.42,68.83,2.41,4.12,87.48,-0.51,86.97,22.83,21.46,24.12,2.66,2.27,17.36,16.50,18.17,1.67,1.51,77.09,-1.05,76.04
Americas,77.07,74.42,79.76,5.34,2.98,65.76,64.51,67.01,2.50,2.19,85.80,-0.48,85.33,22.64,21.23,23.92,2.69,1.62,16.61,15.74,17.40,1.66,0.96,74.45,-1.09,73.37
Argentina,77.02,74.00,79.91,5.91,2.73,66.90,65.43,68.27,2.84,2.17,87.13,-0.27,86.86,21.59,19.24,23.64,4.40,1.28,16.50,14.99,17.81,2.82,0.86,77.01,-0.58,76.42
Uruguay,77.01,73.36,80.50,7.14,2.13,66.81,64.91,68.60,3.69,1.47,87.26,-0.50,86.75,21.71,18.95,24.04,5.09,1.02,16.51,14.71,18.02,3.31,0.59,76.95,-0.90,76.05
Brazil,75.48,72.22,78.73,6.51,3.98,64.53,62.96,66.07,3.11,3.61,85.20,0.29,85.49,21.32,19.58,22.84,3.26,1.54,15.81,14.74,16.74,2.00,1.13,74.22,-0.06,74.16
Paraguay,75.08,72.18,78.16,5.98,0.40,64.87,63.47,66.38,2.91,0.46,86.25,0.15,86.40,21.01,19.22,22.82,3.60,-1.09,15.88,14.73,17.04,2.31,-0.85,75.70,-0.12,75.58
World,73.12,70.61,75.70,5.09,6.35,63.45,62.33,64.59,2.26,5.33,87.05,-0.27,86.78,21.03,19.41,22.54,3.13,2.16,15.80,14.87,16.67,1.80,1.52,75.68,-0.54,75.13
Suriname,73.02,69.99,76.10,6.11,2.46,63.12,61.48,64.76,3.28,1.74,86.99,-0.55,86.44,20.69,18.80,22.31,3.51,1.10,15.62,14.30,16.74,2.44,0.59,76.72,-1.23,75.50
Bolivia,72.92,72.03,73.79,1.76,6.83,63.64,63.72,63.54,-0.18,5.87,87.41,-0.14,87.27,19.42,19.07,19.71,0.64,1.62,14.79,14.69,14.88,0.19,1.10,76.91,-0.75,76.16
Venezuela,72.71,68.38,77.35,8.97,-1.32,63.40,60.57,66.43,5.86,-0.98,86.96,0.23,87.20,20.67,18.52,22.64,4.12,-0.54,15.77,14.31,17.11,2.80,-0.39,76.19,0.10,76.29
Guyana,68.73,65.58,71.99,6.41,4.08,59.14,57.25,61.11,3.86,3.19,86.54,-0.50,86.05,18.01,16.52,19.40,2.88,1.56,13.43,12.42,14.39,1.97,1.02,75.44,-0.87,74.57

In [36]:
table_code_S_America = create_table_countries(df_S_America, lang='en')
output_table_code(table_code_S_America, 'Table code WHO -S_America -en.txt', destination=DESTINATION_OUTPUT)

Data has written to file

In [37]:
table_code_S_America = create_table_countries(df_S_America, lang='ru')
output_table_code(table_code_S_America, 'Table code WHO -S_America -ru.txt', destination=DESTINATION_OUTPUT)

Data has written to file

<br />
<br />

In [39]:
ls_Americas = ls_N_America + ls_S_America
ls_Americas.remove('World')
ls_Americas.remove('Americas')

print("Number of records for the Americas:", len(ls_Americas))

df_Americas = df.loc[ls_Americas]   \
                 .sort_values(by=['LE_birth_o', 'HALE_birth_o', 'LE_60_o', 'HALE_60_o'], ascending=False)
df_Americas

Number of records for the Americas: 36

,LE_birth_o,LE_birth_m,LE_birth_f,LE_birth_fΔm,LE_birth_Δ_2000,HALE_birth_o,HALE_birth_m,HALE_birth_f,HALE_birth_fΔm,HALE_birth_Δ_2000,ratio_birth_2000,ratio_birth_Δ,ratio_birth,LE_60_o,LE_60_m,LE_60_f,LE_60_fΔm,LE_60_Δ_2000,HALE_60_o,HALE_60_m,HALE_60_f,HALE_60_fΔm,HALE_60_Δ_2000,ratio_60_2000,ratio_60_Δ,ratio_60
,,,,,,,,,,,,,,,,,,,,,,,,,,
Canada,82.02,80.12,83.90,3.78,2.93,70.30,69.66,70.91,1.25,1.76,86.66,-0.95,85.71,24.99,23.66,26.23,2.57,2.52,18.66,17.89,19.38,1.49,1.58,76.01,-1.34,74.67
Chile,81.03,78.66,83.34,4.68,4.23,69.37,68.65,70.05,1.40,3.11,86.28,-0.67,85.61,24.57,23.01,25.97,2.96,3.25,18.34,17.48,19.10,1.62,2.11,76.13,-1.48,74.64
Puerto Rico,80.50,76.86,84.04,7.18,4.25,69.44,67.20,71.62,4.42,3.24,86.82,-0.56,86.26,25.32,23.46,26.98,3.52,3.21,19.07,17.74,20.26,2.52,2.17,76.44,-1.12,75.32
Costa Rica,80.30,77.93,82.71,4.78,2.13,69.21,68.09,70.35,2.26,1.38,86.77,-0.58,86.19,24.52,23.11,25.85,2.74,1.97,18.37,17.49,19.20,1.71,1.25,75.92,-1.00,74.92
Panama,78.97,76.20,81.86,5.66,2.82,68.31,66.89,69.79,2.90,2.06,87.00,-0.50,86.50,23.98,22.14,25.80,3.66,1.85,18.08,16.88,19.26,2.38,1.18,76.37,-0.97,75.40
Nicaragua,78.87,76.30,81.27,4.97,2.69,67.68,66.26,69.00,2.74,2.39,85.70,0.11,85.81,24.50,23.23,25.51,2.28,0.46,18.19,17.38,18.83,1.45,0.22,74.75,-0.51,74.24
USA,78.74,76.53,80.98,4.45,2.08,66.02,65.13,66.93,1.80,0.70,85.21,-1.36,83.85,23.24,21.99,24.41,2.42,1.90,16.59,15.82,17.31,1.49,0.92,73.43,-2.04,71.39
Peru,78.29,76.69,79.88,3.19,3.17,68.41,67.97,68.86,0.89,2.99,87.09,0.29,87.38,23.37,22.59,24.10,1.51,0.56,18.02,17.65,18.37,0.72,0.47,76.94,0.17,77.11
Colombia,77.95,75.33,80.55,5.22,5.41,67.90,66.44,69.34,2.90,4.58,87.29,-0.18,87.11,22.69,21.20,24.03,2.83,2.40,17.41,16.42,18.31,1.89,1.80,76.93,-0.20,76.73
Ecuador,77.75,75.32,80.23,4.91,5.16,67.62,66.42,68.83,2.41,4.12,87.48,-0.51,86.97,22.83,21.46,24.12,2.66,2.27,17.36,16.50,18.17,1.67,1.51,77.09,-1.05,76.04
Cuba,77.66,75.30,80.12,4.82,0.91,67.80,66.74,68.88,2.14,0.78,87.32,-0.02,87.30,21.57,19.96,23.15,3.19,-0.04,16.55,15.53,17.55,2.02,-0.17,77.37,-0.64,76.73
Americas,77.07,74.42,79.76,5.34,2.98,65.76,64.51,67.01,2.50,2.19,85.80,-0.48,85.33,22.64,21.23,23.92,2.69,1.62,16.61,15.74,17.40,1.66,0.96,74.45,-1.09,73.37
Argentina,77.02,74.00,79.91,5.91,2.73,66.90,65.43,68.27,2.84,2.17,87.13,-0.27,86.86,21.59,19.24,23.64,4.40,1.28,16.50,14.99,17.81,2.82,0.86,77.01,-0.58,76.42
Uruguay,77.01,73.36,80.50,7.14,2.13,66.81,64.91,68.60,3.69,1.47,87.26,-0.50,86.75,21.71,18.95,24.04,5.09,1.02,16.51,14.71,18.02,3.31,0.59,76.95,-0.90,76.05
Saint Lucia,76.12,72.53,79.93,7.40,2.90,65.71,63.71,67.84,4.13,2.18,86.77,-0.44,86.32,22.16,19.63,24.67,5.04,2.18,16.73,14.96,18.49,3.53,1.51,76.18,-0.68,75.50
Barbados,76.04,74.33,77.61,3.28,1.43,66.29,65.76,66.76,1.00,1.00,87.51,-0.33,87.18,20.94,19.97,21.74,1.77,0.30,16.07,15.48,16.56,1.08,0.05,77.62,-0.87,76.74
Mexico,75.83,72.80,78.89,6.09,1.61,65.46,63.92,67.02,3.10,1.36,86.36,-0.04,86.32,22.20,21.03,23.30,2.27,0.76,16.53,15.86,17.16,1.30,0.60,74.30,0.16,74.46
Antigua and Barbuda,75.66,74.05,77.07,3.02,1.27,65.78,65.16,66.31,1.15,0.89,87.23,-0.29,86.94,20.14,19.28,20.79,1.51,0.20,15.35,14.74,15.80,1.06,-0.04,77.18,-0.97,76.22
Brazil,75.48,72.22,78.73,6.51,3.98,64.53,62.96,66.07,3.11,3.61,85.20,0.29,85.49,21.32,19.58,22.84,3.26,1.54,15.81,14.74,16.74,2.00,1.13,74.22,-0.06,74.16
Paraguay,75.08,72.18,78.16,5.98,0.40,64.87,63.47,66.38,2.91,0.46,86.25,0.15,86.40,21.01,19.22,22.82,3.60,-1.09,15.88,14.73,17.04,2.31,-0.85,75.70,-0.12,75.58
Belize,74.87,72.55,77.38,4.83,4.77,65.19,64.05,66.45,2.40,3.59,87.87,-0.80,87.07,21.69,20.81,22.65,1.84,3.17,16.68,16.13,17.28,1.15,2.17,78.35,-1.45,76.90
El Salvador,74.28,69.48,78.73,9.25,2.63,64.39,60.89,67.62,6.73,2.37,86.56,0.13,86.69,22.01,20.20,23.48,3.28,1.18,16.68,15.34,17.77,2.43,0.74,76.52,-0.74,75.78
Trinidad and Tobago,74.09,70.71,77.54,6.83,3.67,64.07,62.06,66.11,4.05,2.68,87.18,-0.70,86.48,21.44,19.58,23.05,3.47,2.60,16.17,14.85,17.31,2.46,1.73,76.65,-1.23,75.42
Dominican Republic,73.91,70.87,77.18,6.31,0.51,64.14,62.41,66.01,3.60,0.38,86.87,-0.09,86.78,22.60,21.24,23.94,2.70,0.11,17.23,16.31,18.13,1.82,-0.09,77.01,-0.77,76.24
World,73.12,70.61,75.70,5.09,6.35,63.45,62.33,64.59,2.26,5.33,87.05,-0.27,86.78,21.03,19.41,22.54,3.13,2.16,15.80,14.87,16.67,1.80,1.52,75.68,-0.54,75.13
St. Vincent and the Grenadines,73.11,70.76,75.82,5.06,1.45,63.49,62.21,64.98,2.77,0.95,87.27,-0.43,86.84,20.51,19.45,21.71,2.26,1.05,15.52,14.74,16.39,1.65,0.58,76.77,-1.10,75.67
Suriname,73.02,69.99,76.10,6.11,2.46,63.12,61.48,64.76,3.28,1.74,86.99,-0.55,86.44,20.69,18.80,22.31,3.51,1.10,15.62,14.30,16.74,2.44,0.59,76.72,-1.23,75.50
Bolivia,72.92,72.03,73.79,1.76,6.83,63.64,63.72,63.54,-0.18,5.87,87.41,-0.14,87.27,19.42,19.07,19.71,0.64,1.62,14.79,14.69,14.88,0.19,1.10,76.91,-0.75,76.16
Grenada,72.73,70.46,75.32,4.86,1.14,63.36,62.26,64.67,2.41,0.72,87.50,-0.38,87.12,18.39,16.72,20.26,3.54,0.95,14.05,12.87,15.37,2.50,0.56,77.35,-0.95,76.40
Venezuela,72.71,68.38,77.35,8.97,-1.32,63.40,60.57,66.43,5.86,-0.98,86.96,0.23,87.20,20.67,18.52,22.64,4.12,-0.54,15.77,14.31,17.11,2.80,-0.39,76.19,0.10,76.29
Guatemala,72.71,70.19,75.20,5.01,4.40,62.54,61.18,63.88,2.70,3.84,85.93,0.08,86.01,20.65,19.76,21.45,1.69,0.89,15.39,14.84,15.89,1.05,0.51,75.30,-0.78,74.53
Jamaica,72.24,69.48,75.14,5.66,-0.01,63.55,62.11,65.08,2.97,-0.06,88.04,-0.07,87.97,18.66,16.94,20.39,3.45,0.04,14.57,13.37,15.78,2.41,-0.06,78.57,-0.49,78.08
Honduras,71.44,69.99,72.90,2.91,1.68,62.35,61.85,62.85,1.00,1.60,87.08,0.19,87.28,18.13,17.36,18.84,1.48,-1.17,13.76,13.26,14.23,0.97,-0.96,76.27,-0.37,75.90
Bahamas,70.74,68.08,73.26,5.18,-0.23,61.78,60.38,63.11,2.73,-0.44,87.67,-0.34,87.33,20.20,18.68,21.50,2.82,0.15,15.54,14.48,16.44,1.96,-0.04,77.71,-0.78,76.93
Guyana,68.73,65.58,71.99,6.41,4.08,59.14,57.25,61.11,3.86,3.19,86.54,-0.50,86.05,18.01,16.52,19.40,2.88,1.56,13.43,12.42,14.39,1.97,1.02,75.44,-0.87,74.57
Haiti,63.66,63.18,64.16,0.98,6.93,55.00,55.56,54.47,-1.09,5.84,86.66,-0.26,86.40,16.25,16.28,16.24,-0.04,1.06,12.35,12.54,12.20,-0.34,0.70,76.70,-0.70,76.00

In [40]:
table_code_Americas = create_table_countries(df_Americas, lang='en')
output_table_code(table_code_Americas, 'Table code WHO -Americas -en.txt', destination=DESTINATION_OUTPUT)

Data has written to file

In [41]:
table_code_Americas = create_table_countries(df_Americas, lang='ru')
output_table_code(table_code_Americas, 'Table code WHO -Americas -ru.txt', destination=DESTINATION_OUTPUT)

Data has written to file

<br />
<br />

In [43]:
ls_Africa = ['Algeria', 'Angola', 'Benin', 'Botswana', 'Burkina Faso', 'Burundi', 'Cameroon', 'Cape Verde',
             'Central African Republic', 'Chad', 'Comoros', 'Congo DR', 'Congo Republic', "Cote d'Ivoire",
             'Djibouti', 'Egypt', 'Equatorial Guinea', 'Eritrea', 'Eswatini', 'Ethiopia', 'Gabon', 'Gambia',
             'Ghana', 'Guinea', 'Guinea-Bissau', 'Kenya', 'Lesotho', 'Liberia', 'Libya', 'Madagascar', 'Malawi',
             'Mali', 'Mauritania', 'Mauritius', 'Morocco', 'Mozambique', 'Namibia', 'Niger', 'Nigeria', 'Rwanda',
             'Sao Tome and Principe', 'Senegal', 'Seychelles', 'Sierra Leone', 'Somalia', 'South Africa',
             'South Sudan', 'Sudan', 'Tanzania', 'Togo', 'Tunisia', 'Uganda', 'Zambia', 'Zimbabwe',
             'World', 'Africa']

# main countries: Nigeria, Ethiopia, Egypt, Democratic Republic of the Congo, South Africa, Algeria, Tanzania, Kenya

print("Number of records for Africa:", len(ls_Africa))

df_Africa = df.loc[ls_Africa]   \
              .sort_values(by=['LE_birth_o', 'HALE_birth_o', 'LE_60_o', 'HALE_60_o'], ascending=False)
df_Africa

Number of records for Africa: 56

,LE_birth_o,LE_birth_m,LE_birth_f,LE_birth_fΔm,LE_birth_Δ_2000,HALE_birth_o,HALE_birth_m,HALE_birth_f,HALE_birth_fΔm,HALE_birth_Δ_2000,ratio_birth_2000,ratio_birth_Δ,ratio_birth,LE_60_o,LE_60_m,LE_60_f,LE_60_fΔm,LE_60_Δ_2000,HALE_60_o,HALE_60_m,HALE_60_f,HALE_60_fΔm,HALE_60_Δ_2000,ratio_60_2000,ratio_60_Δ,ratio_60
,,,,,,,,,,,,,,,,,,,,,,,,,,
Tunisia,77.51,75.09,79.99,4.90,3.21,66.68,66.03,67.38,1.35,2.33,86.61,-0.58,86.03,21.74,20.14,23.33,3.19,1.47,16.19,15.26,17.12,1.86,0.89,75.48,-1.01,74.47
Algeria,76.55,76.24,77.08,0.84,4.08,66.14,67.04,65.34,-1.70,3.20,86.85,-0.45,86.40,21.43,21.62,21.47,-0.15,1.39,16.09,16.45,15.89,-0.56,0.82,76.20,-1.12,75.08
Cape Verde,74.06,69.71,78.23,8.52,2.36,64.76,62.30,67.06,4.76,2.32,87.09,0.36,87.44,19.59,16.54,21.95,5.41,-1.09,14.91,12.93,16.44,3.51,-0.90,76.45,-0.34,76.11
Mauritius,74.06,70.83,77.43,6.60,2.92,64.25,62.46,66.12,3.66,2.06,87.42,-0.67,86.75,20.40,18.56,22.09,3.53,2.59,15.08,13.99,16.08,2.09,1.65,75.41,-1.49,73.92
Morocco,73.75,72.85,74.64,1.79,3.56,63.60,64.13,63.04,-1.09,2.91,86.47,-0.23,86.24,18.97,18.32,19.59,1.27,-0.09,14.15,13.92,14.36,0.44,-0.32,75.92,-1.33,74.59
Libya,73.54,71.47,75.70,4.23,-0.50,63.36,62.73,63.99,1.26,-0.87,86.75,-0.59,86.16,19.90,19.10,20.63,1.53,-1.02,14.76,14.36,15.13,0.77,-1.08,75.72,-1.55,74.17
Seychelles,73.12,70.08,76.65,6.57,1.01,64.31,62.52,66.37,3.85,0.62,88.32,-0.37,87.95,19.38,17.51,21.23,3.72,0.19,14.54,13.34,15.75,2.41,-0.12,76.39,-1.37,75.03
World,73.12,70.61,75.70,5.09,6.35,63.45,62.33,64.59,2.26,5.33,87.05,-0.27,86.78,21.03,19.41,22.54,3.13,2.16,15.80,14.87,16.67,1.80,1.52,75.68,-0.54,75.13
Sao Tome and Principe,71.66,70.16,73.18,3.02,8.53,62.95,62.80,63.09,0.29,7.43,87.95,-0.10,87.85,17.77,16.82,18.69,1.87,0.83,13.62,13.21,14.02,0.81,0.58,76.98,-0.33,76.65
Egypt,71.59,68.97,74.30,5.33,2.44,62.52,61.66,63.40,1.74,2.10,87.38,-0.04,87.33,17.18,15.30,18.94,3.64,-0.66,13.02,11.93,14.05,2.12,-0.65,76.63,-0.84,75.79
Mauritania,70.18,70.00,70.38,0.38,7.26,61.59,62.49,60.82,-1.67,6.38,87.75,0.01,87.76,18.63,18.89,18.39,-0.50,1.61,14.45,14.95,14.01,-0.94,1.27,77.44,0.12,77.56
Sudan,69.47,68.35,70.55,2.20,6.98,60.11,60.26,59.98,-0.28,5.98,86.62,-0.10,86.53,19.04,18.65,19.39,0.74,1.68,14.42,14.32,14.52,0.20,1.20,76.15,-0.42,75.74
Ethiopia,68.85,67.17,70.54,3.37,18.06,59.93,59.20,60.67,1.47,15.48,87.52,-0.47,87.04,18.67,17.89,19.39,1.50,5.23,14.05,13.67,14.40,0.73,3.94,75.22,0.03,75.25
Senegal,68.76,67.08,70.28,3.20,10.15,59.87,59.62,60.11,0.49,8.92,86.93,0.14,87.07,17.90,17.08,18.55,1.47,1.34,13.54,13.23,13.78,0.55,0.99,75.79,-0.14,75.64
Comoros,68.10,66.80,69.43,2.63,6.06,59.76,59.44,60.07,0.63,5.47,87.51,0.25,87.75,18.05,17.58,18.49,0.91,1.96,13.82,13.64,13.99,0.35,1.48,76.69,-0.13,76.57
Rwanda,67.76,65.65,69.62,3.97,20.87,59.10,58.15,59.93,1.78,18.34,86.93,0.29,87.22,17.82,16.50,18.83,2.33,5.14,13.66,12.87,14.27,1.40,3.96,76.50,0.16,76.66
Tanzania,66.79,65.20,68.37,3.17,14.00,58.31,57.97,58.68,0.71,12.39,86.99,0.32,87.30,18.05,17.23,18.79,1.56,2.62,13.80,13.44,14.12,0.68,2.02,76.34,0.11,76.45
Kenya,66.50,64.07,68.99,4.92,12.41,58.25,57.12,59.40,2.28,11.10,87.17,0.42,87.59,17.37,15.81,18.80,2.99,0.66,13.16,12.24,13.99,1.75,0.72,74.45,1.32,75.76
Uganda,66.09,62.82,69.31,6.49,17.20,57.55,55.58,59.50,3.92,15.06,86.91,0.17,87.08,17.70,15.57,19.52,3.95,3.77,13.46,11.99,14.71,2.72,2.90,75.81,0.24,76.05
Ghana,65.97,63.47,68.59,5.12,6.88,57.94,56.84,59.12,2.28,6.21,87.54,0.28,87.83,16.99,15.45,18.52,3.07,1.16,13.11,12.14,14.07,1.93,0.94,76.88,0.28,77.16
South Africa,65.84,62.50,68.85,6.35,8.72,56.29,54.65,57.73,3.08,6.89,86.48,-0.99,85.50,18.71,16.78,19.92,3.14,1.70,13.77,12.67,14.46,1.79,1.02,74.96,-1.36,73.60
Djibouti,65.44,63.63,67.27,3.64,5.92,57.61,56.90,58.34,1.44,5.24,87.99,0.05,88.03,17.45,16.30,18.54,2.24,1.48,13.44,12.77,14.08,1.31,1.13,77.08,-0.06,77.02
Gabon,64.97,62.61,67.75,5.14,7.28,56.38,55.38,57.56,2.18,6.34,86.74,0.04,86.78,16.24,14.72,17.96,3.24,1.73,12.21,11.20,13.34,2.14,1.24,75.60,-0.42,75.18
Botswana,64.92,62.74,66.95,4.21,17.76,56.05,55.04,56.96,1.92,14.74,87.60,-1.26,86.34,17.93,16.14,19.42,3.28,3.85,13.38,12.20,14.36,2.16,2.73,75.64,-1.02,74.62
Gambia,64.91,62.91,66.98,4.07,5.76,56.60,56.31,56.93,0.62,5.09,87.08,0.11,87.20,16.45,15.48,17.44,1.96,0.39,12.53,12.19,12.87,0.68,0.28,76.28,-0.11,76.17
Burundi,64.32,62.37,66.23,3.86,19.96,56.21,55.10,57.29,2.19,17.41,87.47,-0.08,87.39,16.51,15.46,17.42,1.96,3.78,12.78,12.16,13.30,1.14,2.99,76.90,0.50,77.41
Africa,64.17,62.26,66.08,3.82,11.19,55.81,55.14,56.49,1.35,9.83,86.79,0.18,86.97,17.57,16.58,18.44,1.86,2.22,13.29,12.79,13.73,0.94,1.71,75.44,0.20,75.64
Benin,64.14,61.76,66.58,4.82,6.72,55.87,54.94,56.83,1.89,5.98,86.89,0.22,87.11,17.78,16.47,18.98,2.51,1.55,13.46,12.77,14.11,1.34,1.18,75.66,0.04,75.70
Madagascar,63.82,62.83,64.82,1.99,5.09,56.16,56.09,56.23,0.14,4.83,87.40,0.60,88.00,16.25,15.90,16.57,0.67,1.29,12.56,12.48,12.64,0.16,1.08,76.74,0.55,77.29
Eritrea,63.76,61.00,66.53,5.53,8.83,55.67,53.75,57.59,3.84,7.98,86.82,0.49,87.31,15.09,13.87,16.18,2.31,1.87,11.49,10.65,12.23,1.58,1.37,76.55,-0.41,76.14
Togo,63.65,61.21,66.34,5.13,7.57,55.81,54.83,56.91,2.08,6.79,87.41,0.27,87.68,16.38,15.00,17.84,2.84,1.11,12.64,11.84,13.48,1.64,0.93,76.69,0.48,77.17
Namibia,63.49,59.99,66.90,6.91,10.47,55.53,53.34,57.66,4.32,8.81,88.12,-0.66,87.46,16.47,14.24,18.26,4.02,2.40,12.59,11.05,13.82,2.77,1.71,77.33,-0.89,76.44
Cote d'Ivoire,63.48,61.19,66.19,5.00,12.31,55.42,54.42,56.64,2.22,10.90,87.00,0.30,87.30,17.07,15.86,18.55,2.69,2.48,13.00,12.30,13.85,1.55,2.01,75.33,0.83,76.16
Liberia,63.44,62.68,64.20,1.52,10.17,53.99,54.54,53.47,-1.07,8.88,84.68,0.42,85.10,17.05,16.96,17.11,0.15,1.60,12.57,12.83,12.36,-0.47,1.15,73.92,-0.19,73.72
Malawi,63.23,60.43,66.05,5.62,18.59,55.54,54.20,56.91,2.71,16.53,87.39,0.45,87.84,15.90,14.19,17.44,3.25,2.82,12.24,11.21,13.17,1.96,2.25,76.38,0.60,76.98
Nigeria,63.07,61.68,64.51,2.83,9.01,54.81,54.68,54.95,0.27,8.18,86.26,0.65,86.90,18.61,18.00,19.21,1.21,2.39,14.10,13.94,14.25,0.31,1.94,74.97,0.80,75.77
Congo Republic,62.76,62.43,63.08,0.65,10.54,54.67,55.30,54.06,-1.24,9.14,87.19,-0.08,87.11,15.56,15.31,15.79,0.48,2.48,11.80,11.79,11.82,0.03,1.84,76.15,-0.31,75.84
Burkina Faso,62.61,60.08,65.06,4.98,10.72,54.96,53.78,56.09,2.31,9.90,86.84,0.94,87.78,16.77,15.33,17.92,2.59,1.49,12.93,12.04,13.64,1.60,1.31,76.05,1.05,77.10
Angola,62.49,60.33,64.65,4.32,13.12,54.32,53.24,55.40,2.16,11.47,86.79,0.13,86.93,16.35,14.90,17.69,2.79,2.31,12.31,11.34,13.21,1.87,1.70,75.57,-0.28,75.29
Cameroon,62.03,60.08,64.06,3.98,9.07,54.24,53.56,54.96,1.40,8.11,87.10,0.34,87.44,16.80,15.66,17.89,2.23,2.01,12.77,12.19,13.33,1.14,1.60,75.52,0.49,76.01
Congo DR,61.84,59.67,64.08,4.41,9.20,53.50,52.46,54.59,2.13,8.47,85.54,0.97,86.51,15.99,14.89,17.04,2.15,1.52,11.99,11.28,12.67,1.39,1.25,74.22,0.76,74.98
Mali,61.83,61.28,62.41,1.13,8.77,53.81,54.23,53.40,-0.83,7.75,86.81,0.22,87.03,17.18,17.15,17.20,0.05,1.34,13.00,13.22,12.82,-0.40,1.01,75.69,-0.03,75.67
Zambia,61.76,59.43,63.95,4.52,17.23,53.87,52.67,54.97,2.30,14.98,87.33,-0.11,87.22,16.00,14.43,17.22,2.79,3.30,12.20,11.17,13.00,1.83,2.48,76.54,-0.29,76.25
Equatorial Guinea,61.39,59.88,63.05,3.17,7.36,53.17,52.76,53.51,0.75,6.57,86.25,0.36,86.61,16.92,15.62,18.23,2.61,1.95,12.58,11.78,13.37,1.59,1.44,74.42,-0.07,74.35
Guinea,61.13,59.80,62.36,2.56,6.93,53.51,53.36,53.67,0.31,6.08,87.51,0.03,87.53,16.58,16.02,17.01,0.99,1.09,12.71,12.57,12.81,0.24,0.84,76.63,0.03,76.66
Niger,60.57,59.64,61.52,1.88,10.33,53.15,53.31,52.99,-0.32,9.29,87.30,0.45,87.75,17.24,16.85,17.58,0.73,1.43,13.21,13.23,13.21,-0.02,1.15,76.28,0.34,76.62
Sierra Leone,60.40,59.50,61.30,1.80,10.61,52.63,52.68,52.58,-0.10,9.56,86.50,0.63,87.14,16.62,16.32,16.87,0.55,1.45,12.62,12.64,12.61,-0.03,1.15,75.61,0.32,75.93
Chad,59.37,57.84,60.94,3.10,8.20,51.78,51.37,52.20,0.83,7.22,87.08,0.13,87.22,16.05,15.34,16.71,1.37,1.41,12.18,11.90,12.44,0.54,1.11,75.61,0.27,75.89
Zimbabwe,59.07,56.90,61.02,4.12,13.32,51.95,50.90,52.93,2.03,11.42,88.59,-0.64,87.95,14.31,13.12,15.27,2.15,0.71,10.98,10.21,11.58,1.37,0.48,77.21,-0.48,76.73
South Sudan,59.00,56.78,61.16,4.38,7.10,50.96,49.90,52.00,2.10,6.35,85.95,0.42,86.37,15.60,14.35,16.65,2.30,0.37,11.47,10.85,11.99,1.14,0.30,73.34,0.18,73.53
Guinea-Bissau,58.98,56.41,61.44,5.03,8.78,51.81,50.60,52.96,2.36,7.86,87.55,0.29,87.84,14.57,13.43,15.47,2.04,1.60,11.17,10.55,11.65,1.10,1.23,76.64,0.03,76.66
Mozambique,58.51,55.39,61.67,6.28,7.56,50.65,49.27,52.06,2.79,7.10,85.48,1.09,86.57,15.15,12.92,17.06,4.14,0.47,11.41,9.96,12.64,2.68,0.59,73.71,1.61,75.31
Eswatini,55.75,52.47,59.38,6.91,8.97,48.65,46.64,50.88,4.24,7.23,88.54,-1.28,87.26,14.22,11.96,16.13,4.17,1.59,10.69,9.11,12.02,2.91,0.94,77.20,-2.02,75.18
Somalia,55.21,52.87,57.75,4.88,5.93,48.65,47.28,50.14,2.86,5.24,88.09,0.03,88.12,13.52,12.42,14.59,2.17,1.17,10.41,9.72,11.08,1.36,0.88,77.17,-0.17,77.00
Central African Republic,52.93,50.31,55.89,5.58,8.70,45.97,44.41,47.75,3.34,7.67,86.59,0.26,86.85,12.61,11.19,14.27,3.08,1.48,9.42,8.44,10.56,2.12,1.15,74.30,0.40,74.70
Lesotho,51.78,48.96,54.91,5.95,4.40,45.04,43.39,46.88,3.49,3.22,88.27,-1.28,86.98,12.71,10.80,14.33,3.53,-0.41,9.52,8.24,10.59,2.35,-0.61,77.21,-2.31,74.90

In [44]:
table_code_Africa = create_table_countries(df_Africa, lang='en')
output_table_code(table_code_Africa, 'Table code WHO -Africa -en.txt', destination=DESTINATION_OUTPUT)

Data has written to file

In [45]:
table_code_Africa = create_table_countries(df_Africa, lang='ru')
output_table_code(table_code_Africa, 'Table code WHO -Africa -ru.txt', destination=DESTINATION_OUTPUT)

Data has written to file

<br />
<br />
<br />

[Demographics of the European Union](https://en.wikipedia.org/wiki/Demographics_of_the_European_Union)<br>
[Население стран Европейского союза](https://ru.wikipedia.org/wiki/Население_стран_Европейского_союза)

In [47]:
ls_EU =  ['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus', 'Czechia', 'Denmark', 'Estonia',
          'Finland', 'France', 'Germany', 'Greece', 'Hungary', 'Ireland', 'Italy', 'Latvia',
          'Lithuania', 'Luxembourg', 'Malta', 'Netherlands', 'Poland', 'Portugal', 'Romania',
          'Slovakia', 'Slovenia', 'Spain', 'Sweden', 'United Kingdom',
          'World']  #  - UK left EU 2020 January 31

print("Number of records for the European Union:", len(ls_EU))

df_EU = df.loc[ls_EU]   \
          .sort_values(by=['LE_birth_o', 'HALE_birth_o', 'LE_60_o', 'HALE_60_o'], ascending=False)
df_EU

Number of records for the European Union: 29

,LE_birth_o,LE_birth_m,LE_birth_f,LE_birth_fΔm,LE_birth_Δ_2000,HALE_birth_o,HALE_birth_m,HALE_birth_f,HALE_birth_fΔm,HALE_birth_Δ_2000,ratio_birth_2000,ratio_birth_Δ,ratio_birth,LE_60_o,LE_60_m,LE_60_f,LE_60_fΔm,LE_60_Δ_2000,HALE_60_o,HALE_60_m,HALE_60_f,HALE_60_fΔm,HALE_60_Δ_2000,ratio_60_2000,ratio_60_Δ,ratio_60
,,,,,,,,,,,,,,,,,,,,,,,,,,
Spain,83.14,80.54,85.66,5.12,4.05,71.69,70.90,72.42,1.52,2.80,87.10,-0.88,86.23,25.39,23.28,27.33,4.05,2.69,19.18,17.94,20.33,2.39,1.78,76.65,-1.11,75.54
Italy,82.99,80.94,84.91,3.97,3.62,71.43,70.85,71.92,1.07,3.04,86.17,-0.10,86.07,25.14,23.53,26.56,3.03,2.60,18.95,18.03,19.78,1.75,1.94,75.47,-0.09,75.38
Luxembourg,82.80,80.83,84.74,3.91,4.38,71.46,70.98,71.89,0.91,3.61,86.52,-0.22,86.30,24.73,23.13,26.22,3.09,2.85,18.83,17.97,19.64,1.67,2.10,76.46,-0.32,76.14
Sweden,82.71,81.17,84.24,3.07,3.14,71.41,71.33,71.46,0.13,2.15,87.04,-0.71,86.34,24.78,23.57,25.91,2.34,2.36,18.80,18.26,19.32,1.06,1.57,76.85,-0.98,75.87
France,82.53,79.77,85.15,5.38,3.62,70.72,69.78,71.60,1.82,2.74,86.15,-0.46,85.69,25.69,23.63,27.51,3.88,2.68,19.26,18.07,20.33,2.26,1.89,75.49,-0.52,74.97
Netherlands,82.34,80.85,83.76,2.91,4.33,71.08,71.05,71.07,0.02,2.98,87.30,-0.97,86.32,24.65,23.43,25.76,2.33,3.33,18.64,18.07,19.16,1.09,2.16,77.30,-1.68,75.62
Cyprus,82.18,80.20,84.16,3.96,3.35,71.13,70.69,71.55,0.86,2.66,86.86,-0.30,86.55,24.36,22.91,25.77,2.86,2.53,18.56,17.79,19.31,1.52,1.93,76.18,0.01,76.19
Malta,82.15,80.31,83.98,3.67,4.33,71.16,70.80,71.43,0.63,3.14,87.41,-0.78,86.62,24.59,23.06,26.03,2.97,3.77,18.91,18.07,19.70,1.63,2.66,78.05,-1.15,76.90
Ireland,81.94,80.27,83.60,3.33,5.52,70.48,70.25,70.71,0.46,4.16,86.78,-0.77,86.01,24.26,23.00,25.48,2.48,4.07,18.53,17.90,19.14,1.24,2.97,77.07,-0.69,76.38
Austria,81.65,79.45,83.78,4.33,3.47,70.44,69.73,71.10,1.37,2.81,86.51,-0.23,86.27,24.09,22.43,25.60,3.17,2.14,18.18,17.17,19.10,1.93,1.56,75.72,-0.25,75.47
Finland,81.65,79.11,84.15,5.04,4.06,70.19,69.05,71.29,2.24,3.33,86.17,-0.21,85.96,24.36,22.49,26.06,3.57,2.76,18.28,17.09,19.37,2.28,2.08,75.00,0.04,75.04
Belgium,81.61,79.50,83.66,4.16,3.94,70.10,69.61,70.55,0.94,2.89,86.53,-0.64,85.90,24.23,22.60,25.72,3.12,2.59,18.18,17.34,18.96,1.62,1.73,76.02,-0.99,75.03
Portugal,81.37,78.38,84.15,5.77,4.78,70.06,68.81,71.20,2.39,4.01,86.24,-0.14,86.10,24.20,21.97,26.15,4.18,2.98,18.40,17.04,19.60,2.56,2.25,76.11,-0.07,76.03
Slovenia,81.29,78.57,84.04,5.47,5.24,70.23,68.78,71.69,2.91,4.25,86.76,-0.36,86.39,23.82,21.84,25.64,3.80,3.34,17.69,16.41,18.88,2.47,2.44,74.46,-0.20,74.27
Denmark,81.28,79.49,83.06,3.57,4.35,70.31,69.86,70.75,0.89,3.65,86.65,-0.15,86.50,23.55,22.18,24.85,2.67,2.92,18.10,17.33,18.84,1.51,2.30,76.59,0.27,76.86
United Kingdom,81.22,79.50,82.92,3.42,3.36,69.74,69.38,70.07,0.69,2.46,86.41,-0.55,85.87,24.12,22.91,25.25,2.34,2.81,18.25,17.64,18.82,1.18,1.96,76.44,-0.78,75.66
Germany,80.97,78.75,83.19,4.44,2.86,69.44,69.00,69.86,0.86,1.97,86.38,-0.62,85.76,23.57,21.86,25.17,3.31,1.81,17.62,16.74,18.45,1.71,1.09,75.97,-1.21,74.76
Greece,80.91,78.80,83.01,4.21,2.49,69.82,69.14,70.47,1.33,2.08,86.38,-0.09,86.29,23.71,22.42,24.94,2.52,1.90,18.09,17.31,18.84,1.53,1.43,76.39,-0.09,76.30
Czechia,79.14,76.30,81.93,5.63,4.11,68.49,66.92,70.01,3.09,3.18,87.05,-0.50,86.54,22.08,19.93,24.00,4.07,2.75,16.32,14.87,17.62,2.75,1.92,74.50,-0.58,73.91
Estonia,78.89,74.69,82.61,7.92,7.92,68.37,65.80,70.59,4.79,6.52,87.15,-0.48,86.66,22.50,19.20,24.96,5.76,3.89,16.93,14.66,18.63,3.97,2.87,75.55,-0.31,75.24
Croatia,78.60,75.58,81.59,6.01,3.85,68.38,66.66,70.07,3.41,3.15,87.26,-0.27,87.00,21.87,19.71,23.79,4.08,2.50,16.34,14.92,17.61,2.69,1.79,75.12,-0.40,74.71
Poland,77.73,73.94,81.50,7.56,4.03,67.56,65.08,70.01,4.93,3.39,87.07,-0.15,86.92,21.80,19.23,24.00,4.77,2.60,16.31,14.49,17.86,3.37,1.98,74.64,0.18,74.82
Slovakia,77.61,74.23,80.90,6.67,4.29,67.48,65.48,69.41,3.93,3.62,87.10,-0.15,86.95,21.43,18.97,23.51,4.54,2.92,15.99,14.32,17.42,3.10,2.20,74.50,0.11,74.62
Hungary,76.34,72.98,79.52,6.54,4.98,66.59,64.67,68.39,3.72,4.37,87.19,0.04,87.23,20.21,17.72,22.27,4.55,2.25,15.17,13.48,16.56,3.08,1.84,74.22,0.84,75.06
Lithuania,76.25,71.45,80.82,9.37,4.25,66.23,63.10,69.17,6.07,3.67,86.89,-0.03,86.86,21.22,17.87,23.80,5.93,1.79,15.84,13.41,17.70,4.29,1.29,74.88,-0.24,74.65
Latvia,75.68,71.05,79.97,8.92,5.47,66.02,63.05,68.74,5.69,4.82,87.17,0.07,87.24,20.77,17.44,23.26,5.82,2.46,15.60,13.24,17.37,4.13,1.87,74.99,0.12,75.11
Romania,75.46,71.78,79.23,7.45,4.32,66.18,63.77,68.64,4.87,3.89,87.56,0.14,87.70,20.21,17.74,22.37,4.63,2.02,15.45,13.64,17.04,3.40,1.53,76.53,-0.08,76.45
Bulgaria,75.00,71.52,78.62,7.10,3.36,65.67,63.46,67.95,4.49,2.91,87.60,-0.04,87.56,19.70,17.24,21.92,4.68,2.10,14.99,13.25,16.55,3.30,1.58,76.19,-0.10,76.09
World,73.12,70.61,75.70,5.09,6.35,63.45,62.33,64.59,2.26,5.33,87.05,-0.27,86.78,21.03,19.41,22.54,3.13,2.16,15.80,14.87,16.67,1.80,1.52,75.68,-0.54,75.13

In [48]:
table_code_EU = create_table_countries(df_EU, lang='en')
output_table_code(table_code_EU, 'Table code WHO -EU -en.txt', destination=DESTINATION_OUTPUT)

Data has written to file

In [49]:
table_code_EU = create_table_countries(df_EU, lang='ru')
output_table_code(table_code_EU, 'Table code WHO -EU -ru.txt', destination=DESTINATION_OUTPUT)

Data has written to file

<br />
<br />
<br />

[CIS](https://en.wikipedia.org/wiki/Commonwealth_of_Independent_States#Life_expectancy) /
[СНГ](https://ru.wikipedia.org/wiki/Содружество_Независимых_Государств#Социальное_развитие_стран_СНГ)

In [51]:
ls_CIS = ['Armenia', 'Azerbaijan', 'Belarus', 'Kazakhstan', 'Kyrgyzstan',
          'Moldova', 'Russia', 'Tajikistan', 'Turkmenistan', 'Uzbekistan',
          'World']    # Georgia and Ukraine are former CIS members

print("Number of records for the Commonwealth of Independent States:", len(ls_CIS))

df_CIS = df.loc[ls_CIS]   \
           .sort_values(by=['LE_birth_o', 'HALE_birth_o', 'LE_60_o', 'HALE_60_o'], ascending=False)
df_CIS

Number of records for the Commonwealth of Independent States: 11

,LE_birth_o,LE_birth_m,LE_birth_f,LE_birth_fΔm,LE_birth_Δ_2000,HALE_birth_o,HALE_birth_m,HALE_birth_f,HALE_birth_fΔm,HALE_birth_Δ_2000,ratio_birth_2000,ratio_birth_Δ,ratio_birth,LE_60_o,LE_60_m,LE_60_f,LE_60_fΔm,LE_60_Δ_2000,HALE_60_o,HALE_60_m,HALE_60_f,HALE_60_fΔm,HALE_60_Δ_2000,ratio_60_2000,ratio_60_Δ,ratio_60
,,,,,,,,,,,,,,,,,,,,,,,,,,
Azerbaijan,75.80,73.38,78.09,4.71,10.57,66.62,65.57,67.63,2.06,8.81,88.62,-0.74,87.89,20.86,19.55,21.95,2.40,4.86,16.15,15.49,16.72,1.23,3.54,78.81,-1.39,77.42
Armenia,75.67,70.82,79.79,8.97,4.05,66.48,63.56,68.96,5.40,3.51,87.92,-0.07,87.86,20.10,16.81,22.61,5.80,2.12,15.45,13.30,17.09,3.79,1.56,77.25,-0.39,76.87
Belarus,74.82,69.73,79.66,9.93,6.03,65.44,62.14,68.56,6.42,5.23,87.53,-0.06,87.46,19.67,16.07,22.49,6.42,2.55,14.88,12.30,16.90,4.60,1.93,75.64,0.01,75.65
Tajikistan,73.81,72.28,75.37,3.09,8.16,64.91,64.42,65.42,1.00,7.12,88.03,-0.09,87.94,20.10,19.57,20.62,1.05,2.73,15.67,15.54,15.80,0.26,2.07,78.30,-0.34,77.96
Kyrgyzstan,73.59,69.92,77.14,7.22,7.66,64.84,62.68,66.93,4.25,6.73,88.14,-0.03,88.11,19.46,17.19,21.40,4.21,2.91,15.13,13.69,16.37,2.68,2.29,77.58,0.17,77.75
Moldova,73.32,69.32,77.17,7.85,7.66,64.43,62.01,66.75,4.74,6.41,88.36,-0.49,87.88,19.02,16.63,20.92,4.29,4.09,14.49,12.87,15.79,2.92,3.01,76.89,-0.71,76.18
Russia,73.22,68.17,78.00,9.83,8.06,63.72,60.41,66.84,6.43,7.01,87.03,-0.01,87.03,19.93,16.80,22.19,5.39,3.54,14.92,12.75,16.49,3.74,2.64,74.92,-0.06,74.86
Kazakhstan,73.20,68.84,77.20,8.36,8.85,63.97,61.26,66.45,5.19,7.60,87.60,-0.21,87.39,19.15,16.43,21.16,4.73,3.25,14.49,12.75,15.77,3.02,2.39,76.10,-0.43,75.67
World,73.12,70.61,75.70,5.09,6.35,63.45,62.33,64.59,2.26,5.33,87.05,-0.27,86.78,21.03,19.41,22.54,3.13,2.16,15.80,14.87,16.67,1.80,1.52,75.68,-0.54,75.13
Uzbekistan,72.27,70.15,74.28,4.13,10.59,63.62,62.85,64.32,1.47,8.92,88.68,-0.65,88.03,17.82,16.51,18.89,2.38,4.45,13.80,13.06,14.40,1.34,3.30,78.53,-1.09,77.44
Turkmenistan,69.14,65.70,72.54,6.84,3.57,61.13,59.04,63.20,4.16,3.30,88.20,0.22,88.41,18.23,16.33,19.79,3.46,0.97,14.24,13.02,15.23,2.21,0.75,78.16,-0.04,78.11

In [52]:
# table_code_CIS = create_table_countries(df_CIS, lang='en')
# output_table_code(table_code_CIS, 'Table code WHO -CIS -en.txt', destination=DESTINATION_OUTPUT)

In [53]:
table_code_CIS = create_table_countries(df_CIS, lang='ru')
output_table_code(table_code_CIS, 'Table code WHO -CIS -ru.txt', destination=DESTINATION_OUTPUT)

Data has written to file

<br />
<br />

In [55]:
# create code for placing info about countries in Wikipedia (for countries)
def create_table_regions(df, lang='en', file_header=None):

    def if_value(x, prec=2):
        return '—' if math.isnan(x) else \
               f"{x:0.{prec}f}"  if x>=0 else \
               f"−{-x:0.{prec}f}"

    if lang=='ru':
        file_header='who_stats_header_regions_ru.txt'
        prettify_name = {
            "World": "\'\'\'Мир\'\'\'",
            "Europe": "[[Европа]]<ref>{{cite web|title=ВОЗ: Европа |publisher=Всемирная организация здравоохранения |url=https://www.who.int/europe/ru/ |access-date=2025-10-18}}</ref>",
            "Eastern Mediterranean": "Восточное Средиземноморье<ref>{{cite web|title=WHO: Eastern Mediterranean: Countries |lang=en |publisher=Всемирная организация здравоохранения |url=http://www.emro.who.int/countries.html |access-date=2025-10-18}}</ref>",
            "South-East Asia": "[[Юго-Восточная Азия]]<ref>{{cite web|title=WHO: South-East Asia: Where we work |lang=en |publisher=Всемирная организация здравоохранения |url=https://www.who.int/southeastasia/about/where-we-work |access-date=2025-10-18}}</ref>",
            "Western Pacific": "Западно-тихоокеанский регион<ref>{{cite web|title=WHO: Western Pacific: Where we work |lang=en |publisher=Всемирная организация здравоохранения |url=https://www.who.int/westernpacific/about/where-we-work |access-date=2025-10-18}}</ref>",
            "Americas": "[[Америка]]<ref>{{cite web|title=WHO: PAHO: Countries and Centers |lang=en |publisher=Всемирная организация здравоохранения |url=https://www.paho.org/en/countries-and-centers |access-date=2025-10-18}}</ref>",
            "Africa": "[[Африка]]<ref>{{cite web|title=WHO: Africa: Countries |lang=en |publisher=Всемирная организация здравоохранения |url=https://www.afro.who.int/countries |access-date=2025-10-18}}</ref>",
            "High-income": "Высокий доход",
            "Upper-middle-income": "Средне-высокий доход",
            "Lower-middle-income": "Средне-низкий доход",
            "Low-income": "Низкий доход"
        }
    else:
        file_header='who_stats_header_regions_en.txt'
        prettify_name = {
            "World": "\'\'\'World\'\'\'",
            "Europe": "[[Europe]]<ref>{{cite web|title=WHO: Europe |publisher=World Health Organization |url=https://www.who.int/europe |access-date=18 November 2025}}</ref>",
            "Eastern Mediterranean": "[[Eastern Mediterranean]]<ref>{{cite web|title=WHO: Eastern Mediterranean: Countries |publisher=World Health Organization |url=http://www.emro.who.int/countries.html |access-date=18 November 2025}}</ref>",
            "South-East Asia": "[[South-East Asia]]<ref>{{cite web|title=WHO: South-East Asia: Where we work |language=en |publisher=World Health Organization |url=https://www.who.int/southeastasia/about/where-we-work |access-date=18 November 2025}}</ref>",
            "Western Pacific": "Western Pacific<ref>{{cite web|title=WHO: Western Pacific: Where we work |publisher=World Health Organization |url=https://www.who.int/westernpacific/about/where-we-work |access-date=18 November 2025}}</ref>",
            "Americas": "[[Americas]]<ref>{{cite web|title=WHO: PAHO: Countries and Centers |publisher=World Health Organization |url=https://www.paho.org/en/countries-and-centers |access-date=18 November 2025}}</ref>",
            "Africa": "[[Africa]]<ref>{{cite web|title=WHO: Africa: Countries |language=en |publisher=World Health Organization |url=https://www.afro.who.int/countries |access-date=18 November 2025}}</ref>",
        } 
            

    with open('design/' + file_header, mode='r', encoding="utf-8") as fh:
        st_header = fh.read()
        
    st_header = st_header.strip()
    st = ''
        
    for i in range(len(df)):
        ser = df.iloc[i]
        
        comp_LE_birth = ser.LE_birth_Δ_2000
        comp_HALE_birth = ser.HALE_birth_Δ_2000
        comp_LE_60 = ser.LE_60_Δ_2000
        comp_HALE_60 = ser.HALE_60_Δ_2000
        
        if ser.name in ['World']:
            st += '\n' + '|-class=static-row-header\n' + \
                  f'|style="text-align:center"| {prettify_name.get(ser.name, ser.name)} ' + \
                  f'||style="background:#e0ffd8;"| \'\'\'{ser.LE_birth_o:0.2f}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| \'\'\'{ser.LE_birth_m:0.2f}\'\'\' ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{ser.LE_birth_f:0.2f}\'\'\' ' + \
                  f'|| \'\'\'{if_value(ser.LE_birth_fΔm, 2)}\'\'\' ' + \
                  f'||style="background:#fff8dc;"| \'\'\'{if_value(comp_LE_birth, 2)}\'\'\' ' + \
                  f'||style="background:#e0ffd8; border-left-width:2px;"| \'\'\'{ser.HALE_birth_o:0.2f}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| \'\'\'{ser.HALE_birth_m:0.2f}\'\'\' ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{ser.HALE_birth_f:0.2f}\'\'\' ' + \
                  f'|| \'\'\'{if_value(ser.HALE_birth_fΔm, 2)}\'\'\' ' + \
                  f'||style="background:#fff8dc;"| \'\'\'{if_value(comp_HALE_birth, 2)}\'\'\' ' + \
                  f'||style="background:#e0ffd8; border-left-width:3px;"| \'\'\'{ser.LE_60_o:0.2f}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| \'\'\'{ser.LE_60_m:0.2f}\'\'\' ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{ser.LE_60_f:0.2f}\'\'\' ' + \
                  f'|| \'\'\'{if_value(ser.LE_60_fΔm, 2)}\'\'\' ' + \
                  f'||style="background:#fff8dc;"| \'\'\'{if_value(comp_LE_60, 2)}\'\'\' ' + \
                  f'||style="background:#e0ffd8; border-left-width:2px;"| \'\'\'{ser.HALE_60_o:0.2f}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| \'\'\'{ser.HALE_60_m:0.2f}\'\'\' ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{ser.HALE_60_f:0.2f}\'\'\' ' + \
                  f'|| \'\'\'{if_value(ser.HALE_60_fΔm, 2)}\'\'\' ' + \
                  f'||style="background:#fff8dc;"| \'\'\'{if_value(comp_HALE_60, 2)}\'\'\''
        else:
            st += '\n' + '|-\n' + \
                  f'| {prettify_name.get(ser.name, ser.name)} ' + \
                  f'||style="background:#e0ffd8;"| {ser.LE_birth_o:0.2f} ' + \
                  f'||style="background:#eaf3ff;"| {ser.LE_birth_m:0.2f} ' + \
                  f'||style="background:#fee7f6;"| {ser.LE_birth_f:0.2f} ' + \
                  f'|| {if_value(ser.LE_birth_fΔm, 2)} ' + \
                  f'||style="background:#fff8dc;| {if_value(comp_LE_birth, 2)} ' + \
                  f'||style="background:#e0ffd8;border-left-width:2px;"| {ser.HALE_birth_o:0.2f} ' + \
                  f'||style="background:#eaf3ff;"| {ser.HALE_birth_m:0.2f} ' + \
                  f'||style="background:#fee7f6;"| {ser.HALE_birth_f:0.2f} ' + \
                  f'|| {if_value(ser.HALE_birth_fΔm, 2)} ' + \
                  f'||style="background:#fff8dc;| {if_value(comp_HALE_birth, 2)} ' + \
                  f'||style="background:#e0ffd8;border-left-width:3px;"| {ser.LE_60_o:0.2f} ' + \
                  f'||style="background:#eaf3ff;"| {ser.LE_60_m:0.2f} ' + \
                  f'||style="background:#fee7f6;"| {ser.LE_60_f:0.2f} ' + \
                  f'|| {if_value(ser.LE_60_fΔm, 2)} ' + \
                  f'||style="background:#fff8dc;| {if_value(comp_LE_60, 2)} ' + \
                  f'||style="background:#e0ffd8;border-left-width:2px;"| {ser.HALE_60_o:0.2f} ' + \
                  f'||style="background:#eaf3ff;"| {ser.HALE_60_m:0.2f} ' + \
                  f'||style="background:#fee7f6;"| {ser.HALE_60_f:0.2f} ' + \
                  f'|| {if_value(ser.HALE_60_fΔm, 2)} ' + \
                  f'||style="background:#fff8dc;| {if_value(comp_HALE_60, 2)}'
    st += '\n|}'
    
    # WARNING: be sure that inline styles do not contains numbers with comma
    if lang == 'ru':
        st = re.sub('(?<=\\d)\\.(?=\\d)', ',', st)  # replace . to comma, if this . is between two digits
        
    st = st_header + st

    return st

In [56]:
df_regions = df.loc[df.index.isin(LS_WHO_REGIONS+['World'])]
df_regions

,LE_birth_o,LE_birth_m,LE_birth_f,LE_birth_fΔm,LE_birth_Δ_2000,HALE_birth_o,HALE_birth_m,HALE_birth_f,HALE_birth_fΔm,HALE_birth_Δ_2000,ratio_birth_2000,ratio_birth_Δ,ratio_birth,LE_60_o,LE_60_m,LE_60_f,LE_60_fΔm,LE_60_Δ_2000,HALE_60_o,HALE_60_m,HALE_60_f,HALE_60_fΔm,HALE_60_Δ_2000,ratio_60_2000,ratio_60_Δ,ratio_60
,,,,,,,,,,,,,,,,,,,,,,,,,,
Europe,78.10,74.99,81.13,6.14,5.70,67.58,66.07,69.04,2.97,4.69,86.86,-0.33,86.53,22.47,20.48,24.18,3.70,2.91,16.92,15.69,17.98,2.29,2.11,75.72,-0.42,75.30
Western Pacific,77.49,74.51,80.70,6.19,5.53,68.35,66.70,70.13,3.43,4.53,88.69,-0.48,88.20,21.75,19.68,23.84,4.16,2.73,16.64,15.38,17.90,2.52,1.90,77.50,-0.99,76.51
Americas,77.07,74.42,79.76,5.34,2.98,65.76,64.51,67.01,2.50,2.19,85.80,-0.48,85.33,22.64,21.23,23.92,2.69,1.62,16.61,15.74,17.40,1.66,0.96,74.45,-1.09,73.37
World,73.12,70.61,75.70,5.09,6.35,63.45,62.33,64.59,2.26,5.33,87.05,-0.27,86.78,21.03,19.41,22.54,3.13,2.16,15.80,14.87,16.67,1.80,1.52,75.68,-0.54,75.13
South-East Asia,71.37,69.61,73.23,3.62,7.30,61.82,61.38,62.28,0.90,6.48,86.37,0.24,86.62,18.90,17.88,19.89,2.01,1.37,14.03,13.58,14.46,0.88,1.10,73.76,0.47,74.23
Eastern Mediterranean,70.18,68.70,71.75,3.05,4.73,60.52,60.34,60.69,0.35,3.84,86.60,-0.37,86.24,18.88,18.24,19.48,1.24,1.27,14.06,13.85,14.26,0.41,0.78,75.41,-0.94,74.47
Africa,64.17,62.26,66.08,3.82,11.19,55.81,55.14,56.49,1.35,9.83,86.79,0.18,86.97,17.57,16.58,18.44,1.86,2.22,13.29,12.79,13.73,0.94,1.71,75.44,0.20,75.64

In [57]:
table_code_all = create_table_regions(df_regions, lang='en')
output_table_code(table_code_all, 'Table code WHO -regions -en.txt', destination=DESTINATION_OUTPUT)

Data has written to file

In [58]:
table_code_all = create_table_regions(df_regions, lang='ru')
output_table_code(table_code_all, 'Table code WHO -regions -ru.txt', destination=DESTINATION_OUTPUT)

Data has written to file

<br />
<br />
<br />

[regions](https://en.wikipedia.org/wiki/List_of_world_regions_by_life_expectancy) / [регионы](https://ru.wikipedia.org/wiki/Список_регионов_мира_по_ожидаемой_продолжительности_жизни)

In [60]:
df_income_groups = df.loc[df.index.isin(LS_INCOME_GROUPS+['World'])]
df_income_groups

,LE_birth_o,LE_birth_m,LE_birth_f,LE_birth_fΔm,LE_birth_Δ_2000,HALE_birth_o,HALE_birth_m,HALE_birth_f,HALE_birth_fΔm,HALE_birth_Δ_2000,ratio_birth_2000,ratio_birth_Δ,ratio_birth,LE_60_o,LE_60_m,LE_60_f,LE_60_fΔm,LE_60_Δ_2000,HALE_60_o,HALE_60_m,HALE_60_f,HALE_60_fΔm,HALE_60_Δ_2000,ratio_60_2000,ratio_60_Δ,ratio_60
,,,,,,,,,,,,,,,,,,,,,,,,,,
High-income,80.91,78.48,83.33,4.85,3.38,69.28,68.28,70.26,1.98,2.32,86.37,-0.74,85.63,24.28,22.55,25.87,3.32,2.45,18.09,17.02,19.07,2.05,1.63,75.40,-0.90,74.51
Upper-middle-income,75.67,72.73,78.72,5.99,5.87,66.42,64.88,68.01,3.13,4.87,88.18,-0.40,87.78,20.80,18.93,22.57,3.64,2.71,15.82,14.71,16.87,2.16,1.92,76.84,-0.78,76.06
World,73.12,70.61,75.70,5.09,6.35,63.45,62.33,64.59,2.26,5.33,87.05,-0.27,86.78,21.03,19.41,22.54,3.13,2.16,15.80,14.87,16.67,1.80,1.52,75.68,-0.54,75.13
Lower-middle-income,69.57,67.70,71.53,3.83,6.97,60.22,59.70,60.77,1.07,6.14,86.39,0.17,86.56,18.69,17.61,19.73,2.12,1.42,13.91,13.41,14.39,0.98,1.10,74.17,0.25,74.42
Low-income,64.22,62.10,66.34,4.24,10.61,55.89,54.98,56.81,1.83,9.29,86.92,0.10,87.03,17.16,16.14,18.06,1.92,2.40,13.04,12.47,13.53,1.06,1.84,75.88,0.11,75.99

In [61]:
table_code_all = create_table_regions(df_income_groups, lang='en')
output_table_code(table_code_all, 'Table code WHO -income_groups -en.txt', destination=DESTINATION_OUTPUT)

Data has written to file

In [62]:
table_code_all = create_table_regions(df_income_groups, lang='ru')
output_table_code(table_code_all, 'Table code WHO -income_groups -ru.txt', destination=DESTINATION_OUTPUT)

Data has written to file

<br />
<br />
<br />
<hr />

[my private wiki-page for exploration of HALE](https://en.wikipedia.org/wiki/User:Lady3mlnm/HALE)

In [64]:
# create code for placing info about countries in Wikipedia (for countries)
def create_table_countries_extended(df, lang='en'):

    def if_value(x, prec=2):
        return '—' if math.isnan(x) else \
               f"{x:0.{prec}f}"  if x>=0 else \
               f"−{-x:0.{prec}f}"

    def chval(x, prec=2):  # change_value
        return '"| —' if math.isnan(x) else \
               f'color:darkgreen;"| {x:0.{prec}f}' if x>0.0049 else \
               f'color:crimson;"| −{-x:0.{prec}f}' if x<-0.0049 else \
               f'color:darkgray;"| {x:0.{prec}f}'
    
    def chval_bold(x, prec=2):  # change_value
        return '"| —' if math.isnan(x) else \
               f'color:darkgreen;"| \'\'\'{x:0.{prec}f}\'\'\'' if x>0 else \
               f'color:crimson;"| \'\'\'−{-x:0.{prec}f}\'\'\'' if x<0 else \
               f'color:darkgray;"| \'\'\'{x:0.{prec}f}\'\'\''

    if lang=='ru':
        file_header='who_stats_header_countries_extended_ru.txt'
        ptn_1 = 'флагификация'
        ptn_2 = 'флаг'
        prettify_name = {
            "World": "\'\'\'Мир\'\'\'",
            "Europe": "[[Европа]]<ref>{{cite web|title=ВОЗ: Европа |publisher=Всемирная организация здравоохранения |url=https://www.who.int/europe/ru/ |access-date=2025-10-12}}</ref>",
            "Eastern Mediterranean": "\'\'\'{{нп5|Восточное Средиземноморье||en|Eastern Mediterranean}}\'\'\'<ref>{{cite web|title=WHO: Eastern Mediterranean: Countries |lang=en |publisher=Всемирная организация здравоохранения |url=http://www.emro.who.int/countries.html |access-date=2025-10-12}}</ref>",
            "South-East Asia": "\'\'\'[[Юго-Восточная Азия]]\'\'\'<ref>{{cite web|title=WHO: South-East Asia: Where we work |lang=en |publisher=Всемирная организация здравоохранения |url=https://www.who.int/southeastasia/about/where-we-work |access-date=2025-10-12}}</ref>",
            "Western Pacific": "\'\'\'Западно-тихоокеанский регион\'\'\'<ref>{{cite web|title=WHO: Western Pacific: Where we work |lang=en |publisher=Всемирная организация здравоохранения |url=https://www.who.int/westernpacific/about/where-we-work |access-date=2025-10-12}}</ref>",
            "Americas": "\'\'\'[[Америка]]\'\'\'<ref>{{cite web|title=WHO: PAHO: Countries and Centers |lang=en |publisher=Всемирная организация здравоохранения |url=https://www.paho.org/en/countries-and-centers |access-date=2025-10-12}}</ref>",
            "Africa": "\'\'\'[[Африка]]\'\'\'<ref>{{cite web|title=WHO: Africa: Countries |lang=en |publisher=Всемирная организация здравоохранения |url=https://www.afro.who.int/countries |access-date=2025-10-12}}</ref>", 
        }
    else:
        file_header='who_stats_header_countries_extended_en.txt'
        ptn_1 = 'flaglist'
        ptn_2 = 'flagicon'
        prettify_name = {
            "World": "\'\'\'World\'\'\'",
            "Europe": "[[Europe]]<ref>{{cite web|title=WHO: Europe |publisher=World Health Organization |url=https://www.who.int/europe |access-date=12 November 2025}}</ref>",
            "Eastern Mediterranean": "\'\'\'[[Eastern Mediterranean]]\'\'\'<ref>{{cite web|title=WHO: Eastern Mediterranean: Countries |publisher=World Health Organization |url=http://www.emro.who.int/countries.html |access-date=12 November 2025}}</ref>",
            "South-East Asia": "\'\'\'[[South-East Asia]]\'\'\'<ref>{{cite web|title=WHO: South-East Asia: Where we work |language=en |publisher=World Health Organization |url=https://www.who.int/southeastasia/about/where-we-work |access-date=12 November 2025}}</ref>",
            "Western Pacific": "\'\'\'Western Pacific\'\'\'<ref>{{cite web|title=WHO: Western Pacific: Where we work |publisher=World Health Organization |url=https://www.who.int/westernpacific/about/where-we-work |access-date=12 November 2025}}</ref>",
            "Americas": "\'\'\'[[Americas]]\'\'\'<ref>{{cite web|title=WHO: PAHO: Countries and Centers |publisher=World Health Organization |url=https://www.paho.org/en/countries-and-centers |access-date=12 November 2025}}</ref>",
            "Africa": "\'\'\'[[Africa]]\'\'\'<ref>{{cite web|title=WHO: Africa: Countries |language=en |publisher=World Health Organization |url=https://www.afro.who.int/countries |access-date=12 November 2025}}</ref>",
        }
            

    with open('design/' + file_header, mode='r', encoding="utf-8") as fh:
        st_header = fh.read()
        
    st_header = st_header.strip()
    st = ''
        
    for i in range(len(df)):
        ser = df.iloc[i]
        
        comp_LE_birth = ser.LE_birth_Δ_2000
        comp_HALE_birth = ser.HALE_birth_Δ_2000
        comp_LE_60 = ser.LE_60_Δ_2000
        comp_HALE_60 = ser.HALE_60_Δ_2000
        
        if ser.name in ['World', 'Europe', 'Eastern Mediterranean', 'South-East Asia', 'Western Pacific', 'Americas', 'Africa']:
            st += '\n' + '|-class=static-row-header\n' + \
                  f'|style="text-align:center"| {prettify_name.get(ser.name, ser.name)} ' + \
                  f'||style="background:#e0ffd8;"| \'\'\'{ser.LE_birth_o:0.2f}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| \'\'\'{ser.LE_birth_m:0.2f}\'\'\' ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{ser.LE_birth_f:0.2f}\'\'\' ' + \
                  f'|| \'\'\'{if_value(ser.LE_birth_fΔm, 2)}\'\'\' ' + \
                  f'||style="background:#fff8dc;"| \'\'\'{if_value(comp_LE_birth, 2)}\'\'\' ' + \
                  f'||style="background:#e0ffd8; border-left-width:2px;"| \'\'\'{ser.HALE_birth_o:0.2f}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| \'\'\'{ser.HALE_birth_m:0.2f}\'\'\' ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{ser.HALE_birth_f:0.2f}\'\'\' ' + \
                  f'|| \'\'\'{if_value(ser.HALE_birth_fΔm, 2)}\'\'\' ' + \
                  f'||style="background:#fff8dc;"| \'\'\'{if_value(comp_HALE_birth, 2)}\'\'\' ' + \
                  f'||style="background:aliceblue;border-left-width:2px;"| \'\'\'{ser.ratio_birth_2000:0.2f}\'\'\' ' + \
                  f'||style="background:aliceblue;{chval_bold(ser.ratio_birth_Δ, 2)} ' + \
                  f'||style="background:aliceblue;"| \'\'\'{ser.ratio_birth:0.2f}\'\'\' ' + \
                  f'||style="background:#e0ffd8; border-left-width:3px;"| \'\'\'{ser.LE_60_o:0.2f}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| \'\'\'{ser.LE_60_m:0.2f}\'\'\' ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{ser.LE_60_f:0.2f}\'\'\' ' + \
                  f'|| \'\'\'{if_value(ser.LE_60_fΔm, 2)}\'\'\' ' + \
                  f'||style="background:#fff8dc;"| \'\'\'{if_value(comp_LE_60, 2)}\'\'\' ' + \
                  f'||style="background:#e0ffd8; border-left-width:2px;"| \'\'\'{ser.HALE_60_o:0.2f}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| \'\'\'{ser.HALE_60_m:0.2f}\'\'\' ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{ser.HALE_60_f:0.2f}\'\'\' ' + \
                  f'|| \'\'\'{if_value(ser.HALE_60_fΔm, 2)}\'\'\' ' + \
                  f'||style="background:#fff8dc;"| \'\'\'{if_value(comp_HALE_60, 2)}\'\'\' ' + \
                  f'||style="background:aliceblue;border-left-width:2px;"| \'\'\'{ser.ratio_60_2000:0.2f}\'\'\' ' + \
                  f'||style="background:aliceblue;{chval_bold(ser.ratio_60_Δ, 2)} ' + \
                  f'||style="background:aliceblue;"| \'\'\'{ser.ratio_60:0.2f}\'\'\' ' + \
                  f'||'
        else:
            st += '\n' + '|-\n' + \
                  f'| {{{{{ptn_1}|{ser.name}}}}} ' + \
                  f'||style="background:#e0ffd8;"| {ser.LE_birth_o:0.2f} ' + \
                  f'||style="background:#eaf3ff;"| {ser.LE_birth_m:0.2f} ' + \
                  f'||style="background:#fee7f6;"| {ser.LE_birth_f:0.2f} ' + \
                  f'|| {if_value(ser.LE_birth_fΔm, 2)} ' + \
                  f'||style="background:#fff8dc;| {if_value(comp_LE_birth, 2)} ' + \
                  f'||style="background:#e0ffd8;border-left-width:2px;"| {ser.HALE_birth_o:0.2f} ' + \
                  f'||style="background:#eaf3ff;"| {ser.HALE_birth_m:0.2f} ' + \
                  f'||style="background:#fee7f6;"| {ser.HALE_birth_f:0.2f} ' + \
                  f'|| {if_value(ser.HALE_birth_fΔm, 2)} ' + \
                  f'||style="background:#fff8dc;| {if_value(comp_HALE_birth, 2)} ' + \
                  f'||style="background:aliceblue;border-left-width:2px;"| {ser.ratio_birth_2000:0.2f} ' + \
                  f'||style="background:aliceblue;{chval(ser.ratio_birth_Δ, 2)} ' + \
                  f'||style="background:aliceblue;"| {ser.ratio_birth:0.2f} ' + \
                  f'||style="background:#e0ffd8;border-left-width:3px;"| {ser.LE_60_o:0.2f} ' + \
                  f'||style="background:#eaf3ff;"| {ser.LE_60_m:0.2f} ' + \
                  f'||style="background:#fee7f6;"| {ser.LE_60_f:0.2f} ' + \
                  f'|| {if_value(ser.LE_60_fΔm, 2)} ' + \
                  f'||style="background:#fff8dc;| {if_value(comp_LE_60, 2)} ' + \
                  f'||style="background:#e0ffd8;border-left-width:2px;"| {ser.HALE_60_o:0.2f} ' + \
                  f'||style="background:#eaf3ff;"| {ser.HALE_60_m:0.2f} ' + \
                  f'||style="background:#fee7f6;"| {ser.HALE_60_f:0.2f} ' + \
                  f'|| {if_value(ser.HALE_60_fΔm, 2)} ' + \
                  f'||style="background:#fff8dc;| {if_value(comp_HALE_60, 2)} ' + \
                  f'||style="background:aliceblue;border-left-width:2px;"| {ser.ratio_60_2000:0.2f} ' + \
                  f'||style="background:aliceblue;{chval(ser.ratio_60_Δ, 2)} ' + \
                  f'||style="background:aliceblue;"| {ser.ratio_60:0.2f} ' + \
                  f'|| {{{{{ptn_2}|{ser.name}}}}}'
    st += '\n|}'
    # f'||style="background:#fff8dc;{chval(comp_LE_birth, 2)} ' + \
    
    # WARNING: be sure that inline styles do not contains numbers with comma
    if lang == 'ru':
        st = re.sub('(?<=\\d)\\.(?=\\d)', ',', st)  # replace . to comma, if this . is between two digits
        
    st = st_header + st

    return st

In [65]:
table_code_all = create_table_countries_extended(df_all_countries, lang='en')
output_table_code(table_code_all, 'Table code WHO -all_countries -extended -en.txt', destination=DESTINATION_OUTPUT)

Data has written to file

<br />
<br />

In [67]:
# create code for placing info about countries in Wikipedia (for countries)
def create_table_regions_extended(df, lang='en'):

    def if_value(x, prec=2):
        return '—' if math.isnan(x) else \
               f"{x:0.{prec}f}"  if x>=0 else \
               f"−{-x:0.{prec}f}"

    def chval(x, prec=2):  # change_value
        return '"| —' if math.isnan(x) else \
               f'color:darkgreen;"| {x:0.{prec}f}' if x>0.0049 else \
               f'color:crimson;"| −{-x:0.{prec}f}' if x<-0.0049 else \
               f'color:darkgray;"| {x:0.{prec}f}'
    
    def chval_bold(x, prec=2):  # change_value
        return '"| —' if math.isnan(x) else \
               f'color:darkgreen;"| \'\'\'{x:0.{prec}f}\'\'\'' if x>0 else \
               f'color:crimson;"| \'\'\'−{-x:0.{prec}f}\'\'\'' if x<0 else \
               f'color:darkgray;"| \'\'\'{x:0.{prec}f}\'\'\''

    if lang=='ru':
        file_header='who_stats_header_regions_extended_ru.txt'
        prettify_name = {
            "World": "\'\'\'Мир\'\'\'",
            "Europe": "[[Европа]]<ref>{{cite web|title=ВОЗ: Европа |publisher=Всемирная организация здравоохранения |url=https://www.who.int/europe/ru/ |access-date=2025-10-12}}</ref>",
            "Eastern Mediterranean": "Восточное Средиземноморье<ref>{{cite web|title=WHO: Eastern Mediterranean: Countries |lang=en |publisher=Всемирная организация здравоохранения |url=http://www.emro.who.int/countries.html |access-date=2025-10-12}}</ref>",
            "South-East Asia": "[[Юго-Восточная Азия]]<ref>{{cite web|title=WHO: South-East Asia: Where we work |lang=en |publisher=Всемирная организация здравоохранения |url=https://www.who.int/southeastasia/about/where-we-work |access-date=2025-10-12}}</ref>",
            "Western Pacific": "Западно-тихоокеанский регион<ref>{{cite web|title=WHO: Western Pacific: Where we work |lang=en |publisher=Всемирная организация здравоохранения |url=https://www.who.int/westernpacific/about/where-we-work |access-date=2025-10-12}}</ref>",
            "Americas": "[[Америка]]<ref>{{cite web|title=WHO: PAHO: Countries and Centers |lang=en |publisher=Всемирная организация здравоохранения |url=https://www.paho.org/en/countries-and-centers |access-date=2025-10-12}}</ref>",
            "Africa": "[[Африка]]<ref>{{cite web|title=WHO: Africa: Countries |lang=en |publisher=Всемирная организация здравоохранения |url=https://www.afro.who.int/countries |access-date=2025-10-12}}</ref>", 
        }
    else:
        file_header='who_stats_header_regions_extended_en.txt'
        prettify_name = {
            "World": "\'\'\'World\'\'\'",
            "Europe": "[[Europe]]<ref>{{cite web|title=WHO: Europe |publisher=World Health Organization |url=https://www.who.int/europe |access-date=12 November 2025}}</ref>",
            "Eastern Mediterranean": "[[Eastern Mediterranean]]<ref>{{cite web|title=WHO: Eastern Mediterranean: Countries |publisher=World Health Organization |url=http://www.emro.who.int/countries.html |access-date=12 November 2025}}</ref>",
            "South-East Asia": "[[South-East Asia]]<ref>{{cite web|title=WHO: South-East Asia: Where we work |language=en |publisher=World Health Organization |url=https://www.who.int/southeastasia/about/where-we-work |access-date=12 November 2025}}</ref>",
            "Western Pacific": "Western Pacific<ref>{{cite web|title=WHO: Western Pacific: Where we work |publisher=World Health Organization |url=https://www.who.int/westernpacific/about/where-we-work |access-date=12 November 2025}}</ref>",
            "Americas": "[[Americas]]<ref>{{cite web|title=WHO: PAHO: Countries and Centers |publisher=World Health Organization |url=https://www.paho.org/en/countries-and-centers |access-date=12 November 2025}}</ref>",
            "Africa": "[[Africa]]<ref>{{cite web|title=WHO: Africa: Countries |language=en |publisher=World Health Organization |url=https://www.afro.who.int/countries |access-date=12 November 2025}}</ref>",
        } 
            

    with open('design/' + file_header, mode='r', encoding="utf-8") as fh:
        st_header = fh.read()
        
    st_header = st_header.strip()
    st = ''
        
    for i in range(len(df)):
        ser = df.iloc[i]
        
        comp_LE_birth = ser.LE_birth_Δ_2000
        comp_HALE_birth = ser.HALE_birth_Δ_2000
        comp_LE_60 = ser.LE_60_Δ_2000
        comp_HALE_60 = ser.HALE_60_Δ_2000
        
        if ser.name in ['World']:
            st += '\n' + '|-class=static-row-header\n' + \
                  f'|style="text-align:center"| {prettify_name.get(ser.name, ser.name)} ' + \
                  f'||style="background:#e0ffd8;"| \'\'\'{ser.LE_birth_o:0.2f}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| \'\'\'{ser.LE_birth_m:0.2f}\'\'\' ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{ser.LE_birth_f:0.2f}\'\'\' ' + \
                  f'|| \'\'\'{if_value(ser.LE_birth_fΔm, 2)}\'\'\' ' + \
                  f'||style="background:#fff8dc;"| \'\'\'{if_value(comp_LE_birth, 2)}\'\'\' ' + \
                  f'||style="background:#e0ffd8; border-left-width:2px;"| \'\'\'{ser.HALE_birth_o:0.2f}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| \'\'\'{ser.HALE_birth_m:0.2f}\'\'\' ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{ser.HALE_birth_f:0.2f}\'\'\' ' + \
                  f'|| \'\'\'{if_value(ser.HALE_birth_fΔm, 2)}\'\'\' ' + \
                  f'||style="background:#fff8dc;"| \'\'\'{if_value(comp_HALE_birth, 2)}\'\'\' ' + \
                  f'||style="background:aliceblue;border-left-width:2px;"| \'\'\'{ser.ratio_birth_2000:0.2f}\'\'\' ' + \
                  f'||style="background:aliceblue;{chval_bold(ser.ratio_birth_Δ, 2)} ' + \
                  f'||style="background:aliceblue;"| \'\'\'{ser.ratio_birth:0.2f}\'\'\' ' + \
                  f'||style="background:#e0ffd8; border-left-width:3px;"| \'\'\'{ser.LE_60_o:0.2f}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| \'\'\'{ser.LE_60_m:0.2f}\'\'\' ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{ser.LE_60_f:0.2f}\'\'\' ' + \
                  f'|| \'\'\'{if_value(ser.LE_60_fΔm, 2)}\'\'\' ' + \
                  f'||style="background:#fff8dc;"| \'\'\'{if_value(comp_LE_60, 2)}\'\'\' ' + \
                  f'||style="background:#e0ffd8; border-left-width:2px;"| \'\'\'{ser.HALE_60_o:0.2f}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| \'\'\'{ser.HALE_60_m:0.2f}\'\'\' ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{ser.HALE_60_f:0.2f}\'\'\' ' + \
                  f'|| \'\'\'{if_value(ser.HALE_60_fΔm, 2)}\'\'\' ' + \
                  f'||style="background:#fff8dc;"| \'\'\'{if_value(comp_HALE_60, 2)}\'\'\' ' + \
                  f'||style="background:aliceblue;border-left-width:2px;"| \'\'\'{ser.ratio_60_2000:0.2f}\'\'\' ' + \
                  f'||style="background:aliceblue;{chval_bold(ser.ratio_60_Δ, 2)} ' + \
                  f'||style="background:aliceblue;"| \'\'\'{ser.ratio_60:0.2f}\'\'\''
        else:
            st += '\n' + '|-\n' + \
                  f'| {prettify_name.get(ser.name, ser.name)} ' + \
                  f'||style="background:#e0ffd8;"| {ser.LE_birth_o:0.2f} ' + \
                  f'||style="background:#eaf3ff;"| {ser.LE_birth_m:0.2f} ' + \
                  f'||style="background:#fee7f6;"| {ser.LE_birth_f:0.2f} ' + \
                  f'|| {if_value(ser.LE_birth_fΔm, 2)} ' + \
                  f'||style="background:#fff8dc;| {if_value(comp_LE_birth, 2)} ' + \
                  f'||style="background:#e0ffd8;border-left-width:2px;"| {ser.HALE_birth_o:0.2f} ' + \
                  f'||style="background:#eaf3ff;"| {ser.HALE_birth_m:0.2f} ' + \
                  f'||style="background:#fee7f6;"| {ser.HALE_birth_f:0.2f} ' + \
                  f'|| {if_value(ser.HALE_birth_fΔm, 2)} ' + \
                  f'||style="background:#fff8dc;| {if_value(comp_HALE_birth, 2)} ' + \
                  f'||style="background:aliceblue;border-left-width:2px;"| {ser.ratio_birth_2000:0.2f} ' + \
                  f'||style="background:aliceblue;{chval(ser.ratio_birth_Δ, 2)} ' + \
                  f'||style="background:aliceblue;"| {ser.ratio_birth:0.2f} ' + \
                  f'||style="background:#e0ffd8;border-left-width:3px;"| {ser.LE_60_o:0.2f} ' + \
                  f'||style="background:#eaf3ff;"| {ser.LE_60_m:0.2f} ' + \
                  f'||style="background:#fee7f6;"| {ser.LE_60_f:0.2f} ' + \
                  f'|| {if_value(ser.LE_60_fΔm, 2)} ' + \
                  f'||style="background:#fff8dc;| {if_value(comp_LE_60, 2)} ' + \
                  f'||style="background:#e0ffd8;border-left-width:2px;"| {ser.HALE_60_o:0.2f} ' + \
                  f'||style="background:#eaf3ff;"| {ser.HALE_60_m:0.2f} ' + \
                  f'||style="background:#fee7f6;"| {ser.HALE_60_f:0.2f} ' + \
                  f'|| {if_value(ser.HALE_60_fΔm, 2)} ' + \
                  f'||style="background:#fff8dc;| {if_value(comp_HALE_60, 2)} ' + \
                  f'||style="background:aliceblue;border-left-width:2px;"| {ser.ratio_60_2000:0.2f} ' + \
                  f'||style="background:aliceblue;{chval(ser.ratio_60_Δ, 2)} ' + \
                  f'||style="background:aliceblue;"| {ser.ratio_60:0.2f}'
    st += '\n|}'
    
    # WARNING: be sure that inline styles do not contains numbers with comma
    if lang == 'ru':
        st = re.sub('(?<=\\d)\\.(?=\\d)', ',', st)  # replace . to comma, if this . is between two digits
        
    st = st_header + st

    return st

In [68]:
# df_regions = df.loc[df.index.isin(LS_WHO_REGIONS+['World'])]
# df_regions

In [69]:
table_code_all = create_table_regions_extended(df_regions, lang='en')
output_table_code(table_code_all, 'Table code WHO -regions -extended -en.txt', destination=DESTINATION_OUTPUT)

Data has written to file

<br />
<br />

In [71]:
# df_income_groups = df.loc[df.index.isin(LS_INCOME_GROUPS+['World'])]
# df_income_groups

In [72]:
table_code_all = create_table_regions_extended(df_income_groups, lang='en')
output_table_code(table_code_all, 'Table code WHO -income_groups -extended -en.txt', destination=DESTINATION_OUTPUT)

Data has written to file

<br />
<br />

In [74]:
# check that all countries are considered for local tables
ls_all_countries = sorted(df.index.to_list())
print(len(ls_all_countries))

196

In [75]:
# combine all local lists into one

import itertools
all_local_lists = \
    sorted(set(itertools.chain(ls_Europe, ls_Asia, ls_Oceania, ls_N_America, ls_S_America, ls_Africa,
                                             LS_WHO_REGIONS, LS_INCOME_GROUPS, LS_IGNORE)))
print(len(all_local_lists))

196

In [76]:
[country for country in ls_all_countries if country not in all_local_lists]

[]

In [77]:
[country for country in all_local_lists if country not in ls_all_countries]

[]

<br />
<br />

In [79]:
# play beep to denote completion of the program
import IPython.display as ipd
import numpy as np

# manually generated sound
t = 1  # time is seconds
beep = np.sin(2*np.pi*400*np.arange(10000*t)/10000)
ipd.Audio(beep, rate=10000, autoplay=True)