[data source 1](https://archpublichealth.biomedcentral.com/articles/10.1186/s13690-023-01170-8), [data source 2](https://link.springer.com/article/10.1186/s13690-023-01170-8#MOESM1)<br>
[List of Indian states by life expectancy at birth](https://en.wikipedia.org/wiki/List_of_Indian_states_by_life_expectancy_at_birth) / [Продолжительность жизни в штатах Индии](https://ru.wikipedia.org/wiki/Продолжительность_жизни_в_штатах_Индии)<br>
[MapChart](https://www.mapchart.net/india.html)

In [2]:
import pandas as pd
import numpy as np
import math
import re
from collections import namedtuple

In [3]:
df1 = pd.read_csv('data/NFHS_2015-16.csv', sep='\t', index_col='state')
df1.index.name = ''
print(len(df1))

df1.head(3).fillna('')

37

,NFHS-2015-16_total,NFHS-2015-16_male,NFHS-2015-16_female,SRS-2015_total,SRS-2015_male,SRS-2015_female
,,,,,,
India,66.6,64.3,69.2,68.0,66.8,69.3
Chandigarh,73.3,69.1,79.5,,,
Delhi,69.2,66.8,73.1,74.6,72.9,76.5

In [4]:
df2 = pd.read_csv('data/NFHS_2019-21.csv', sep='\t', index_col='state')
df2.index.name = ''
print(len(df2))

df2.head(3).fillna('')

37

,NFHS-2019-21_total,NFHS-2019-21_male,NFHS-2019-21_female,SRS-2020_total,SRS-2020_male,SRS-2020_female
,,,,,,
India,65.8,62.9,68.9,69.3,67.6,71.2
Chandigarh,66.5,64.1,69.4,,,
Delhi,68.0,65.2,71.3,74.2,71.5,77.9

In [5]:
# just for interest
df_SRS = pd.concat([df1.iloc[:, 3:], df2.iloc[:, 3:]], axis='columns')

df_SRS.rename(columns = {'SRS-2015_total' : '2015_total',
                         'SRS-2015_male'  : '2015_male',
                         'SRS-2015_female': '2015_female',
                         'SRS-2020_total' : '2020_total',
                         'SRS-2020_male'  : '2020_male',
                         'SRS-2020_female': '2020_female'                         
                         }, inplace=True)
print(len(df_SRS))

df_SRS.dropna(how='all', inplace=True)
print(len(df_SRS))

df_SRS.sort_values(by=['2015_total', '2015_male'], ascending=False, inplace=True)
df_SRS = pd.concat([df_SRS.loc[['India']], df_SRS.drop('India')])

df_SRS.insert(loc=3, column='2015_fΔm' ,  value=(df_SRS['2015_female']-df_SRS['2015_male']).round(1))
df_SRS.insert(loc=4, column='Δ_periods',  value=(df_SRS['2020_total']-df_SRS['2015_total']).round(1))
df_SRS.insert(loc=8, column='2020_fΔm' ,  value=(df_SRS['2020_female']-df_SRS['2020_male']).round(1))

df_SRS.fillna('')

37
23

,2015_total,2015_male,2015_female,2015_fΔm,Δ_periods,2020_total,2020_male,2020_female,2020_fΔm
,,,,,,,,,
India,68.0,66.8,69.3,2.5,1.3,69.3,67.6,71.2,3.6
Delhi,74.6,72.9,76.5,3.6,-0.4,74.2,71.5,77.9,6.4
Jammu and Kashmir,74.4,72.0,77.6,5.6,1.3,75.7,72.7,80.3,7.6
Kerala,74.3,71.4,77.2,5.8,-1.0,73.3,69.7,77.1,7.4
Punjab,72.4,70.8,74.2,3.4,-2.5,69.9,67.8,72.2,4.4
Himachal Pradesh,71.7,67.7,76.2,8.5,0.0,71.7,68.5,75.7,7.2
Maharashtra,71.6,70.5,72.7,2.2,0.4,72.0,70.1,74.2,4.1
West Bengal,70.6,69.7,71.5,1.8,0.7,71.3,69.5,73.4,3.9
Tamil Nadu,70.4,68.5,72.4,3.9,3.1,73.5,71.3,75.9,4.6
Uttarakhand,69.2,66.4,72.2,5.8,-0.2,69.0,66.4,71.9,5.5
Andhra Pradesh,69.0,67.8,70.3,2.5,1.5,70.5,69.1,72.1,3.0
Gujarat,68.9,66.6,71.4,4.8,1.6,70.5,67.7,73.6,5.9
Telangana,68.4,67.4,69.8,2.4,0.9,69.3,67.8,70.9,3.1
Haryana,68.4,66.2,70.9,4.7,-0.2,68.2,65.3,71.7,6.4
Karnataka,68.2,66.8,69.4,2.6,0.8,69.0,66.6,71.7,5.1
Odisha,67.5,65.8,69.4,3.6,2.1,69.6,68.5,71.0,2.5
Bihar,67.4,68.4,66.4,-2.0,1.2,68.6,68.7,68.5,-0.2
Jharkhand,67.4,67.4,67.4,0.0,0.9,68.3,68.5,68.1,-0.4
Rajasthan,67.0,64.9,69.4,4.5,1.9,68.9,66.1,71.9,5.8
Assam,65.4,64.5,66.4,1.9,1.8,67.2,66.6,67.9,1.3
Madhya Pradesh,64.5,62.9,66.3,3.4,2.3,66.8,64.8,69.1,4.3
Chhattisgarh,64.3,62.8,65.9,3.1,-0.7,63.6,62.0,65.2,3.2
Uttar Pradesh,63.9,63.4,64.3,0.9,1.7,65.6,64.7,66.7,2.0

In [6]:
df_NFHS = pd.concat([df1.iloc[:, :3], df2.iloc[:, :3]], axis='columns')

df_NFHS.rename(columns = {'NFHS-2015-16_total' : '2015-16_total',
                          'NFHS-2015-16_male'  : '2015-16_male',
                          'NFHS-2015-16_female': '2015-16_female',
                          'NFHS-2019-21_total' : '2019-21_total',
                          'NFHS-2019-21_male'  : '2019-21_male',
                          'NFHS-2019-21_female': '2019-21_female'                          
                         }, inplace=True)

print(len(df_NFHS))

df_NFHS.sort_values(by=['2015-16_total', '2015-16_male'], ascending=False, inplace=True)
df_NFHS = pd.concat([df_NFHS.loc[['India']], df_NFHS.drop('India')])

df_NFHS.insert(loc=3, column='2015-16_fΔm',  value=(df_NFHS['2015-16_female']-df_NFHS['2015-16_male']).round(1))
df_NFHS.insert(loc=4, column='Δ_periods'  ,  value=(df_NFHS['2019-21_total']-df_NFHS['2015-16_total']).round(1))
df_NFHS.insert(loc=8, column='2019-21_fΔm',  value=(df_NFHS['2019-21_female']-df_NFHS['2019-21_male']).round(1))

df_NFHS.fillna('')

37

,2015-16_total,2015-16_male,2015-16_female,2015-16_fΔm,Δ_periods,2019-21_total,2019-21_male,2019-21_female,2019-21_fΔm
,,,,,,,,,
India,66.6,64.3,69.2,4.9,-0.8,65.8,62.9,68.9,6.0
Nagaland,76.2,73.0,79.8,6.8,-0.8,75.4,71.5,79.9,8.4
Kerala,73.9,70.1,77.8,7.7,-2.7,71.2,67.1,75.5,8.4
Chandigarh,73.3,69.1,79.5,10.4,-6.8,66.5,64.1,69.4,5.3
Dadra and Nagar haveli,73.0,73.4,72.7,-0.7,-2.4,70.6,67.7,76.9,9.2
Mizoram,72.1,66.1,81.0,14.9,0.0,72.1,66.9,78.4,11.5
Punjab,71.1,69.0,73.5,4.5,-4.9,66.2,63.3,69.4,6.1
Himachal Pradesh,70.8,67.5,74.3,6.8,-0.2,70.6,67.9,73.2,5.3
Maharashtra,70.2,67.9,72.8,4.9,-0.9,69.3,66.4,72.4,6.0
Rajasthan,70.2,67.3,73.4,6.1,1.3,71.5,68.1,75.4,7.3
Manipur,70.1,66.0,74.5,8.5,-2.5,67.6,63.7,71.7,8.0
Sikkim,69.8,69.4,70.7,1.3,-3.9,65.9,62.7,70.2,7.5
Goa,69.7,66.1,74.0,7.9,3.6,73.3,68.7,79.1,10.4
Jammu and Kashmir,69.2,67.6,70.8,3.2,2.6,71.8,70.9,72.8,1.9
Delhi,69.2,66.8,73.1,6.3,-1.2,68.0,65.2,71.3,6.1
Gujarat,68.7,65.9,72.0,6.1,-1.0,67.7,64.3,71.5,7.2
Lakshadweep,68.5,65.9,71.6,5.7,2.7,71.2,66.1,76.3,10.2
Meghalaya,68.5,65.0,72.6,7.6,0.3,68.8,66.5,71.4,4.9
Haryana,68.4,65.8,71.9,6.1,-2.4,66.0,61.9,71.0,9.1
West Bengal,68.3,67.4,69.2,1.8,-3.6,64.7,63.0,66.6,3.6
Karnataka,68.2,64.6,72.3,7.7,-0.9,67.3,63.2,72.0,8.8
Tripura,67.8,64.4,71.8,7.4,-1.8,66.0,63.7,68.6,4.9
Uttarakhand,67.6,64.1,71.6,7.5,0.7,68.3,65.4,71.4,6.0
Andaman and nicobar islands,67.4,64.1,71.5,7.4,-0.3,67.1,62.1,84.3,22.2
Jharkhand,66.7,64.9,68.6,3.7,-2.0,64.7,62.7,66.7,4.0
Chhattisgarh,66.4,64.6,68.3,3.7,-2.6,63.8,60.8,67.0,6.2
Puducherry,66.3,60.3,73.9,13.6,-1.7,64.6,59.0,70.7,11.7
Daman and diu,66.2,61.7,72.5,10.8,4.4,70.6,67.7,76.9,9.2
Madhya Pradesh,66.0,63.6,68.8,5.2,0.2,66.2,63.2,69.5,6.3
Uttar Pradesh,64.9,63.3,66.6,3.3,-1.9,63.0,60.6,65.6,5.0
Odisha,64.7,63.4,66.1,2.7,-0.5,64.2,61.4,67.1,5.7
Arunachal Pradesh,64.6,63.0,66.5,3.5,2.9,67.5,65.0,70.2,5.2
Andhra Pradesh,64.2,59.9,69.2,9.3,-0.8,63.4,59.6,67.8,8.2
Tamil Nadu,63.6,60.2,67.4,7.2,0.3,63.9,59.3,69.1,9.8
Assam,63.5,61.0,66.4,5.4,2.6,66.1,63.1,69.5,6.4
Bihar,63.0,62.0,64.0,2.0,1.4,64.4,63.3,65.4,2.1
Telangana,62.4,58.4,66.8,8.4,1.4,63.8,60.4,67.3,6.9

In [7]:
# handle special case
if all(df_NFHS.loc['Dadra and Nagar haveli', '2019-21_total':'2019-21_fΔm'] == df_NFHS.loc['Daman and diu', '2019-21_total':'2019-21_fΔm']):
    new_record = df_NFHS.loc['Dadra and Nagar haveli', '2019-21_total':'2019-21_fΔm']
    new_record.name = 'Dadra and Nagar Haveli and Daman and Diu'
    # df_NFHS = df_NFHS.append(new_record)
    df_NFHS = pd.concat([df_NFHS, new_record.to_frame().T], axis='index')
    df_NFHS.loc['Dadra and Nagar haveli', 'Δ_periods':'2019-21_fΔm'] = [np.NaN] * 5
    df_NFHS.loc['Daman and diu', 'Δ_periods':'2019-21_fΔm'] = [np.NaN] * 5

df_NFHS.fillna('')

,2015-16_total,2015-16_male,2015-16_female,2015-16_fΔm,Δ_periods,2019-21_total,2019-21_male,2019-21_female,2019-21_fΔm
India,66.6,64.3,69.2,4.9,-0.8,65.8,62.9,68.9,6.0
Nagaland,76.2,73.0,79.8,6.8,-0.8,75.4,71.5,79.9,8.4
Kerala,73.9,70.1,77.8,7.7,-2.7,71.2,67.1,75.5,8.4
Chandigarh,73.3,69.1,79.5,10.4,-6.8,66.5,64.1,69.4,5.3
Dadra and Nagar haveli,73.0,73.4,72.7,-0.7,,,,,
Mizoram,72.1,66.1,81.0,14.9,0.0,72.1,66.9,78.4,11.5
Punjab,71.1,69.0,73.5,4.5,-4.9,66.2,63.3,69.4,6.1
Himachal Pradesh,70.8,67.5,74.3,6.8,-0.2,70.6,67.9,73.2,5.3
Maharashtra,70.2,67.9,72.8,4.9,-0.9,69.3,66.4,72.4,6.0
Rajasthan,70.2,67.3,73.4,6.1,1.3,71.5,68.1,75.4,7.3
Manipur,70.1,66.0,74.5,8.5,-2.5,67.6,63.7,71.7,8.0
Sikkim,69.8,69.4,70.7,1.3,-3.9,65.9,62.7,70.2,7.5
Goa,69.7,66.1,74.0,7.9,3.6,73.3,68.7,79.1,10.4
Jammu and Kashmir,69.2,67.6,70.8,3.2,2.6,71.8,70.9,72.8,1.9
Delhi,69.2,66.8,73.1,6.3,-1.2,68.0,65.2,71.3,6.1
Gujarat,68.7,65.9,72.0,6.1,-1.0,67.7,64.3,71.5,7.2
Lakshadweep,68.5,65.9,71.6,5.7,2.7,71.2,66.1,76.3,10.2
Meghalaya,68.5,65.0,72.6,7.6,0.3,68.8,66.5,71.4,4.9
Haryana,68.4,65.8,71.9,6.1,-2.4,66.0,61.9,71.0,9.1
West Bengal,68.3,67.4,69.2,1.8,-3.6,64.7,63.0,66.6,3.6
Karnataka,68.2,64.6,72.3,7.7,-0.9,67.3,63.2,72.0,8.8
Tripura,67.8,64.4,71.8,7.4,-1.8,66.0,63.7,68.6,4.9
Uttarakhand,67.6,64.1,71.6,7.5,0.7,68.3,65.4,71.4,6.0
Andaman and nicobar islands,67.4,64.1,71.5,7.4,-0.3,67.1,62.1,84.3,22.2
Jharkhand,66.7,64.9,68.6,3.7,-2.0,64.7,62.7,66.7,4.0
Chhattisgarh,66.4,64.6,68.3,3.7,-2.6,63.8,60.8,67.0,6.2
Puducherry,66.3,60.3,73.9,13.6,-1.7,64.6,59.0,70.7,11.7
Daman and diu,66.2,61.7,72.5,10.8,,,,,
Madhya Pradesh,66.0,63.6,68.8,5.2,0.2,66.2,63.2,69.5,6.3
Uttar Pradesh,64.9,63.3,66.6,3.3,-1.9,63.0,60.6,65.6,5.0
Odisha,64.7,63.4,66.1,2.7,-0.5,64.2,61.4,67.1,5.7
Arunachal Pradesh,64.6,63.0,66.5,3.5,2.9,67.5,65.0,70.2,5.2
Andhra Pradesh,64.2,59.9,69.2,9.3,-0.8,63.4,59.6,67.8,8.2
Tamil Nadu,63.6,60.2,67.4,7.2,0.3,63.9,59.3,69.1,9.8
Assam,63.5,61.0,66.4,5.4,2.6,66.1,63.1,69.5,6.4
Bihar,63.0,62.0,64.0,2.0,1.4,64.4,63.3,65.4,2.1
Telangana,62.4,58.4,66.8,8.4,1.4,63.8,60.4,67.3,6.9
Dadra and Nagar Haveli and Daman and Diu,,,,,,70.6,67.7,76.9,9.2

<br>
<br>

In [9]:
# Some inner statistics for interest:
def min_and_max(df, region_center=''):
    print(f"Number of values: {len(df)}")
    
    def find_3_largest(df):
        t_df = df.nlargest(3)
        t_df = t_df.reset_index()
        return t_df.apply(lambda v: f"{v.iloc[1]:.1f} – {v.iloc[0]}", axis=1)

    def find_3_smallest(df):
        t_df = df.nsmallest(3).iloc[::-1]
        t_df = t_df.reset_index()
        return t_df.apply(lambda v: f"{v.iloc[1]:.1f} – {v.iloc[0]}", axis=1)
    
    if region_center:
        ser_center = df.loc[region_center].map(lambda v: f" — {v} —")
        final_df = pd.concat([df.apply(find_3_largest), ser_center.to_frame().T, df.apply(find_3_smallest)])
        final_df.index = ['max', 'max_2', 'max_3', region_center, 'min_3', 'min_2', 'min']
    else:
        final_df = pd.concat([df.apply(find_3_largest), df.apply(find_3_smallest)])
        final_df.index = ['max', 'max_2', 'max_3', 'min_3', 'min_2', 'min']
    return final_df.style.set_properties(**{'text-align': 'left'})

min_and_max(df_SRS, region_center="India")

Number of values: 23

In [10]:
min_and_max(df_NFHS, region_center="India")

Number of values: 38

<br>
<br>

In [12]:
# for state in sorted(df_NFHS.index.to_list()):
#     print(f"    '{state}': {{'en': ('', ''), 'ru': ('', '')}},")

In [13]:
dd_replacement = {
    'India': {'en': ('India on average', ''), 'ru': ('Индия в среднем', '')},
    'Andaman and nicobar islands': {'en': ('Andaman and<br>Nicobar Islands', 'Andaman and Nicobar Islands'), 'ru': ('Андама́нские и<br>Никоба́рские острова', 'Андаманские и Никобарские острова')},
    'Andhra Pradesh': {'en': ('Andhra Pradesh', 'Andhra Pradesh'), 'ru': ('А́ндхра-Праде́ш', 'Андхра-Прадеш')},
    'Arunachal Pradesh': {'en': ('Arunachal Pradesh', 'Arunachal Pradesh'), 'ru': ('Аруна́чал-Праде́ш', 'Аруначал-Прадеш')},
    'Assam': {'en': ('Assam', 'Assam'), 'ru': ('Асса́м', 'Ассам')},
    'Bihar': {'en': ('Bihar', 'Bihar'), 'ru': ('Биха́р', 'Бихар')},
    'Chandigarh': {'en': ('Chandigarh', 'Chandigarh'), 'ru': ('Чандига́рх', 'Чандигарх')},
    'Chhattisgarh': {'en': ('Chhattisgarh', 'Chhattisgarh'), 'ru': ('Чхаттисга́рх', 'Чхаттисгарх')},
    'Dadra and Nagar haveli': {'en': ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), 'ru': ('Да́дра и Нагар-Хавели', 'Дадра и Нагар-Хавели')},
    'Dadra and Nagar Haveli and Daman and Diu': {'en': ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), 'ru': ('Да́дра и Нагар-Хавели и Дама́н и Ди́у', 'Дадра и Нагар-Хавели и Даман и Диу')},
    'Daman and diu': {'en': ('Daman and Diu', 'Daman and Diu'), 'ru': ('Дама́н и Ди́у', 'Даман и Диу')},
    'Delhi': {'en': ('Delhi', 'Delhi'), 'ru': ('Де́ли', 'Дели')},
    'Goa': {'en': ('Goa', 'Goa'), 'ru': ('Го́а', 'Гоа')},
    'Gujarat': {'en': ('Gujarat', 'Gujarat'), 'ru': ('Гуджара́т', 'Гуджарат')},
    'Haryana': {'en': ('Haryana', 'Haryana'), 'ru': ('Харья́на', 'Харьяна')},
    'Himachal Pradesh': {'en': ('Himachal Pradesh', 'Himachal Pradesh'), 'ru': ('Химача́л-Праде́ш', 'Химачал-Прадеш')},
    'Jammu and Kashmir': {'en': ('Jammu and Kashmir', 'Jammu and Kashmir (union territory)'), 'ru': ('Джа́мму и Кашми́р', 'Джамму и Кашмир (союзная территория)')},
    'Jharkhand': {'en': ('Jharkhand', 'Jharkhand'), 'ru': ('Джаркха́нд', 'Джаркханд')},
    'Karnataka': {'en': ('Karnataka', 'Karnataka'), 'ru': ('Карна́така', 'Карнатака')},
    'Kerala': {'en': ('Kerala', 'Kerala'), 'ru': ('Ке́рала', 'Керала')},
    'Lakshadweep': {'en': ('Lakshadweep', 'Lakshadweep'), 'ru': ('Лакшадви́п', 'Лакшадвип')},
    'Madhya Pradesh': {'en': ('Madhya Pradesh', 'Madhya Pradesh'), 'ru': ('Ма́дхья-Праде́ш', 'Мадхья-Прадеш')},
    'Maharashtra': {'en': ('Maharashtra', 'Maharashtra'), 'ru': ('Махара́штра', 'Махараштра')},
    'Manipur': {'en': ('Manipur', 'Manipur'), 'ru': ('Манипу́р', 'Манипур')},
    'Meghalaya': {'en': ('Meghalaya', 'Meghalaya'), 'ru': ('Мегхала́я', 'Мегхалая')},
    'Mizoram': {'en': ('Mizoram', 'Mizoram'), 'ru': ('Мизора́м', 'Мизорам')},
    'Nagaland': {'en': ('Nagaland', 'Nagaland'), 'ru': ('Нагале́нд', 'Нагаленд')},
    'Odisha': {'en': ('Odisha', 'Odisha'), 'ru': ('Оди́ша', 'Одиша')},
    'Puducherry': {'en': ('Puducherry', 'Puducherry (union territory)'), 'ru': ('Пондичерри', 'Пондичерри')},
    'Punjab': {'en': ('Punjab', 'Punjab, India'), 'ru': ('Пенджа́б', 'Пенджаб (Индия)')},
    'Rajasthan': {'en': ('Rajasthan', 'Rajasthan'), 'ru': ('Раджастха́н', 'Раджастхан')},
    'Sikkim': {'en': ('Sikkim', 'Sikkim'), 'ru': ('Сикки́м', 'Сикким')},
    'Tamil Nadu': {'en': ('Tamil Nadu', 'Tamil Nadu'), 'ru': ('Тамилна́д', 'Тамилнад')},
    'Telangana': {'en': ('Telangana', 'Telangana'), 'ru': ('Телингана', 'Телингана')},
    'Tripura': {'en': ('Tripura', 'Tripura'), 'ru': ('Трипу́ра', 'Трипура')},
    'Uttar Pradesh': {'en': ('Uttar Pradesh', 'Uttar Pradesh'), 'ru': ('У́ттар-Праде́ш', 'Уттар-Прадеш')},
    'Uttarakhand': {'en': ('Uttarakhand', 'Uttarakhand'), 'ru': ('Уттаракха́нд', 'Уттаракханд')},
    'West Bengal': {'en': ('West Bengal', 'West Bengal'), 'ru': ('Западная Бенга́лия', 'Западная Бенгалия')}
}

In [14]:
# create code for placing info in Wikipedia
def create_table(df, file_header, lang='ru'):

    def if_value(x, prec=1):
        return '—' if math.isnan(x) else \
               f"{x:0.{prec}f}"  if x>=0 else \
               f"−{-x:0.{prec}f}"                #"{x:0.{prec}f}".format(x, prec)

    def chval(x, prec=1, *, add_par=''):  # change_value
        return f'style="padding-right:2ex;{add_par}"|—' if math.isnan(x) else \
               f'style="padding-right:2ex;color:darkgreen;{add_par}"|{x:0.{prec}f}' if x>0 else \
               f'style="padding-right:2ex;color:crimson;{add_par}"|−{-x:0.{prec}f}' if x<0 else \
               f'style="padding-right:2ex;color:darkgray;{add_par}"|{x:0.{prec}f}'
    
    def chval_bold(x, prec=1, *, add_par=''):  # change_value
        return '—' if math.isnan(x) else \
               f'style="padding-right:2ex;color:darkgreen;{add_par}"|\'\'\'{x:0.{prec}f}\'\'\'' if x>0 else \
               f'style="padding-right:2ex;color:crimson;{add_par}"|\'\'\'−{-x:0.{prec}f}\'\'\'' if x<0 else \
               f'style="padding-right:2ex;color:darkgray;{add_par}"|\'\'\'{x:0.{prec}f}\'\'\''
    
    with open('design/' + file_header, mode='r', encoding="utf-8") as fh:
        table_header = fh.read()

    st = ''
    for i in range(len(df)):
        ser = df.iloc[i]    
        if ser.name == 'India':
            st += '\n' + '|-class=static-row-header\n' + \
                  f'|style="text-align:left;"|\'\'\'{dd_replacement[ser.name][lang][0]}\'\'\' ' + \
                  f'|| style="text-align:center; background:#e0ffd8;"|\'\'\'{if_value(ser["2015-16_total"])}\'\'\' ' + \
                  f'|| style="text-align:center;background:#eaf3ff;"|\'\'\'{if_value(ser["2015-16_male"])}\'\'\' ' + \
                  f'|| style="text-align:center;background:#fee7f6;"|\'\'\'{if_value(ser["2015-16_female"])}\'\'\' ' + \
                  f'|| style="padding-right:2ex;"|\'\'\'{if_value(ser["2015-16_fΔm"])}\'\'\' ' + \
                  f'|| {chval_bold(ser["Δ_periods"], add_par="border-left-width:2px;")} ' + \
                  f'|| style="text-align:center;background:#e0ffd8;border-left-width:2px;"|\'\'\'{if_value(ser["2019-21_total"])}\'\'\' ' + \
                  f'|| style="text-align:center;background:#eaf3ff;"|\'\'\'{if_value(ser["2019-21_male"])}\'\'\' ' + \
                  f'|| style="text-align:center;background:#fee7f6;"|\'\'\'{if_value(ser["2019-21_female"])}\'\'\' ' + \
                  f'|| style="padding-right:2ex;"|\'\'\'{if_value(ser["2019-21_fΔm"])}\'\'\''
        else:
            name_link = dd_replacement[ser.name][lang][1]
            name_visible = dd_replacement[ser.name][lang][0]
            name_inserted = name_link if name_link == name_visible else f"{name_link}|{name_visible}"
            st += '\n' + '|-\n' + \
                  f'|style="text-align:left;"|[[{name_inserted}]] ' + \
                  f'|| style="text-align:center; background:#e0ffd8;"|\'\'\'{if_value(ser["2015-16_total"])}\'\'\' ' + \
                  f'|| style="text-align:center;background:#eaf3ff;"|{if_value(ser["2015-16_male"])} ' + \
                  f'|| style="text-align:center;background:#fee7f6;"|{if_value(ser["2015-16_female"])} ' + \
                  f'|| style="padding-right:2ex;"|{if_value(ser["2015-16_fΔm"])} ' + \
                  f'|| {chval(ser["Δ_periods"], add_par="border-left-width:2px;")} ' + \
                  f'|| style="text-align:center;background:#e0ffd8;border-left-width:2px;"|\'\'\'{if_value(ser["2019-21_total"])}\'\'\' ' + \
                  f'|| style="text-align:center;background:#eaf3ff;"|{if_value(ser["2019-21_male"])} ' + \
                  f'|| style="text-align:center;background:#fee7f6;"|{if_value(ser["2019-21_female"])} ' + \
                  f'|| style="padding-right:2ex;"|{if_value(ser["2019-21_fΔm"])}'

    if lang == 'ru':
        st = re.sub('(?<=\\d)\\.(?=\\d)', ',', st)  # replace . to comma, if this . is between two digits
        # st = st.replace('padding-right:1,5ex;', 'padding-right:1.5ex;')

    st = table_header + st + '\n|}'
    
    # gray color for missing values
    st = st.replace(';"|—', ';color:silver;"|—') \
           .replace(';"|\'\'\'—\'\'\'', ';color:silver;"|\'\'\'—\'\'\'')

    return st


table_code = create_table(df_NFHS, file_header='NFHS_header_ru -2019-21.txt', lang='ru')

# write the code to file
with open('output/Table code for Indian states by NFHS -ru.txt', 'w', encoding="utf-8") as fh:
    fh.write(table_code)

In [15]:
table_code = create_table(df_NFHS, file_header='NFHS_header_en -2019-21.txt', lang='en')

# write the code to file
with open('output/Table code for Indian states by NFHS -en.txt', 'w', encoding="utf-8") as fh:
    fh.write(table_code)

<br>
<br>
<br>
<hr>

<h3>Map creation</h3>

In [17]:
CountryGroup = namedtuple('CountryGroup', ['group_label', 'color', 'countries'])

In [18]:
# for state in sorted(df_NFHS.index.to_list()):
#     print(f"'{state}'", end=', ')

In [19]:
df_map = df_NFHS.copy()                                    \
                .drop(['India', 'Daman and diu', 'Dadra and Nagar haveli']) \
                .rename(index={
                    'Andaman and nicobar islands' : 'Andaman and Nicobar Islands',
                    'Jammu and Kashmir' : 'Jammu and Kashmir disp'
                })

df_map.head(3).fillna('')

,2015-16_total,2015-16_male,2015-16_female,2015-16_fΔm,Δ_periods,2019-21_total,2019-21_male,2019-21_female,2019-21_fΔm
Nagaland,76.2,73.0,79.8,6.8,-0.8,75.4,71.5,79.9,8.4
Kerala,73.9,70.1,77.8,7.7,-2.7,71.2,67.1,75.5,8.4
Chandigarh,73.3,69.1,79.5,10.4,-6.8,66.5,64.1,69.4,5.3

In [20]:
dd_legend = {
    # '78.0–78.9' : '002000',
    # '77.0–77.9' : '006000',
    '76.0–76.9' : '009000',
    '75.0–75.9' : '00b800',
    '74.0–74.9' : '00e000',
    '73.0–73.9' : '00ff00',
    '72.0–72.9' : 'b8ff00',
    '71.0–71.9' : 'ffff00',
    '70.0–70.9' : 'ffe000',
    '69.0–69.9' : 'ffc000',
    '68.0–68.9' : 'ffa000',
    '67.0–67.9' : 'ff8000',
    '66.0–66.9' : 'ff5000',
    '65.0–65.9' : 'ff0000',
    '64.0–64.9' : 'c80000',
    '63.0–63.9' : '900000',
    '62.0–62.9' : '400000'
}

def create_legend_code(dd_legend):
    for k, v in dd_legend.items():
        print(f"{{{{Legend|#{v}|{k}}}}}")

create_legend_code(dd_legend)

{{Legend|#009000|76.0–76.9}}
{{Legend|#00b800|75.0–75.9}}
{{Legend|#00e000|74.0–74.9}}
{{Legend|#00ff00|73.0–73.9}}
{{Legend|#b8ff00|72.0–72.9}}
{{Legend|#ffff00|71.0–71.9}}
{{Legend|#ffe000|70.0–70.9}}
{{Legend|#ffc000|69.0–69.9}}
{{Legend|#ffa000|68.0–68.9}}
{{Legend|#ff8000|67.0–67.9}}
{{Legend|#ff5000|66.0–66.9}}
{{Legend|#ff0000|65.0–65.9}}
{{Legend|#c80000|64.0–64.9}}
{{Legend|#900000|63.0–63.9}}
{{Legend|#400000|62.0–62.9}}

In [21]:
def filter_df(df, selected_column):
    filtered_df = df.loc[:, [selected_column]]   \
                    .sort_values(by=selected_column, ascending=False) \
                    .dropna()

    filtered_df['group_label'] = filtered_df[selected_column].map(lambda x: f"{int(x):.1f}–{int(x) + 0.9:.1f}")
    
    
    # filtered_df['group_label'] = filtered_df['group_label'].replace(['79.5–79.99', '79.0–79.49', '78.5–78.99', '78.0–78.49'], '78.0–79.99')
    
    min_value = filtered_df[selected_column].min()
    max_value = filtered_df[selected_column].max()
    
    print(f"           ——— {selected_column} ———")
    print(f"Range: {min_value:.1f} – {max_value:.1f}   " +
          f"({filtered_df[selected_column].idxmin()} – {filtered_df[selected_column].idxmax()})")
    print(f"Number of groups: {filtered_df['group_label'].nunique()}")
    print(f"Number of values: {len(filtered_df)}")

    return filtered_df


df_sel = filter_df(df_map, selected_column='2019-21_total')
df_sel

           ——— 2019-21_total ———
Range: 63.0 – 75.4   (Uttar Pradesh – Nagaland)
Number of groups: 12
Number of values: 35

                                          2019-21_total group_label
Nagaland                                           75.4   75.0–75.9
Goa                                                73.3   73.0–73.9
Mizoram                                            72.1   72.0–72.9
Jammu and Kashmir disp                             71.8   71.0–71.9
Rajasthan                                          71.5   71.0–71.9
Kerala                                             71.2   71.0–71.9
Lakshadweep                                        71.2   71.0–71.9
Dadra and Nagar Haveli and Daman and Diu           70.6   70.0–70.9
Himachal Pradesh                                   70.6   70.0–70.9
Maharashtra                                        69.3   69.0–69.9
Meghalaya                                          68.8   68.0–68.9
Uttarakhand                                        68.3   68.0–68.9
Delhi                                              68.0   68.0–68.9
Gujarat                                            67.7   67.0–67.9
Manipur                                            67.6   67.0–67.9
Arunachal Pradesh                                  67.5   67.0–67.9
Karnataka                                          67.3   67.0–67.9
Andaman and Nicobar Islands                        67.1   67.0–67.9
Chandigarh                                         66.5   66.0–66.9
Madhya Pradesh                                     66.2   66.0–66.9
Punjab                                             66.2   66.0–66.9
Assam                                              66.1   66.0–66.9
Haryana                                            66.0   66.0–66.9
Tripura                                            66.0   66.0–66.9
Sikkim                                             65.9   65.0–65.9
West Bengal                                        64.7   64.0–64.9
Jharkhand                                          64.7   64.0–64.9
Puducherry                                         64.6   64.0–64.9
Bihar                                              64.4   64.0–64.9
Odisha                                             64.2   64.0–64.9
Tamil Nadu                                         63.9   63.0–63.9
Chhattisgarh                                       63.8   63.0–63.9
Telangana                                          63.8   63.0–63.9
Andhra Pradesh                                     63.4   63.0–63.9
Uttar Pradesh                                      63.0   63.0–63.9

In [22]:
def extract_indexes(subdf, dd_legend = dd_legend):
    group_label = subdf['group_label'].iloc[0]
    countries = subdf.index.to_list()
    color = (dd_legend[group_label])
    
    ls_grouping.append(CountryGroup(group_label=group_label, countries=countries, color=color))

    return pd.Series([color, countries], index=['color', 'regions'])


ls_grouping = []
df_grouped = df_sel.groupby(['group_label'])[['group_label']].apply(extract_indexes).loc[::-1]

df_grouped

              color                                            regions
group_label
75.0–75.9    00b800                                         [Nagaland]
73.0–73.9    00ff00                                              [Goa]
72.0–72.9    b8ff00                                          [Mizoram]
71.0–71.9    ffff00  [Jammu and Kashmir disp, Rajasthan, Kerala, La...
70.0–70.9    ffe000  [Dadra and Nagar Haveli and Daman and Diu, Him...
69.0–69.9    ffc000                                      [Maharashtra]
68.0–68.9    ffa000                    [Meghalaya, Uttarakhand, Delhi]
67.0–67.9    ff8000  [Gujarat, Manipur, Arunachal Pradesh, Karnatak...
66.0–66.9    ff5000  [Chandigarh, Madhya Pradesh, Punjab, Assam, Ha...
65.0–65.9    ff0000                                           [Sikkim]
64.0–64.9    c80000  [West Bengal, Jharkhand, Puducherry, Bihar, Od...
63.0–63.9    900000  [Tamil Nadu, Chhattisgarh, Telangana, Andhra P...

In [23]:
# add record for n/a states
states_na = ['Ladakh disp']  # 'Dadra and Nagar Haveli and Daman and Diu', 

ls_on_map = df_map.index.to_list()

assert not [state for state in states_na if state in ls_on_map], "some states, designed to be assign as N/A, are really have values"

ls_grouping.insert(0, CountryGroup(group_label='n/a', countries=states_na, color='e0e0e0'))

In [24]:
def create_map_code_regions(ls_grouping, title=''):
    st = '{"groups":{'
    for group_label, color, regions in ls_grouping[::-1]:
        st_ls_regions = '"' + '","'.join(regions) + '"'
        st_ls_regions = st_ls_regions.replace(' ', '_')
        st += f'"#{color}":{{"label":"{group_label}","paths":[{st_ls_regions}]}},'

    st = st[:-1] + '},"title":"' + title + \
         '","hidden":[],"background":"#fff","borders":"#000","legendFont":"Century Gothic","legendFontColor":"#000","legendBgColor":"#00000000","legendBoxShape":"square","legendBorderColor":"#00000000","legendWidth":506.5357142857147,"areBordersShown":true,"defaultColor":"#d1dbdd","labelsColor":"#6a0707","labelsFont":"Arial","strokeWidth":"medium","areLabelsShown":false,"uncoloredScriptColor":"#ffff33","v5":true,"legendPosition":"custom","legendX":1327.2142857142853,"legendY":120.10714285714283,"canvasWidth":1920,"canvasHeight":2280,"legendSize":"custom","legendScale":1.25,"legendStatus":"show","scalingPatterns":true,"legendRowsSameColor":true,"legendColumnCount":2}'
    
    return st


st = create_map_code_regions(ls_grouping, title='2019 – 2021 (source: NFHS)')
print(st)

{"groups":{"#00b800":{"label":"75.0–75.9","paths":["Nagaland"]},"#00ff00":{"label":"73.0–73.9","paths":["Goa"]},"#b8ff00":{"label":"72.0–72.9","paths":["Mizoram"]},"#ffff00":{"label":"71.0–71.9","paths":["Jammu_and_Kashmir_disp","Rajasthan","Kerala","Lakshadweep"]},"#ffe000":{"label":"70.0–70.9","paths":["Dadra_and_Nagar_Haveli_and_Daman_and_Diu","Himachal_Pradesh"]},"#ffc000":{"label":"69.0–69.9","paths":["Maharashtra"]},"#ffa000":{"label":"68.0–68.9","paths":["Meghalaya","Uttarakhand","Delhi"]},"#ff8000":{"label":"67.0–67.9","paths":["Gujarat","Manipur","Arunachal_Pradesh","Karnataka","Andaman_and_Nicobar_Islands"]},"#ff5000":{"label":"66.0–66.9","paths":["Chandigarh","Madhya_Pradesh","Punjab","Assam","Haryana","Tripura"]},"#ff0000":{"label":"65.0–65.9","paths":["Sikkim"]},"#c80000":{"label":"64.0–64.9","paths":["West_Bengal","Jharkhand","Puducherry","Bihar","Odisha"]},"#900000":{"label":"63.0–63.9","paths":["Tamil_Nadu","Chhattisgarh","Telangana","Andhra_Pradesh","Uttar_Pradesh"]},"#e0e0e0":{"label":"n/a","paths":["Ladakh_disp"]}},"title":"2019 – 2021 (source: NFHS)","hidden":[],"background":"#fff","borders":"#000","legendFont":"Century Gothic","legendFontColor":"#000","legendBgColor":"#00000000","legendBoxShape":"square","legendBorderColor":"#00000000","legendWidth":506.5357142857147,"areBordersShown":true,"defaultColor":"#d1dbdd","labelsColor":"#6a0707","labelsFont":"Arial","strokeWidth":"medium","areLabelsShown":false,"uncoloredScriptColor":"#ffff33","v5":true,"legendPosition":"custom","legendX":1327.2142857142853,"legendY":120.10714285714283,"canvasWidth":1920,"canvasHeight":2280,"legendSize":"custom","legendScale":1.25,"legendStatus":"show","scalingPatterns":true,"legendRowsSameColor":true,"legendColumnCount":2}