[data](https://www.abs.gov.au/statistics/people/population/life-expectancy/latest-release)<br>
[Administrative division of Australia](https://en.wikipedia.org/wiki/States_and_territories_of_Australia#States)<br>
[List of Australian states by life expectancy](https://en.wikipedia.org/wiki/List_of_Australian_states_by_life_expectancy) / 
[Продолжительность жизни в штатах Австралии](https://ru.wikipedia.org/wiki/Продолжительность_жизни_в_штатах_Австралии)<br>
[MapChart](https://www.mapchart.net/australia.html)

In [2]:
import pandas as pd
import math
import re
import itertools
from collections import namedtuple

import sys
sys.path.append("..")
import mal_moduls_private.mal_total as mal

In [3]:
df = pd.read_excel(f'data/Life expectancy, Statistical Areas Level 4 - 2016-2018 to 2022-2024.xlsx', sheet_name='Table 1',
                   skiprows=8, skipfooter=1, usecols="B:AC", index_col=0)

df.index.name = ''

# drop empty records and columns
df.dropna(axis='index',   how='all', inplace=True)
df.dropna(axis='columns', how='all', inplace=True)

# rename columns
df.columns = [f'{period}_{sex}' for period, sex in itertools.product(('2016-18', '2017-19', '2018-20', '2019-21', '2020-22', '2021-23', '2022-24'), ('m', 'f', 't'))]

# change order of columns
df = df[[f'{period}_{sex}' for period, sex in itertools.product(('2016-18', '2017-19', '2018-20', '2019-21', '2020-22', '2021-23', '2022-24'), ('t', 'm', 'f'))]]

# filter records
states = ('Total New South Wales', 'Total Victoria', 'Total Queensland', 'Total South Australia', 'Total Western Australia',
          'Total Tasmania', 'Total Northern Territory', 'Total Australian Capital Territory', 'Australia')
df = df.loc[states, :]

df.fillna('')

,2016-18_t,2016-18_m,2016-18_f,2017-19_t,2017-19_m,2017-19_f,2018-20_t,2018-20_m,2018-20_f,2019-21_t,...,2019-21_f,2020-22_t,2020-22_m,2020-22_f,2021-23_t,2021-23_m,2021-23_f,2022-24_t,2022-24_m,2022-24_f
,,,,,,,,,,,,,,,,,,,,,
Total New South Wales,82.7,80.6,84.9,82.8,80.7,85.0,83.3,81.2,85.4,83.3,...,85.4,83.3,81.3,85.3,83.1,81.2,85.2,83.2,81.2,85.3
Total Victoria,83.5,81.7,85.3,83.6,81.8,85.5,83.8,81.9,85.8,83.7,...,85.7,83.5,81.6,85.5,83.4,81.5,85.4,83.4,81.5,85.4
Total Queensland,82.4,80.2,84.7,82.5,80.3,84.8,82.8,80.6,85.1,82.9,...,85.1,82.8,80.7,85.0,82.6,80.5,84.7,82.5,80.5,84.7
Total South Australia,82.5,80.4,84.7,82.5,80.4,84.7,82.9,80.7,85.2,83.1,...,85.3,83.0,81.0,85.1,82.9,80.9,85.0,82.9,80.9,84.9
Total Western Australia,82.8,80.5,85.1,83.0,80.9,85.4,83.4,81.3,85.7,83.8,...,85.9,83.7,81.7,85.8,83.6,81.6,85.7,83.6,81.5,85.7
Total Tasmania,81.2,79.3,83.2,81.5,79.5,83.6,82.0,79.9,84.3,82.3,...,84.4,82.3,80.3,84.3,82.1,80.2,84.0,82.0,80.3,83.7
Total Northern Territory,77.8,75.5,80.2,78.0,75.5,80.6,78.5,76.2,81.0,78.6,...,81.0,78.4,76.2,80.7,78.3,76.4,80.4,78.8,77.0,80.7
Total Australian Capital Territory,83.2,81.2,85.3,83.5,81.6,85.6,84.0,82.1,85.9,84.5,...,86.3,84.1,82.2,86.0,83.6,81.7,85.7,83.8,82.0,85.8
Australia,82.8,80.7,84.9,82.9,80.9,85.0,83.2,81.2,85.3,83.3,...,85.4,83.2,81.2,85.3,83.0,81.1,85.1,83.0,81.1,85.1

In [4]:
# rename indexes
df.rename(index = {'Total New South Wales': 'NSW',
                   'Total Victoria': 'VIC',
                   'Total Queensland': 'QLD',
                   'Total South Australia': 'SA',
                   'Total Western Australia': 'WA',
                   'Total Tasmania': 'TAS',
                   'Total Northern Territory': 'NT',
                   'Total Australian Capital Territory': 'ACT',
                   'Australia': '_AU_'                   
                  }, inplace=True)

# sort values
df.sort_values(by=['2020-22_t', '2020-22_m', '2020-22_f'], ascending=False, inplace=True)
df = pd.concat([df.loc[['_AU_']], df.drop('_AU_')])

df

,2016-18_t,2016-18_m,2016-18_f,2017-19_t,2017-19_m,2017-19_f,2018-20_t,2018-20_m,2018-20_f,2019-21_t,...,2019-21_f,2020-22_t,2020-22_m,2020-22_f,2021-23_t,2021-23_m,2021-23_f,2022-24_t,2022-24_m,2022-24_f
,,,,,,,,,,,,,,,,,,,,,
_AU_,82.8,80.7,84.9,82.9,80.9,85.0,83.2,81.2,85.3,83.3,...,85.4,83.2,81.2,85.3,83.0,81.1,85.1,83.0,81.1,85.1
ACT,83.2,81.2,85.3,83.5,81.6,85.6,84.0,82.1,85.9,84.5,...,86.3,84.1,82.2,86.0,83.6,81.7,85.7,83.8,82.0,85.8
WA,82.8,80.5,85.1,83.0,80.9,85.4,83.4,81.3,85.7,83.8,...,85.9,83.7,81.7,85.8,83.6,81.6,85.7,83.6,81.5,85.7
VIC,83.5,81.7,85.3,83.6,81.8,85.5,83.8,81.9,85.8,83.7,...,85.7,83.5,81.6,85.5,83.4,81.5,85.4,83.4,81.5,85.4
NSW,82.7,80.6,84.9,82.8,80.7,85.0,83.3,81.2,85.4,83.3,...,85.4,83.3,81.3,85.3,83.1,81.2,85.2,83.2,81.2,85.3
SA,82.5,80.4,84.7,82.5,80.4,84.7,82.9,80.7,85.2,83.1,...,85.3,83.0,81.0,85.1,82.9,80.9,85.0,82.9,80.9,84.9
QLD,82.4,80.2,84.7,82.5,80.3,84.8,82.8,80.6,85.1,82.9,...,85.1,82.8,80.7,85.0,82.6,80.5,84.7,82.5,80.5,84.7
TAS,81.2,79.3,83.2,81.5,79.5,83.6,82.0,79.9,84.3,82.3,...,84.4,82.3,80.3,84.3,82.1,80.2,84.0,82.0,80.3,83.7
NT,77.8,75.5,80.2,78.0,75.5,80.6,78.5,76.2,81.0,78.6,...,81.0,78.4,76.2,80.7,78.3,76.4,80.4,78.8,77.0,80.7

<br>
<br>

In [6]:
# just for interest, explore results: determine regions with max and min values, and also look at specific regions
mal.min_and_max_values(df[['2016-18_t', '2017-19_t', '2018-20_t', '2019-21_t', '2020-22_t', '2021-23_t', '2022-24_t']],
                       row_center='_AU_', nmb=(5, 3), max_lng=11, show_difference=True)

Number of records: 9

In [7]:
# df = df.loc[:, '2019-21_t':]
df

,2016-18_t,2016-18_m,2016-18_f,2017-19_t,2017-19_m,2017-19_f,2018-20_t,2018-20_m,2018-20_f,2019-21_t,...,2019-21_f,2020-22_t,2020-22_m,2020-22_f,2021-23_t,2021-23_m,2021-23_f,2022-24_t,2022-24_m,2022-24_f
,,,,,,,,,,,,,,,,,,,,,
_AU_,82.8,80.7,84.9,82.9,80.9,85.0,83.2,81.2,85.3,83.3,...,85.4,83.2,81.2,85.3,83.0,81.1,85.1,83.0,81.1,85.1
ACT,83.2,81.2,85.3,83.5,81.6,85.6,84.0,82.1,85.9,84.5,...,86.3,84.1,82.2,86.0,83.6,81.7,85.7,83.8,82.0,85.8
WA,82.8,80.5,85.1,83.0,80.9,85.4,83.4,81.3,85.7,83.8,...,85.9,83.7,81.7,85.8,83.6,81.6,85.7,83.6,81.5,85.7
VIC,83.5,81.7,85.3,83.6,81.8,85.5,83.8,81.9,85.8,83.7,...,85.7,83.5,81.6,85.5,83.4,81.5,85.4,83.4,81.5,85.4
NSW,82.7,80.6,84.9,82.8,80.7,85.0,83.3,81.2,85.4,83.3,...,85.4,83.3,81.3,85.3,83.1,81.2,85.2,83.2,81.2,85.3
SA,82.5,80.4,84.7,82.5,80.4,84.7,82.9,80.7,85.2,83.1,...,85.3,83.0,81.0,85.1,82.9,80.9,85.0,82.9,80.9,84.9
QLD,82.4,80.2,84.7,82.5,80.3,84.8,82.8,80.6,85.1,82.9,...,85.1,82.8,80.7,85.0,82.6,80.5,84.7,82.5,80.5,84.7
TAS,81.2,79.3,83.2,81.5,79.5,83.6,82.0,79.9,84.3,82.3,...,84.4,82.3,80.3,84.3,82.1,80.2,84.0,82.0,80.3,83.7
NT,77.8,75.5,80.2,78.0,75.5,80.6,78.5,76.2,81.0,78.6,...,81.0,78.4,76.2,80.7,78.3,76.4,80.4,78.8,77.0,80.7

<br>
<br>

In [9]:
df.insert(loc=3, column='2019-21_fΔm',  value=(df['2019-21_f']-df['2019-21_m']).round(1))
df.insert(loc=4, column='Δ1', value=(df['2020-22_t']-df['2019-21_t']).round(1))

df.insert(loc=8, column='2020-22_fΔm',  value=(df['2020-22_f']-df['2020-22_m']).round(1))
df.insert(loc=9, column='Δ2', value=(df['2021-23_t']-df['2020-22_t']).round(1))

df.insert(loc=13, column='2021-23_fΔm',  value=(df['2021-23_f']-df['2021-23_m']).round(1))
df.insert(loc=14, column='Δ3', value=(df['2022-24_t']-df['2021-23_t']).round(1))

df.insert(loc=18, column='2022-24_fΔm',  value=(df['2022-24_f']-df['2022-24_m']).round(1))
df.insert(loc=19, column='Δ_total', value=(df['2022-24_t']-df['2019-21_t']).round(1))

df

,2016-18_t,2016-18_m,2016-18_f,2019-21_fΔm,Δ1,2017-19_t,2017-19_m,2017-19_f,2020-22_fΔm,Δ2,...,Δ_total,2020-22_t,2020-22_m,2020-22_f,2021-23_t,2021-23_m,2021-23_f,2022-24_t,2022-24_m,2022-24_f
,,,,,,,,,,,,,,,,,,,,,
_AU_,82.8,80.7,84.9,4.1,-0.1,82.9,80.9,85.0,4.1,-0.2,...,-0.3,83.2,81.2,85.3,83.0,81.1,85.1,83.0,81.1,85.1
ACT,83.2,81.2,85.3,3.6,-0.4,83.5,81.6,85.6,3.8,-0.5,...,-0.7,84.1,82.2,86.0,83.6,81.7,85.7,83.8,82.0,85.8
WA,82.8,80.5,85.1,4.2,-0.1,83.0,80.9,85.4,4.1,-0.1,...,-0.2,83.7,81.7,85.8,83.6,81.6,85.7,83.6,81.5,85.7
VIC,83.5,81.7,85.3,4.0,-0.2,83.6,81.8,85.5,3.9,-0.1,...,-0.3,83.5,81.6,85.5,83.4,81.5,85.4,83.4,81.5,85.4
NSW,82.7,80.6,84.9,4.0,0.0,82.8,80.7,85.0,4.0,-0.2,...,-0.1,83.3,81.3,85.3,83.1,81.2,85.2,83.2,81.2,85.3
SA,82.5,80.4,84.7,4.3,-0.1,82.5,80.4,84.7,4.1,-0.1,...,-0.2,83.0,81.0,85.1,82.9,80.9,85.0,82.9,80.9,84.9
QLD,82.4,80.2,84.7,4.2,-0.1,82.5,80.3,84.8,4.3,-0.2,...,-0.4,82.8,80.7,85.0,82.6,80.5,84.7,82.5,80.5,84.7
TAS,81.2,79.3,83.2,4.1,0.0,81.5,79.5,83.6,4.0,-0.2,...,-0.3,82.3,80.3,84.3,82.1,80.2,84.0,82.0,80.3,83.7
NT,77.8,75.5,80.2,4.7,-0.2,78.0,75.5,80.6,4.5,-0.1,...,0.2,78.4,76.2,80.7,78.3,76.4,80.4,78.8,77.0,80.7

In [10]:
mal.min_and_max_values(df[['2019-21_t', 'Δ1', '2020-22_t', 'Δ2', '2021-23_t', 'Δ3', '2022-24_t', 'Δ_total']],
                       row_center='_AU_', nmb=(5, 3), max_lng=11, show_difference=True)

Number of records: 9

<br>
<br>

In [12]:
dd_replacement = {
    'ACT': {'en': ('Capital Territory', 'Australian Capital Territory'), 'ru': ('Столичная территория', 'Австралийская столичная территория')},
    'NSW': {'en': ('New South Wales', 'New South Wales'), 'ru': ('Новый Южный Уэ́льс', 'Новый Южный Уэльс')},
    'NT': {'en': ('Northern Territory', 'Northern Territory'), 'ru': ('Северная территория', 'Северная территория')},
    'QLD': {'en': ('Queensland', 'Queensland'), 'ru': ('Кви́нсленд', 'Квинсленд')},
    'SA': {'en': ('South Australia', 'South Australia'), 'ru': ('Южная Австралия', 'Южная Австралия')},
    'TAS': {'en': ('Tasmania', 'Tasmania'), 'ru': ('Тасма́ния', 'Тасмания')},
    'VIC': {'en': ('Victoria', 'Victoria (state)'), 'ru': ('Викто́рия', 'Виктория (штат)')},
    'WA': {'en': ('Western Australia', 'Western Australia'), 'ru': ('Западная Австралия', 'Западная Австралия')},
    '_AU_': {'en': ('Australia', 'Australia'), 'ru': ('Австралия в целом', 'Австралия')}
}

In [13]:
# create code for placing info in Wikipedia
def create_table(df, file_header, lang='ru'):

    def if_value(x, prec=1):
        return '—' if math.isnan(x) else \
               f"{x:0.{prec}f}"  if x>=0 else \
               f"−{-x:0.{prec}f}"                #"{x:0.{prec}f}".format(x, prec)
    
    def chval(x, prec=1, *, add_par=''):  # change_value
        return f'style="padding-right:1.5ex;{add_par}"| —' if math.isnan(x) else \
               f'style="padding-right:1.5ex;color:darkgreen;{add_par}"| {x:0.{prec}f}' if x>0 else \
               f'style="padding-right:1.5ex;color:crimson;{add_par}"| −{-x:0.{prec}f}' if x<0 else \
               f'style="padding-right:1.5ex;color:darkgray;{add_par}"| {x:0.{prec}f}'
    
    def chval_bold(x, prec=1, *, add_par=''):  # change_value
        return ' \'\'\'—\'\'\'' if math.isnan(x) else \
               f'style="padding-right:1.5ex;color:darkgreen;{add_par}"| \'\'\'{x:0.{prec}f}\'\'\'' if x>0 else \
               f'style="padding-right:1.5ex;color:crimson;{add_par}"| \'\'\'−{-x:0.{prec}f}\'\'\'' if x<0 else \
               f'style="padding-right:1.5ex;color:darkgray;{add_par}"| \'\'\'{x:0.{prec}f}\'\'\''

    with open('design/' + file_header, mode='r', encoding="utf-8") as fh:
        table_header = fh.read()

    st = ''
    for i in range(len(df)):
        ser = df.iloc[i]    
        if ser.name == '_AU_':
             st += '\n' + '|-class=static-row-header\n' + \
                  f'| \'\'\'{dd_replacement[ser.name][lang][0]}\'\'\' ' + \
                  f'||style="background:#e0ffd8;"| \'\'\'{if_value(ser["2019-21_t"])}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| \'\'\'{if_value(ser["2019-21_m"])}\'\'\' ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{if_value(ser["2019-21_f"])}\'\'\' ' + \
                  f'||style="background:#fff8dc;"| \'\'\'{if_value(ser["2019-21_fΔm"])}\'\'\' ' + \
                  f'||{chval_bold(ser["Δ1"], add_par="border-left-width:2px;")} ' + \
                  f'||style="background:#e0ffd8;border-left-width:2px;"| \'\'\'{if_value(ser["2020-22_t"])}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| \'\'\'{if_value(ser["2020-22_m"])}\'\'\' ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{if_value(ser["2020-22_f"])}\'\'\' ' + \
                  f'||style="background:#fff8dc;"| \'\'\'{if_value(ser["2020-22_fΔm"])}\'\'\' ' + \
                  f'||{chval_bold(ser["Δ2"], add_par="border-left-width:2px;")} ' + \
                  f'||style="background:#e0ffd8;border-left-width:2px;"| \'\'\'{if_value(ser["2021-23_t"])}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| \'\'\'{if_value(ser["2021-23_m"])}\'\'\' ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{if_value(ser["2021-23_f"])}\'\'\' ' + \
                  f'||style="background:#fff8dc;"| \'\'\'{if_value(ser["2021-23_fΔm"])}\'\'\' ' + \
                  f'||{chval_bold(ser["Δ3"], add_par="border-left-width:2px;")} ' + \
                  f'||style="background:#e0ffd8;border-left-width:2px;"| \'\'\'{if_value(ser["2022-24_t"])}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| \'\'\'{if_value(ser["2022-24_m"])}\'\'\' ' + \
                  f'||style="background:#fee7f6;"| \'\'\'{if_value(ser["2022-24_f"])}\'\'\' ' + \
                  f'||style="background:#fff8dc;"| \'\'\'{if_value(ser["2022-24_fΔm"])}\'\'\' ' + \
                  f'||{chval_bold(ser["Δ_total"], add_par="border-left-width:2px;")}'
        else:
            name_link = dd_replacement[ser.name][lang][1]
            name_visible = dd_replacement[ser.name][lang][0]
            name_inserted = name_link if name_link == name_visible else f"{name_link}|{name_visible}"
            st += '\n' + '|-\n' + \
                  f'| [[{name_inserted}]] ' + \
                  f'||style="background:#e0ffd8;"| \'\'\'{if_value(ser["2019-21_t"])}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| {if_value(ser["2019-21_m"])} ' + \
                  f'||style="background:#fee7f6;"| {if_value(ser["2019-21_f"])} ' + \
                  f'||style="background:#fff8dc;"| {if_value(ser["2019-21_fΔm"])} ' + \
                  f'||{chval(ser["Δ1"], add_par="border-left-width:2px;")} ' + \
                  f'||style="background:#e0ffd8;border-left-width:2px;"| \'\'\'{if_value(ser["2020-22_t"])}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| {if_value(ser["2020-22_m"])} ' + \
                  f'||style="background:#fee7f6;"| {if_value(ser["2020-22_f"])} ' + \
                  f'||style="background:#fff8dc;"| {if_value(ser["2020-22_fΔm"])} ' + \
                  f'||{chval(ser["Δ2"], add_par="border-left-width:2px;")} ' + \
                  f'||style="background:#e0ffd8;border-left-width:2px;"| \'\'\'{if_value(ser["2021-23_t"])}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| {if_value(ser["2021-23_m"])} ' + \
                  f'||style="background:#fee7f6;"| {if_value(ser["2021-23_f"])} ' + \
                  f'||style="background:#fff8dc;"| {if_value(ser["2021-23_fΔm"])} ' + \
                  f'||{chval(ser["Δ3"], add_par="border-left-width:2px;")} ' + \
                  f'||style="background:#e0ffd8;border-left-width:2px;"| \'\'\'{if_value(ser["2022-24_t"])}\'\'\' ' + \
                  f'||style="background:#eaf3ff;"| {if_value(ser["2022-24_m"])} ' + \
                  f'||style="background:#fee7f6;"| {if_value(ser["2022-24_f"])} ' + \
                  f'||style="background:#fff8dc;"| {if_value(ser["2022-24_fΔm"])} ' + \
                  f'||{chval(ser["Δ_total"], add_par="border-left-width:2px;")}'

    if lang == 'ru':
        st = re.sub('(?<=\\d)\\.(?=\\d)', ',', st)  # replace . to comma, if this . is between two digits
        st = st.replace('padding-right:1,5ex;', 'padding-right:1.5ex;')

    st = table_header + st + '\n|}'
    
    # gray color for missing values
    st = st.replace(';"| —', ';color:silver;"| —')

    return st


table_code = create_table(df, file_header='Australia_header_ru -2024.txt', lang='ru')

# write the code to file
with open('output/Table code for Australian states -ru.txt', 'w', encoding="utf-8") as fh:
    fh.write(table_code)

In [14]:
table_code = create_table(df, file_header='Australia_header_en -2024.txt', lang='en')

# write the code to file
with open('output/Table code for Australian states -en.txt', 'w', encoding="utf-8") as fh:
    fh.write(table_code)

<br>
<br>
<br>
<hr>

<h3>Map creation</h3>

In [16]:
SELECTED_COLUMN = '2022-24_t'

In [17]:
CountryGroup = namedtuple('CountryGroup', ['group_label', 'color', 'countries'])

In [18]:
df_map = df.copy()                                    \
           .drop(['_AU_']) \
           .rename(index={
               'ACT' : 'Australian Capital Territory',
               'NSW' : 'New South Wales',
               'NT'  : 'Northern Territory',
               'QLD' : 'Queensland',
               'SA'  : 'South Australia',
               'TAS' : 'Tasmania',
               'VIC' : 'Victoria',
               'WA'  : 'Western Australia'
           })

df_map

,2016-18_t,2016-18_m,2016-18_f,2019-21_fΔm,Δ1,2017-19_t,2017-19_m,2017-19_f,2020-22_fΔm,Δ2,...,Δ_total,2020-22_t,2020-22_m,2020-22_f,2021-23_t,2021-23_m,2021-23_f,2022-24_t,2022-24_m,2022-24_f
,,,,,,,,,,,,,,,,,,,,,
Australian Capital Territory,83.2,81.2,85.3,3.6,-0.4,83.5,81.6,85.6,3.8,-0.5,...,-0.7,84.1,82.2,86.0,83.6,81.7,85.7,83.8,82.0,85.8
Western Australia,82.8,80.5,85.1,4.2,-0.1,83.0,80.9,85.4,4.1,-0.1,...,-0.2,83.7,81.7,85.8,83.6,81.6,85.7,83.6,81.5,85.7
Victoria,83.5,81.7,85.3,4.0,-0.2,83.6,81.8,85.5,3.9,-0.1,...,-0.3,83.5,81.6,85.5,83.4,81.5,85.4,83.4,81.5,85.4
New South Wales,82.7,80.6,84.9,4.0,0.0,82.8,80.7,85.0,4.0,-0.2,...,-0.1,83.3,81.3,85.3,83.1,81.2,85.2,83.2,81.2,85.3
South Australia,82.5,80.4,84.7,4.3,-0.1,82.5,80.4,84.7,4.1,-0.1,...,-0.2,83.0,81.0,85.1,82.9,80.9,85.0,82.9,80.9,84.9
Queensland,82.4,80.2,84.7,4.2,-0.1,82.5,80.3,84.8,4.3,-0.2,...,-0.4,82.8,80.7,85.0,82.6,80.5,84.7,82.5,80.5,84.7
Tasmania,81.2,79.3,83.2,4.1,0.0,81.5,79.5,83.6,4.0,-0.2,...,-0.3,82.3,80.3,84.3,82.1,80.2,84.0,82.0,80.3,83.7
Northern Territory,77.8,75.5,80.2,4.7,-0.2,78.0,75.5,80.6,4.5,-0.1,...,0.2,78.4,76.2,80.7,78.3,76.4,80.4,78.8,77.0,80.7

In [19]:
dd_legend = {
    '84.5–84.9' : '00b800',
    '84.0–84.4' : '00e000',
    '83.5–83.9' : '00ff00',
    '83.0–83.4' : 'b8ff00',
    '82.5–82.9' : 'ffff00',
    '82.0–82.4' : 'ffe000',
    '81.5–81.9' : 'ffbc00',
    '81.0–81.4' : 'ff9c00',
    '80.5–80.9' : 'ff7400',
    '80.0–80.4' : 'ff0000',
    '77.5–79.9' : 'c80000'
}

def create_legend_code(dd_legend):
    for k, v in dd_legend.items():
        print(f"{{{{Legend|#{v}|{k}}}}}")  

create_legend_code(dd_legend)

{{Legend|#00b800|84.5–84.9}}
{{Legend|#00e000|84.0–84.4}}
{{Legend|#00ff00|83.5–83.9}}
{{Legend|#b8ff00|83.0–83.4}}
{{Legend|#ffff00|82.5–82.9}}
{{Legend|#ffe000|82.0–82.4}}
{{Legend|#ffbc00|81.5–81.9}}
{{Legend|#ff9c00|81.0–81.4}}
{{Legend|#ff7400|80.5–80.9}}
{{Legend|#ff0000|80.0–80.4}}
{{Legend|#c80000|77.5–79.9}}

<br>
<br>

In [21]:
def filter_df(df, selected_column):
    filtered_df = df.loc[:, [selected_column]]   \
                    .sort_values(by=selected_column, ascending=False) \
                    .dropna()

    filtered_df['group_label'] = filtered_df[selected_column].map(lambda x: f"{x * 4 // 2 / 2:.1f}–{x * 4 // 2 / 2 + 0.4:.1f}")
    
    
    filtered_df['group_label'] = filtered_df['group_label'].replace(['79.5–79.9', '79.0–79.4', '78.5–78.9', '78.0–78.4', '77.5–77.9'], '77.5–79.9')
    
    min_value = filtered_df[selected_column].min()
    max_value = filtered_df[selected_column].max()
    
    print(f"           ——— {selected_column} ———")
    print(f"Range: {min_value:.1f} – {max_value:.1f}   " +
          f"({filtered_df[selected_column].idxmin()} – {filtered_df[selected_column].idxmax()})")
    print(f"Number of groups: {filtered_df['group_label'].nunique()}")
    print(f"Number of values: {len(filtered_df)}")

    return filtered_df


df_sel = filter_df(df_map, selected_column=SELECTED_COLUMN)
df_sel

           ——— 2022-24_t ———
Range: 78.8 – 83.8   (Northern Territory – Australian Capital Territory)
Number of groups: 5
Number of values: 8

                              2022-24_t group_label

Australian Capital Territory       83.8   83.5–83.9
Western Australia                  83.6   83.5–83.9
Victoria                           83.4   83.0–83.4
New South Wales                    83.2   83.0–83.4
South Australia                    82.9   82.5–82.9
Queensland                         82.5   82.5–82.9
Tasmania                           82.0   82.0–82.4
Northern Territory                 78.8   77.5–79.9

In [22]:
def extract_indexes(subdf, dd_legend = dd_legend):
    group_label = subdf['group_label'].iloc[0]
    countries = subdf.index.to_list()
    color = (dd_legend[group_label])
    
    ls_grouping.append(CountryGroup(group_label=group_label, countries=countries, color=color))

    return pd.Series([color, countries], index=['color', 'regions'])


ls_grouping = []
df_grouped = df_sel.groupby(['group_label'])[['group_label']].apply(extract_indexes).loc[::-1] \
                   .rename(index={'77.5–79.9': '<80'})

if ls_grouping[0].group_label == '77.5–79.9':
    ls_grouping[0] = ls_grouping[0]._replace(group_label = '<80')

df_grouped

              color                                            regions
group_label
83.5–83.9    00ff00  [Australian Capital Territory, Western Australia]
83.0–83.4    b8ff00                        [Victoria, New South Wales]
82.5–82.9    ffff00                      [South Australia, Queensland]
82.0–82.4    ffe000                                         [Tasmania]
<80          c80000                               [Northern Territory]

In [23]:
def create_map_code(ls_grouping, title='', legend_color='#000'):
    false, true = False, True

    jo = {
        "groups": { },
        "title": title,
        "hidden": [],
        "background": "#fff",
        "borders": "#000",
        "legendFont": "Century Gothic",
        "legendFontColor": "#000",
        "legendBorderColor": "#00000000",
        "legendBgColor": "#00000000",
        "legendWidth": 160,
        "legendBoxShape": "square",
        "areBordersShown": true,
        "defaultColor": "#d1dbdd",
        "labelsColor": "#6a0707",
        "labelsFont": "Arial",
        "strokeWidth": "medium",
        "areLabelsShown": false,
        "uncoloredScriptColor": "#ffff33",
        "zoomLevel": "1.00",
        "zoomX": "0.00",
        "zoomY": "0.00",
        "v6": true,
        "page": "australia",
        "legendPosition": "custom",
        "legendX": 95,
        "legendY": 630,
        "legendSize": "large",
        "legendTranslateX": "0.00",
        "legendStatus": "show",
        "scalingPatterns": true,
        "legendRowsSameColor": true,
        "legendColumnCount": 1
    }

    for group_label, color, regions in ls_grouping[::-1]:
        jo["groups"][f"#{color}"] = {"label": group_label,
                                     "paths": [region.replace(' ', '_') for region in regions]}       

    return jo


title = SELECTED_COLUMN[:-2].replace('-', ' – 20')
jo = create_map_code(ls_grouping, title=title, legend_color='#333333')

pretty_jo = json.dumps(jo, indent=2, ensure_ascii=False)

with open(f"output/map_JSON -{SELECTED_COLUMN}.txt", 'w', encoding="utf-8") as fh:
    fh.write(pretty_jo)